### ISSUE TITLE
comments on columns aren't reflected in swagger

### ISSUE THREAD

**Issue by litriv** [begriffs/postgrest#1013]
comments on columns don't seem to show up in swagger.  would be cool if it shows under "description" ?

**Comment by elimisteve** [comment]
Relatedly, the description currently says things that it seems like should be in the schema, like "this is a foreign key to api.todos".  Seems like that info can go elsewhere?

**Comment by kljensen** [comment]
@litriv If you put the comments on the API views, they will show in swagger. The comments on your tables in the data schema do not.

**Comment by litriv** [comment]
@kljensen ah okay thanks yes that makes complete sense - i guess i must've been tired.  i'll close the issue then.

**Comment by devesh23** [comment]
What do you mean by API View here?

**Comment by wolfgangwalther** [comment]
> Are we referring to adding comments on a view created on top of table.

Yes.

Assume you have a view in the exposed schema that selects from a table in a private schema. If you now put database comments on the table in the private schema, those are not shown in the OpenApi output. But if you put the same comments on the view instead, they will show up.

**Comment by devesh23** [comment]
@wolfgangwalther In my use-case, I have exposed the schema to WebAnon role. Will it still not show up?

**Comment by wolfgangwalther** [comment]
"expose" does not mean "grant permissions to role". This is entirely unrelated.

The exposed schema in PostgREST is the one schema that we create api endpoints for and is set via `db-schema`. So all tables and views **in this schema** are "exposed" to the outer world. Only those schemas and views that are exposed, show up in the OpenAPI output.

A view of a table, where the view is exposed, but the table is private means: From the outer world we only see the view. So we only take everything that belongs to this view: name, column names, comments and so on. In terms of the outer world the base table doesn't even exist. Therefore all the comments **on the base table** do not exist as well.
