### ISSUE TITLE
Scalar returning function's weird (not backward-compatible) response

### ISSUE THREAD

**Issue by EmpireFleet** [begriffs/postgrest#1014]
Definition like the following

`CREATE FUNCTION postgrest_foo()  returns text as $$ SELECT 'bar'::text $$ LANGUAGE SQL`

that used to be returning in version 3.2 response like this

`[{"postgrest_foo":"bar"}]`

in version 4.* emits just

`"bar"`

Is that behavior by design or some little lapse while dealing with corner cases? 

_Tested on_ 
PostgreSQL 9.6.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18) 6.3.0 20170516, 64-bit

**Comment by ruslantalpa** [comment]
by design, `"bar"` is valid json

**Comment by EmpireFleet** [comment]
So, the issue is response compatibility - not json validity.
```SQL
CREATE OR REPLACE FUNCTION postgrest_fooset(single_first boolean)  
  RETURNS setof text 
AS $$ 
	SELECT foo
	FROM (
		SELECT *, row_number() over() AS rn
		FROM ( VALUES ('bar'::text), ('bazz'::text) ) foo(foo)
	) foo
	WHERE NOT single_first OR rn = 1
$$ LANGUAGE SQL
```

Apparently, this sequence of interactions is by design too
```HTTP
POST /rpc/postgrest_fooset -d {"single_first":false}
HTTP/1.1 200
[
    {
        "postgrest_fooset": "bar"
    },
    {
        "postgrest_fooset": "bazz"
    }
]
```
```HTTP
POST /rpc/postgrest_fooset -d {"single_first":true}
HTTP/1.1 200
"bar"
```
?

**Comment by ruslantalpa** [comment]
the behaviour for the first function is correct, it returns a string, thus you get a string.
for the section function it looks like it not very good, i guess for it it should have been a array of strings.

**Comment by steve-chavez** [comment]
On master branch:
```http
POST /rpc/postgrest_fooset -d {"single_first":false}
HTTP/1.1 200
[
    {
        "postgrest_fooset": "bar"
    },
    {
        "postgrest_fooset": "bazz"
    }
]
```
```http
POST /rpc/postgrest_fooset -d {"single_first":true}
HTTP/1.1 200
[
    {
        "postgrest_fooset": "bar"
    }
]
```

**Comment by EmpireFleet** [comment]
If on master branch the topic-starting function yields
```
[ { "postgrest_foo": "bar" } ]
```
then the issue should be closed.

**Comment by EmpireFleet** [comment]
The problem, possibly, remains.
```SQL
CREATE FUNCTION postgrest_foo() returns text as $$ SELECT 'bar'::text $$ LANGUAGE SQL
```
> docker start pg_rest4_4
> curl -i -X POST localhost:3000/rpc/postgrest_foo
```HTTP
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Thu, 19 Apr 2018 13:17:07 GMT
Server: postgrest/0.4.4.0 (f9e770b)
Content-Type: application/json; charset=utf-8
Content-Range: 0-0/*

"bar"
```
> curl -i -X POST localhost:3000/rpc/postgrest_foo2
```HTTP
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Date: Thu, 19 Apr 2018 13:17:15 GMT
Server: postgrest/0.4.4.0 (f9e770b)
Content-Type: application/json; charset=utf-8

{"hint":"No function matches the given name and argument types. You might need to add explicit type casts.","details":null,"code":"42883","message":"function public.postgrest_foo2() does not exist"}
```
```SQL
CREATE FUNCTION postgrest_foo2() returns text as $$ SELECT 'bazz'::text $$ LANGUAGE SQL
```
> curl -i -X POST localhost:3000/rpc/postgrest_foo2
```HTTP
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Thu, 19 Apr 2018 13:17:24 GMT
Server: postgrest/0.4.4.0 (f9e770b)
Content-Type: application/json; charset=utf-8
Content-Range: 0-0/*

[{"postgrest_foo2":"bazz"}]
```
> docker exec pg_rest4_4 bash -c 'kill -HUP \`pgrep postgrest\`'
> curl -i -X POST localhost:3000/rpc/postgrest_foo2
```HTTP
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Thu, 19 Apr 2018 13:18:37 GMT
Server: postgrest/0.4.4.0 (f9e770b)
Content-Type: application/json; charset=utf-8
Content-Range: 0-0/*

"bazz"
```

**Comment by steve-chavez** [comment]
That's expected behavior, the db structured needs to be cached and refreshed if there's a change, for this to be automated in development there's now https://github.com/begriffs/pg_listen. There are instructions of how to use it in https://postgrest.com/en/v4.4/admin.html#schema-reloading.

**Comment by EmpireFleet** [comment]
But that means the answer to the [above comment](#issuecomment-344808968) is effectively NO

**Comment by EmpireFleet** [comment]
To be clear.
[Specification](https://postgrest.com/en/v4.4/api.html#singular-or-plural) declares
> By default PostgREST returns all JSON results in an array

but actual tests reveal that scalar function does not follow the spec (unless it's beyond PostgREST’s database schema cache)

**Comment by steve-chavez** [comment]
That's true, we should add to the docs the RPC dependency on the db cache and warn that the restart is needed.

As it is now, there's no way to differentiate scalar from row return type in the function unless we query the db cache.

I can see how that can be a problem for development environments, that's why I added the suggestion to use the utility above, however in production environments changes are done with care and there's likely some sort of CI that can do a `SIGHUP` to pgrst after the db migration, so the cache is no problem for that case, it should always be refreshed on deployment.

**Comment by EmpireFleet** [comment]
And, also, the docs should probably specify that for now scalar function returns its result in a JSON-value, not a JSON-array (which is, i suppose, breaking change from v3.2)
