### ISSUE TITLE
Things broken when jwt aud is specified

### ISSUE THREAD

**Issue by ruslantalpa** [begriffs/postgrest#1016]
This line is wrong
https://github.com/begriffs/postgrest/blob/master/src/PostgREST/Auth.hs#L42
when aud is specified and a request without jwt comes (anonymous), things break.
Also config should treat empty string for aud as Nothing (for docker.)

I have the code for this, i'll make a pr, just documenting so that we don't forget and do a release

**Comment by begriffs** [comment]
Ah man, yet another config file "empty string vs Maybe"  bug. Well hopefully it'll be the last. 😄 

Yeah send over the PR when you get the chance.

**Comment by PierreR** [comment]
By the way I would like to suggest the replacement of `configurator-ng` which is not actively maintained, not on stackage and used by one package only (you guess `postgrest`) by `[dhall](https://github.com/dhall-lang/dhall-haskell)` ?

Would such a proposition (with PR) be accepted ?

**Comment by begriffs** [comment]
@PierreR yeah I'd consider the PR as long as Dhall can interpolate environment variables into the config file, as required for our Docker setup. For instance: https://github.com/begriffs/postgrest/blob/master/docker/postgrest.conf

**Comment by PierreR** [comment]
@begriffs it can surely do that ;-)
