### ISSUE TITLE
Slow allcolumns query when DB has foreign tables

### ISSUE THREAD

**Issue by nextstopsun** [begriffs/postgrest#1020]
I've got a lot of foreign tables in my DB and postgrest takes a very long time to start. The cause is [this query](https://github.com/begriffs/postgrest/blob/master/src/PostgREST/DbStructure.hs#L329).

So when I add just one single schema in a `WHERE` clause [here](https://github.com/begriffs/postgrest/blob/master/src/PostgREST/DbStructure.hs#L434)
Like so 
```
WHERE NOT pg_is_other_temp_schema(nc.oid) AND a.attnum > 0 AND NOT a.attisdropped AND (c.relkind = ANY (ARRAY['r'::"char", 'v'::"char", 'f'::"char"])) AND nc.nspname = 'api'
``` 
It gets magnitudes faster.

Can this list of scanned schemas be added as a config param?

**Comment by begriffs** [comment]
I merged your PR, so closing this issue.
