### ISSUE TITLE
[Request] Update postgrest Docker Hub image

### ISSUE THREAD

**Issue by elimisteve** [begriffs/postgrest#1026]
v0.4.3.0 isn't there, and that's the version I need: https://hub.docker.com/r/begriffs/postgrest/tags/

Thanks!

**Comment by ruslantalpa** [comment]
Notice the docker badge in the reademe at the top, the link is different

https://hub.docker.com/r/postgrest/postgrest/

**Comment by elimisteve** [comment]
`docker pull postgrest/postgrest:v0.4.3.0` indeed, thanks :-)
