### ISSUE TITLE
Protect (up/in)serts from future key collisions

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#103]
The issue is explained [here](https://stackoverflow.com/questions/9108833/postgres-autoincrement-not-updated-on-explicit-id-inserts).

We should either forbid specifying the values of sequence columns, or run a post-insert operation to advance the sequence with `nextval()`.

**Comment by ruslantalpa** [comment]
I don't think this has ever come up in discussions as a problem and it's somehow at a deeper level (the db) so not sure PostgREST is the place to solve this.
Let's reopen when it comes up and the user can explain why it's a problem for them and they can't work around it.
