### ISSUE TITLE
Question about production

### ISSUE THREAD

**Issue by puny-d** [begriffs/postgrest#1032]
When l close ssh, the api would be "Something went wrongHTTP/1.0 500 Internal Server Error".
Any demo code about keep it on server service and auto start with system?

**Comment by begriffs** [comment]
Autostart is operating system dependent, but there's a section in the docs about keeping postgrest running after ssh closes: https://postgrest.com/en/v4.3/install.html#running-the-server

**Comment by puny-d** [comment]
thanks!
