### ISSUE TITLE
Make postgrest more advanced

### ISSUE THREAD

**Issue by puny-d** [begriffs/postgrest#1033]
Hello, I would like to move from [parse-server](https://github.com/parse-community/parse-server) to postgrest, here are some few question:

- hope there cloud be an ACL control over rest api，I know this could be done by postgresql，but it is not convenient for debug & testing

- the config support more features, like set some column readonly/(could not read) to some roles , just likes [pREST](https://postgres.rest/permissions/).

**Comment by steve-chavez** [comment]
PostgREST establishes the db as the single source of truth, having custom ACL in the config file would diverge from that and would actually give you one more thing to maintain/debug.

For seeing pg user privileges in `psql` you can use `\dp your_api_schema.*`, this coupled with pgrst error responses or [pg logs](https://postgrest.com/en/v4.4/admin.html#database-logs) should be enough for debugging privilege errors.

**Comment by steve-chavez** [comment]
I don't see how this feature request can progress, as it goes against the PostgREST philosophy, so I'll close this.

About improving debugging we could continue the discussion on #540.
