### ISSUE TITLE
Version v0.4.3.0 missing in Docker Hub

### ISSUE THREAD

**Issue by joshgummersall** [begriffs/postgrest#1037]
Just want to start by thanking you, @begriffs, for such a useful piece of software. That said, it appears that version `v0.4.3.0` is missing from https://hub.docker.com/r/begriffs/postgrest. I was able to build this version locally and verify that the build worked without issue.

Again, thanks for your time and continued efforts.

**Comment by begriffs** [comment]
The correct repo is actually https://hub.docker.com/r/postgrest/postgrest/

We link to it in a badge at the top of the readme, but you're not the first person to use the older repo. Maybe I should add a more prominent note about the move...

**Comment by joshgummersall** [comment]
That makes sense - I was using the other repo as it ranks higher in a Google search for "postgrest docker". Thanks for the correction!
