### ISSUE TITLE
Doc Improvement - Running on Windows

### ISSUE THREAD

**Issue by mithold** [begriffs/postgrest#1040]
Hello,

In the documentation (https://postgrest.com/en/v4.3/tutorials/tut0.html) It states - 

> PostgREST requires libpq, the PostgreSQL C library, to be installed on your system. Without the library you’ll get an error like “error while loading shared libraries: libpq.so.5.” Here’s how to fix it:
>Windows
>It isn't fun. Learn more here. It might be easier to execute PostgREST in its own Docker image as well.

However there is a simpler way than the suggested link. All of the DLL files that are required to run PostgREST are available in the [windows installation of PostgreSQL](https://www.postgresql.org/download/windows/) server. Once installed they are found in the BIN folder eg: C:\Program Files\PostgreSQL\10\bin

Therefore, in the documentation it could be written -

**Windows** 

1. Install PostgreSQL for windows https://www.postgresql.org/download/windows/
2. Copy PostgREST.exe into the BIN folder of PostgreSQL. eg: C:\Program Files\PostgreSQL\10\bin
3. Run PostgREST from the BIN folder. (Alternatively setup environment variable pointing to the BIN folder and run PostgREST from anywhere).

Thank you

**Comment by begriffs** [comment]
Cool, thanks for letting me know about that. Want to send a pull request to update the docs?

Also the environment variable approach sounds better than copying the postgrest binary to a special directory.
