### ISSUE TITLE
Add repository topic "automatic-api"

### ISSUE THREAD

**Issue by dbohdan** [begriffs/postgrest#1041]
Could you add the topic `automatic-api` to your repository? Software that automatically exposes APIs to databases type isn't well-cataloged. (There didn't even seem to be a GitHub list, so I [started one](https://github.com/dbohdan/automatic-api).) It will be easier to discover if there is a standard [GitHub topic](https://help.github.com/articles/about-topics/), and `automatic-api` seems as good a candidate as any. Three projects [already use it](https://github.com/topics/automatic-api).

**Comment by begriffs** [comment]
Done. 😄

**Comment by dbohdan** [comment]
Thanks!
