### ISSUE TITLE
About PGRST_SERVER_PROXY_URI

### ISSUE THREAD

**Issue by abbapappa** [begriffs/postgrest#1042]
Hi,

Is it possible to make the environment variable `PGRST_SERVER_PROXY_URI` optional? It took me half a day to figure out why a standard deployment with just `PGRST_DB_URI`, `PGRST_DB_SCHEMA` and `PGRST_DB_ANON_ROLE` isn't working.

Thanks guys!

**Comment by ruslantalpa** [comment]
what was the error? what version/image were you using?

**Comment by abbapappa** [comment]
I am running via Docker. If I run without `PGRST_SERVER_PROXY_URI`, I get:

```
postgrest: FatalError {fatalErrorMessage = "Malformed proxy uri, a correct example: https://example.com:8443/basePath"}
```

**Comment by ruslantalpa** [comment]
what is the image url/version?

**Comment by abbapappa** [comment]
I am using image `postgrest/postgrest:latest`.

```
latest: Pulling from postgrest/postgrest
Digest: sha256:cd5df30b4a7e435aafe9abeac0e4158b98df03182de5bce93823c843293223c1
Status: Image is up to date for postgrest/postgrest:latest
```

**Comment by ruslantalpa** [comment]
this has been fixed (but not released), see changelog.
#968, Treat blank proxy uri as missing - @begriffs

**Comment by abbapappa** [comment]
Great! Thank you for your very quick reply.
