### ISSUE TITLE
Ensure deprecated Docker Hub image at begriffs/postgrest is clearly announced and new location clearly visible

### ISSUE THREAD

**Issue by ahtik** [begriffs/postgrest#1049]
A good example could be https://hub.docker.com/_/elasticsearch/
What could be the easiest way to contribute this announcement to the old image description at https://hub.docker.com/r/begriffs/postgrest/ ?

Badge alone doesn't seem to be enough as people are having trouble (#1029 #1037 #1012 #982 #973) to migrate to the latest, especially as google search keeps returning the old Docker Hub link.

**Comment by begriffs** [comment]
I agree that it's causing confusion. Thanks for pointing out the elasticsearch thing as an example. I'll make some time to fix this up.

**Comment by begriffs** [comment]
OK, I updated the project info to redirect people to the new one.
