### ISSUE TITLE
When doing user management entirely through SQL, how to create a user

### ISSUE THREAD

**Issue by christiaanwesterbeek** [begriffs/postgrest#1051]
I want to support logins entirely through SQL. No use of an external service like Auth0. When following this guide (https://postgrest.com/en/v4.4/auth.html#sql-user-management) to do that, I end up with a hidden schema `basic_auth`. For checking credentials through functions, that's fine. What if I want to create new users through the REST api? The table in the schema to create the user in is hidden, so I can't do `POST /users` to create the new user.

However, I could create a function `register` similar to the function [`login`](https://postgrest.com/en/v4.4/auth.html#sql-user-management) then `grant select, create on table basic_auth.users to anon` instead of just `select`, and also `grant execute on function register(...) to anon;`.

That way I would be allowing an API request like this:

```
POST /rpc/register

{ "email": "foo@bar.com", "pass": "foobar" }
```

I'm I thinking in the right direction?

**Comment by ruslantalpa** [comment]
2 (grant create) is wrong.
Anon only needs execute on that function (no rights to the table) and you make the signup function absecurity definer.
(As before, this is implemented in the starter kit)

**Comment by christiaanwesterbeek** [comment]
Thank you. That means, I'm thinking in the right direction. Also, thank you for your starter kit! I found the [signup function](https://github.com/subzerocloud/postgrest-starter-kit/blob/master/db/src/libs/auth/api/signup.sql) too.
