### ISSUE TITLE
Resource Embedding for 'Self Joins' does not work anymore in 4.4

### ISSUE THREAD

**Issue by devguf** [begriffs/postgrest#1057]
```
CREATE TABLE person (
	id INT PRIMARY KEY,
	name TEXT,
	manager INT REFERENCES person ON DELETE RESTRICT
);
INSERT INTO person (id, name) values (1, 'Person 1');
INSERT INTO person (id, name) values (2, 'Person 2');
INSERT INTO person (id, name, manager) values (3, 'Person 3', 1);
```
The following query
`http://localhost:8080/person?id=eq.3&select=id,name,manager(id,name)`
gives with 4.3 the correct result:
`[{"id":3,"name":"Person 3","manager":{"id":1,"name":"Person 1"}}]`
In the new 4.4 version the resource is missing:
`[{"id":3,"name":"Person 3","manager":null}]`

**Comment by steve-chavez** [comment]
The regression was caused unintendenly in https://github.com/begriffs/postgrest/pull/978, there's a fix in progress here https://github.com/begriffs/postgrest/pull/1054, and in addition self join embedding now works for child relations as well(e.g. 
`GET /person?select=id,name,managees:person.manager(id,name)`).

**Comment by steve-chavez** [comment]
This is now fixed on master.
