### ISSUE TITLE
Show introspection for all endpoints, even if current permission is lacking?

### ISSUE THREAD

**Issue by canadaduane** [begriffs/postgrest#1060]
Here's what I'm trying to accomplish:
- I'm using swagger to show documentation for the API that PostgREST has so kindly created for me
- Most of the API requires a jwt token, and is therefore inaccessible to anonymous users
- When I visit the Introspection endpoint `/`, I can only see endpoints that are publicly visible

How can I configure the postgresql permissions to allow anonymous users to SEE but not USE all endpoints?

What I've tried so far:

```
GRANT USAGE ON SCHEMA beagle_api TO beagle_anyone;
```

where `beagle_anyone` is my anonymous user as declared in `postgrest.conf`: `db-anon-role = "beagle_anyone"`.

This "works" but is too permissive:

```
GRANT SELECT ON ALL TABLES IN SCHEMA beagle_api TO beagle_anyone;
```

Can I have my cake and eat it too?

**Comment by begriffs** [comment]
That's actually how things used to work until #954 caused the change in #970 so I guess we can't please everybody. 😛

**Comment by canadaduane** [comment]
Hmm, that's unfortunate. I'd like documentation to be complete and unobscured, without logging in. Perhaps this should be a configuration setting? (I'm not asking you to actually change anything, just curious about the acceptability of adding it as a config).

**Comment by canadaduane** [comment]
Interesting approach, thank you. I'm using nginx in front as well.

**Comment by rvernica** [comment]
@ruslantalpa how could one add an Authorization Bearer token field to Swagger UI? The user would then provide a token or credentials and get access to the complete API.

**Comment by respondcreate** [comment]
@rvernica That's exactly what I'm trying to implement now...did you ever figure out how to do it?

**Comment by rvernica** [comment]
No, I did not and I'm still interested in figuring it out. I was hoping to get some guidance from the postgrest team.

**Comment by steve-chavez** [comment]
@respondcreate @rvernica Not ideal, but another option is to use a chrome extension to add the header.

**Comment by Ashokrayal** [comment]
> 
> 
> @canadaduane you can have openresty in front of postgrest like here https://github.com/subzerocloud/postgrest-starter-kit
> then for your "GET /" location, you have a one line nginx config where you replace the Authorizaton heder with a hardcoded token that has all the privileges and this way postgrest will generate for you a swagger output the way you want it based on the privileges of that hardcoded JWT token

Hi @ruslantalpa,
Can you please point out where and how it is happening there?

**Comment by ruslantalpa** [comment]
it's not happening there, the link was to a repo showing nginx in front of postgrest setup, the specific configuration of nginx for this specific case it's not there (it was assumed the readers would figure out how to add a custom nginx location that adds a header).

For the starter kit setup specifically that location could look like (not tested)

placed here https://github.com/subzerocloud/postgrest-starter-kit/blob/master/openresty/nginx/rest.conf#L3

```
location = /rest {
    proxy_set_header  Authorization  " ...";
    rewrite ^/rest/(.*)$ /internal/rest/$1;
}
```
