### ISSUE TITLE
Where to store secrets in database?

### ISSUE THREAD

**Issue by canadaduane** [begriffs/postgrest#1062]
I've been following along with the excellent documentation at https://postgrest.com/en/v4.4/auth.html, and the suggested place to store app secrets is as a property of the database:

```
-- run this once
ALTER DATABASE mydb SET "app.jwt_secret" TO 'reallyreallyreallyreallyverysafe';

-- then all functions can refer to app.jwt_secret
SELECT sign(
  row_to_json(r), current_setting('app.jwt_secret')
) AS token
FROM ...
```

However, it appears that this is not allowed on Amazon RDS:

```
beagle=> ALTER DATABASE beagle SET "app.test" TO "value";
ERROR:  permission denied to set parameter "app.test"
```

(the same `ALTER DATABASE` call works locally for me).

Do you have any other suggestions for keeping app secrets in a secure place, i.e. not stored insecurely at rest?

**Comment by ruslantalpa** [comment]
Why not store them in tables?
https://github.com/subzerocloud/postgrest-starter-kit/blob/master/db/src/init.sql#L30
https://github.com/subzerocloud/postgrest-starter-kit/blob/master/db/src/libs/settings/schema.sql

It's more secure then a global env var.
Setting them as a "session var" as you've started with your PR also a good idea

**Comment by mkarnovan** [comment]
piznes vnature
