### ISSUE TITLE
filtering question

### ISSUE THREAD

**Issue by BrandonChubb** [begriffs/postgrest#1067]
Looking for some filtering advice.  Consider the following:
`create table albums (
  id integer not null primary key,
  name text not null,
  year integer not null,
  leader integer
);

create table artists (
  id integer not null primary key,
  name text not null
);

alter table only albums add constraint leadid foreign key (leader) references artists(id);

grant all on table albums to testuser;
grant all on table artists to testuser;

insert into artists values (1, 'Miles');
insert into artists values (2, 'Trane');
insert into artists values (3, 'Garland');
insert into albums values (1, 'Milestones', 1958, 1);
insert into albums values (2, 'Kind of Blue', 1959, 1);
insert into albums values (3, 'Blue Train', 1957, 2);
insert into albums values (4, 'Red Alone', 1960, 3);
`

collect all miles albums
` % curl 'http://localhost:3000/artists?name=eq.Miles&select=id,name,albums(name),albums(year)'
[{"id":1,"name":"Miles","albums":[{"name":"Milestones"},{"name":"Kind of Blue"}],"albums":[{"year":1958},{"year":1959}]}]
`
Only the 1958 Miles albums, but why list the extra year:
`% curl 'http://localhost:3000/artists?name=eq.Miles&albums.year=eq.1958&select=id,name,albums(name),albums(year)'
[{"id":1,"name":"Miles","albums":[{"name":"Milestones"}],"albums":[{"year":1958},{"year":1959}]}]
`

So this would be the starting question.... how do I filter such that I don't get the extra "year" clause for a Miles album that was NOT from the specified year?

**Comment by ruslantalpa** [comment]
your select param is not right
`http://localhost:3000/artists?name=eq.Miles&select=id,name,albums(name, year)`

**Comment by BrandonChubb** [comment]
OK that was great advice.  But I didn't quite get to the point here.   Here's a query to get all 1958 albums with Miles as leader:

% curl 'http://localhost:3000/albums?year=eq.1958&artists.name=eq.Miles&select=name,artists(name)'
[{"name":"Milestones","artists":{"name":"Miles"}}]

Perfect!  Same thing, but get the 1958 albums with Trane as a leader:

%curl 'http://localhost:3000/albums?year=eq.1958&artists.name=eq.Trane&select=name,artists(name)'
[{"name":"Milestones","artists":null}]

So there's an "extra" album listed here.  Is there a way to have both filters applied here and end up with an empty list?

**Comment by ruslantalpa** [comment]
Mot possible out of the box
See https://github.com/begriffs/postgrest/issues/696#issuecomment-239876019

**Comment by ruslantalpa** [comment]
If your case is exactly as in your examole then you can request artist and embed albums and get the results you want

**Comment by BrandonChubb** [comment]
We're trying to allow the most freedom for the end user -- which could include more arbitrary searches than a pre-canned function would allow.  Given that we could design SQL to apply all the conditions to filtering the main table, it seems like it should be possible to do the same with postgREST.  Are there technical obstacles to providing this functionality, or is it just a resource/priority problem?
