### ISSUE TITLE
Blank role does not exist

### ISSUE THREAD

**Issue by kishyr** [begriffs/postgrest#1083]
Hi,

I just set up a brand new Postgres database instance on Azure and am running Postgrest from a docker container. On my local machine Postgrest talks to the database fine and works great. The moment I point the Postgrest docker container to the production Postgres database instance, I get the following error for every API call:

```
{
  "hint": null,
  "details": null,
  "code": "22023",
  "message": "role \"\" does not exist"
}
```

Any idea where I can start to debug this? I've double checked all my settings. Postgrest can definitely connect to the db instance (I get a `Connection successful` message in the logs).

**Comment by kishyr** [comment]
Using the latest version of the official Postgrest docker container fixes this.

**Comment by begriffs** [comment]
The role is part of the connection string you use to connect to the db, so my guess is that it was blank. I see you closed the issue, is that what the problem was?

**Comment by kishyr** [comment]
It worked on my local machine because the docker image was built a few months ago using an older version of postgrest, before the PGRST_ prefix. The newer docker image that my server used required the new prefix and once I added it in, it worked as normal. 

On 12 March 2018 at 17:28:29, Joe Nelson (notifications@github.com) wrote:

The role is part of the connection string you use to connect to the db, so my guess is that it was blank. I see you closed the issue, is that what the problem was?
