### ISSUE TITLE
Debug configuration option for more informative error messages

### ISSUE THREAD

**Issue by nathan-rice** [begriffs/postgrest#1084]
I recently ran into an issue where a query was failing because of a bad trigger, and I had to re-create the insert statement postgrest was executing to see the problem.  The post reply only contained the following information:

`ERROR:  column "type" does not exist`

While psql was much more informative:

```
ERROR:  column "type" does not exist
LINE 1: SELECT type, name                                 FROM compa...
               ^
QUERY:  SELECT type, name                                 FROM companies WHERE NEW.company_id = id
CONTEXT:  PL/pgSQL function configure_user_after_insert() line 13 at SQL statement
```
Since more verbose errors by default could potentially be a security risk, it would be helpful to have a "debug mode" configuration variable that can be set to display more informative error messages like the above.

**Comment by begriffs** [comment]
One thing you can do is increase the verbosity of the database's log itself. There's a section about that in https://postgrest.com/en/v4.4/admin.html#database-logs

Then if weird things happen you can review a log of exactly what statements postgrest executed.

**Comment by steve-chavez** [comment]
For now I'm also on the side of just checking the db logs, but we can continue the discussion in #540.
