### ISSUE TITLE
Plans to support OpenAPI 3.0

### ISSUE THREAD

**Issue by ranjanprj** [begriffs/postgrest#1096]
Hello Guys, thanks for this wonderful project.
Just wanted to know if there are plans to supporting OpenAPI 3.0

**Comment by steve-chavez** [comment]
What would be the advantages of moving PostgREST to OpenAPI 3.0?

As far as I've seen the OpenAPI changes are mostly renaming/regrouping the metadata, don't see in what way this would benefit PostgREST.

**Comment by steve-chavez** [comment]
Let's continue the discussion in #932.
