### ISSUE TITLE
Expose stored procedures 

### ISSUE THREAD

**Issue by alexpdp7** [begriffs/postgrest#114]
There's stuff that cannot be done well through views, such as a full text search. Stored procedures are not very RESTful, but I think it would be useful.

**Comment by begriffs** [comment]
How would you suggest the routes should look for the procedures and their arguments?

**Comment by adambaker** [comment]
Here's a possibility:
```POST /procname?args=[abc,123,etc]```
Could result in a query like:
```select procname('abc'::unknown, '123'::unknown, 'etc'::unknown)```

This could be distinguished from a POST intended to insert to table `procname` by the presence of `args`. As far as I know, inserts to tables don't accept query parameters in the POST.

**Comment by alexpdp7** [comment]
I think both GET and POST should be allowed; GET for query-like SPs, following as much as possible the regular query routes (minus the eq, gt, thing...). You can have a function named like a table, but it would be nice if you could substitute a table/view with an SP transparently.

POSTs would be SPs which do stuff, not a fan of @adambaker 's proposal- I'd rather have SP params as POST params.

**Comment by awildeep** [comment]
This would be **awesome**.  

The real key would be supporting set returning functions for me that depend on PostgreSQL types.  

I think that a POST with a data payload defining the arguments makes the most sense.  Getting the meta data for an OPTION call could be a bit tricky however, but should be doable.   But you should be able to even reference the stored procedures argument names to allow for arbitrary argument order in the payload.   If they are not defined they simply would have to be presented in the order given.

```
CREATE OR REPLACE FUNCTION my_sp(input_a varchar,
                                                  input_b varchar)
RETURNS varchar AS $$
BEGIN
    RETURN input_a || input_b;
END;
$$ LANGUAGE plpgsql;
```

Could be called with:
```
POST /my_sp
```
and a payload of (I assume the payload format would be standard HTTP, not JSON, but this does not matter to me):
```
input_a: value1
input_b: value2
```

The return structure is a bit tricky.  In the example above I am returning a singular value, but it could be a set of data.  In this case I would think the data would be labeled as a set of the function name.   Ideally a set returning function would be able to identify a type defined for the set and use that to label the return correctly.

**Comment by awildeep** [comment]
Here is an example of a trivial SP that returns a set:
```
CREATE TYPE my_custom_return_type AS (col_a int, col_b varchar);

CREATE OR REPLACE FUNCTION my_set_sp() RETURNS SETOF my_custom_return_type AS
%
DECLARE
ret holder%rowtype;
BEGIN
    FOR r IN SELECT a, b FROM source_table LOOP
        RETURN NEXT ret;
    END LOOP;
    RETURN;
END
%
LANGUAGE 'plpgsql';
```

**Comment by begriffs** [comment]
There are a few reasons I am worried about this feature. First as @alexpdp7 mentioned, it's RPC (as opposed to REST) pretty much by definition. The action of POSTing to these resources is mysterious and neither standard nor self-documenting. Can the system inspect a the return type to tell the client what the response will look like?

The examples of concatenation and selecting from a table are not themselves compelling, although full text search certainly is. Might there be a way to expose an interface for full text search without opening the whole can of worms of arbitrary stored procedures?

**Comment by darsana** [comment]
CREATE TYPE typ_checkEmailExists As(
  user_id  integer,
  party_id integer
);


CREATE OR REPLACE FUNCTION  fn_checkEmailExists(username varchar) 
RETURNS SETOF typ_checkEmailExists AS
$$
	declare
	sql varchar;
	user_rec typ_checkEmailExists;
BEGIN
	sql:=' SELECT  user_id AS "UserId",  party_id AS "PartyId" FROM user_data
	WHERE username = '''||username||'''';

	raise info'sql --> %',sql;
	FOR user_rec IN EXECUTE sql
	LOOP	
	return next user_rec;
	END LOOP;
end;
$$
LANGUAGE 'plpgsql';


Hai, here i created a function to fetch user id from user_data table by passing username  as a parameter to the function ,and i called the function like bellow

{
"sql": "select * from fn_checkEmailExists('test123@gmail.com')" 
}

but i am getting error code like this
{
    "length": 95,
    "name": "error",
    "severity": "ERROR",
    "code": "42703",
    "position": "37",
    "file": "parse_expr.c",
    "line": "768",
    "routine": "transformColumnRef"
}
This kind of error coming only kind of functions which accepts the strings as parameters ,Any help please ..

**Comment by Brent-Tucker** [comment]
Maybe something similar to this
https://github.com/cthulhuology/pgproc.js
 https://github.com/cthulhuology/pgproc.http.js

**Comment by begriffs** [comment]
Here's a proposal: expose each stored procedure in `/rpc/proc_name` and make them each accept only the post verb with json objects. It would would use the keys and values to call the procedure using [named notation](http://www.postgresql.org/docs/9.4/static/sql-syntax-calling-funcs.html#SQL-SYNTAX-CALLING-FUNCS-NAMED). Query params would be free to work as they do for views/tables, by filtering rows if the procedure generates a table-like output.

So why the `/rpc` prefix?  One reason is to avoid name collisions between views and procedures. It also helps emphasize to API consumers that these functions are not normal restful things. The functions can have arbitrary and surprising behavior, not the standard "post creates a resource" thing that users expect from the other routes.

I am considering allowing GET requests for functions that are marked non-volatile but then how do we pass in parameters? It seems nicer to always send params in the same way (through a post body).

Any thoughts before I jump in and start coding?

**Comment by snuxoll** [comment]
For the most part a function that would be suitable for a GET request could likely be implemented entirely as or used in a view - as a result I think restricting the `/rpc` prefix to POST requests is appropriate.

**Comment by riaanvddool** [comment]
>It would would use the keys and values to call the procedure using named notation.

>I am considering allowing GET requests for functions that are marked non-volatile but then how do we pass in parameters? It seems nicer to always send params in the same way (through a post body).

>Any thoughts before I jump in and start coding?

Would passing the parameters using HTTP headers (rather than in the POST body) not be an option that would support POST and GET in the same way?

**Comment by alexpdp7** [comment]
> I am considering allowing GET requests for functions that are marked non-volatile but then how do we pass in parameters? It seems nicer to always send params in the same way (through a post body).
>
> Any thoughts before I jump in and start coding?

I think GET and POST work differently wrt. to parameters and going against that is a pain. GET parameters should be in the URL, POST parameters in the http request body.

**Comment by snuxoll** [comment]
> I think GET and POST work differently wrt. to parameters and going against that is a pain. GET parameters should be in the URL, POST parameters in the http request body.

They in essence work the same way depending on the implementation, in a GET request you request a URL `/rpc/my_function?param1=a&param2=b`

But in a POST you can request `/rpc/my_function` and then submit `param1=a&param2-b` in the body, this is the default used by HTML forms.

**Comment by begriffs** [comment]
There is a complication in that the params of a GET can be used to filter result columns as well, so if a function param's name conflicted with a column name in the result there would be ambiguity.

**Comment by eric-brechemier** [comment]
How about allowing `GET` to be used to call functions without parameters?

My use case is to use functions instead of views because 

> Access to tables referenced in the view is determined by permissions of the view owner.
— http://www.postgresql.org/docs/current/static/sql-createview.html

and not the view user, which prevents role level policies defined for the calling user to apply.

Functions on the other hand, unless defined with `SECURITY DEFINER` option, will run with the privileges of the calling user, including row level policies for access to tables referenced in the function.

**Comment by snuxoll** [comment]
@eric-brechmier Any reason to not use security barrier views instead?

**Comment by eric-brechemier** [comment]
@snuxoll > Any reason to not use security barrier views instead?

Instead of row level policies? We use a set of different policies which get combined in a transparent way depending on which group the current user is part of. This would be more complex to express all at once, and we don't want to duplicate the row level policies defined for the table at the level of the view defined on top.
