### ISSUE TITLE
Support more normal restful URLs?

### ISSUE THREAD

**Issue by joevandyk** [begriffs/postgrest#116]
I believe now, I have to do the following to update a row with `id=4`.
```
curl -X PATCH -d '{"email": "joe-new@tanga.com"}' http://localhost:3000/foos?id=eq.4
```

Would be nice to be able to do something like:
```
curl -X PATCH -d '{"email": "joe-new@tanga.com"}' http://localhost:3000/foos/1
```

**Comment by begriffs** [comment]
When a table's primary key is compound this won't be possible, but I suppose it would be convenient to allow your proposed syntax when dealing with a simple numerical key. I'll look into this.

**Comment by joevandyk** [comment]
What about a specially formatted comment on the view? 

Could you check for that, and if it's present, then postgrest would support that key?

**Comment by begriffs** [comment]
Sounds interesting, can you elaborate? Like you would add a comment saying "the primary key column on this table is simple and named xyz"?

**Comment by joevandyk** [comment]
Right, something like:

`COMMENT ON COLUMN "1".my_table.my_primary_key IS 'Postgrest primary key;`

**Comment by begriffs** [comment]
Actually it's even easier than that. We can consult Postgres' information tables directly:
https://github.com/begriffs/postgrest/blob/master/src/PgStructure.hs#L88-L101

We would just have to modify the router to check this structural information. Currently it naively shifts the burden of identifying column filters to the client.

**Comment by joevandyk** [comment]
Does that work on views?

**Comment by begriffs** [comment]
Good point, I just tried it and it does not work for views. Which has some bad implications for the way I have POST and PUT check that a full primary key has been provided.

**Comment by adambaker** [comment]
I think this particular feature is a nice-to-have, so I'd put it on the back burner.

First, note that this could conflict with other routes. For instance, for semantic and caching reasons, we are going to move getting the table info from `OPTIONS /[table]` to some sort of GET request, probably something like `GET /[table]/meta`, which would now be ambiguous. We'd have to resolve the ambiguity in favor of getting meta information, so if you had an id `meta`, you'd be forced to use the old `GET /[table]/id=eq.meta`.

Here are a couple of options I see though:
1) Have `/[table]/[id-value]` just be a shorthand for `/[table]?id=eq.[id-value]`. No smarts, just a convention: use this syntax with the `id` column, or not at all.
2) Have the app figure out what the primary key for the table (or view) is. Then, for a simple primary key, `/[table]/[pk-value]` can be shorthand for `/[table]/[pk]=eq.[pk-value]`. For tables with complex primary keys, or for which we cannot determine a pk, one would have to always use the longhand.
3) Comment on a column or table. To me the complexity seems to outweigh the value of the feature, unless we end up needing to inspect that kind of comment for another more important feature.

**Comment by joevandyk** [comment]
Could the endpoint for the table info be something like `/postgresrt/[table]`?

**Comment by begriffs** [comment]
I've always kind of liked OPTIONS and thought it was the best way to describe a resource, but then I read [this article](https://www.mnot.net/blog/2012/10/29/NO_OPTIONS) which argues there's another way to describe resources using header links and a separate endpoint. One thing about OPTIONS is they are not allowed to be cacheable. Issue #56 has a few more notes. I'm thinking it might be best to restrict OPTIONS to describing the allowed verbs on a resource and for CORS.

But about the `?id=eq.1` url format -- other than it being unusual does it cause problems with javascript libraries you'd like to use to access the data from the client or is this something you can work around for the time being?

**Comment by joevandyk** [comment]
It's not causing me any problems, it was just an idea I had. :)  

Using something like http://tools.ietf.org/html/rfc5785 might be nice to avoid conflicts.

**Comment by begriffs** [comment]
I think the amount of effort on this feature may not be worth the payoff. The `/foos/1` is more customary but not actually more "restful" than `/foos?id=eq.1`. Plus the latter scales to compound keys and maintains a uniform way of filtering keys vs other columns.

I'm closing this issue. If you feel strongly about it we can re-open and discuss.
