### ISSUE TITLE
Allow default schema override

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#117]
It picks "1" right now, but we can add a command-line option to pick another to make it easier to run from an existing db with no changes necessary.

**Comment by karthiksibox** [comment]
Will it be possible to make schema part of the http request instead of "command-line option" so a single server can handle multiple schemas?

**Comment by begriffs** [comment]
You can change the schema through the HTTP accept header ([documented here](https://github.com/begriffs/postgrest/wiki/API-Versioning)). Does that do what you want, or do you have something else in mind?

**Comment by chumpalump** [comment]
Here is our scenario-- we have separate APIs for different vendors.  We do this to narrow the scope of potential security problems, and often the different APIs have different rate limiting needs.  It seems like a command-line parameter which can tell the server process exactly which search-path to server would elegantly solve our problem.  The existing client-side choice is needed for maintaining legacy compatibility as your code-base grows.  Server-side search paths would allow multiple APIs for one database, which avoids increasing security complexity and allows flexible network operations for internal versus public APIs.

**Comment by begriffs** [comment]
Have you considered creating different db roles for the different vendors? If a role does not have access to a table or view then postgrest hides it from the client. That way you aren't having to define a special version of the api for different vendors -- the api gets restricted automatically with the vendors' permissions.

However if the actual columns of views differ per vendor then I can see how you need to use different versions. It is certainly feasible to add the command line argument like you suggest, but I just want to double check that there isn't an easier way for you.

**Comment by chumpalump** [comment]
It would work in theory.  In practice, it's fussy to have to test our slowly-evolving public API every time our rapidly evolving internal API changes.  The other issue is our internal API (accessed via ssl client cert) has different rate limits than our vendor APIs (accessed via https with API key header).   Nginx can proxy for each at their assigned port, but perhaps both URLs could be mapped to the same port.  Seems odd though.

**Comment by begriffs** [comment]
Another approach would be to allow the "version" to be an arbitrary string rather than a number, so you could have schemas `client-a-1`, `client-a-2` etc. Would you prefer this to setting a schema search path from the command line?

**Comment by begriffs** [comment]
Here is how I'm planning to address this issue. Rather than allowing versions to be arbitrary strings as mentioned above, they can only be numbers. However I would add a command line param to specify the "default schema" which is what would be selected when clients either do not specify a version in their requests, or if they specify version 1. Thereafter if you want to release a new version of your API you would create a schema called `2` and override things as described in the [versioning wiki](https://github.com/begriffs/postgrest/wiki/API-Versioning).
