### ISSUE TITLE
query on json

### ISSUE THREAD

**Issue by andelo** [begriffs/postgrest#118]
How do you select on json attribute/value ?
```
http://127.0.0.1:3000/test?data->>fullname=eq.Davy%20Jones
```
produces
```
{"status":"Fatal error","hint":null,"code":"42703","message":"column \"data->>fullname\" does not exist"}
```

**Comment by ludwigschubert** [comment]
From what I get so far you don't use `data->>`. In your example you would simply request 

```
http://127.0.0.1:3000/test?fullname=eq.Davy%20Jones
```

You can try `https://postgrest.herokuapp.com/sessions?location=eq.The%20Gym` live.

@begriffs _Fascinating_ project.

**Comment by andelo** [comment]
```data``` is the name of a column containing a json object ```{fullname:"string",...}```

**Comment by ludwigschubert** [comment]
@andelo thanks for the clarification. In this case this question is a little over my head, but from looking at [the PostgreSQL documentation](http://www.postgresql.org/docs/9.3/static/functions-json.html) and the [opCode matching statement](https://github.com/begriffs/postgrest/blob/9712549d6472ed7c0c4a8f61501c249192ff3ec1/src/PgQuery.hs#L149) I'd guess the JSON Operators query operators are not yet supported.

I just discovered this project an hour ago, though, so hopefully @begriffs could chime in.

**Comment by PierreR** [comment]
:+1:

**Comment by begriffs** [comment]
Sure, I can add support for `->`.

One question though, have you considered normalizing the data so it is stored in multiple columns rather than as JSON within a single column?

**Comment by andelo** [comment]
In a real scenario I would create a more robust data model.
But for my test code, no.

**Comment by adambaker** [comment]
There currently are many, many options that postgresql gives for filtering the results of a query that are not supported by postgrest. To some degree this is because this is a minimal viable product release, with more features on the way. For instance, we definitely want to make it easy to include a IN clause in a GET/PATCH request, eg:
```GET /items?id=in.[1,3,11,24]```
should generate:
```select * from items where id in [1,3,11,24]```
(but with the query properly parametrized, of course.

Support for schemaless columns like this is an advanced feature that to some extent runs against the philosophy of postgrest: use the database to model your application domain as much as possible. It'd be a cool feature to have, but I'm unlikely to give it priority. If someone were gracious enough to send us a pull request implementing this, I wouldn't turn it down...

**Comment by begriffs** [comment]
@PierreR can you tell me more about your use-case for using the postgres json column operations? It seems like it certainly has its uses but I'm trying to prioritize between this and other features.

**Comment by PierreR** [comment]
At my work Postgresql is an emerging standard. We are really interested in using the new `jsonb` feature for a couple of projects. I really would like to propose `postgrest` and I suspect that `jsonb` support would be a real plus.

Then I will need that feature for a personal project of mine later on this year.

So nothing urgent really. I will keep an eye on the project and hope to make use of it quite soon.

Thanks for your support. `postgrest` looks amazing !

**Comment by begriffs** [comment]
@PierreR I've just finished some other features and can take a look at the jsonb support soon. Any plans to try postgrest for your personal project?

**Comment by PierreR** [comment]
I would love to say yes but I am quite busy with other things ;-)

Following the spirit of [this article](https://blog.compose.io/is-postgresql-your-next-json-database/) I would start by implementing the "read" (query) feature.

Hope this is helpful.

Cheers,

**Comment by thorstenz** [comment]
@begriffs fascinating project!

jsonb support with --> access and 
ability to query with the in clause 
would be great.

**Comment by arunnairmr** [comment]
@begriffs Did you implement this feature? If yes give me a sample get API. I am still getting the same error as above.

**Comment by begriffs** [comment]
Sorry I haven't implemented it yet.

**Comment by arunnairmr** [comment]
ok. Can you implement it fast ? we get stuck on this problem.

**Comment by begriffs** [comment]
@arunnairmr would next Monday be too late for you? During this week I'm busy with some other things but I can add this issue to my weekend todos.

**Comment by arunnairmr** [comment]
@begriffs OK. we are waiting for your new update.all the best.
