### ISSUE TITLE
No command 'postgrest' found

### ISSUE THREAD

**Issue by john-qin** [begriffs/postgrest#122]
I downloaded postgrest-0.2.4.10.tar.xz to my ubuntu 14.04 server. then i run the following command to install it.

postgrest  --db-host localhost  --db-port 5432     \
           --db-name my_db      --db-user postgres \
           --db-pass foobar     --db-pool 200      \
           --anonymous postgres --secure           \
           --port 3000

I got the following error message.  what did I do wrong?

No command 'postgrest' found, did you mean:
 Command 'postgres' from package 'postgres-xc' (universe)

**Comment by adambaker** [comment]
Is postgrest in your PATH?

Perhaps cd into the path where you extracted the binary and try `./postgrest` instead

**Comment by begriffs** [comment]
Also have you decompressed the binary from the tar file?

```bash
tar xf postgrest-0.2.4.10.tar.xz
```

**Comment by john-qin** [comment]
I decompressed the file.  got this new error message. how do i fix it?

-bash: ./postgrest-0.2.4.10: cannot execute binary file: Exec format error

**Comment by john-qin** [comment]
another quick question. what is --anonymous postgres and why we need it?  we already provide username and password --db-user postgres --db-pass foobar

**Comment by begriffs** [comment]
Are you on Mac or Linux? Make sure you downloaded the binary to match your operating system.

If you like you can pick `anonymous` to be the same role as `db-user`. The `db-user` role is what is used to check passwords and switch roles if someone tries to authenticate. If the client does not try to authenticate (does not send HTTP Basic auth headers) then Postgrest executes their queries as the `anonymous` role.

**Comment by john-qin** [comment]
I am using ubuntu 14.04. and download the right version.  Here's what I did step by step.  Dont know why still couldn't get it to work.


vagrant@vagrant-ubuntu-trusty-32:~$ wget http://bin.begriffs.com/dbapi/heroku/postgrest-0.2.4.10.tar.xz
--2015-01-13 01:37:51--  http://bin.begriffs.com/dbapi/heroku/postgrest-0.2.4.10.tar.xz
Resolving bin.begriffs.com (bin.begriffs.com)... 54.231.232.89
Connecting to bin.begriffs.com (bin.begriffs.com)|54.231.232.89|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4284312 (4.1M) [binary/octet-stream]
Saving to: ‘postgrest-0.2.4.10.tar.xz’

100%[=====================================================================================================================>] 4,284,312   1.68MB/s   in 2.4s   

2015-01-13 01:37:59 (1.68 MB/s) - ‘postgrest-0.2.4.10.tar.xz’ saved [4284312/4284312]

vagrant@vagrant-ubuntu-trusty-32:~$ ls
db  postgrest-0.2.4.10.tar.xz
vagrant@vagrant-ubuntu-trusty-32:~$ tar xf postgrest-0.2.4.10.tar.xz
vagrant@vagrant-ubuntu-trusty-32:~$ ls
db  postgrest-0.2.4.10  postgrest-0.2.4.10.tar.xz
vagrant@vagrant-ubuntu-trusty-32:~$ postgest
postgest: command not found
vagrant@vagrant-ubuntu-trusty-32:~$ ./postgrest-0.2.4.10 
-bash: ./postgrest-0.2.4.10: cannot execute binary file: Exec format error
vagrant@vagrant-ubuntu-trusty-32:~$ ./postgrest-0.2.4.10 --db-host localhost --db-port 5432 --db-name appmonkey --db-user appmonkey --db-pass foo123456 --db-pool 200 --anonymous appmonkey --secure --port 3000
-bash: ./postgrest-0.2.4.10: cannot execute binary file: Exec format error

**Comment by begriffs** [comment]
What's your CPU architecture? The binary on the readme was built for x86 64-bit.

**Comment by john-qin** [comment]
got it. i am running ubuntu trusty 32. no wonder it wont work. let me try it on 64 bit. thanks for  your help

**Comment by john-qin** [comment]
begriffs, thanks alot for your help. I got it working , but still have one more issue.

$ ./postgrest-0.2.4.10  
--db-host localhost 
--db-port 5432 
--db-name appmonkey 
--db-user appmonkey 
--db-pass Abcd1234567 
--db-pool 200 
--anonymous postgres 
--port 3000
WARNING, running in insecure mode, auth will be in plaintext

when I test it using postman, i got following error message.  postgres is the default superuser, what permission does it need? btw, I have another user called "appmonkey" and its the owner of "appmonkey" database.

{
"status": "Fatal error",
"hint": null,
"code": "42501",
"message": "permission denied to set role \"postgres"
}

**Comment by begriffs** [comment]
What's happening is that you've chosen the user `appmonkey` to do the authentication. A request arrives without credentials and postgres tries to switch to the anonymous role which you've specified as `postgres`. It attempts to do a `set role` command as appmonkey, but that account does not have the permissions that postgres does, so the database forbids it to switch roles to a more powerful account.

What you need to do is choose a `--db-user` which is at least as powerful as the anonymous role. In your case you could set both `db-user` and `anonymous` to be postgres.

**Comment by john-qin** [comment]
finally got it to work, thank you
