### ISSUE TITLE
Is the auth id passed through to triggers to set rows as owned by particular user?

### ISSUE THREAD

**Issue by pvdvreede** [begriffs/postgrest#123]
Just wondering if the auth system allows me to attribute a particular record to an id from the auth table, rather than just the role name?

When I had a play using `current_user` in a trigger it gave me the role name that a particular user id was assigned. Obviously this is what you want for authentication to tables, schemas etc, but it would be good to be able get the id of the logged in user for auditing/record ownership along with the role they are in etc.

Not sure if this can be done, or I'm doing it wrong...?

**Comment by begriffs** [comment]
That's a good point. Right now the database can see only the user's role. It can't see anything about the credentials they used when making the web request.

One idea could be to ensure that when a user gets created in the auth table the system creates a new role for them too. Maybe we add a parameter to say what base roles these user roles inherit from (e.g. `author` for a blogging platform).

Another option would be to make a view in the `pg_temp` schema which contains specific login information. This is a schema that lasts for only the duration of a connection. Although the app uses a connection pool so we would have to be vigilant about erasing the schema between http requests.

Do you like either of these options?

**Comment by pvdvreede** [comment]
I like the first option as it uses the native postgres auth system. A role is created for each user and that role is granted or inherited rights from a group role. This way it seems like I can keep all the auth rules in a single group, but can still use the native `current_user` functionality in triggers, views etc.

Not knowing postgres that well, is there any concern with having lots of roles in the system, for cases where you might have 100's or possibly 1000's of people using the system?

**Comment by begriffs** [comment]
So we could leave the interface for creating new web logins the same, except have it create an additional [login]_role role that inherits from whatever role was specified in the http post. I don't think that keeping large numbers of roles around is an issue, or at least I've never heard of any problems arising from it.

Also if you're creating a few users by hand you could just create specialized roles for each before creating the logins. Depending on your use case it could get you by while this feature is added.

**Comment by pvdvreede** [comment]
That idea sounds good. It sounds like the way to go. 

Could the template for the role name perhaps be `[login]_user` instead of `[login]_role`? It would help me out in easily seeing it is a specific user role, rather than a group role...

**Comment by framp** [comment]
Another solution could be simply setting a `user_vars` when we open the connection.

    SET user_vars.user_id = ID; 
    SHOW user_vars.user_id; 

In this way we keep our roles system untouched and we can use both the role and the user id in our trigger

**Comment by pvdvreede** [comment]
@framp that sounds like a good idea.

**Comment by begriffs** [comment]
Ah yeah I like that, just set the user_id variable upon connection and erase it for anonymous connections. There are a few issues I want to work on first like #188 and #114.

If anybody wants to get started on this issue and send a pull request I'd be happy to look at it though.

**Comment by framp** [comment]
I'll try to look into this next weekend and I'll be happy to come up with a PR
