### ISSUE TITLE
how to auto start postgrest when server restarts?

### ISSUE THREAD

**Issue by john-qin** [begriffs/postgrest#124]
I am using ubuntu 14.04. in rc.local, i added the following command line. but not working, still need to manually run it once server restarts. what else can i do ?

/home/vagrant/postgrest-0.2.4.10  --db-host localhost --db-port 5432 --db-name appmonkey --db-user postgres --db-pass Abcd1234567 --db-pool 200 --anonymous postgres --secure --port 3000

**Comment by begriffs** [comment]
You could try hooking into `init.d` - http://jonathonhill.net/2009-04-23/auto-start-a-shell-script-on-ubuntu-server/

**Comment by begriffs** [comment]
Did this suggestion work for you?
