### ISSUE TITLE
I just want to know how to delete a record....

### ISSUE THREAD

**Issue by fate-lovely** [begriffs/postgrest#125]
in my MBP,postgrest works very well when I inserted and updated records,but when I tried to delete some records using `DELETE http://locahost:3000/comments?id=eq.1` or `DELETE http://localhost:3000/comments` , I got `404 NOT FOUND`.(I am sure the permissions are ok)

I don't know why.It's strange,maybe I think my parameters are wrong?

**Comment by begriffs** [comment]
Oops, I overlooked that verb. :)

It'll be added to version 0.2.5.0 and released momentarily.
