### ISSUE TITLE
Enable SSL encrypted DB connection to RDS

### ISSUE THREAD

**Issue by jensfinnas** [begriffs/postgrest#126]
I'm setting up Postgrest on Heroku with an Amazon RDS instance as backend. I'm making a simple webapp that writes to the database as users complete a form. Works great, but I have a few questions. 

Thinking about security. I want to make sure that only requests coming from my site, via Postgrest can write to the database. Can I restrict Postgrest to only listen to request from authorized domains?

Also thinking about security in between Heroku and Amazon RDS. Does Postgrest support SSL encryption (as described here: https://reinteractive.net/posts/128-heroku-app-backed-by-an-aws-rds-postgres-database)?

**Comment by adambaker** [comment]
RE: security, one approach would be to add a role with no read or write permissions, and make that your anonymous role (the `-a|--anonymous` option). This will force all requests to authenticate to see anything of value.

Another approach would be to set up a reverse proxy such as nginx. That may not be possible on heroku though.

We don't have any plans for a domain whitelist, but if enough people asked for it we might put it on our to do list.

RE: SSL between RDS and Heroku. I don't really know much about that. I don't see anything that requires the actual app to change to make that work, so I don't see any reason those instructions wouldn't work. But if you can point me to some specific feature of the app that's needed to do this, I'll try to make it happen.

**Comment by adambaker** [comment]
oh, I see. You need to be able to add the certificate to your app's repo. I'll look into this.

**Comment by begriffs** [comment]
@jensfinnas this does seem like an important security measure. So it looks like it requires three things: setting a Heroku config variable, modifying the database connection uri, and hosting a `pem` file in a config folder in the server filesystem. I think I could modify the [postgrest buildpack](https://github.com/begriffs/postgrest-heroku) to take another parameter which is a url to download the pem file. If that url is present it could install it. If I make these changes to the buildpack are you willing to help me test it and see if it works?

**Comment by begriffs** [comment]
@jensfinnas sorry I haven't prioritized this issue. There were a lot of other things to deal with. But it may be almost time to investigate it more. Care to join the project chat room? https://gitter.im/begriffs/postgrest

**Comment by begriffs** [comment]
@jensfinnas nowadays PostgREST supports a full db connection string, so you can include an `sslmode` parameter as suggested by the article you linked. Also we use libpq so it should pick up files like

```
~/.postgresql/postgresql.crt
~/.postgresql/postgresql.key
```
[etc](http://www.postgresql.org/docs/9.5/static/libpq-ssl.html#LIBPQ-SSL-FILE-USAGE).

Can you please try again and see if this works for you? If so I'll add it to our docs.

**Comment by jensfinnas** [comment]
Great work Joe.

Unfortunately I don't have the app at hands at the moment so I won't be
able to test it easily.

2016-04-03 23:19 GMT+02:00 Joe Nelson <notifications@github.com>:

> @jensfinnas <https://github.com/jensfinnas> nowadays PostgREST supports a
> full db connection string, so you can include an sslmode parameter as
> suggested by the article you linked. Also we use libpq so it should pick up
> files like
>
> ~/.postgresql/postgresql.crt
> ~/.postgresql/postgresql.key
>
> etc
> <http://www.postgresql.org/docs/9.5/static/libpq-ssl.html#LIBPQ-SSL-FILE-USAGE>
> .
>
> Can you please try again and see if this works for you? If so I'll add it
> to our docs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/begriffs/postgrest/issues/126#issuecomment-205057847>
>



-- 
...
Jens Finnäs
Journalism++ Stockholm
+46 76 901 7438
jplusplus.se

**Comment by begriffs** [comment]
I'm assuming what I described will address the issue, so closing it.
