### ISSUE TITLE
Provide graphical entity-relation diagram

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#13]
If the client requests `/` with the right accept headers, use graphviz to serve a graphical representation of the tables and key relations.

**Comment by smilliken** [comment]
An implementation in Python: https://bitbucket.org/zzzeek/sqlalchemy/wiki/UsageRecipes/SchemaDisplay. The rendered visualizations are ok, but often cluttered and awkward.

**Comment by astewart-twist** [comment]
This one is pretty nice: https://github.com/Alexis-benoist/eralchemy

**Comment by ruslantalpa** [comment]
This can be implemented outside PostgREST.
For example, Take this query https://gist.github.com/ruslantalpa/b2f10eb1b5f6dd0fc1c154e071a1c91b
which does the same kind of introspection as PostgREST, format it a bit to return a GraphQL type schema output, make it a view, then use something like https://apis.guru/graphql-voyager/ to visualize it
