### ISSUE TITLE
Please add support for recent versions of optparse-applicative

### ISSUE THREAD

**Issue by peti** [begriffs/postgrest#131]
It would be very convenient for us in NIxOS if we could `postgrest` with the default version of `optparse-applicative`: http://packdeps.haskellers.com/feed?needle=postgrest.

**Comment by begriffs** [comment]
OK, I'll look into this in combination with #130.

I'll also try adding packdeps as a step in continuous integration so that packages never get out of date.

**Comment by peti** [comment]
Thank you very much! The package now compiles fine: http://hydra.cryp.to/build/537202.

**Comment by begriffs** [comment]
Cool! I'm glad you pointed out the outdated packages.

Two questions. Would there be a way to let Hydra create my binaries for me and host them for download? Right now I build them manually, upload to S3, and update the links on the readme which is time consuming.

Also the postgrest hackage page links me to a [nix hydra status page](http://hydra.nixos.org/job/nixpkgs/haskell-updates/haskellngPackages.postgrest.x86_64-linux#tabs-status) that shows failed builds of 0.2.5.0. Will it get around to trying 0.2.5.3 or has it given up on this package?

**Comment by peti** [comment]
Hydra creates binary packages for every release you make on Hackage. The trouble with those binaries is that they won't work easily on any system that doesn't have Nix installed, because our directory structure is vastly different from that of traditional Linux distributions. I know that some Nix users have set up chroot builds that use Nix to compile binaries for Ubuntu, Debian, etc. As a matter of fact, the releases for the Nix package are built that way so that people from other distributions can use Nix. I don't know much about how that works, though, I'm afraid. I know it's possible, but I don't know how it's done.

About your second question: hydra.nixos.org typically lags two or three days behind the current `HEAD` of the Nixpkgs git repository. By now, you'll find that it has built `postgrest-0.2.5.3` successfully and that package is now available to our users for download.
