### ISSUE TITLE
Testing with cURL, wget, Postman - getting empty results

### ISSUE THREAD

**Issue by StefanScott** [begriffs/postgrest#134]
Hi -

Thank you for this excellent RESTful interface to Postgres using the efficient WARP server. This seems like a very "feature-complete" project, drawing on the author's extensive experience with REST APIs, and I am eager to try it out.

I have been testing my PostgREST installation today (on an Amazon AWS EC2 "micro" instance running Debian Wheezy and Postgres 9.3), and it is returning nothing when accessed via cURL, wget (on the server), and Postman (from my Windows 7 laptop running Chrome).

Unfortunately I am getting empty responses all the time, so I suspect I have incorrectly configured something.

I have done the following:

(1) Created a `DATABASE universitynew`, with a `TABLE course` and `INSERT`ed a couple of records:
```
admin:~$ sudo -i
root:~# su - postgres
postgres:~$ psql
psql (9.3.5)
Type "help" for help.

postgres=# \c universitynew
You are now connected to database "universitynew" as user

universitynew=# SELECT * FROM course;

  cid  |    cname
-------+-------------
 12345 | Anatomia
 99999 | Cardiologia
(2 rows)
```
(2) Created a `SCHEMA "1"` and a `VIEW "1".course`:
```
universitynew=# CREATE SCHEMA "1";
CREATE SCHEMA

universitynew=# GRANT USAGE ON SCHEMA "1" TO PUBLIC;
GRANT

universitynew=# CREATE VIEW "1".course AS
universitynew-# SELECT * FROM course;
CREATE VIEW

universitynew=# SELECT * FROM "1".course;
  cid  |    cname
-------+-------------
 12345 | Anatomia
 99999 | Cardiologia
(2 rows)
```
(3) Edited `/etc/postgresql/9.3/main/pg_hba.conf` to allow remote connections:
```
host    all             all            0.0.0.0/0            md5
```
(4) Edited `/etc/postgresql/9.3/main/postgresql.conf` to allow remote connections:
```
listen_addresses = '*'
```
(5) Restarted postgres:
```
sudo /etc/init.d/postgresql restart
```
(6) Launched PostgREST:
```
./postgrest-0.2.5.3 --db-host localhost --db-port 5432 --db-name universitynew --db-user postgres --db-pass <MYPASSWORD> --db-pool 200 --anonymous anon --secure --port 3000
```
(7)(a) Tried connecting using `curl` (http):
```
$ curl -k -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://127.0.0.1:3000/course

HTTP/1.1 301 Moved Permanently
Transfer-Encoding: chunked
Date: Tue, 10 Feb 2015 03:07:00 GMT
Server: postgrest/0.2.5.3
Location: https://127.0.0.1:3000/course
```

(7)(b) Tried connecting using `curl` (https):
```
$ curl -k -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET https://127.0.0.1:3000/course

curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```
(8)(a) Tried connecting using `wget` (http):
```
$ wget http://127.0.0.1:3000/course
--2015-02-10 03:25:48--  http://127.0.0.1:3000/course
Connecting to 127.0.0.1:3000... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://127.0.0.1:3000/course [following]
--2015-02-10 03:25:48--  https://127.0.0.1:3000/course
Connecting to 127.0.0.1:3000... connected.
```
(8)(b) Tried connecting using `wget` (https):
```
$ wget https://127.0.0.1:3000/course
--2015-02-10 03:26:41--  https://127.0.0.1:3000/course
Connecting to 127.0.0.1:3000... connected.
```

(8)(c) Tried connecting using `wget --no-check-certificate` (https):
```
$ wget --no-check-certificate https://127.0.0.1:3000/course
--2015-02-10 03:28:16--  https://127.0.0.1:3000/course
Connecting to 127.0.0.1:3000... connected.
```
(9)(a) Installed Postman in Chrome on Windows and tried connecting using Postman:
```
http://XXX.XXX.XXX.XXX:3000        
```
(my Amazon AWS EC2 server - with the IP address obfuscated here)
```
Could not get any response

This seems to be like an error connecting to http://XXX.XXX.XXX.XXX:3000

Why this might have happened:

The server couldn't send a response: Ensure that the backend is working properly

SSL connections are being blocked: Fix this by importing SSL certificates in Chrome

Cookies not being sent: Use the Postman Interceptor extension

Restricted headers are not being sent: Use the Postman Interceptor extension

Request timeout: Change request timeout settings
```
(9)(b) Also tried sending GET requests via Postman with the user `postgres` and the Postgres db password, and with the user `anon` and no password, and got the same results.

(10)(a) Also tried deliberately using a non-existent table, and got the same empty response from curl:
```
$ curl -k -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://127.0.0.1:3000/nonexistenttable
HTTP/1.1 301 Moved Permanently
Transfer-Encoding: chunked
Date: Tue, 10 Feb 2015 03:58:38 GMT
Server: postgrest/0.2.5.3
Location: https://127.0.0.1:3000/nonexistenttable
```
(10)(b) Also tried using an incorrect port and got an actual error from curl (so this seems to show that PostgREST is at least running correctly on port 3000):
```
admin@ip-172-30-0-4:~/wrk/postgrest$ curl -k -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://127.0.0.1:3001
curl: (7) couldn't connect to host
```

As you can see from the various tests above, in all cases (using curl or wget locally, and using Postman remotely) I got an empty response. 

Thank you for any insights or help so that I can get my installation configured properly!

**Comment by begriffs** [comment]
Nice detailed error report, let's figure this out. My first thought is to try omitting `--secure`. All that flag does is tell postgrest to redirect to https, but postgres itself does not handle SSL. It would rely on Heroku (or whatever server it is on) to decode the message.

**Comment by StefanScott** [comment]
Wow, thanks, that fixed it! Very cool! Now, onward and RESTward!
```
$ curl -k -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://127.0.0.1:3000/course
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Tue, 10 Feb 2015 16:51:57 GMT
Server: postgrest/0.2.5.3
Content-Type: application/json
Content-Range: 0-1/2
Content-Location: /course

[{"cid":"12345","cname":"Anatomia"},{"cid":"99999","cname":"Cardiologia"}]
```

**Comment by begriffs** [comment]
Excellent! Keep in mind that when you run a public server it's important to put postgrest inside something like heroku or nginx that can use SSL and enable `--secure`, but in local development you don't need to do that. I should probably document the security flag better.

**Comment by StefanScott** [comment]
Ok, thanks for the quick fix - and for the reminder about nginx.

I guess this also in some way answers my other question here:

https://github.com/begriffs/postgrest/issues/136

So if I put nginx in front of PostgREST, then I could just use nginx to serve any static pages.

I'm a little unsure about the SSL and `--secure` stuff, but I will look into that later - if/when I get something close to production.
