### ISSUE TITLE
Command line schema selection

### ISSUE THREAD

**Issue by rssp78** [begriffs/postgrest#135]
Hi, I've tried PostgREST as a possible solution to avoid implementing restful interfaces for all our tables in a Postgres, and it works nice. I like it the idea and the performance is great.

Anyway, we would find it more suitable to our needs if we could launch the server telling which schema to use, as we have some databases already designed and in develop stage that would be useful to use.

I saw this https://github.com/begriffs/postgrest/issues/117 issue, and its related, that solution was proposed but as it's not closed I would like to know if its planned to put this new feature.

Thanks in advance.

**Comment by begriffs** [comment]
Let's close this issue and discuss on #117 to keep things in one place.
