### ISSUE TITLE
Would ng-admin combine well with PostgREST?

### ISSUE THREAD

**Issue by StefanScott** [begriffs/postgrest#137]
Hi -

I've been looking at a new project on github called ng-admin, which adds an AngularJS admin GUI to any RESTful API:

"**ng-admin:** Plug me to your RESTFul API to get a complete administration tool (CRUD, multi-model relationships, dashboard, complex form widgets) in no time!."

https://github.com/marmelab/ng-admin

demo:
http://ng-admin.marmelab.com/

For someone who has an existing Postgres database and wants to quickly add an AngularJS CRUD admin GUI, it seems that PostgrREST + ng-admin would be an excellent combination!

**Comment by begriffs** [comment]
This looks really promising, thanks for pointing it out. Care to try making a an ng-admin demo that hooks up with https://postgrest.herokuapp.com ?

**Comment by DrBoolean** [comment]
If I understand correctly, you'll have to manually setup each resource (entity) and view (forms/tables). Postgrest allows you to create an admin on the fly via the schema endpoints. Perhaps we can make an "auto-builder" on top of it. I started a project like this earlier, but didn't have the foundation you're providing

**Comment by brikou** [comment]
ng-admin combines very well with postgrest :+1:

**Comment by begriffs** [comment]
Have you made a demo I can take a look at?

**Comment by brikou** [comment]
@begriffs I keep you in touch in the next days :zap:

**Comment by begriffs** [comment]
Given the cool demo you put together I'm going to close this issue!
