### ISSUE TITLE
batch insertion using postREST

### ISSUE THREAD

**Issue by justinjoseph89** [begriffs/postgrest#140]
Hi,
Is there any possible ways to achieve the batch insertion(bulk) using postREST? I want to insert more than one records simultaneously into a postgre table. Please let me explain How to do this?

Thanks

**Comment by begriffs** [comment]
Did you close this because it's no longer something you want to do, or because you found a workaround? It seems like an important feature to me, and one which I am planning to implement.

**Comment by justinjoseph89** [comment]
absolutely its an important feature. For now am going with jdbc. That is why i closed. Am really looking forward to this.

**Comment by begriffs** [comment]
I'm closing this issue to consolidate it with #17
