### ISSUE TITLE
Postrgest app logging

### ISSUE THREAD

**Issue by pvdvreede** [begriffs/postgrest#141]
Having a play with Postgrest it seems really cool but I haven't seen any logging happening to stdout.

Is it possible to add in logging for what port/ip the server is running on, and optionally (based on log level perhaps) log the requests and responses received by the server?

It would be good to have this log to stdout/stderr by default so it will work well with docker...

**Comment by begriffs** [comment]
Absolutely, good idea. I'll add a log level argument and that supports `error`, `info`, and `debug` levels. What would the ideal format be for log messages in your opinion?

**Comment by pvdvreede** [comment]
How about something like this: http://en.wikipedia.org/wiki/Common_Log_Format ?

Better to go with someone that is common to make it easier for log analyzers, eg Splunk.

**Comment by begriffs** [comment]
This looks great.

I totally agree that we should add logging, although I am going to prioritize this lower than some other open issues.

**Comment by begriffs** [comment]
It turned out to be really easy to do so I just added some basic logging.

It could still be improved though because it does not show the user identifier when someone makes an authenticated request.
