### ISSUE TITLE
Support OAuth

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#145]
https://github.com/gseitz/oauth-provider

**Comment by pvdvreede** [comment]
This would be cool!

Would it be possible to do in the context of #123?

**Comment by begriffs** [comment]
So we've chosen not to implement OAuth internally to postgrest. We are going to use JWT though so another service can handle the OAuth and can issue a json web token telling postgrest that a user is authenticated. Specifically I've been experimenting with auth0.io for handling other forms of auth and integrating with postgrest.

Closing the issue, but open to questions. :)
