### ISSUE TITLE
Ececute sql query

### ISSUE THREAD

**Issue by arunr307** [begriffs/postgrest#149]
Can we able to execute any sql query ? Is there any option for that?

**Comment by begriffs** [comment]
This is not yet an option. Running queries isn't RESTful (it's a remote procedure call) but tell me more about what you'd like to do with queries that you can't do already. Maybe there is a way to provide you the functionality you need without enabling arbitrary queries.

**Comment by arunr307** [comment]
I want to execute some database functions using this rest api. for that i need to pass any query with request. Is it available now?

**Comment by begriffs** [comment]
Also, this seems related to #114

**Comment by arunr307** [comment]
So how can one possible to execute join query and complex query.

**Comment by begriffs** [comment]
To do joins and more complicated queries you can create a custom [views](http://www.postgresql.org/docs/9.4/static/rules-views.html). Each view creates an API route just like a table would. The client side web code actually cannot tell tables and views apart.

**Comment by arunr307** [comment]
Thanks for the information. Is any similar way to call  functions that i already created in db? http://www.postgresql.org/docs/9.1/static/sql-createfunction.html

**Comment by begriffs** [comment]
That's what people are asking for in the other issue (114) linked above.

Can you give some examples of functions you would like to expose in the API?

**Comment by arunr307** [comment]
Ok. suppose i want to return rows with a specific condition. Here is my sample function.

CREATE OR REPLACE FUNCTION  fn_party(tmp_party_name varchar) RETURNS SETOF typ_test AS
$$
	declare
	sql varchar;
	user_rec typ_test;
BEGIN
	sql:='select  id,party_name from party inner join tbl_user on(fki_party_id=id) where party_name='''||tmp_party_name||''' ';
	FOR user_rec IN EXECUTE sql
	LOOP
	return next user_rec;
	END LOOP;
end;
$$
LANGUAGE 'plpgsql';

In normal case we can use this query given below for getting the result.

select * from fn_party('xxx');

How can we able to achieve this requirement ?

**Comment by begriffs** [comment]
Make a view that displays the join

```sql
CREATE OR REPLACE VIEW user_parties AS
SELECT id, party_name
FROM party
INNER JOIN tbl_user ON (fki_party_id=id);
```

Then request the postgrest route `/user_parties?party_name=eq.xxx`
