### ISSUE TITLE
DELETE fails on demo server

### ISSUE THREAD

**Issue by arunr307** [begriffs/postgrest#150]
This is not a issue, its for my reference. Can you please give me sample api for update delete and single get for a particular id. Now i can insert using 
POST https://postgrest.herokuapp.com/sessions
{
  "id": 2,
  "speaker_id": 4,
  "start_time": "13:00:00+00",
  "end_time": "15:00:00+00",
  "location": "The Gym",
  "session_type": "workshop"
}

**Comment by begriffs** [comment]
To update the entire record, you can

PUT https://postgrest.herokuapp.com/sessions?id=eq.2
```json
{
"id": 2,
"speaker_id": 4,
"start_time": "13:00:00+00",
"end_time": "15:00:00+00",
"location": "Not The Gym",
"session_type": "workshop"
}
```

Or you can update individual fields

PATCH https://postgrest.herokuapp.com/sessions?id=eq.2
```json
{
"location": "The Library",
"session_type": "talk"
}
```

**Comment by arunr307** [comment]
Thanks for the information. What about DELETE? i am try with,
DELETE https://postgrest.herokuapp.com/sessions?id=eq.2 
but its not getting delete.

**Comment by begriffs** [comment]
You're right, it doesn't work for me either. Either I didn't give the web user permission to do that, or it's a CORS problem, or it's a bug. There are [tests](https://github.com/begriffs/postgrest/blob/master/test/Feature/DeleteSpec.hs) that say it should work so I'm guessing it is a CORS problem. I'll look into it.

**Comment by arunr307** [comment]
Ok. so in normal case DELETE https://postgrest.herokuapp.com/sessions?id=eq.2  will work (if iam install in my local system). right?

**Comment by begriffs** [comment]
I think so. Would you please try it and let me know?

**Comment by arunr307** [comment]
Ok.I will check and inform you.One more doubt how any we apply an 'OR' condition for select? for 'AND' its possible with the following api.
https://postgrest.herokuapp.com/sessions?id=eq.2&location=eq.The Gym

**Comment by begriffs** [comment]
Correct, you can't yet do an OR. But you could make a view for more complicated conditions. The view will appear just like a table to the web client.

**Comment by arunr307** [comment]
Is it possible to pass dynamic values into view? 
What will be the view corresponding to this api(https://postgrest.herokuapp.com/sessions?id=eq.2&location=eq.The Gym) where i need to take values for id  and location taken dynamically. Can you please help me to solve this.

**Comment by begriffs** [comment]
Looks like you just changed the location, that's all. It's no longer called "The Gym" but "The Gymss". Try this one
https://postgrest.herokuapp.com/sessions?id=eq.2&location=eq.The%20Gymss

**Comment by arunr307** [comment]
I know that, but right now i am looking for creating a 'VIEW' in postgresql for returning the same details.But i want to pass values dynamically.

**Comment by arunr307** [comment]
How can i write a less than condition in query?

**Comment by begriffs** [comment]
Please consult the [route wiki](https://github.com/begriffs/postgrest/wiki/Routing#filtering-and-ordering).

(Also I am still thinking about your question about view arguments, and I don't have a solution yet)

**Comment by arunr307** [comment]
Thank you for you guideline, let me know if any solution for 'VIEW'.

**Comment by begriffs** [comment]
I'm going to close this issue and we can talk about the view arguments in another one.
