### ISSUE TITLE
Install in local system

### ISSUE THREAD

**Issue by arunr307** [begriffs/postgrest#151]
Hai,
I want to install this in my local system(Linux). For that i download the file from this link http://bin.begriffs.com/dbapi/heroku/postgrest-0.2.5.3.tar.xz .
What are the next steps that is need to do for using this service.

**Comment by begriffs** [comment]
Did you close this because you figured it out?

**Comment by arunr307** [comment]
Ya. I think installation i complete successfully now. Did i need to do anything in postgresql for this connection?
