### ISSUE TITLE
function call with string parameters to the postgre sql db is giving response error code 

### ISSUE THREAD

**Issue by darsana** [begriffs/postgrest#153]
CREATE TYPE typ_checkEmailExists As(
          user_id integer,
          party_id integer
);

CREATE OR REPLACE FUNCTION fn_checkEmailExists(username varchar)
RETURNS SETOF typ_checkEmailExists AS
$$
declare
sql varchar;
user_rec typ_checkEmailExists;
BEGIN
sql:=' SELECT user_id AS "UserId", party_id AS "PartyId" FROM user_data
WHERE username = '''||username||'''';
FOR user_rec IN EXECUTE sql
LOOP

return next user_rec;
END LOOP;
end;
$$
LANGUAGE 'plpgsql';

Hai, here i created a function to fetch user id ,party id from user_data table by passing username as a parameter to the function ,and i called the function like bellow

{
"sql": "select * from fn_checkEmailExists('test123@gmail.com')"
}

but i am getting error code like this
{
"length": 95,
"name": "error",
"severity": "ERROR",
"code": "42703",
"position": "37",
"file": "parse_expr.c",
"line": "768",
"routine": "transformColumnRef"
}
This kind of error coming only kind of functions which accepts the strings as parameters ,Any help please

**Comment by begriffs** [comment]
Which url are you requesting and with which http verb?

**Comment by darsana** [comment]
![querywith string](https://cloud.githubusercontent.com/assets/3468405/6282099/e9f695d2-b8f4-11e4-8621-765bf2d44983.JPG)

Please have a look on this image

**Comment by begriffs** [comment]
A couple more questions:

* what schema do these functions live in?
* what command line arguments did you use to start postgrest?
* what version of postgres are you running?

**Comment by darsana** [comment]
Schema
---------------------
![schema](https://cloud.githubusercontent.com/assets/3468405/6282354/981b59fa-b8f9-11e4-8576-a977fe54bcf8.JPG)
command 
-----------
postgresql-http-server --port 3002 --database testems --user usernameofdb--password passwordofdb--raw true --cors true&
version 
----------------
![version](https://cloud.githubusercontent.com/assets/3468405/6282364/ca314800-b8f9-11e4-8234-04c10b770a49.JPG)

**Comment by begriffs** [comment]
OK so there are three problems right now. The first is that your PostgreSQL version is too old (we require at least 9.2). I created issue #157 to properly warn people about this requirement.

The next problem is that PostgREST is expecting your data to be in a schema called `1` rather than `testems` because it defines version 1 of your API. This restriction will be removed when I finish issue #117.

Finally, to access a table you have to visit its route rather than passing raw sql. So in your case it would be http://192.168.1.219:3002/pg_person?person_fname=eq.Shaheer123

**Comment by begriffs** [comment]
In fact, I think you are confusing this project with https://github.com/bjornharrtell/postgresql-http-server

**Comment by darsana** [comment]
Ok thank you so much  for the help..
