### ISSUE TITLE
SSL error in API call

### ISSUE THREAD

**Issue by arunr307** [begriffs/postgrest#155]
I am getting SSL error when making te following api call

curl  https://localhost:3000/db_name/table_name

error
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Comment by begriffs** [comment]
If you're running it locally you'll want to not use the `--secure` option. Postgrest does not handle SSL itself, it relies on being behind a proxy like nginx or Heroku's load balancer that would do the actual encryption. All the secure option does is send a 301 redirect to https for any http request.

**Comment by arunr307** [comment]
So you are telling that use the following command for starting server.

./postgrest-0.2.6.0  --db-host localhost  --db-port 5432 --db-name my_db --db-user postgres --db-pass mypas--db-pool 200 --anonymous postgres  --port 3000

Is this api correct?
curl https://localhost:3000/db_name/table_name

what protocol we need to use http or https?

**Comment by begriffs** [comment]
Your command line arguments look good. I updated the readme to be more clear about the secure flag thanks to your question.

The reason you're not seeing results from curl is that curl is getting a 404. If you pass an argument to get more info you can see

```
$ curl -I http://localhost:3000/db_name/table_name
HTTP/1.1 404 Not Found
Date: Fri, 20 Feb 2015 05:31:08 GMT
Server: postgrest/0.2.6.0
```

That's because urls are of the form `http://localhost:3000/table_name` where the table needs to live in a schema called `1` (because the default api version requested is version 1).

**Comment by arunr307** [comment]
can i able to change schema from '1' to any other name? because i can't able to create schema with name '1' in postgresql, its getting error.

**Comment by begriffs** [comment]
Right now it has to be called `1`, but issue #117 will allow you to specify the default schema name as a command line argument. I'll be working on that issue next.

In the meantime does it give you an error if you try to run this?
```sql
CREATE SCHEMA "1";
```

**Comment by arunr307** [comment]
ok. Now schema was created successfully. But get an error as function does not exist. 

{"hint":"No function matches the given name and argument types. You might need to add explicit type casts.","details":null,"code":"42883","message":"function row_to_json(record) does not exist"} 

Is it need to create that function by myself?

**Comment by begriffs** [comment]
Oh, it looks like `row_to_json` was introduced in postgresql 9.2 -- are you able to upgrade? I should add this to the readme.

**Comment by arunr307** [comment]
Ok. now its working fine in schema "1". Is there any way to access tables from my public schema, without altering my tables schema. I want to keep all my tables in public or any other (with project needs)  schema its self.

**Comment by begriffs** [comment]
You could create views in schema `1` which basically select * from underlying tables in `public`. In fact postgresql makes simple views like this "auto-updating" meaning the client can write to the views and it will pass the updates through to the underlying table.

Doing the masking with views allows you to change the underlying table while theoretically keeping your API the same by adjusting the views.

**Comment by arunr307** [comment]
Are you telling for making view for each table or  is there any option for handling all these in single view? can you give an example view for that.

**Comment by arunr307** [comment]
@begriffs Can we able to pass any schema name in header in your next release?

**Comment by begriffs** [comment]
You can now pass the `--v1schema` argument when starting postgrest to select which schema is the default one. Should fix your problem, let me know if it doesn't.

**Comment by arunnairmr** [comment]
ya, its helpful for me. Thanks a lot. Is it possible to change schema at run time(by any header value)?

**Comment by begriffs** [comment]
Yes, but currently only to an integer value. In short you can choose which schema to consider version 1, then ask for other integer versions through a request header.
