### ISSUE TITLE
[JSON column] allow posting object instead of stringified value

### ISSUE THREAD

**Issue by brikou** [begriffs/postgrest#156]
Would be nice to allow posting (putting, patching...) real object instead of stringified JSON.

so use:

```sh
echo '{
    "my_json_column": {
        "foo": true,
        "bar": null,
    }
}' | curl http://localhost:9000/objects?id=eq.1 -X PATCH --data-binary @-
```

instead of:

```sh
echo '{
    "foo": true,
    "bar": null,
}' | \
python -c 'import json,sys; print json.dumps(sys.stdin.read())' | \
xargs -0 printf '{ "my_json_column": %s }' | \
curl http://localhost:9000/objects?id=eq.1 -X PATCH --data-binary @-
```

@begriffs what do you think of it?

**Comment by begriffs** [comment]
Sorry for the delayed response. I'm a little busy at the moment but I'll look into this more deeply over the weekend.

**Comment by begriffs** [comment]
Still caught up with fixing other issues but haven't forgotten this one.
