### ISSUE TITLE
find maximum value and count

### ISSUE THREAD

**Issue by arunr307** [begriffs/postgrest#160]
How can we find max value and count for a coulmn.

select max(id) from tbl_login;

select count(id) from tbl_login;

**Comment by begriffs** [comment]
The count is returned with every request in the http headers. It will say `Content-Range: a-b/n` where `n` is the total. To do max you can make a view and name it something like `tbl_login_stats`. This view will be accessible just like a table.

**Comment by begriffs** [comment]
Did my suggestion resolve this issue for you?
