### ISSUE TITLE
AS in select query

### ISSUE THREAD

**Issue by darsana** [begriffs/postgrest#161]
I want to select fields from the table with AS key word,How can i use?

SELECT party_id AS "OrganizationId" FROM party_relation;

**Comment by begriffs** [comment]
```sql
CREATE VIEW foo AS
SELECT party_id AS "OrganizationId" FROM party_relation;
```

Then this will be accessible at the route `/foo`.

**Comment by begriffs** [comment]
Ideally you'll keep `party_relation` will in an underlying private schema, and `foo` in a schema called `1` which will be the publicly visible interface to the first [version](https://github.com/begriffs/postgrest/wiki/API-Versioning) of your api.

**Comment by begriffs** [comment]
Let's reopen this issue if creating the view doesn't solve your problem.
