### ISSUE TITLE
Unable to setup basic auth

### ISSUE THREAD

**Issue by c11z** [begriffs/postgrest#162]
*This may not be the correct place for this, if so please direct me to the right place.*

 I just started using postgrest recently and I followed the wiki tutorial https://github.com/begriffs/postgrest/wiki/Security-and-Permissions to setup basic auth access. I have the schema, table and trigger and I manually set a few of the roles as well as verified that the the trigger rejected adding rows that do not correspond to roles. Everything seems to be there and I have access through the anonymous flag but I cannot authenticate with basic auth. I always get a 

    401 Invalid username or password 

response.

the --db-user and --db-pass I am using is granted usage on the postgrest schema. Currently it is a super user and can insert and delete data.

Any ideas?

**Comment by begriffs** [comment]
The authentication can be tricky and its setup should probably be better automated by postgrest in the future. If you inspect the `postgrest.auth` in something like pgadmin can you tell me what rows you see inside it? I want to be sure that you not only have database roles set up but that you have "web users" in the auth table as well.

**Comment by c11z** [comment]
Yeah I just have trivial roles and passwords:
**From roles.sql**

    -- c11z is god
    CREATE ROLE c11z SUPERUSER LOGIN PASSWORD 'c11z';
    -- anon is useless
    CREATE ROLE anon NOLOGIN;
    -- lurker is the web crawler's database user
    CREATE ROLE lurker LOGIN UNENCRYPTED PASSWORD 'lurker' NOSUPERUSER INHERIT        NOCREATEDB NOCREATEROLE NOREPLICATION;
    -- Group for sharing api access
    CREATE ROLE api;
    -- maestro is the main api that has access to the database
    CREATE ROLE maestro LOGIN UNENCRYPTED PASSWORD 'maestro' NOSUPERUSER INHERIT  NOCREATEDB NOCREATEROLE NOREPLICATION;
    GRANT api to maestro;

**From postgrest.auth**

    cdb=# select * from postgrest.auth;
       id    | rolname |                             pass                             
    ---------+---------+--------------------------------------------------------------
     c11z    | c11z    | c11z                                                        
     lurker  | lurker  | lurker                                                      
     maestro | api     | maestro                                                     
    (3 rows)

**When I launch postgrest**

    postgrest -d cdb -P 5432 -U c11z --db-pass c11z --db-host 192.168.33.10 -p 3000 -a c11z


Sometimes I use anon of for -a but of course I get nothing. With c11z as -a I get full access until I try to use basic auth then I get 401 for any user I try.

**Comment by begriffs** [comment]
One problem is that you have plaintext passwords in the auth table. The proper way to create users right now is to run postgrest with a powerful anonymous role and post to the `/postgrest/users` route with a payload that looks like

```json
{
  "id": "lurker",
  "pass": "lurker",
  "role": "lurker"
}
```

It will encrypt the password with bcrypt and then write a row to the auth table. So erase the rows you have in there now and recreate them by posting to this route.

In the future I should add command line options to make users without having to do HTTP posts.

**Comment by c11z** [comment]
That worked, thanks.

One small problem is that in the 201 response I see

    Malformed JSON

Since the post worked and my json is simple I suspect there may be a bug in whatever json is supposed to be returned as a response.

Also I get 404's when I try to GET ````/postgrest/users?id=eq.c11z```` whether I use the c11z basic auth or not.

**Comment by begriffs** [comment]
I think the Malformed JSON message happens because the response is blank and yet is delivered with content type json (an empty string is not proper json). I could have it omit a content type or use text/plain when the response is empty to avoid the warning.

Also the reason you can't request `/postgrest/users` is that it is a special-case route that only accepts post. It is kind of limited so far. There is no way to change a password over HTTP for instance. Tasks like that still require some manual intervention.

**Comment by c11z** [comment]
Thank you.
