### ISSUE TITLE
JSON Web Tokens

### ISSUE THREAD

**Issue by c11z** [begriffs/postgrest#163]
I see that there is motivation to implementing OAuth, I would also like to recommend that the leadership consider adding support for JSON Web Tokens as a lightweight authentication for claims.

Relevant links:
https://bitbucket.org/ssaasen/haskell-jwt
http://jwt.io/

**Comment by begriffs** [comment]
Cool, thanks for letting me know about that. Is it an alternative to OAuth or complementary?

**Comment by c11z** [comment]
Most use cases I am familiar with are associated with closed api's and is independent of OAuth. But it is pretty flexible and I have seen it used to replace OAuth tokens. You can return a stateless JWT instead, with the allowed scopes and expiration.

**Comment by rattrayalex** [comment]
+1

**Comment by pvdvreede** [comment]
I like this idea as well. From the limited understanding I have of JWT, it is a way of signing and verifying arbitrary data so it seems very flexible to use and allows auth to be pluggable rather than restricted to a single standard.

**Comment by framp** [comment]
+1

Is there anyone working on it?
I'll be happy to implement it as Basic Auth is not enough for my use case

**Comment by begriffs** [comment]
Thanks a lot, go right ahead.

**Comment by trinque** [comment]
@framp what's your estimate for when you might work on this? I have a need for this as well, and wouldn't mind helping.

**Comment by framp** [comment]
I'll probably give it a shot this weekend.

If you want to start working on it before we need to install [`jwt`](https://hackage.haskell.org/package/jwt) and do something like this somewhere in `Middlweare.hs`:

     import Web.JWT (decodeAndVerifySignature, encodeSigned, secret) as JWT

     ...

     Data.Map.lookup "role" <$> 
       JWT.unregisteredClaims <$> 
       JWT.claims <$> 
       JWT.decodeAndVerifySignature (JWT.secret "secret")

And then add a route for logging in (or use the existing one with a flag) using `encodeSigned`

**Comment by trinque** [comment]
Hooray!

**Comment by arunnairmr** [comment]
Well. I am trying for a sample JWT.

**Comment by framp** [comment]
You need to set a proper secret and not the default one for security reasons, launch postgrest with `--jwt-secret horsebatterystaplecorrect`

**Comment by arunnairmr** [comment]
Thank you for your suggestion.Now its working fine for me.

**Comment by arunnairmr** [comment]
Thank you for your suggestion.Now its working fine for me.

**Comment by twinkle316** [comment]
Does postgrest JWT support specify `expire time` for the token? 
I tried below but not working.
```
{ "id": "user", "pass": "passed",exp=<unixtimestamp>}
```

**Comment by framp** [comment]
Unfortunately expiry has not been implemented in the upstream library we are using.

**Comment by twinkle316** [comment]
@framp Got it. Thank you for you reply.

**Comment by bobcolner** [comment]
Does this mean that the JWT postgrest generates (user management / blog examples) are valid forever? I do see the external authentication examples reference JWT TTL expiration.  --Great project btw!

**Comment by begriffs** [comment]
We could modify the example for [generating jwt](http://postgrest.com/examples/users/#generating-jwt) to include an expiration of five minutes:

```sql
create type basic_auth.jwt_claims AS (role text, email text, exp as integer);

create or replace function
login(email text, pass text) returns basic_auth.jwt_claims
  language plpgsql
  as $$
declare
  _role name;
  result basic_auth.jwt_claims;
begin
  select basic_auth.user_role(email, pass) into _role;
  if _role is null then
    raise invalid_password using message = 'invalid user or password';
  end if;
  -- TODO; check verified flag if you care whether users
  -- have validated their emails
  select _role as role, login.email as email,
         round(extract(epoch from now()))+5*60 as exp
         into result;
  return result;
end;
$$;
```

**Comment by bobcolner** [comment]
Nice -that makes sense.

This is probably a naive question, Does this mean that postgrest will enforce the jwt `exp` TTL?

I've updated my db with your modified example but I'm still **not** getting logged out of the API after 5 mins. I don't see the `exp` field when I decode the jwt either so perhaps something else is going on.

I did verify that the login function reflects the updated code with 5 min `exp` field.

thanks

**Comment by begriffs** [comment]
Which version of postgrest are you running? As of 0.3.0.2 and later it should reject expired JWTs.

**Comment by bobcolner** [comment]
I have re-created the `exp` extended blog db using the latest postgrest 3.04.

I can confirm that the psql `login` function returns an jwt_claims type with the `exp` integer field added. However, the actual jwt token returned by the postgrest login endpoint does not include the `exp` field, only `email` and `role`.

Perhaps I missing something obvious?
