### ISSUE TITLE
Strange behavior regarding Post and Patch with Basic Auth

### ISSUE THREAD

**Issue by c11z** [begriffs/postgrest#164]
I have a table T and a user U.

GRANT ALL PERMISSIONS ON T TO U;

I can POST a resource and then PATCH using url parameters to isolate the primary key or a unique column multiple times successfully.

If I POST again after a PATCH I correctly get HTTP 400.

But if I PATCH after that second POST I get a 404 and this error:

    {
    "hint": null,
    "details": null,
    "code": "42501",
    "message": "permission denied for relation auth"
    }

I now cannot PATCH unless I restart postgrest, then I am allowed to PATCH successfully unless I POST again and the cycle repeats.

I have a super user S that cannot reproduce this behavior.

**Comment by c11z** [comment]
This is on postgrest 0.2.6.0 I see that another version was released last night. I test to see if the bug is still present. Here is the repo of my sqitch based database https://github.com/comicgator/cdb that causes the bug.

Let me know if you cannot easily reproduce the bug. I'll take some time and build a small vagrant box you can run to prove the issue.

**Comment by begriffs** [comment]
I'll look into this over the weekend.

**Comment by c11z** [comment]
I tested in the latest build and the problem still exists.

**Comment by begriffs** [comment]
Does the table you are posting/patching use any sequences? There may be permissions implications for updating sequences. Can you tell me more about the structure of the table?

**Comment by begriffs** [comment]
Which table in the cdb project is causing the post/patch error? Perhaps it has to do with permissions on a sequence.

**Comment by ssoriche** [comment]
I'm seeing the same error message after issuing a PATCH against a table with a trigger that throws an EXCEPTION. If I try to issue another call I get the error message: permission denied for relation auth. If I restart postgrest, I can continue.
