### ISSUE TITLE
Virtual private database with mutitenanacy 

### ISSUE THREAD

**Issue by razakpm** [begriffs/postgrest#165]
Have any option to achieve secure multi tenancy access with postgrest ?, Have any virtual private data base concept?

**Comment by begriffs** [comment]
You can create different users with different access to tables within a single database. You can also run two copies of postgres configured to run on entirely different databases on a single postgresql server. Can you tell me more about your specific use case?

**Comment by begriffs** [comment]
Did my comment help or do you have more questions?

**Comment by razakpm** [comment]
@begriffs 
Let me to explain my usecase. 
I have 4 clients (tenants) , A, B, C, D 

I have kept all clients data in the same database, means same table and using clientId/ tenant Id to distinguish records.

If I have provided postgrest to access data for each client , how can I ensure  Tenant A will access only A's data, Never ever know/access B's Data. any option in postgrest to achieve it easily.

**Comment by pvdvreede** [comment]
If you have a look at issue #123 I talk about what I think you are asking about.

There is the `current_user` inside postgres views and triggers that you can use but it cannot be done based on the user logged in via postgrest, but rather the role that is assigned to the user.

See also the wiki here for info on to setup security and permissions: https://github.com/begriffs/postgrest/wiki/Security-and-Permissions#scenario-signed-in-authors-can-edit-own-content

Does this help answer the question?

**Comment by razakpm** [comment]
Thanks @pvdvreede  , Just tried and understood it is possible. and hopes postgres 9.5 release will make more easier.

**Comment by begriffs** [comment]
PostgreSQL 9.5 beta has been released!

New documentation now lives at postgrest.com and we'll be adding a section about your use case.
