### ISSUE TITLE
Command line usage: defaults

### ISSUE THREAD

**Issue by jtdaugherty** [begriffs/postgrest#170]
From looking at the `postgrest` command line usage output, it appears that some settings are optional (those surrounded in brackets) and others are required (those surrounded in parentheses).  For the optional settings, I'm not sure what defaults will be used if I omit them.  Can those defaults be documented?

Meanwhile, if I specify all of the settings that seem to be required, I get the following. Any assistance would be greatly appreciated!
```
$ postgrest -d $USER -U $USER -a $USER
WARNING, running in insecure mode, auth will be in plaintext
Listening on port 3000
127.0.0.1 - - [10/Mar/2015:16:36:37 -0700] "GET / HTTP/1.1" 500 - "" "Wget/1.15 (linux-gnu)"
```
And a client request shown in the log above:
```
$ wget http://localhost:3000/
--2015-03-10 16:36:37--  http://localhost:3000/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:3000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2015-03-10 16:36:37 ERROR 500: Internal Server Error.
```
And from `postgresql-9.4-main.log`:
```
2015-03-10 16:41:44 PDT [23859-1] $USER@$USER LOG:  could not receive data from client: Connection reset by peer
```

**Comment by jtdaugherty** [comment]
Here's another data point.  An `OPTIONS` request fares better, at least resulting in a response body. The error says I haven't provided a password, but I can't provide one since I'm using trust authentication over a UNIX socket in a development environment.  Perhaps `postgrest` is attempting to connect over a TCP socket; if it does, then Postgres will want a password.  So this comes back to another request I opened (https://github.com/begriffs/postgrest/issues/169).

Here is the request/response pair:
```
$ telnet localhost 3000
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
OPTIONS / HTTP/1.1

HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Date: Tue, 10 Mar 2015 23:44:14 GMT
Server: postgrest/0.2.7.0
Content-Type: application/json

05B
{"details":"fe_sendauth: no password supplied\n","message":"Can't connect to the database"}
0
```

**Comment by jtdaugherty** [comment]
Also, for what it's worth, if there is an approach to resolving this and #169 that we can both be happy with, I would probably be able to write up patches and submit them.

**Comment by begriffs** [comment]
Thanks for submitting this issue and for volunteering to help with patches down the road.

As for the original question, you can pass `--help` to get more info about default values. However the catch is that this option is itself not documented. :stuck_out_tongue: Maybe a quick note in the readme or in the program description would suffice. https://github.com/begriffs/postgrest/blob/master/src/Main.hs#L31-L33

Care to send a pull request to document this?

I'll look into the Unix socket problem and take that up in issue #169

**Comment by jtdaugherty** [comment]
Regarding `--help`: I see! I think that's surprising behavior, since usually any time a program shows help, it shows all of it unless there is just too much to show, in which case it shows a synopsis with more detailed help commands provided.  Would you be willing to accept a patch that changes this to emit the same help output no matter what?  That would also sidestep the issue of documenting the more detailed help option since it'd be the default.

**Comment by jtdaugherty** [comment]
Another way in which this could be improved would be to use `<...>` instead of `(...)` to indicate required parameters, and to put them first in the usage output so they're noticed up front.  Right now the `(...)` syntax makes them harder to spot, as does their interleaving with optional parameters.  I also suggest `<...>` since that's the syntax I'm used to seeing when things are required.

**Comment by begriffs** [comment]
This all sounds great. I'd love a pull request if you've got the time to put one together.

**Comment by jtdaugherty** [comment]
Looking into this now, I see that to get most of the things I've asked about would require patching `optparse-applicative`. I'd rather not do that since it'd affect more users than might be appropriate, so I'll live with the option ordering and choice of syntax. There are a couple of things left: whether required options are grouped together, and whether the default output is the more verbose output with defaults.

As for the first issue, I could reorder the fields of the `AppConfig` type to reorder the options in the help output, but that's unpleasant because it means that the presentation issues drive the type declaration, and that seems wrong to me. So unless you see a better path forward there, I'll live with that as-is, too, since the alternative is worse.

The second issue of showing better help output by default might be feasible, but I don't know for sure because I don't understand how `optparse-applicative` decides whether to show the long or short forms of the usage output, and I don't know how to get it to show the long form by default. I've only ever used the Getopt-style option parsing in Haskell; if you know how to achieve this already, it might be more expedient for you to make this change.

So: as much as I am happy to help out, these issues might be hitting a wall.

**Comment by begriffs** [comment]
There was a pull request two weeks ago where @adambaker made a friendlier command line parser. It actually worked really nicely but had problems with linting and building on Circle CI. Maybe with a little more work it could be revived: https://github.com/begriffs/postgrest/pull/139

**Comment by jtdaugherty** [comment]
Oh, great!  Aside from the change to use `record`, it looks like those patches essentially take the approach I prefer, i.e., use `System.Console.GetOpt`.  As far as I can tell, the test failures are build infrastructure issues - perhaps dependency resolution problems?  In other words, as far as I can tell, they aren't issues with the code per se, but perhaps I missed the details.

If you could point me at what needs more work, I can take a look!

**Comment by begriffs** [comment]
Basically it would be great if you could make the GetOpt way work without using Record. The build/linter problems happen because of the record library, and that library is by no means necessary. I think a more vanilla haskell data type would work just fine.

Improving the command line interface would be valuable. The current interface can be confusing.

**Comment by begriffs** [comment]
@jtdaugherty have you thought about this issue since since the comments above?

**Comment by jtdaugherty** [comment]
Hi! Pardon my long absence; the work project I was working on decided it needed something more customized than `postgrest` and so I haven't returned to this project since then. Although I'd like to see the change described here, I don't have the resources to contribute it right now. I would be happy to have this ticket closed if you would.

**Comment by begriffs** [comment]
I'll close the ticket for now.
