### ISSUE TITLE
Handling file uploads

### ISSUE THREAD

**Issue by bartvandendriessche** [begriffs/postgrest#171]
More of a question than an issue really, but I've been thinking about the idea of PostgREST as the main backend for an application, and was wondering what a good way to handle file uploads would look like.

Ideally file uploads would be unlimited with regards to size, and it would be straightforward to serve files from a CDN.

**Comment by begriffs** [comment]
You could put postgrest behind nginx and have nginx handle uploads behind a route like `/uploads`. See this article https://coderwall.com/p/swgfvw/nginx-direct-file-upload-without-passing-them-through-backend

It's probably better to use existing tools for this sort of thing rather than trying to build the functionality into postgrest. What do you think?

Also if you're adventurous and want to create a demo of this nginx technique I'd love to create a wiki in this project to explain your findings.

**Comment by bartvandendriessche** [comment]
I definitely see the benefit of handling file uploads outside of PostgREST, and while that nginx techique looks interesting, it can see a few drawbacks:

- it ties us to nginx
- it looks like `client_body_in_file_only` is intended to be used for debugging mainly, so it's a bit of a hack
- it requires uploading files naked, i.e. not as a standard form POST with accompanying parameters. This means it's a bit involved to e.g. update the `image` property for a `Product` item.

On the other hand, it's definitely something that can be made to work, so pragmatist points are in order :)

**Comment by begriffs** [comment]
How about doing direct browser-to-S3 uploads? You could use a library like this https://github.com/TTLabs/EvaporateJS

**Comment by begriffs** [comment]
Have you found a way to do uploads that you're happy with?

**Comment by bartvandendriessche** [comment]
Hey @begriffs, my project needed some extra functionality besides just reading from and writing to a postgres database, so I didn't end up using postgrest.

Regarding the EvaporateJS suggestion, my main API client is a mobile app so ideally a file uploading solution would just work as a vanilla POST or PUT.

**Comment by begriffs** [comment]
While we're not planning to add asset management and file uploading directly to postgrest, there has been some experiments by others to do it. http://postgrest.com/install/ecosystem/

Specifically you can check out https://github.com/srid/spas

**Comment by joaoportela** [comment]
I'll just leave this here. https://devcenter.heroku.com/articles/s3#direct-upload

I had to do this recently and between the [python example](https://devcenter.heroku.com/articles/s3-upload-python) and the [official documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html) it wasn't too hard.

**Comment by begriffs** [comment]
Thanks for adding this note.

**Comment by rlhk** [comment]
I'm looking for a simple way to generate s3 signedUrl directly from Postgres function (without resorting to a separate Node JS / Python based server) which is to be served from Postgrest endpoint upon browser request. I'm not able to find directly related information. Any pointer is appreciated. Thanks.

**Comment by ruslantalpa** [comment]
https://github.com/s3tools/s3cmd/blob/edd7c7df64e7cd7bc2a2e9fa6054c2ad7eb40ff3/S3/Crypto.py#L120-L133

in postgres you usually have python available, also you have pgcrypto
these two should be enough to be able to sign urls for s3

**Comment by ruslantalpa** [comment]
these are the low level details of how to generate the key
http://s3.amazonaws.com/doc/s3-developer-guide/RESTAuthentication.html
it seems you only need hmac and sha1
https://www.postgresql.org/docs/current/static/pgcrypto.html

**Comment by thebf** [comment]
@joaoportela  You say that you were able to implement this, could you share it as an example?

**Comment by joaoportela** [comment]
I didn't do it for PostgREST in particular; but I had the server providing a valid client with the upload url.

Your probably better of following the linked guides, but here is my method:
```
def _canonical_headers(headers):
    """Turn headers dictionary into a CanonicalizedAmzHeaders element.

    http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationConstructingCanonicalizedAmzHeaders
    """
    headers_items = [(k.lower(), v) for k, v in headers.items()]
    # lexicographical sorting is just regular sorting when strings are
    # lowercase.
    sorted_h = sorted(headers_items)
    return "\n".join("{}:{}".format(k, v) for k, v in sorted_h)


def sign_s3(obj_path, mime_type, uploader):
    """Create signed upload URI for 'object_path'.

    Complete documentation of signing request:
    http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html

    :returns: an object with the necessary info to upload
    the object. 'uri' is the upload uri, 'headers' are the
    headers to use for upload and 'read_uri' is a read uri
    to use after upload to read the object.
    """
    AWS_ACCESS_KEY = os.environ['S3_AWS_ACCESS_KEY']
    AWS_SECRET_KEY = os.environ['S3_AWS_SECRET_KEY']
    S3_BUCKET = os.environ['S3_BUCKET']

    object_name_quoted = "/".join(urllib.parse.quote_plus(p) for p in obj_path)
    mime_type = mime_type

    date = datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S GMT')
    uploader = strip_accents(uploader)  # just to make it prettier.
    amz_headers = {'x-amz-date': date, 'x-amz-meta-uploader': uploader}
    amz_string = _canonical_headers(amz_headers)

    string_to_sign = "PUT\n{}\n{}\n{}\n{}\n/{}/{}".format(
        "", mime_type, "", amz_string, S3_BUCKET, object_name_quoted)

    _logger.debug("signing: %r", string_to_sign)
    digest = hmac.new(AWS_SECRET_KEY.encode('utf8'),
                      msg=string_to_sign.encode('utf8'),
                      digestmod=hashlib.sha1).digest()

    signature = base64.b64encode(digest).strip().decode('ascii')

    url = 'https://{}.s3.amazonaws.com/{}'.format(S3_BUCKET,
                                                  object_name_quoted)
    read_url = _sign_read_url(obj_path)
    headers = {
        'Authorization': 'AWS {}:{}'.format(AWS_ACCESS_KEY, signature),
        'Content-Type': mime_type,
    }
    headers.update(amz_headers)
    return {'url': url, 'headers': headers, 'read_url': read_url}
```

Where `uploader` is just metadata for me to know who requested the upload and `_sign_read_url` is a similar method for signing the read url.
