### ISSUE TITLE
negating queries

### ISSUE THREAD

**Issue by rall** [begriffs/postgrest#173]
Here's a feature request to consider:

Rather than using the explicit negative query params ```neq```  and ```isnot``` could there instead (or as well) be a ```not``` param that would map to a postgres NOT operator. Perhaps something like this:

```
/people?age=not.eq.13
/people?admin=is.not.null
```

My particular use case would be the awesome new ```like``` route:

```
/people?name=not.like.*Jones*
```

Thanks!

**Comment by begriffs** [comment]
This does seem like a cleaner API. Perhaps I should make a backwards-incompatible change and remove the negative forms neq etc and provide only the `not`.

**Comment by rall** [comment]
I'm in favor! (if that was a question :smile: )

**Comment by begriffs** [comment]
Cool. I'm preoccupied with the bulk uploads feature right now, but I'll get to this one.

**Comment by rall** [comment]
May I politely nudge you on this?

**Comment by begriffs** [comment]
Oh thank you -- absolutely. I'll make the change this week.

**Comment by rall** [comment]
great news!!

**Comment by rall** [comment]
hello again! Any news on this?

**Comment by begriffs** [comment]
Thanks to the ever-helpful @diogob this is now fixed!
