### ISSUE TITLE
Can I filter with 'or' instead of 'and' in query parameters.

### ISSUE THREAD

**Issue by c11z** [begriffs/postgrest#174]
I have a view that left joins a table to a junction table and I want to use the where clause to filter on if the id in the junction table is a particular value or null.

```
CREATE OR REPLACE VIEW "1".comics
(id, geek_id, hostname, is_viewed, is_favorited) AS (
SELECT
	c.id AS comic_id,
	cg.geek_id AS geek_id,
	c.hostname AS hostname,
	cg.is_viewed AS is_viewed,
	cg.is_starred AS is_starred
FROM "1".comic c LEFT JOIN "1".comic_geek cg ON c.id = cg.comic_id);
```
Is there a way I can make this call through postgrest:

```SELECT * FROM "1".comics WHERE geek_id=1 OR geek_id IS NULL;```

**Comment by begriffs** [comment]
You might try `/comics?geek_id=in.1,null` but I am not sure if NULL will be coerced to the right type.

Another hack would be to do it in two calls, `/comics?geek_id=is.null` and `/comics?geek_id=eq.1`.

**Comment by c11z** [comment]
Thanks, I didn't know that 'in' was a valid routing, it is not in the https://github.com/begriffs/postgrest/wiki/Routing wiki page.

**Comment by begriffs** [comment]
Thanks for pointing that out. I just added IN to the wiki. (I had added it to the changelog but forgot the wiki)

Does this solve your problem though? I'm not sure how well `null` interacts as a value of `IN`.
