### ISSUE TITLE
Return ISO-8601 formatted date times

### ISSUE THREAD

**Issue by adambaker** [begriffs/postgrest#177]
Eg:
`2015-03-30T16:31:53.000+00:00` or `2015-03-30T16:31:53Z`

Currently, it's something like:
`2015-03-30 09:31:53-07:00`

**Comment by begriffs** [comment]
Hmm, it's using postgresql's default output for a timestamp with timezone. I think it will be difficult for me to intervene because the db itself is serializing the whole response to json automatically.

You could try choosing the column type timestamp (without timezone) and I think you'll get the output you want.

**Comment by adambaker** [comment]
Not true. Instead, I get `2015-03-31 22:58:50`, which, although a valid* does not parse according to Data.Thyme's FromJSON instance for UTCTime.

*: "By mutual agreement of the partners in information interchange, the character [T] may be omitted in applications where there is no risk of confusing a date and time of day representation with others defined in this International Standard"

**Comment by begriffs** [comment]
We could set the `datestyle` right after connecting to the db. I think that will cause timestamps to render the way you want.

http://stackoverflow.com/questions/6123484/how-do-i-alter-the-date-format-in-postgres

**Comment by begriffs** [comment]
Also Data.Thyme has a FromJson instance for ZonedTime as well which for all I know may parse `2015-03-30 09:31:53-07:00` just fine.

https://hackage.haskell.org/package/thyme-0.3.5.5/docs/Data-Thyme-LocalTime.html#t:ZonedTime

**Comment by adambaker** [comment]
It may. I wouldn't use it because I don't believe an API should be handing out times in any zone other than UTC.

This isn't urgent. I wrote a parser for the times we get back (without timezones). It would be nice.

**Comment by begriffs** [comment]
(I'm noting your discovery here for other people's benefit)

If you have some_timestamp_column, you can output it in exactly the right ISO format like so

```sql
select to_char(some_timestamp_column, 'YYYY-MM-DD"T"HH24:MI:SS.MSZ')
```

For those who don't want to specially format the column in a view but are satisfied with things at least being displayed in GMT, they can have a database admin set the `timezone` connection default for an entire database.
http://www.postgresql.org/docs/9.4/static/runtime-config-client.html#GUC-TIMEZONE
This will affect the zone used for the default display of timestamptz's.
