### ISSUE TITLE
PUT Request Issue with auto increment table

### ISSUE THREAD

**Issue by zukeru** [begriffs/postgrest#178]
I'm trying to understand how the software works currently. I'm trying to make a put request to my database to store a user, and I have a column called is which is a auto incrementing sequence. When I try to do the put request without the id in the json it says must include all columns. When I make the put request I get the following error:

'''
{
"hint": null,
"details": null,
"code": "22P02",
"message": "array value must start with \"{\" or dimension information"
}
'''

I get this error even when I put a value in for id, the below request is left blank with the idea that it would create it with the auto increment.

my request:
'''
{
    "id":"",
    "username":"myusername",
    "password":"password",
    "email":"test@gmail.com",
    "first_name":"grant",
    "last_name":"zukel"
}
'''
my header:
'''
Accept: application/10.0.0.6:3000+json; version=1
'''
Url
'''
http://10.0.0.6:3000/user
'''
database
'''
tablename: user
schemaname: 1
'''
Get request work fine.

**Comment by begriffs** [comment]
Does the record already exist and you're trying to update it, or are you trying to create a new record? If you want to make a new one you can post rather than put. If you want to update the record then you need to include the pre-existing id value, not a blank string. If you want to update certain parts of the record but not all of it you can use an HTTP patch.

**Comment by zukeru** [comment]
I am trying to create a new record, when I change it to post with 

raw_data '''
{
    "id":"",
    "username":"zukeru",
    "password":"gismogt",
    "email":"zukeru@gmail.com",
    "first_name":"grant",
    "last_name":"zukel"
}
'''
it gives me '''
{
"hint": null,
"details": null,
"code": "22P02",
"message": "array value must start with \"{\" or dimension information"
}
'''

**Comment by begriffs** [comment]
How about if you omit the id field when posting?

**Comment by zukeru** [comment]
same thing without the id field

**Comment by zukeru** [comment]
postgrest  --db-host localhost  --db-port 5432     \
           --db-name thewaywardjourney     --db-user test \
           --db-pass passwprd     --db-pool 200      \
           --anonymous postgres --port 3000

**Comment by zukeru** [comment]
{
    "username":"test",
    "password":"test",
    "email":"test@gmail.com",
    "first_name":"grant",
    "last_name":"zukel"
}

{
"hint": null,
"details": null,
"code": "22P02",
"message": "array value must start with \"{\" or dimension information"
}

**Comment by zukeru** [comment]
of note I have another table with data in it that returns data with get request. It is just the post request that aren't working on that table.

**Comment by begriffs** [comment]
What is the definition of your table, and what route are you posting to?

**Comment by zukeru** [comment]
I know I need to change the types but made it as easy as possible.
 
                                    Table "1.user"
   Column   |           Type            |                   Modifiers                    
------------+---------------------------+------------------------------------------------
 id         | integer                   | not null default nextval('user_seq'::regclass)
 username   | character varying(4000)[] | 
 email      | character varying(4000)[] | 
 first_name | character varying(4000)[] | 
 last_name  | character varying(4000)[] | 
 password   | character varying(4000)[] | 

route url: http://10.0.0.6:3000/user

header: Accept:application/10.0.0.6:3000+json; version=1

raw: 
{
    "username":"test",
    "password":"test",
    "email":"test@gmail.com",
    "first_name":"grant",
    "last_name":"zukel"
}
retrurn:
{
"hint": null,
"details": null,
"code": "22P02",
"message": "array value must start with \"{\" or dimension information"
}

**Comment by zukeru** [comment]
I changed my table types to character varying(4000) instead of the character varying(4000)[] and now im getting malformed json.

**Comment by zukeru** [comment]
the problem was the varying char [] i deleted the array [] and now it works but when it saves a record it doesn't return a value is that right?

**Comment by zukeru** [comment]
is there a way to get it to not add the value if it exist?
