### ISSUE TITLE
Pre-flight ajax request is registering with the server as Options but my post never post

### ISSUE THREAD

**Issue by zukeru** [begriffs/postgrest#179]
I'm using ajax to post data to the api and on the api server my post are showing up as options. I did some research and from what I found that is the pre-flighted request. My POST request are never arriving. I wonder if you could help me out as to why?

I"m using the same code on my main page to post to a another table with essentially the same code and its working.

I'm loggin the returned data from the post

this is me outputting the post data from my form to make sure it got all the data.
    
     Object {username: "a", password: "a", email: "a", first_name: "a", last_name: "aa"}

this is the response header

    login.html:51 Object {readyState: 0, getResponseHeader: function, getAllResponseHeaders: function,       setRequestHeader: function, overrideMimeType: function…}
    Navigated to file:///H:/Prologue/login.html

database structure

    'CREATE TABLE "1"."user"
    (
      id integer NOT NULL DEFAULT nextval('user_seq'::regclass),
      username character varying(4000),
      email character varying(4000),
      first_name character varying(4000),
      last_name character varying(4000),
      password character varying(4000)
    ) 

This is postgrest output:

    10.0.0.3 - - [01/Apr/2015:19:19:43 -0600] "OPTIONS /user HTTP/1.1" 200 - "" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"

the ajax call

		'''<script>
			$.ajaxSetup ({
				// Disable caching of AJAX responses
				cache: false
			});
			function register() {
				console.log('send message');
				var email = document.getElementById("email").value;
				var username = document.getElementById("usernames").value;
				var first_name = document.getElementById("first_name").value;
				var last_name = document.getElementById("last_name").value;
				var password = document.getElementById("passwords").value;
				var post = { "username": username, "password": password, "email": email, "first_name":first_name, "last_name": last_name };
				console.log(post)
				$.ajax({
					headers: { 
						'Accept' : "application/10.0.0.6:3000+json; version=1",
						'Cache-Control': 'no-cache'
					},
					url: 'http://10.0.0.6:3000/user',
					dataType: 'json',
					type: 'post',
					contentType: 'application/json',
					data: JSON.stringify( post ),
					processData: false,
					  success: function(data){
						console.log(data);
					  },
					  error: function(data){
						console.log(data);
					  }
				});

			}
			
		</script>'''

**Comment by zukeru** [comment]
I'm also running into this problem with a page hosted in a iframe or if I try to post on the one that works twice and im not sure why. Any help would be appreciated.

**Comment by zukeru** [comment]
fixed close.

**Comment by begriffs** [comment]
What turned out to be the problem?
