### ISSUE TITLE
Update Response Code 204 Issue.

### ISSUE THREAD

**Issue by zukeru** [begriffs/postgrest#182]
I'm doing a patch statement, the update is being completed on the database. The return code however is 204. That means the statusText for my call is Not Found, but it updated it. Furthermore if it doesn't find the entry it replies not found as well.

I can't report on the status of my message update if the response code does not reflect a correct response.

Here is my code:
    URL: Cynergi.update('http://127.0.0.1:3000/page_contact?id=eq.26', json_data);

    Cynergi.update = function(url, data){
				var request = new XMLHttpRequest();
				request.open("PATCH", url, false);
				request.setRequestHeader('Accept', 'application/thewaywardjourney.com:3000+json; version=1');
				request.send(JSON.stringify(data));
				updateStatus = request.statusText;
				console.log(request);
				return updateStatus;
    }

I've tried using put but I get a 405 which is method not allowed. 204 means succeeds with no content from what I can gather reading through the source code. 

Any ideas?

**Comment by begriffs** [comment]
Ah, so whether or not any rows get updated the server responds 204 (success with empty response) so you can't tell on the client how many rows have changed.

Ideally we could set a response header to indicate how many things were changed, but a good first step would be to return 404 if no rows were updated.

Am I understanding your issue correctly?

**Comment by MadMartigan** [comment]
I think returning a 404 when no rows are updated would be a good choice.   In my situation I am using a incrementing version_id field in the database to avoid stale data overwrites.  So knowing if any rows were updated is the only way for me to notify the user that they need to refresh and save again.   

btw... GREAT project!  Thank you for all your hard work.
