### ISSUE TITLE
Allow Prefer: return=representation on PATCH request

### ISSUE THREAD

**Issue by MadMartigan** [begriffs/postgrest#187]
I might have a use case for allowing a PATCH request to return the updated data. 

In a situation where you have a trigger which modifies table data before update, there is no way for the client to know the updated value without re-requesting the resource.  Allowing "Prefer: return=representation" may be a solution.

**Comment by begriffs** [comment]
Good idea!

I'm going to work on the stored procedure issue first and then I can get to this. How high priority is it for you?

**Comment by MadMartigan** [comment]
No hurry at all, I'm still in development mode for a while.  Looking forward to using postgrest on a fairly large e-commerce site.

**Comment by begriffs** [comment]
I am getting a SQL syntax error for queries such as

```sql
SELECT count(t),
       array_to_json(array_agg(row_to_json(t)))::character varying
FROM
  (UPDATE "1".simple_pk
   SET (extra) = ('20'::UNKNOWN) RETURNING *) t
```

Postgres complains about the '.' in line 4. I need to use this kind of a query to return a representation of changed rows. I'll keep working on this but wanted to share the problem in case somebody knows what to do.

**Comment by begriffs** [comment]
(I managed to fix the SQL syntax error by using a CTE)
