### ISSUE TITLE
PATCH is converting null values into empty string

### ISSUE THREAD

**Issue by MadMartigan** [begriffs/postgrest#188]
I think there may be an issue concerning null values on patch requests.  As far as I can tell, postgrest is converting JSON null values to empty strings.  

I have tested with multiple rest clients, the results are the same. When trying to update a table with a column that has a unique constraint, the patch request fails due to a unique constraint error.  When updating the same column through sql, the update succeeds. 

For clarity here are the test queries I used. 

SQL : Succeeded
`UPDATE item
   SET gtin=null, height=10
 WHERE id='1';`

PATCH: Failed:
`http://localhost:3000/item?id=eq.1
{"gtin" : null, "height" : 10}`

**Comment by begriffs** [comment]
Thanks for the report, I'll check it out.

**Comment by begriffs** [comment]
This has been fixed. https://github.com/begriffs/postgrest/blob/master/test/Feature/InsertSpec.hs#L264-L268
