### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by andrewcstewart** [begriffs/postgrest#189]
Hey there.  I was playing around with PostgREST and ended up making a dockerfile for myself.  Thought you may be find it useful?  (I use the example call to postgrest from the documentation but obviously one would want to change that, or probably replace the parameter values with environment variables that can be set during container run time).

https://gist.github.com/andrewcstewart/f5b41912747401a3db01

**Comment by begriffs** [comment]
This is very cool, thank you!

Care to add more details to this wiki page? We can then link to it from the readme.
https://github.com/begriffs/postgrest/wiki/Docker
