### ISSUE TITLE
Option to serve a directory of static files

### ISSUE THREAD

**Issue by srid** [begriffs/postgrest#190]
Although I realize that this may be out of scope for this project, I wonder if postgrest can be modified to provide an option (`--static-dir`) to serve a custom directory containing static assets (HTML, css, JS).

I would like to use postgrest on Heroku and access it straight from JavaScript (actually, Elm). I would like to run just a single web process for all of this. Normally postgrest is run as "web1" and the static files are served via warp as "web2" - but the later is redundant, and Heroku's free tire supports running single node only.

**Comment by srid** [comment]
Another option is to write a small Scotty server and somehow invoke [this](https://github.com/begriffs/postgrest/blob/master/src/Main.hs), while mapping `/static/` to server local files. I'm not greatly experienced with Haskell, but will poke around this option now ...

**Comment by begriffs** [comment]
It actually shouldn't be too hard to implement, just a change in
https://github.com/begriffs/postgrest/blob/master/src/Main.hs#L55

There was some discussion about it in #136 - what's your opinion about the topics raised there?

**Comment by srid** [comment]
I don't have a strong opinion either way with respect to the general production uses case. I'm only trying to get postgrest up and running for my personal projects (based on self-tracking) where nobody but me would be using the system. 

I'm taking baby steps, by getting postgrest working against Heroku. The road block I'm hitting is trying to understand the configure the [auth system](https://github.com/begriffs/postgrest/wiki/Security-and-Permissions). The configuration seems complicated for my use case. I executed the SQL under "Example scenarios" and the scenario I'm looking for read-write access to only single user. So much to understand ...

**Comment by trinque** [comment]
> Now I see that it makes sense to let PostgREST focus on providing the REST API - and let nginx or a CDN serve the static assets.

That guy has it. This seems to be an unnecessary bit of complexity given that the deploy should always involve a frontend webserver capable of TLS.

**Comment by rngadam** [comment]
Would like to see this feature just for the development phase where the development occurs on the localhost machine. 

It's convenient to have both the API and static resources served from the same URL. Example: create database, start postgrest, write an index.html (hopefully with autoreload on change functionality), query the API from the index.html.

Once deployed, that static/ directory can of course be served by an nginx instance. It's very typical development flow when using other environments such as ExpressJS.

**Comment by begriffs** [comment]
How about a nice copy-and-paste example in the docs of an nginx config file for this use case?

**Comment by rngadam** [comment]
I could, but I don't want/should not need to have to setup nginx on my desktop. What I end up doing is running ```autoreload-server``` npm package. It watches for updates to files and reloads the page (websocket connection) and serves it on a separate port. It's convenient; it would be even more convenient if postgrest did this out of the box.

**Comment by PierreRochard** [comment]
I'm going to be blunt: I don't see why you "should not need to have to setup nginx on my desktop" when you need a feature that nginx has and is best suited for. 

I don't want PostgREST to be anything but a REST API server for my PostgreSQL database. Any effort put into re-creating nginx functionality detracts from its core purpose.

**Comment by begriffs** [comment]
@rngadam I empathize with you that installing a reverse proxy on a dev machine might sound intimidating/annoying, but as @PierreRochard says, it's a nice separation of concerns that helps postgrest stay lean.

Installation shouldn't be so bad though - there are [packages](https://nginx.org/en/linux_packages.html) for linux and `brew install nginx` should do it on mac ([mac howto](https://coderwall.com/p/dgwwuq/installing-nginx-in-mac-os-x-maverick-with-homebrew)).

**Comment by ruslantalpa** [comment]
A better option is to just have docker on you dev box (useful in lots of ways) then it will be very easy to start nginx/postgrest from docker, you will just need to have one config file on your disk, no need to install anything else (we can provide that config file in the docs or separate repo).

**Comment by fab1an** [comment]
I think it would be great if postgrest could be configure to serve `index.html` (and only that) from a view in the database.

Benefits:
* Single-page-apps are possible (javascript and images can be easily inlined nowadays).
* no file-access for postgrest
* no routing logic.

**Comment by raoofha** [comment]
hey guys sorry to bother and thanks for PostgREST I just want to say I add a static file server in my fork [PostgRESTui](https://github.com/raoofha/postgrestui/releases) in case anyone interested

**Comment by elimisteve** [comment]
Here's a new-ish tutorial for serving up images or other binary data directly from PostgREST, though yes the file data is stored in the DB, not on the file system: https://postgrest.org/en/v7.0.0/how-tos/providing-images-for-img.html
