### ISSUE TITLE
0.2.8.0 is unavailable on Hackage

### ISSUE THREAD

**Issue by srid** [begriffs/postgrest#192]
https://hackage.haskell.org/package/postgrest has only 0.2.7.0 but changelog indicates that 0.2.8.0 is already released. I'm trying to use postgrest as library in my Haskell program.

**Comment by begriffs** [comment]
Oops, I'll put it on hackage.

Also we may have to make some changes to allow you to use it as a middleware.

**Comment by srid** [comment]
> Also we may have to make some changes to allow you to use it as a middleware.

Yes, thank you. Earlied I saw [some ideas here](http://stackoverflow.com/a/12305972/55246).

**Comment by begriffs** [comment]
It's now uploaded.

**Comment by srid** [comment]
Thanks.

@begriffs - FYI, I started work on this (to unblock myself from [working on this](https://groups.google.com/forum/#!topic/elm-discuss/6kyabQgUMJk)) here: https://github.com/srid/postgrest/commits/makelibrary

If on the hand if you had started on it already, please let me know - maybe I can provide you with some of my time.
