### ISSUE TITLE
Read configuration from Environment Variables

### ISSUE THREAD

**Issue by framp** [begriffs/postgrest#195]
In an effort to comply with the [twelve factor app manifesto](http://12factor.net/config), I think it would be great to support reading configuration from `System.Environment`

**Comment by srid** [comment]
I implemented this here: https://github.com/srid/postgrest/commit/dbdfe4e21e655529b84aba52ca6062ec4ecdf8cd

Would be happy to send a PR replacing all those `--db-???` arguments with a *single* `--db-uri`. I run that forked postgrest like this on heroku:

```
web: postgrest -p ${PORT:-3000} --db-uri=${DATABASE_URL:-"postgres://"}
```

**Comment by framp** [comment]
What I actually meant was to support reading the arguments from ENV from the code, without using an external tool.

Like in: 

    DB_NAME=whatever DB_USER=authenticator ... postgrest

Nowadays I deploy most of my apps as docker-compose configuration file + a repo: setting everything in the environment makes everything so much simpler

**Comment by begriffs** [comment]
I'd suggest @srid's solution of interpolating the vars on the command line.

Closing this issue, but happy to reopen if there are other reasons to consider using custom named env vars.
