### ISSUE TITLE
Third party (Github) login

### ISSUE THREAD

**Issue by framp** [begriffs/postgrest#196]
This is a lot of work and I'm not aware of any haskell library to do that (something analogous to [this on](https://github.com/jed/authom) for node.js).
But nowadays having third party login is a requirement in a lot of applications (at least for my clients, ymmv).

We can support third party login through a set of redirect at `/postgrest/auth/SERVICE`

Eg:
`/postgrest/auth/github` will redirect to github authentication page, receive the data back from github, login the user via JWT, redirect to a developer-configured URL passing the token (\* this is 'safe' only if on https).

The flow from the developer perspective is something like:
- Set up a github configuration file

```
{
  service: "github",
  id: "7e38d12b740a339b2d31",
  secret: "116e41bd4cd160b7fae2fe8cc79c136a884928c3",
  scope: ["gist"]
}
```
- Set up a redirect link

```
--third-party-redirect "https://my-app.com/logged#TOKEN"
```
- Set up my client side application to save the token to the same storage where the JWT tokens are stored using the normal login (`POST /postgrest/tokens`) and redirect the user to the application

The flow from the client perspective is something like:
- Click on `Github Login`
- Authenticate
- Get redirected to the application you were working in

**Comment by begriffs** [comment]
I can see how this feature would be really convenient.

Help me understand the flow a little better. How will postgrest know which user has logged in after examining a successful response from github?

**Comment by framp** [comment]
After logging on github, github will send POST data to our endpoint containing information about the user and a token for his session on the service.
With the user's email we can check if user is already registered and complete the login or create a new passwordless user.
In both cases we need to link the user with the new service storing the token (and, eventually the other data sent by the service: profile picture, job title, whatever).

From a technical point of view the best way to store 3rd party logins is to create another reserved table in the `postgrest` schema and have a 1-n relationship between `auth` and `linkedaccounts`.

Something like:

    linkedaccounts (userid, servicename, token, data) 
    VALUES ('totally@notmyemail.com', 'github', 'al1jlk234kj12lkhjlhsdf2ui3ocw4e', { profile_picture: "https://octodex.github.com/images/baracktocat.jpg"})

**Comment by begriffs** [comment]
I think we can handle Github logins using a service like https://auth0.com and configuring it to issue a special JWT that can be used with postgrest. I'm talking to their support people about it.

**Comment by begriffs** [comment]
@framp now that we've got JWT set up would you be interested in exploring how to integrate with github logins?

**Comment by begriffs** [comment]
@framp bump

**Comment by framp** [comment]
Hey Joe, time is tight as of lately but thanks for the ping.
I'll try to find some time for it and notify people in this thread as soon as I can work on it.

Anyway, I think supporting auth0 and providing openid authentication (what I was referring in the first one) are two different issues.

The second one seems more interesting to me - mainly because it's not a paid solution and works with everything.
Using http://hackage.haskell.org/package/authenticate should help us

**Comment by begriffs** [comment]
Now that I just made a bunch of improvements to JWT it reminds me of this issue. @framp anything to report about Github integration via JWT?

**Comment by begriffs** [comment]
I think people have successfully hooked up Github logins to PostgREST via Auth0 and JWT. I don't have documentation about it though.
