### ISSUE TITLE
Make postgrest string configurable

### ISSUE THREAD

**Issue by framp** [begriffs/postgrest#197]
It's probably a good idea to make the postgrest string configurable somehow.

One use case:
In this way people who don't want to be detected as using postgrest (eg: for security reasons) will be safer

**Comment by begriffs** [comment]
If I don't `setServerName` then I think Warp sets its own identifier. You're right that it would probably be a good idea to have a flag to conceal it.

**Comment by begriffs** [comment]
For now I'd suggest masking the string with nginx.
