### ISSUE TITLE
Add iss, sub, aud, exp, nbf, iat, jti support to JWT

### ISSUE THREAD

**Issue by framp** [begriffs/postgrest#198]
The Haskell JWT library doesn't offer an implementation at the time (even though there is [this issue](https://bitbucket.org/ssaasen/haskell-jwt/issue/9/make-it-easy-to-verify-exp-nbf-and-iat))

I'm not sure what's the best way to deal with the problem, maybe it's better to contribute upstream the changes and keep most of the changes outside postgrest?

The [Ruby library](https://github.com/progrium/ruby-jwt) by progrium is a good reference

**Comment by begriffs** [comment]
It would probably be most helpful for the Haskell ecosystem if these features were contributed to the [jwt](https://hackage.haskell.org/package/jwt) package itself.

**Comment by NikolayS** [comment]
Moreover, if you'll try to return, say, `iat` among other things in your jwt_claims value, PostgREST will suppress it and you'll not see it in JWT payload. At the same time, other wording (like `issued_at`) will work fine.

This issue limits PostgREST usage if you're trying to use it as a part of some large infrastructure where some parties expect standard JWT structure provided by your API.

**Comment by NikolayS** [comment]
:clap: great
