### ISSUE TITLE
Hai Joe Nelson....

### ISSUE THREAD

**Issue by darsana** [begriffs/postgrest#203]
I wanted to check the value of a particular field is null  like bellow,its an integer field,in some cases we are not inserting values to that field .

http://192.118.1.170:3003/person?mark=eq.null 

how can i write the same?can u help me?

**Comment by begriffs** [comment]
Sure, there's a special one for that: `?mark=is.null`. The full set of these filtering options can be found here https://github.com/begriffs/postgrest/wiki/Routing#filtering-and-ordering

(`eq` null would test that the column is equal to the string "null", kind of confusing I know but I had to find a way to distinguish those cases.)

**Comment by darsana** [comment]
Hey...thank you for the response ...I tried the way you said like bellow 
http://192.168.1.170:3003/person?mark=is.null 
Its and integer field ,so its giving the response like bellow,Can you help me to fix the same.

{
    "hint": null,
    "details": null,
    "code": "22P02",
    "message": "invalid input syntax for integer: \"null\""
}

**Comment by begriffs** [comment]
Odd, I'll investigate.

**Comment by begriffs** [comment]
Hi @darsana I'm not able to reproduce this issue. I created a test to guard against it and the test passes. Which version of postgrest are you using?
