### ISSUE TITLE
issue when integrating with wso2 api manage

### ISSUE THREAD

**Issue by arunnairmr** [begriffs/postgrest#204]
Hello, 
I am trying to integrate postgrest api into wsp2 api manger. GET,PUT,DELETE api works fine. But POST API is not work correctly inside API manager. Actually its may not your issue, If you have any idea about this, please help me.

http://wso2.com/api-management/try-it/

**Comment by begriffs** [comment]
I'd be happy to investigate. Can you give me some steps to reproduce the problem?

**Comment by arunnairmr** [comment]
step 1:
For example, I have a table named server and postgrest api for that table is,
http://localhost:3000/server
step 2:
Then create a API in wso2 API manager with production endpoint as our postgrest api (http://localhost:3000/server).
the following link help you for that.
https://docs.wso2.com/display/AM170/Quick+Start+Guide

step 3:
Access the POST API of api manager(GET api works correctly). You will get some error for that.

**Comment by arunnairmr** [comment]
I think the issue is because "Location" in the response header. Can we able to remove or disable the location value from header.

**Comment by arunnairmr** [comment]
as per the documentation given in the below link, Location value is  absolute URI. But in our case its relative URI. wso2 api manager trying to redirect into that path and getting failed. Here i need any of the following to solve the issue.
1. Remove the "Location" from response header.
2. Make "Location" value to  a valid absolute URI. 
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.30

**Comment by arunnairmr** [comment]
According to new release of ESB,  absolute URI is not mandatory. So WSO2 will handle the issue issue. 

https://wso2.org/jira/browse/ESBJAVA-3461

Thank you.

**Comment by begriffs** [comment]
OK, glad they are fixing the problem. I think returning a Location header after creating a resource is the right thing to do.
