### ISSUE TITLE
Update or Delete from postgrest/users

### ISSUE THREAD

**Issue by ireverent** [begriffs/postgrest#205]
Is there any way after adding a user through postgrest/users to update the underlying postgrest.auth table? Either to delete or to update passwords?

**Comment by begriffs** [comment]
Not from the rest api yet. It's still a manual process for the database admin. What's worse, the password fields are generated in a specific way by bcrypt in the Haskell code so it's hard to generate legitimate values for the password column of the auth table without busting out the Haskell repl and running bcrypt yourself.

**Comment by ireverent** [comment]
That is what I figure.  Starting to look at the code and it looks like it blindly inserts.  I wonder if one could run a check at that same point and then condition an update with the new bycrpt value of ID already exists instead of the insert.

**Comment by omani** [comment]
Hi begriffs,

I really enjoy using postgrest. I came here to push this issue. It would be really helpful to have CRUD operations on the postgrest/users resource. Think of a web app with users wanting to change their passwords. it would be nearly impossible to maintain this by hand.

**Comment by ireverent** [comment]
I am actually still working on this. Got pulled away for a large project with a short deadline.

**Comment by begriffs** [comment]
Actually don't worry about this one. Version 0.3 will not include user/password management internally but will delegate that to other programs or services using JWT.
