### ISSUE TITLE
Take into account `views.is_trigger_insertable_into` when emitting schema description

### ISSUE THREAD

**Issue by motiz88** [begriffs/postgrest#206]
When describing a view in JSON, it might be beneficial to use `views.is_trigger_insertable_into OR views.is_insertable_into` as the source of the `insertable` field, rather than just `views.is_insertable_into`. This field is supported [as of Postgres 9.1](http://www.postgresql.org/docs/9.1/static/infoschema-views.html).

Disclaimer: I am a relative newcomer to both Postgres and PostgREST, and cannot for the life of me read any Haskell, so I'm out of my depth here and could very well be wrong... Thought I might report the issue anyhow.

**Comment by begriffs** [comment]
Nice trick, thanks. Does postgrest currently describe some tables/views as insertable when they are not or vice versa?

**Comment by motiz88** [comment]
Yes, I have a non-automatically-updatable view with a working INSTEAD OF INSERT trigger, and it shows up as not insertable.
