### ISSUE TITLE
API testing

### ISSUE THREAD

**Issue by parauchf** [begriffs/postgrest#207]
I am using `INSTEAD OF` triggers and some other vodoo to customize my API.  Do you have any suggestions for testing my postgrest API instance using something like CircleCI?

In a sense it is a non-standard stack that none of the testing services will support out of the box.  Is there something like a buildpack or yml file that can help with the setup?

**Comment by begriffs** [comment]
What's an example scenario you'd like to test?

**Comment by parauchf** [comment]
Sorry, I missed this message.  Mine is probably an unusual use-case.  I use triggers to execute dynamic DDL and there's lots of edge cases that would be good to test.

After thinking about it though, I decided it is adequate to test the function of the triggers directly using SQL and trust that postgrest correctly translates the requests.  I have implemented my tests this way.

**Comment by begriffs** [comment]
Sounds smart to test as close to the sql as you can. A while back I discovered [pgTAP](http://justatheory.com/computers/databases/postgresql/introducing_pgtap.html) for writing succinct sql tests, you might find it helpful.

I'll close this issue for now but let me know if there is any integration test I could add to the postgrest suite to help ensure everything goes well for your use case.
