### ISSUE TITLE
Does bcrypt password use any kind of salt?

### ISSUE THREAD

**Issue by ireverent** [begriffs/postgrest#210]
I just started looking at the code in auth.hs and noticed that the fastBcryptHashingPolicy is used. Does this take any kind of salt value or does it do a straight hash. Thanks in advance.  

Figured this out on my own. Just got to look into the code.

**Comment by begriffs** [comment]
Bcrypt actually uses [built-in salts](http://stackoverflow.com/questions/6832445/how-can-bcrypt-have-built-in-salts).

However you're right to point out that only the `fastBcryptHashingPolicy` is used. Maybe we should turn that to a higher setting, or make it configurable via a command line argument.

**Comment by ireverent** [comment]
I think 2 changes should be made. We should have a flag to set the current hashing cost and we should have it so the validate password checks to see if the hash meets the current hashing policy and if not rehashes it with the new cost.

**Comment by begriffs** [comment]
:+1: Sounds smart. Can you help me out with a pull request?

**Comment by ireverent** [comment]
Sorry, kinda new to using github. Do you want me to make those changes and submit a pull request? Or can I make a pull requrest before I have actually made the changes.I Don't know when I will actually get to it as I am working on getting everything squared with the put on postgrest/users.

**Comment by begriffs** [comment]
Oh that's right. We can look at this issue after resolving the PUT issue.

**Comment by begriffs** [comment]
Oh by the way I don't think we can rehash an existing hash to increase its strength. I believe that doing so would mean we would be able to extract the plaintext for rehashing. But we could certainly provide a command line option to control hash strength for new hashes.

**Comment by ireverent** [comment]
I was looking at Crypto.BCrypt. Shouldn't be able to check if the current password matches the current hashing policy with hashUsesPolicy :: HashingPolicy -> ByteString -> Bool, store the plain text, hash it while maintaining the plain text, checking using validatePassword :: ByteString -> ByteString -> Bool  against the hash and if it validates rehash it using the  newer policy to rehash the stored plaintext into the new strong hash.

**Comment by begriffs** [comment]
Oh I see, at next user login recreate the password field with better hashing. That makes sense.

**Comment by ireverent** [comment]
Yeah, there is no way to safely autoupdate on increasing the HashingPolicy since that would ultimately break the hash. But we can check on each authentication and them apply the new policy.

**Comment by begriffs** [comment]
Since we won't be handling passwords anymore as of version 0.3 I'm closing this issue.
