### ISSUE TITLE
Fix GHC 7.10 build

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#212]
The `regex-tdfa-text` dependency requires `FlexibleContexts` to build. I have [forked](http://hub.darcs.net/begriffs/regex-tdfa-text) the package on darcs hub (!) but am unsure how to send a pull request there. I have tweeted at the maintainer, @shelarcy, to apply a fix. Not sure if the package is still actively maintained.

This package is needed for the `(=~)` comparisons in the PostgREST.PgQuery module between Text valued variables. There are a number of workarounds

- Convert variables to ByteString before comparing
- Ditch `regex-tdfa` altogether and find a new library
- Rewrite regex logic in terms of simpler string operations
- Include a forked copy of `regex-tdfa-text` as a module within our own codebase

**Comment by diogob** [comment]
How about trying to push this code into regex-tdfa package?
The description in the package reads: 
```
                   This should be part of regex-tdfa package. But my patches are
                   not accepted yet. So, I made a separate package. If you are
                   interested in my patches, see 
                   <http://hub.darcs.net/shelarcy/regex-base> and
                   <http://hub.darcs.net/shelarcy/regex-tdfa>.
```

I've found that these might be interesting if ditching ```regex-tdfa``` turns out to be the only way:

 * https://github.com/sebfisch/haskell-regexp
 * https://github.com/feuerbach/regex-applicative
