### ISSUE TITLE
Reconsider batch POST in JSON format

### ISSUE THREAD

**Issue by motiz88** [begriffs/postgrest#215]
I think there's a case for going beyond just CSV (#17) and supporting some form(s) of JSON transactional inserts.

1) _Transactional_ is IMHO the key word here, as it is in the discussion about JSON patch support (#208).
2) I believe that even if/when JSON patches are supported, the lack of a multi-inserting JSON endpoint will still stand out.
3) In my view, reusing PostgREST's JSON-to-SQL logic here would provide a clear win over using (and maintaining!) a CSV-with-coercions-and-reserved-words solution.

For a minimal implementation, I propose supporting the following:
```
POST /people
Content-type: application/vnd+postgrest.bulk.insert-proposal-1+json

{
    "fields": ["name", "age", "height"],
    "values": [
        ["J Doe", 62, 70],
        ["Jonas", 10, 55]
    ]
}
```

And I think the following should _probably_ also be supported, following the principle of least surprise (it doesn't have to be _recommended_ - you might want to actually warn against it for performance reasons - but I think it should work).

```
POST /people
Content-type: application/json

[
        {"name": "J Doe", "age": 62, "height": 70},
        {"name": "Jonas", "age": 10, "height": 55},
]
```

This would map to `BEGIN; INSERT ... ; (INSERT ..;)* COMMIT;`. You could even cheaply optimize for the well-behaved case and construct large `INSERT`s out of runs of neighboring records with the same structure.

**Comment by parauchf** [comment]
I would concur with your second proposal!  The first strikes me as again not very intuitive.

**Comment by motiz88** [comment]
@parauchf I like the second one's clarity too, but there's something to be said for providing an endpoint that avoids the bandwidth cost of repeated keys & CPU/memory costs of parsing/matching/validation on the server (_if_ you know ahead of time that you need just a simple `INSERT (...) VALUES (...)`).

**Comment by motiz88** [comment]
Maybe there's some kind of fringe alt-JSON encoding that can represent the second document more efficiently (combining the performance of 1 with the clean structure of 2). I'll look it up.

That in turn raises the interesting question of what's more intuitive - to accept an encoding that, well, isn't JSON :smile:, or to define and document our own little JSON wrapper schema for a well-defined need.

**Comment by parauchf** [comment]
@motiz88:
- WRT bandwidth, gzipped json is really the same as any fringe encoding you're going to find
- In terms of parsing, native JSON parsers are quite quick, so I would be hesitant to pre-optimize.  I would be curious why @begriffs went with CSVs originally

**Comment by begriffs** [comment]
@parauchf I went with CSV to avoid edge cases with JSON arrays of objects that aren't uniform, such as

```json
[
        {"name": "J Doe", "age": 62, "height": 70},
        {"name": "Jonas", "age": 10, "weight": 160}
]
```

It requires a scan through all the rows to see which columns are required, then filling in the blanks with default values in the sql insert. It was a complication. Whereas CSV a document can declare the columns in its first row and the parser can handle irregular row length for me.

Open to other ideas though, including clever ways of handling JSON as mentioned above.

**Comment by parauchf** [comment]
I see.  I don't know the internals, but couldn't you delegate that logic to the database with something like postgres' `json_populate_recordset(null:<target table>, <input json>)`  Would that create a vulnerability if properly prepared?

Here's a relevant [stackoverflow answer](http://stackoverflow.com/questions/25785575/how-to-parse-json-using-json-populate-recordset-in-postgres)

**Comment by sveniu** [comment]
I also support @motiz88's second proposal, and @parauchf's suggestion to use `json_populate_recordset` seems sane. Note [this bug](http://www.postgresql.org/message-id/25904.1417034922@sss.pgh.pa.us), however, which causes an error when trying to populate array fields. It might be worth keeping in mind when implementing.

**Comment by begriffs** [comment]
Nice, postgresql can do just about everything, can't it? Sounds feasible to use `json_populate_recordset` for json bulk insert.

**Comment by alyssaq** [comment]
+1 I would love this feature to bulk post with the 2nd JSON structure. With postgres and postgrest, my apps will be pretty much backendless :)

**Comment by begriffs** [comment]
@ruslantalpa do your changes to handling POSTs support bulk json insertion?

**Comment by ruslantalpa** [comment]
Yes, you can post a json array (as long as all the keys in all the objects match)

I.e. It will be available in v3

**Comment by begriffs** [comment]
In that case, closing the issue.
