### ISSUE TITLE
Build 32-bit binaries

### ISSUE THREAD

**Issue by monemihir** [begriffs/postgrest#220]
Hi,

I want to trial out this package. I am running Ubuntu 14.04 x86. I have PostgreSql 9.3 installed. I downloaded the binary for linux from the website but it does not run.

Looking at the file extensions in the source code, I can tell they are in Haskell. Having never used Haskell, I do not know how to proceed. Is there like a Haskell runtime I need to install or something?

I am getting the following error when I try to run the executable.

```
bash: ./postgrest: cannot execute binary file: Exec format error
```

Cheers
Mihir

**Comment by begriffs** [comment]
What is the URL of the compressed binary you downloaded?

**Comment by monemihir** [comment]
I have downloaded it from the github repository itself from the following URL:

https://github.com/begriffs/postgrest/releases/tag/v0.2.10.0

**Comment by begriffs** [comment]
Can you check if a previous version causes the same problem?

**Comment by sveniu** [comment]
Seems only 64-bit binary builds are available, so presumably you got a 64-bit build. Which arch is your Ubuntu? You say "x86", which is a bit ambiguous. Run `dpkg --print-architecture` to check if you're on i386 or amd64. If you're on i386, is it required by the hardware? If not, then you can install a 64-bit kernel and enable amd64 as an additional architecture (ref Debian/Ubuntu multiarch support), then install libc and other libraries corresponding to the correct arch.

**Comment by begriffs** [comment]
I'd like to have a better system for generating binaries. I currently build them by hand for Mac and Linux (on Heroku Cedar actually). I'd like to find a continuous build system to Haskell that will compile each version-tagged release for many architectures at once.

One other random thing I've been meaning to change is to not include the version number in the executable filename within the tarball, e.g. `postgrest` rather than `postgrest-0.2.10.0`. The version should only be applied to the tarball itself, not its contents.

**Comment by monemihir** [comment]
Ok so looks like @sveniu was right. The binary build is only 64-bit. I just tried running it on Ubuntu 15.04 64-bit and it atleast gave me the generic help when I ran it without specifying any options.

I did need to install **libpq5** as a dependency though.

I think I can now proceed and now actually get some work done :satisfied: ...

**Comment by begriffs** [comment]
Until I get a better cross platform build system in place could you add what you learned to this new wiki please? https://github.com/begriffs/postgrest/wiki/Troubleshooting

**Comment by begriffs** [comment]
The v0.2.12.0 release now includes a 32-bit binary.

https://github.com/begriffs/postgrest/releases/tag/v0.2.12.0
