### ISSUE TITLE
Array size exceeds the maximum limit allowed

### ISSUE THREAD

**Issue by kmatt** [begriffs/postgrest#224]
Performing a simple GET on a large table can exceed the limits of array_agg (I believe):

    ERROR: array size exceeds the maximum allowed (1073741823)
    STATEMENT: select (select count(1) from public.testtable) , count(t), array_to_json(array_agg(row_to_json(t)))::character varying from (select * from public.testtable LIMIT ALL OFFSET 0 ) t

Is there a way to limit result set size by default?

**Comment by begriffs** [comment]
The client can limit the request by sending the right [headers](https://github.com/begriffs/postgrest/wiki/Routing#limiting). But this problem suggests that the server should add a limit of 1073741823 if the client does not specify any limit.

Thanks for reporting this issue.

**Comment by begriffs** [comment]
It turns out that the large number is the number of bytes in a gigabyte minus one. PostgreSQL has a max field length of 1GB. I'll update postgrest to enforce a max result row count.

**Comment by begriffs** [comment]
This should fix your issue, but I want to devise a test for it before merging to master. Maybe a unit test since actually returning this many rows in an integration test could be intense.

**Comment by datasaur** [comment]
Debugging a similar array size overflow with that commit cherry-picked, but noted something interesting the query being executed:

    select  (select count(1) from api.testtbl) , count(t), array_to_json(array_agg(row_to_json(t)))::character varying from (select * from api.testtbl LIMIT 1073741823 OFFSET 0 ) t;

If I am not mistaken, the first sub-select (select count(1) from table) counts all rows in the table, and could potentially add significant runtime. What is that total row count used for?

**Comment by begriffs** [comment]
It is there to set the Range response header. The response will say something like `Range: 100-199/5000` to tell the client which items were selected and how many there are total. The client can use this for drawing a pagination control.

We could adjust this behavior for performance though. When the total size is really big we could decide to strategically reply with `Range: 100-199/*` to indicate we don't know the total or don't choose to calculate it.

**Comment by datasaur** [comment]
Does not "count(t)" return the number number of rows selected? The "select count(1) from table" will be the un-LIMIT-ed size of the table, and potentially more than the client will be able to page through - unless I am still missing something.

BTW - Looking into this as LIMIT 1073741823 still overflows for me, as that is a byte limit, and LIMIT is a row count maximum. Wondering if a LIMIT of 1073741823 / (max row width in bytes) is a potential solution.

**Comment by begriffs** [comment]
I'm unsure how to handle this problem. I could set a max result count but I think the database is having problems with serialization byte count rather than number of results. The width of a result set would then affect the max rows. We could provide a command line argument to customize the max row count, or just let it keep failing the way it does now when too much data is requested.

To your second point there is now an issue specifically about speeding up (by estimation or omission) the table count. https://github.com/begriffs/postgrest/issues/255

**Comment by begriffs** [comment]
Also #288 seems like a good workaround. It would allow you to set a max row count of your choice -- a small enough one to avoid the array size limit.

**Comment by begriffs** [comment]
Closing this issue to deal with it in 288.
