### ISSUE TITLE
Request logging

### ISSUE THREAD

**Issue by timbod7** [begriffs/postgrest#225]
postgrest does a nice job, but sometimes it's hard to see what is going on. This commit 9b15071f23996ade3cb4823f17dba389c9a58e24 looks like it is supposed to enable logging, but I don't see anything logged to stdout. 

Do I need to do something to enable it?

**Comment by begriffs** [comment]
When running the newest version of the postgrest server (with no special command line arguments) and making web requests to it here is what I see on the console:

```
127.0.0.1 - - [09/Jul/2015:23:03:30 -0700] "OPTIONS / HTTP/1.1" 200 - "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36"
127.0.0.1 - - [09/Jul/2015:23:03:36 -0700] "GET /items HTTP/1.1" 200 - "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36"
```

Are you seeing this level of logging as well?

**Comment by timbod7** [comment]
Oh. I see that the logging is actually occurring - because of the small number of requests, buffering was delaying the output. Perhaps a command line flag to switch between `logStdoutDev` and `logStdout` would be handy.

Thanks for the response.
