### ISSUE TITLE
Is there any way to only select specific columns?

### ISSUE THREAD

**Issue by monemihir** [begriffs/postgrest#227]
Our database has more than 30 columns and I am trying to reduce the amount of JSON payload returned.

Is there a filter I can use to select only a subset of columns something like:

http://localhost/table1?columns=col1,col2,col3

**Comment by jmorris644** [comment]
@monemihir Something outside of a view? Is there a reason that a view will not work for you?

**Comment by marcioaguiar** [comment]
I think this feature is important. I, personally, do not want to create a view for every combination of fields I need in my different views.

**Comment by begriffs** [comment]
I agree that views can technically do the job but I can see how it would be convenient to restrict the columns with a query string to avoid creating lots of little views. Shouldn't be too hard to implement either.

**Comment by themightychris** [comment]
Google's latest partial response syntax is really nice: https://developers.google.com/classroom/guides/performance#partial-response

Probably overkill for just listing the columns you want transferred, but would be sweet if the full syntax was supported for JSON columns

**Comment by jmealo** [comment]
:+1: @themightychris

**Comment by ruslantalpa** [comment]
i've added support for this in my pull request.
You can do
&select=col1,col2,col3->sub1->>sub2
Suggestions welcomed

PS: google syntax is nice, the pull request provides the equivalent of
fields=fld1,fld2/sub
fields=items(title,characteristics/length) is a lot trickier but doable

**Comment by begriffs** [comment]
Ruslan's changes are available in release 0.2.12.0!
