### ISSUE TITLE
No log if stdout is not a terminal

### ISSUE THREAD

**Issue by mkhon** [begriffs/postgrest#229]
When I run postgrest in a terminal I get log/access log on stdout.
If postgrest stdout is not a terminal there is no output.

root:~# /usr/local/bin/postgrest --db-name db --db-user dbuser --anonymous dbuser --db-pass dbpass --v1schema public --port 3001
WARNING, running in insecure mode, auth will be in plaintext
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 3001
127.0.0.1 - - [21/Jul/2015:11:30:41 +0200] "GET / HTTP/1.1" 200 - "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12"
127.0.0.1 - - [21/Jul/2015:11:30:41 +0200] "GET /favicon.ico HTTP/1.1" 404 - "http://localhost:3001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12"
^C
root@ns398860:~# /usr/local/bin/postgrest --db-name db --db-user dbuser --anonymous dbuser --db-pass dbpass --v1schema public --port 3001 | tee /tmp/postgrest.log
^C
root:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.1 (jessie)
Release:        7
Codename:       jessie
root:~#

**Comment by exercism-1** [comment]
Sounds like a missing `hSetBuffering stdout LineBuffering`.

**Comment by begriffs** [comment]
Happy to change the buffering like you suggest.
