### ISSUE TITLE
Build/Install Instructions from Source

### ISSUE THREAD

**Issue by scherrey** [begriffs/postgrest#231]
I've not done haskell for many years so need to refresh myself with it. I do need to extend some of the code to test out some ideas for extending postgrest so am getting back into its way of thinking. So far, all the docs I've seen only talk about installing the binaries. I need to be able to (frequently) alter code and run it. Are there any docs for doing this for a newbie haskell dev?

Also, is there any general discussion forum or irc channel for discussing postgrest architectural drivers and features or should that just be done here? I think this is a very promising project and certainly would like to participate in helping it move forward.

**Comment by steventlamb** [comment]
I was able to build this and run the executable buy cloning the repo and running:
`sudo apt-get install libpq-dev` (specific to my distro/installed packages, your system dependencies may vary)
`cabal sandbox init` (optional, but nice for managing haskell dependencies)
`cabal install`

In other words, it looks like this is standard haskell package built with cabal, and build instructions should be covered by the cabal user guide. https://www.haskell.org/cabal/users-guide/. It might be a good idea to add a note about using cabal to the README.

**Comment by begriffs** [comment]
That's right, thanks for responding to this issue @steventlamb.

There is some setup to get tests running locally as well. It requires a database and user with specific names:

```bash
createuser --superuser --no-password postgrest_test
createdb -O postgrest_test -U [your_main_user] postgrest_test
```

(Where `your_main_user` is specific to your local postgresql configuration.) Once you have the db set up you can run feature tests by

```bash
cabal test --show-details=always --test-options="--color"
```

which will display the results in a nice format.

**Comment by begriffs** [comment]
New improved installation instructions available here: http://postgrest.com/install/server/#building-from-source

It uses Stack now which makes things way easier.
