### ISSUE TITLE
JWT vulnerabilities

### ISSUE THREAD

**Issue by WnP** [begriffs/postgrest#232]
Can we ensure that the JWT auth system is not vulnerable to [the last critical vulnerabilities issues](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/) found in most of JWT libraries?

**Comment by begriffs** [comment]
Thanks for bringing this up. PostgREST uses the [jwt](https://hackage.haskell.org/package/jwt) package, so that is where we should direct our audit.

**Comment by WnP** [comment]
thanks @begriffs 
looks like [this issue](https://bitbucket.org/ssaasen/haskell-jwt/issues/15/allow-consumers-to-fix-the-expected) is directly related to this one
