### ISSUE TITLE
JSON booleans implicitly converted to SQL strings

### ISSUE THREAD

**Issue by Jefffrey** [begriffs/postgrest#233]
In the example website if we query `https://postgrest.herokuapp.com/speakers?id=eq.54` we get something like:

```json
[
  {
    "id": 54,
    "name": "測試",
    "twitter": "twitter.com/random",
    "avatar_url": "",
    "bio": "Something",
    "featured": false,
    "lineup_order": 3
  }
]
```

Now, let's say that we want to update the bio field:

If I submit a `PATCH` request on the same URI with the payload:

```json
{
    "bio": true
}
```

I get a 204 - No Content response and querying the resource again gives:

```json
[
  {
    "id": 54,
    "name": "測試",
    "twitter": "twitter.com/random",
    "avatar_url": "",
    "bio": "True",
    "featured": false,
    "lineup_order": 3
  }
]
```

Is this intended behaviour?

**Comment by begriffs** [comment]
When updating the database postgrest sends values as strings marked with type unknown, like `'true'::unknown`. This allows the database to coerce things when possible without postgrest itself needing to have foreknowledge of the types of each column. Most the time this does what you want but sometimes it can be too permissive as you pointed out.

I'd agree that this is a bug. It should reject a boolean passed in for a string column. The fix may take some work though and my instinct is to prioritize other bugs/features higher. Thoughts?

**Comment by Jefffrey** [comment]
I'm personally a big fan of making things as restricted as possible, so I'm naturally against this idea. In my personal experience such dynamic systems provide little to no benefits at the huge expense of having few small issues slip through. 

I'm sure that implementation wise it could be a PITA to enforce the type of each field, especially when SQL provides so many different types, but overall there seems to be a direct mapping between XML/JSON types and SQL types (however loose), which I think should be used to restrict the possible API misuses.

Not to mention that in some other cases these misuses *do* trigger such errors, which yields inconsistency in the overall API. For example, taking the same resource as before, with a `PATCH` as:

```json
{
    "featured": null
}
```

we get:

```json
{
  "hint": null,
  "details": null,
  "code": "22P02",
  "message": "invalid input syntax for type boolean: \"\""
}
```

**Comment by begriffs** [comment]
Hmm, I see what you mean. Some of that coercion logic was developed to handle query string parameters (which are all of type string and are used for filtering). However types in a parsed json object should be better respected as you point out.

Thanks for pointing this out. I'll add test coverage and fix this.

**Comment by begriffs** [comment]
At this point I'd like to ensure that fields can be set to null. The broader issue of coercing of true to "true" for a string field seems less important. I'd totally accept a pull request to fix it, but there are other things I'd personally like to work on in the near future.

I wrote a test to ensure a string field can be set to null. This worked OK but maybe there is something about a boolean field that doesn't work.
