### ISSUE TITLE
inconsistent response to HEAD requests

### ISSUE THREAD

**Issue by drawks** [begriffs/postgrest#236]
calling HEAD against the root url returns a response with a body which seems, to me, to be a violation of RFC2616#9.3 which requires HEAD requests to not have a response body. HEAD calls against other valid endpoint URIs returns a 404 while a GET returns 200. A head call against a valid URI should succeed with a 200 if the GET would have succeeded so that the existence of resources can be tested without retrieving the full contents.

**Comment by begriffs** [comment]
You're absolutely right. The root route currently behaves the same for all verbs, and no other route explicitly handles `HEAD`. I haven't implemented it yet but I need to.

**Comment by begriffs** [comment]
Note to self: the head response should include a count of the resource items via

```http
Content-Range: */n
```

**Comment by calebmer** [comment]
@begriffs: I remember the last time this was discussed there was some mention that adding a `Content-Range` to a `HEAD` request was invalid via the HTTP spec. Is this true?

**Comment by ruslantalpa** [comment]
Will be tracked in #133
