### ISSUE TITLE
ERROR:  missing FROM-clause entry for table "posts"

### ISSUE THREAD

**Issue by juanpastas** [begriffs/postgrest#238]
Hi,

I tried [signed in authors can edit own content](https://github.com/begriffs/postgrest/wiki/Security-and-Permissions/b0d7f1a2c30cb901148401c07379565c309aa0a2#scenario-signed-in-authors-can-edit-own-content).

But I am getting this error:

```
ERROR:  missing FROM-clause entry for table "posts"
LINE 11:  SELECT posts.body,
                 ^
********** Error **********

ERROR: missing FROM-clause entry for table "posts"
SQL state: 42P01
Character: 264
```

Any advice?

I also made a change in the wiki which is incorrect, I thought I would have opportunity to make it right, but it just published change.

**Comment by juanpastas** [comment]
This worked for me:

```SQL
-- underlying source table
CREATE TABLE "1".all_articles (
  body text,
  id serial NOT NULL,
  owner character NOT NULL,
  CONSTRAINT posts_pkey PRIMARY KEY (id)
) WITH ( OIDS=FALSE );

-- view for reading/writing
CREATE OR REPLACE VIEW "1".articles AS 
 SELECT all_articles.body,
    all_articles.id,
    all_articles.owner
   FROM "1".all_articles
  WHERE all_articles.owner = current_setting('user_vars.user_id');

GRANT ALL ON TABLE "1".articles TO author;

-- the trigger function to bookkeep owners
CREATE OR REPLACE FUNCTION postgrest.update_owner()
  RETURNS trigger AS
$BODY$
BEGIN
   NEW.owner = current_setting('user_vars.user_id'); 
   RETURN NEW;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;

-- activate it on all_articles
CREATE TRIGGER articles_owner_track
  BEFORE INSERT OR UPDATE
  ON "1".all_articles
  FOR EACH ROW
  EXECUTE PROCEDURE postgrest.update_owner();
```

I would like to confirm this is correct, because I am not so familiar with DBs. From what I understand this:

1. creates a table all_articles
1. creates a view articles which is needed to use current_setting
1. grant permissions on the view to author, I created a new login role in pgadmin for that
1. setting the current user in column owner after insert or update a record.

**Comment by juanpastas** [comment]
I think I will rename all_articles to posts.

**Comment by begriffs** [comment]
Thanks for reporting this. We're writing new docs on http://postgrest.com and we'll improve this. Plus PostgreSQL 9.5 beta was released so we can use row-level security now!
