### ISSUE TITLE
Request for an addition to the documentation about the required minimum version of PostgreSQL

### ISSUE THREAD

**Issue by GeraldScott** [begriffs/postgrest#239]
I am currently running PostgreSQL 9.1, and I was not sure if PostgREST requires the JSON datatype as a minimum. 

Anyway, I am going to upgrade in any event, but I thought it would be a welcome addtion to have a "Minimum Requirements" page on the wiki.

Thanks for what looks like a wonderful product.

**Comment by begriffs** [comment]
Good idea, I'll update the readme and the [new docs](http://postgrest.com/).
