### ISSUE TITLE
Update demo server to latest version

### ISSUE THREAD

**Issue by alyssaq** [begriffs/postgrest#241]
Hi

I'm trying to do a batch post with this command using the [v0.2.10.0 binary](https://github.com/begriffs/postgrest/releases/tag/v0.2.10.0) (tried both osx and linux):
```
curl -XPOST -H "Content-Type:text/csv" -d "id,name,site_url,logo_url\n1,test,test,test\n" https://postgrest.herokuapp.com/sponsors
```
I also tried moving the content into a csv file: sponsors.csv:
```
curl -XPOST -H "Content-Type: text/csv" -d @sponsors.csv  https://postgrest.herokuapp.com/sponsors
```
In both cases, I get this 400 response error: 
```
{"message":"Failed to parse JSON payload. Failed reading: satisfy"}
```
I've also tried posting using golang and obtained the same result.

Posting with `text/csv` header and json object works:
```
curl -XPOST -H "Content-Type: text/csv" -d '{"id":1, "name":"hello","site_url":"github.com","logo_url":"github.com"}'  https://postgrest.herokuapp.com/sponsors
```

Whats the correct way to do a batch post with csv?

**Comment by begriffs** [comment]
It looks like the demo server is still running version 0.2.7.0 which does not support CSV. Thanks for reporting the problem, I'll upgrade the server.

**Comment by alyssaq** [comment]
I also tried it locally with the v0.2.0.10 binary. Is the first curl correct?
