### ISSUE TITLE
Restrict filters to available (whitelisted) indexes

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#246]
To prevent costly requests do not allow clients to filter by columns which are not indexed. When clients try to do so return HTTP 413 and a message explaining which column(s) are not under index.

There are some issues to be careful about
- If the table has a multicolumn index on  `(a,b)`, and the user filters `a` alone it would be helpful if the error message gives a hint that the client should try adding `b` to the filter conditions.
- Need a way to specify the filterable columns for views which, unlike tables, do not report their underlying indices.
- Should there be a way to disable the filtering restriction in development? That would be convenient for exploratory queries in a trusted environment.

/cc @smilliken

**Comment by diogob** [comment]
If you don't mind my 2 cents here, it seems a very complex feature to implement and IMHO the benefits don't pay off.
 
 * In the example provided above of a multicolumn index on ```(a,b)``` the server can use this index when the user filet by ```a``` alone. 
 * There are situations where an index cannot be used because it is a partial index. 
 * Funcional indexes that could be used in computed columns would also have to be taken into account.

Regarding the benefits of such feature it seems that it departs from the original concept of PostgREST of being a very thin map from the database to a REST API. It is a very opinionated trait considering that table scans have so many legitimate use cases.

If implemented I would love to see it as an optional switch, something like ```--only-indexed-filters```

**Comment by begriffs** [comment]
Good points. If implemented it would certainly be optional.

**Comment by diogob** [comment]
We are running into a related issue, but is actually the lack of a filter that would be a problem in some cases.

So I was thinking in a more general approach to the problem, that would not rely on indexes or whitelists or any particular filter.

We could have a restriction based on the estimated cost of execution as given by the ```EXPLAIN``` command. This would have to be configurable as it can vary greatly, but I believe that for most use cases one can devise a sane threshold that allows all legitimate requests and block absurdly slow queries.

Something like:
```
postgrest --max-query-cost 100000
```

Then, only if this switch was used, we verify the explain result before executing (a small performance penalty that could be alleviated by memoization) and in case the total cost exceeds the parameter we respond with a 
```
422 - Query too expensive (please check your max-query-cost parameter)
```

Another advantage of this approach is that it can be use to prevent things like 
```sql
UPDATE somehugetable SET value = 'x';
```

**Comment by snuxoll** [comment]
Honestly, I'd like to see a simple ability to just restrict what columns could be filtered on. We may have indexes to speed up some queries but I may not necessarily want PostgREST clients to be able to filter on that column. A simple whitelist/blacklist of available columns to filter on would be a nice first step.

**Comment by diogob** [comment]
Totally agree with @snuxoll. I'd say a white/backlist not only is more useful and easier to implement, but also may prevent a ```PATCH``` with no filters (which in my experience has a very ugly solution using triggers).

**Comment by SebAlbert** [comment]
Have you considered solving this "in front of" PostgREST, like in an nginx configuration?

**Comment by snuxoll** [comment]
@SebAlbert trying to parse and filter query parameters in a reverse proxy is not exactly my idea of a fun time.

**Comment by SebAlbert** [comment]
Neither is it mine, but I'm wondering whether it's the job of an intendedly single-purpose tool aiming to provide as transparent as possible a layer between HTTP and the database. To me this looks more like a requirement on the database itself, not for the "translation layer", so basically triggers or, probably suited better, rewrite rules, but in simple cases the reverse proxy might be sufficient.

On a different note, I would really appreciate the "max-query-cost" parameter, but maybe my own argument applies here, too, and I should give planner hooks such as https://github.com/pgexperts/pg_plan_filter a try.

**Comment by ruslantalpa** [comment]
@diogob about --max-query-cost, you can do this on the db side with this:
http://www.databasesoup.com/2015/02/why-you-might-need-statementcostlimit.html

**Comment by ruslantalpa** [comment]
This can be implemented in the future using a plugin (when/if PostgREST will support that).
Until then it can be implemented in the proxy like this https://github.com/subzerocloud/postgrest-starter-kit/wiki/Beyond-Data-Access#restricting-filtering-capabilities
