### ISSUE TITLE
Support for CREATE/ALTER table?

### ISSUE THREAD

**Issue by timwis** [begriffs/postgrest#248]
I'd like to use PostgREST to provide business users at my organization an alternative to MS Access and MS Excel for managing basic data. A front-end tool like [ng-admin for postgrest](https://github.com/marmelab/ng-admin-postgrest) or ExtJS makes me really hopeful here, but I'd also like the users to be able to create the tables/fields.

Is there any intention for PostgREST to support `CREATE` / `ALTER TABLE` statements?

If this isn't on the immediate roadmap, could you point me in the right direction of where this would fit in the codebase so I can start on a PR?

**Comment by begriffs** [comment]
As far as I've seen there isn't a standard for creating entirely new routes, which is kind of meta-RESTful. I think we can make it work though through a pull request I'm working on: #228. You can create a stored procedure which takes a description of a table -- its name, columns, and their types -- and creates the table. Then use the `/rpc` route (which will be exposed by the pull request) to call your procedure. Probably restrict access to certain signed-in users.

**Comment by begriffs** [comment]
You can call stored procedures now! http://postgrest.com/api/reading/#stored-procedures
