### ISSUE TITLE
Sort-filter multiple dispatch

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#250]
As reported by @smilliken

> There's a common problem we have with large table queries that include a filter and a sort: even if both are indexed, it's impossible to predict whether the sort-then-filter or filter-then-sort query plan will be faster in the general case (and by faster, I mean not blow up into a terrible query that causes QOS problems). But, it turns out, each of these plans are complementary in that one of them will be acceptable when the other isn't. So, we dispatch both queries, use the first that returns, and cancel the other.

I can imagine the general approach for postgrest. Grab an extra db connection from the pool, fork a thread and run two parallel queries. Whichever finishes first can [throwTo](https://hackage.haskell.org/package/base-4.8.1.0/docs/Control-Exception.html#v:throwTo) the other to stop it. My only question is whether Hasql would cancel the query. @nikita-volkov do you know the answer?

**Comment by nikita-volkov** [comment]
> Whichever finishes first can throwTo the other to stop it. My only question is whether Hasql would cancel the query.

Hasql doesn't do anything in such situations, so unless "libpq" (which it uses under the hood) does this (which I highly doubt), the answer is "No". I would merge a PR, which would fix this, gladly though.

**Comment by ruslantalpa** [comment]
This seems like a very big complication to the logic with marginal benefits for a small number of users. I would not expose a public api for a table that is that big and this vulnerable to DOS attacks. Maybe a better approach is "lock down" the order in a view.
I personally don't see this type of feature being implemented in PostgREST in the near future.
Please reopen if someone comes up with an idea of how to fix corner case without the need to run two parallel queries (maybe generate a slightly different query based on a param/header)
