### ISSUE TITLE
Do full dataset pagination in less than O(n²)

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#254]
Advancing through records with limits and offsets in postgresql leads to unnecessary row rescans. We should change the implementation. There are a few options:
- Cursors
  - General Pros
    - No costly rescans like limit/offset
    - Consistent results when items are inserted or deleted during pagination
    - No modification needed to db structure, works on any view etc
  - General Cons (see [this](http://stackoverflow.com/a/13149184))
    - Cursors must be discarded after a timeout
    - Locks up connections in database pool
    - Open transaction interferes with autovacuum
    - Alternately a `WITH HOLD` cursor has to materialize and store data
    - State management
  - State Management option 1 - Client state tokens
    - Pros
      - Regular HTTP requests
    - Cons
      - If postgrest is load-balanced then the same token must to go the same server
  - State Management option 2 - Streaming
    - Pros
      - Gathering more data on a web socket over time is a natural idea and removes some http overhead
      - Existing load balancing tech knows how to deal with web sockets
    - Cons
      - Will query timeout settings interrupt it?
      - Custom (non-RESTful) protocol for navigating among records?
      - More javascript sophistication required to use sockets than to do ajax
- [Keyset pagination](http://use-the-index-luke.com/no-offset) (with [row values](http://leopard.in.ua/2014/10/11/postgresql-paginattion/))
  - Pros
    - No costly rescans like limit/offset
    - Stateless
    - No interference with load balancing
    - Bidirectional navigation is possible (but complicated)
    - Standard HTTP affordance through Link headers
  - Cons
    - Cannot directly navigate to arbitrary pages (but neither can cursors per se)
    - Results can be inconsistent (repeated rows after inserts, skipped rows after deletions)
    - Requires special table structure (an [auto-incrementing column](http://blog.clearbit.com/postgres-offsets) or [Index table](http://chrisdone.com/posts/postgresql-pagination))
    - Must annotate a view or traverse the db schema to know if view is built on eligible table(s)
    - Unsure if it works on a join

Both cursors and keyset pagination provide significant speedup for paging through big results but they introduce complications. Cursors require that we manage memory and connection resources, aborting client requests when necessary (and notifying the client in an understandable way). Keysets require that we detect when a table or view supports it, either by inspecting the schema or using user-provided annotations.

I imagine continuing to support the Range-header based limit and offset functionality. The client would use that to jump to a given range, and could thereafter use the other forms of pagination to advance efficiently through the records.

It's a tough choice between cursors or keysets. I'd appreciate community feedback.

/cc @smilliken

**Comment by NikolayS** [comment]
Cursors seem to be more suitable for analytical apps (low number of users, good/predictable connection, small number of heavy/long transactions), while the second approach (as you name it "Keyset pagination") is a common choice for web/mobile apps (huge number of users, unpredictable connection, huge number of tiny transactions).

So the choice depends on PostgREST's target audience, which segment is higher and/or more valuable for the future of the project.

My voice is for the second way, since
 - I'm planning to use PostgREST for web/mobile apps
 - I already use this way in many apps (including "infinite load" of content for social media apps -- really important case nowadays).

**Comment by begriffs** [comment]
After reflecting more deeply on pagination (see [this blog post](https://www.citusdata.com/blog/1872-joe-nelson/409-five-ways-paginate-postgres-basic-exotic)) I'm leaning toward keyset pagination.

Here's how. We should have postgrest detect when the client orders by a column that is known to be indexed. Then internally modify the query to find the min and max values of that column on the current page and use them to construct `rel="next"` and `rel="prev"` pagination headers.

**Comment by NikolayS** [comment]
Are you going to leave `LIMIT/OFFSET` pagination as an option?

Also, there are many cases that are difficult to oversee all  in advance. Multi-level indexes, partial indexes, functional indexes – all of them might allow "keyset pagination", but not understood by automated mechanism. So, please consider leaving some capabilities to control on pagination algorithm to the end user.

**Comment by begriffs** [comment]
Yeah I think limit/offset should always be available. Even if you've used a where condition to filter forward you can still limit and offset that result.

**Comment by ruslantalpa** [comment]
PostgREST so far is a stateless* system, introducing cursors will be a massive complication (not just for us, but for users also).

I think one can do fine with LIMIT/OFFSET +  implement keyset pagination in the client ( `/?id=gt.ID_OF_THE_LAST_RECORD_FROM_PREV_REQUEST&limit=10` ).

**Comment by saward** [comment]
I can't find any mention of "keyset pagination" in the documentation.  Does postgrest have keyset pagination built in?  E.g., similar @ruslantalpa's example:

```
/?id=after.UUID_OF_RECORD&first=10
```

**Comment by NikolayS** [comment]
@saward I don't think there is special support for it in PostgREST – and indeed, documentation mentions only bad (performance-wise, for large volumes of data) way: https://postgrest.org/en/v7.0.0/api.html#limits-and-pagination.

However, keyset pagination is something that needs to be implemented in client, in frontend code. For API calls, just use `=.gt` (or `=.lt`) and `limit` and never `offset` -- similarly as you would do working with plain SQL.

**Comment by dwagin** [comment]
@saward

**Example:**

First request
`GET /api/history?order=date.desc&date=gte.2021-06-20T21:00:00.000Z&date=lt.2021-06-21T09:40:00.000Z&limit=16`

2021-06-21T08:37:55+00:00 - `date` of record №16, 11756 - `id` of record №16

Second request
`GET /api/history?id=not.in.(11756)&date=lte.2021-06-21T08:37:55+00:00,gte.2021-06-20T21:00:00.000Z,lt.2021-06-21T09:40:00.000Z&order=date.desc&limit=15`

Third request
`GET /api/history?id=not.in.(11741)&date=lte.2021-06-21T05:52:38+00:00,gte.2021-06-20T21:00:00.000Z,lt.2021-06-21T09:40:00.000Z&order=date.desc&limit=15`

If less than 15 records were received, then all records were received .

**Comment by saward** [comment]
@dwagin and @NikolayS thanks for the replies.  I'll try to test this myself later when I can set up a test database to see what queries get executed in postgres.  Interested to see how row values for ordering ([Paging Through Results](https://use-the-index-luke.com/sql/partial-results/fetch-next-page)) are handled, and that it works as I'm expecting.

**Comment by brandonros** [comment]
> Requires special table structure (an [auto-incrementing column](http://blog.clearbit.com/postgres-offsets) or [Index table](http://chrisdone.com/posts/postgresql-pagination))

How does this work with views (if at all)? If I have a view returning say... 100k or 500k rows, am I out of luck when it comes to pagination options or is there some kind of trick like a `row_number() OVER ()` with a special name to let PostGREST know it's "like an auto-increment column"?
