### ISSUE TITLE
Including exact record count is too slow in big datasets

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#255]
The count (call it *C*) of results in a response is returned in a `Content-Range: m-n/C` header, meaning the server is returning items *m* through *n* of *C*. This is great information for a client who wants to render pagination controls without needing to make a second HTTP call to get the count. Sadly making the count is slow on a large table (even if the request limits the return count) because postgrest counts the total number of matching rows. How do we resolve the tension of eagerly providing count information while going fast on large tables?

I propose using estimated counts. The accuracy of the count could be specified with a request header. To choose their speed-vs-accuracy tolerance a client could send `Prefer: count=estimated` (or `exact` or `none`) with a default of `estimated`.

To estimate the count we would run two queries with each request, one to get the data and one to get the estimated count. The output of `EXPLAIN [query]` contains a string like `(cost=0.00..1.00 rows=1 width=8)` from which we can parse out the estimated row count. Call the estimate *E*. We would respond with `Content-Range: m-n/E`.

However this could lead to confusing responses such as `Content-Range: 0-9/1` which means we have retrieved ten items from a result-set of size one. As an improvement we could choose an adjusted estimate *E' = max(E, n-m)*. However the client will still need in general to probe the end of the results to ensure it gets all the rows and to know when to really stop advancing. The severity of this situation depends on how result traversal works as discussed in #254.

We also run into the problem that count estimation **on small tables** may be slower than exact counts. This is because issuing two statements (the actual one and EXPLAIN) may be slower than a single complicated query that gets the count and data in one shot.

Finally, if the client requests `Prefer: count=none` we would withhold the count and return `Content-Range: m-n/*`. This is the fastest option of all.

We should provide a way to obtain the count of a resource without retrieving any records. To do this the client would issue a HEAD request to `/foo` with `Prefer: count=exact` and we would respond `Content-Range: */C`. I like this better than adding another endpoint like `/foo/count` because the former approach relies on the grammar of HTTP.

/cc @smilliken

**Comment by diogob** [comment]
Great feature, especially having the header to control (although my vote for default goes to exact).
To estimate without using the EXPLAIN we can use the pg_catalog as in:
```
SELECT reltuples FROM pg_class WHERE ...
```
This could easily be embedded in the same SELECT command issued for the results.

**Comment by diogob** [comment]
Forget what I just said about pg_class, this would not work with any filters. So it has to be through explain. But there is a procedure for doing so here: https://wiki.postgresql.org/wiki/Count_estimate

**Comment by begriffs** [comment]
Closing this issue to consolidate discussion in #273
