### ISSUE TITLE
Directly serve individual field data somehow?

### ISSUE THREAD

**Issue by motiz88** [begriffs/postgrest#257]
My current project generates some binary data on the client, then stores it as part of a database. This got me wondering, could PostgREST just serve this data back over HTTP upon request? Not encoded as part of a result set - just the one plain value.

So this is me thinking out loud about this feature, just trying to get an interesting discussion going.
1. There would have to be a way to unambiguously & idiomatically request a particular value out of a row, as opposed to a representation of a row / set. I feel that's probably doable using a URL and optionally some headers.
   For example, `GET /table/col1?col1=eq.123` could be defined to mean "the value of `table.col1` in the result of `GET /table?col1=eq.123`, provided that _that_ query returns precisely one row".
   To play it extra safe, PostgREST can try to guarantee that ahead of time (looking at keys, uniqueness constraints and any `Range` header) and error out appropriately.
   (Bike shed issue: `GET /table/columns/col1` vs. `GET /table/col1` vs ...)
2. `Content-Type` is a problem - how would PostgREST know it in the general case? I don't know the ins and outs of Postgres' type system nearly well enough, but perhaps we could use a form of reflection and define a map from Postgres types to MIME types, which we would let the user extend for their own types as part of the schema. Along with basic `Accept` handling and some sensible defaults - `text/plain` for text values, `application/octet-stream` for `bytea`, `application/json` for JSON etc - this might even work well.

Yes, the line between database and general-purpose web server has to be drawn somewhere, but insofar as individual values within a row can be thought of as resources, and particular ways of serving them thought of as representations, I think this idea has some merit in a REST context. Hopefully some of you will agree :)

**Comment by begriffs** [comment]
Holy crap @motiz88 I apologize for not responding to this question for **months**.

Returning a single "cell" from the db seems similar to what @nicklasaven just asked about in the context of PostGIS binary data in #506.

I think this feature is feasible and we could enable it if the client does three things in their request

1. Includes header `Prefer: plurality=singular` to single out one row
2. Selects a single column `?select=col` 
3. Includes header `Accept: application/octet-stream` to indicate they do not want the JSON wrapping

**Comment by begriffs** [comment]
This functionality is now in master.
