### ISSUE TITLE
Location returned from POST to /postgrest/users inaccessible 

### ISSUE THREAD

**Issue by ssoriche** [begriffs/postgrest#259]
After creating a new user with a POST to /postgrest/users, the Location header:
```
/postgrest/users?id=eq.jdoe
```
Is returned, however performing a GET request on this location returns a 404 even when authenticated as the user the record is created for.

Looking at the Postgres log while the GET request is performed results in:
```
LOG:  execute 0: select id, pass, rolname from postgrest.auth where id = $1
DETAIL:  parameters: $1 = 'jdoe'
LOG:  execute 1: set user_vars.user_id = 'jdoe'
LOG:  execute 2: set role 'unverified'
LOG:  execute 3: reset role
LOG:  execute 4: reset user_vars.user_id
```
Querying the auth table with the appropriate role via psql returns results.

If the location is returned should it not be accessible? PostgREST should filter out the rolname and password, but other details should be returned.

**Comment by begriffs** [comment]
Is `unverified` the role you chose for anonymous requests (the `--anonymous` command line flag)?

**Comment by ssoriche** [comment]
No, ```unverified``` is the role for a user that has already been created and has credentials. I've tried querying with the ```anon``` role too, nothing returned (which is what I expect).

**Comment by begriffs** [comment]
User management is being removed from v0.3.
