### ISSUE TITLE
GET and POST queries work but DELETE query returns 404

### ISSUE THREAD

**Issue by monemihir** [begriffs/postgrest#262]
Hi,

I have got GET and POST queries working fine. However, DELETE queries are always returning a 404. I have set the anonymous user/role to postgres and still getting the same behavior.

Once in while DELETE query will return 204 but almost always it is returning 404.

Any thoughts?

**Comment by begriffs** [comment]
Thanks for reporting. What version of postgrest are you running, what path are you trying to delete, and what does the schema for the table look like?

Also you can join us in the project [chat room](https://gitter.im/begriffs/postgrest) to talk about it.

**Comment by monemihir** [comment]
I am using the latest version.

My query looks like `http://localhost/table?col1=eq.1234`. `col1` is an integer column. A GET query with the same URI returns a 200 (Ok).

I have done some further diagnosing of this and I think if no records were deleted from the table then the api returns a 404 (NotFound) and if records were deleted then api returns a 204 (NoData).

The way I have got around this at the moment is:
* Run the DELETE query
* If 404, then run a GET query for the same URI with a range header to return only 1 record (to reduce response payload)
* If 200 and we have no data returned or 204, then that is a success, else if 200 and some data returned throw the original 404

To be honest this is a hacky way to do it. Ideally I'd expect the api to return 200 if it deletes some data and 204 if no data was deleted.

**Comment by begriffs** [comment]
I'm having trouble reproducing this on v0.2.12.0. Delete removes the rows when present and issues a 404 when they are absent. Could you try again with this version?

**Comment by begriffs** [comment]
@monemihir can you verify if this is still a problem on newer versions?

**Comment by monemihir** [comment]
@begriffs we haven't updated to the newer versions yet. I'll let you know once we decide to do it.

**Comment by ssoriche** [comment]
I am getting a 404 when deleting from a view with an INSTEAD OF DELETE trigger with 0.3.1.0. The row ends up being successfully deleted, but an error is returned.

**Comment by ruslantalpa** [comment]
When deleting we do something like 
```delete from ... returning *```
then we do a count of the returned items and if that is 0 (your case) we say 404
Your trigger needs to somehow return the deleted rows so ```returning *``` works
Try turing on query logging to get the exact query being generated then try running it manually and see if you can update your trigger so that you get something other then 0 for "page_total" column

**Comment by ssoriche** [comment]
Thanks @ruslantalpa after returning OLD I receive a 204 on delete.

**Comment by begriffs** [comment]
Cool, closing this issue!

**Comment by parauchf** [comment]
Not sure if this has already been discussed: have you considered returning a body from a delete if the query indeed returns records?  So return a 200 with body instead of a 204.  Could use the same `return=representation` flag as POST/PATCH...

**Comment by begriffs** [comment]
As of version 0.3.2.0 postgrest will do this actually when the Prefer header is sent.

**Comment by parauchf** [comment]
Fantastic, I will have to upgrade.  Thank you!
