### ISSUE TITLE
Any bad request causes all subsequent requests to return 404

### ISSUE THREAD

**Issue by thejettdurham** [begriffs/postgrest#264]
Greetings,

I'm attempting to use postgrest to expose an existing manually-maintained postgres database as a REST service.  I've configured Basic Authentication with an authenticator role, and my anonymous user has no privileges.  I'm using the --v1schema flag to expose my public schema.  I'm using the v0.2.10 binary from the GitHub release.  The deployment environment is Ubuntu 12.04.4 and postgres 9.4.4

All of my properly formatted requests are returning the expected responses.  I'm getting data into and out of the database through postgrest.  However, whenever the server responds with a response 400, all requests (even those that previously worked) begin returning 404 with the following response body:

```
{
  "hint": null,
  "details": null,
  "code": "42501",
  "message": "permission denied for relation auth"
}
```

I get this behavior with any form of bad request sent to postgrest.  For example: 
* GETs or DELETEs with misspelled table names
* POSTs or PATCHes with bad date formats

I'm using both Postman and a java app to test requests to postgrest.  The described failure is the same no matter the origin of the initial bad request.

I've found two ways to resolve this issue
* Restart the postgrest service (I'm using an upstart script to start/stop postgrest, if that matters)
* Halt all requests to postgrest for a minute or two.
  * If postgrest receives no requests in a 60-120 second period (I'm not sure exactly how long), previously working requests will begin working again
  * If postgrest receives any requests 60-120 seconds after the initial bad request, this "resets the clock" so to speak, and previously working requests will need another 60-120 seconds to start working again.

Issue #164 sounds similar to this one, but I'm experiencing it in a wider scope of cases, and the "wait X seconds" resolution method is not mentioned there.

I hope that this issue can be resolved!  I'm very excited by the power and flexibility Postgrest has to offer, but I cannot justify sacrificing fault tolerance for those benefits I'm afraid.

**Comment by begriffs** [comment]
Thanks for the detailed report, I'll look into it more this evening. In the meantime please join the [chat room](https://gitter.im/begriffs/postgrest) where people are discussing it.

**Comment by begriffs** [comment]
I reproduced the problem and am working on a fix!
