### ISSUE TITLE
Anonymous login

### ISSUE THREAD

**Issue by mpnieland** [begriffs/postgrest#265]
Having trouble getting the anonymous login to work.  I'm using Amazon RDS Postgres database.  I ran your create role script for anon granting select to all tables in schema "1".  However, when I throw anon into the anonymous_role on the heroku app (which I build using your buildpack), it gives me permission denied to switch to anon role.  I can't figure out what I'm doing wrong.

If I switch the anonymous role in heroku to my admin role it works, but then anonymous users have access to write to my tables so I don't want that.

A step-by-step walkthrough in the order you have to do things to get this working would be much appreciated.  Right now you have to go through different wiki pages that aren't in the order they need to do to get this going.

**Comment by begriffs** [comment]
Point taken about the docs. We're writing new ones here: http://postgrest.com/

There is more detail about getting the roles to work in https://github.com/begriffs/postgrest/issues/313. You need to grant access for the authenticator role to switch into the anonymous role.

Also I apologize for neglecting your question for so long. At any time please join the [project chatroom](https://gitter.im/begriffs/postgrest) for support.

**Comment by jensfinnas** [comment]
I'm having the exact same issue. I've created an `anon` role as described in the documentation.

```postgresql
CREATE ROLE authenticator NOINHERIT LOGIN;
CREATE ROLE anon;
CREATE ROLE author;

GRANT anon, author TO authenticator;
```

But I get this error:

````json
{
"hint": null,
"details": null,
"code": "42501",
"message": "permission denied to set role \"anon\""
}
```

Just as @mpnieland I'm on Heroku + Amazon RDS.

**Comment by ruslantalpa** [comment]
what's the connection string you are using (comment out only the password)?

**Comment by jensfinnas** [comment]
The default one from the Heroku element:

`postgres://USER:PASS@DB_PATH:5432/DB_NAME" -p $PORT -a $ANONYMOUS_ROLE --pool $DB_POOL --jwt-secret $JWT_SECRET --schema $SCHEMA``

(user, pass, path and db name replaced here)

And anonymous role set to `anon` in environment.

![image](https://cloud.githubusercontent.com/assets/1089739/19303868/aefbf72a-906a-11e6-8f2c-ec2e553ef68c.png)

**Comment by ruslantalpa** [comment]
ok, look again at the queries from the example, specifically
`GRANT anon, author TO authenticator;`
this means that `authenticator` role, can switch to `anon` and `author`
but you did not connect to the database using `authenticator` role, you used some other role.
either change your connection string to use `authenticator` or run the same `grant` query for the user you are currently using

**Comment by jensfinnas** [comment]
Okay, trying to change `ANONYMOUS_ROLE` to `authenticator` in environment. But same issue. `"permission denied to set role \"authenticator\""`

**Comment by ruslantalpa** [comment]
you need to use `authenticator` role in your connection string when starting postgrest, not with the -a parameter

`postgres://authenticator:authenticatorpass@DB_PATH:5432/DB_NAME" -p $PORT -a $ANONYMOUS_ROLE --pool $DB_POOL --jwt-secret $JWT_SECRET --schema $SCHEMA`

**Comment by jensfinnas** [comment]
Thanks @ruslantalpa. Got it now!
