### ISSUE TITLE
Close db connections on unix signal

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#268]
Sending signals to postgrest can leave connections open in pg_stat_activity. On signals we should call [destroyAllResources](https://hackage.haskell.org/package/resource-pool-0.2.3.2/docs/Data-Pool.html#v:destroyAllResources) in `resource-pool`.

**Comment by monemihir** [comment]
I have noticed this as well. I have a bunch of postgrests setup via supervisord and postgrest doesn't seem to respond as expected when supervisord sends a Ctrl+C event to stop it.
