### ISSUE TITLE
Add jwt-token to heroku buildpack

### ISSUE THREAD

**Issue by timwis** [begriffs/postgrest#270]
Seems like there's no way to use JWT Tokens in the heroku pack other than forking the heroku repo. Any reason not to include it as an environment variable with a default value of `secret`? Happy to submit a PR, but thought I'd check first.

**Comment by begriffs** [comment]
It was simply overlooked; a pull request would be great!

**Comment by diogob** [comment]
@begriffs I've sent one (https://github.com/begriffs/postgrest-heroku/pull/4) with the JWT_SECRET and V1SCHEMA variables
