### ISSUE TITLE
Including charset in response Content-Type

### ISSUE THREAD

**Issue by raphaelLacerda** [begriffs/postgrest#272]
My database is already enconded using UTF-8, but when i make a request, i get wrong characters and the response header is:

Content-Encoding:gzip
Content-Location:/options
Content-Range:0-2/3
Content-Type:application/json
Date:Wed, 26 Aug 2015 19:21:20 GMT
Server:postgrest/0.2.10.0
Transfer-Encoding:chunked

I would like to add charset=UTF-8 to the response header content-type.

Something like this:
Content-Type:application/json;charset=UTF-8

Is there any way to do it?

**Comment by diogob** [comment]
If your client interprets the data as UTF-8 and the data was correctly encoded in the database you should see the characters just fine, even if the charset is not specified in the headers. What is the client application that is reading the data?

**Comment by begriffs** [comment]
@raphaelLacerda we can include the charset in the content type, and set it to the value that the database reports for
```sql
SHOW SERVER_ENCODING;
```
However for UTF-8 it reports `UTF8` without the hyphen. But I am curious about @diogob's question about what client you're using.

**Comment by begriffs** [comment]
@raphaelLacerda postgrest version 0.3.1.1 should add the charset in its response headers. Give it a try and let me know if it fixes your problem.
