### ISSUE TITLE
how to choose different schema of your database.

### ISSUE THREAD

**Issue by wanghaisheng** [begriffs/postgrest#279]
right now it seems we can only fetch data   inside the public  schema of your database.how to choose a different one

**Comment by begriffs** [comment]
There are two ways:

1. When starting postgrest, give it the `--v1schema` command line argument to select the default schema to use.
2. When making requests from the client, add a version number as described [here](https://github.com/begriffs/postgrest/wiki/API-Versioning). If you pass version 2 then it will search in a schema named 2.

**Comment by begriffs** [comment]
Do either of these options provide you the functionality you need?
