### ISSUE TITLE
Extending the capabilities of &select parameter (and filtering along with it)

### ISSUE THREAD

**Issue by ruslantalpa** [begriffs/postgrest#280]
What do you guys think about implementing this https://github.com/ruslantalpa/skin (ignore the code quality and the specific implementation details)
The details are in the README

Right now you can do this
```
&select=col1,col2::int,col3->>sub1::json,col3->sub1->>sub2::int
```

I propose to add the capabilities to do this
```
&select=id,name,projects(id,name,tasks(id,name))
```
and this
```
&id=eq.1&projects.tasks.completed=eq.true
```

This would allow the capability of getting back results that look like this
```
[  
   {  
      "id":1,
      "name":"Windows 7",
      "clients":{  
         "id":1,
         "name":"Microsoft"
      },
      "tasks":[  
         {  
            "id":1,
            "name":"Design w7"
         },
         {  
            "id":2,
            "name":"Code w7"
         }
      ],
      "users":[  
         {  
            "id":1,
            "name":"Angela Martin"
         },
         {  
            "id":3,
            "name":"Dwight Schrute"
         }
      ]
   }
]

```

**Comment by begriffs** [comment]
Wow, this is really great work! Would love to add this kind of functionality.

Some questions:
* If we're getting a list of movies say and each movie has actors, do we allow the user to include the actors inside each movie? The response could get big. Or do we allow embedding only when requesting a single movie? (Possible by checking if primary key is specified in filter)
* How do we limit the count of embedded resources? Maybe interpret a request range header as applying to the embedded resource rather than a top-level list. This also argues for allowing embeds only on a request for a single top level result.

**Comment by ruslantalpa** [comment]
1. Allow embedding of actors. Yes the response is bigger, but if the data is needed It would have to be fetched anyway (in multiple requests). I would say it's the responsibility of the client to find the best/optimal way to get the data. For example, in case of projects/tasks structure, there is no duplication of data (tasks are unique to project) so it can be efficiently fetched in one request. In case of movies/actors i would make two requests, a) all actors, b) all movies, and include actor info, but only the id, then combine the data on the client side.
2. The limit would refer to the top level items. Most of the time, the use case is you are displaying a list of items (projects, movies), the list is big so you need to paginate it (this is where limit comes in) but each item has some related info that you need (category of the movie, client of the project) so it is great to be able to get that in one request. Anyway, it would be next ti impossible (i think) to get the count of nodes in the tree and limit/offset does not even make sense in a tree like structure.

Most of my opinions are formed on my experience of building paymoapp.com, the interface/feature i described worked great for us, we almost do not have "special" endpoints, everything is done using this interface.

On another note, i am willing to do the development but i would like to get some advice/consensus on what and how to build it (i am still a bit not comfortable with monad transformers and postgresql features).

I will come up with a few point to kick off the discussion, and maybe agree on a date/time to meat in a chat to discuss each point (might be faster then using gihub issues)

**Comment by ruslantalpa** [comment]
**Discussion points regarding the proposed feature**

1. There is an internal/intermediate  data type (and a few secondary) used to represent the DB query that will be performed. I would like suggestions/opinions on the data types to make it complete (able to model all situations/requests) since it's the central piece of the puzzle. 
This makes it easier to work with the request and allows for easy integration of other functions that transform the request, for example there could be functions that traverse/transform each node (Query) of the tree and check that the type of the value used in a condition/filter matches the type of the column (this particular example not necessarily a good idea). It is also good to have some type level information as opposed to functions working on strings.

2. The Wai http request is parsed using parser combinators (Parsec) and translated into a DbRequest (actually there is an intermediate Request type, but not central to the idea). Since there is a clear separation between the raw http request and other functions that transform the request (the internal DbRequest) it is easy to change the format of the http request (names of the parameters and stuff like that) by changing only the parser. For example, if someone has their API providing a specific interface, they can change only the parser and use PostgREST without the need to change the frontend code. We could imagine a situation where PostgREST natively supports different REST dialects (maybe even new stuff like GraphQL :)) by looking at a header like "Request-Format" and using a different parser based on it. The question i have here is: Should we use parsers and internal DbReqeust / Query type (think Update, Insert constructors) for PUT/DELETE/PATCH requests or implement this exclusively for GET requests? My inclination is to say yes (more work but there could be benefits to it).

3.   After the initial DbRequest (Tree Query) is created, there is a function addRelations that walks the tree and marks the relation of each node to it's parent node. That is done based on a list constructed by buildRelations which looks at foreign keys in columns. I have implemented one-many (parent), many-one (child), many-many (many) but my feeling is that i have not covered the corner cases. I would need help from other users in running this function against their db and see if the relations it detects are correct.

4. A DbRequest is translated into a query (String) with a specific format (look in the queries.sql file). Maybe some Postgresql experts could look at it and see if there are potential performance issues with this particular query. Again having an internal/intermediate type helps with a problem like this since there is only one function to modify in order to completely change the shape of the query.

5.  In the current implementation i did not quite understand why inside parentheticT, there is a call to whereT qt qq $ countRows qt, why not leave it like a "select *"?

6. In the current implementation it seems that the final query is a string that has it's parameters embedded in it (i am talking SELECT * FROM a WHERE id = 10 as opposed to SELECT * FROM a WHERE id = ?). Is there a particular reason why it was constructed like that? Using "?" would protect against sql injection and things like "::unknown" would not be needed.

**Comment by ruslantalpa** [comment]
Is there a possibility to have a meeting and discuss the things above (gitter,Google Hangouts)?
I would like to start working on it ASAP but also avoid going too far off in the woods  with this if i start it without input/review from others.
Thank you

**Comment by begriffs** [comment]
I totally see your point about letting the client decide the embedding strategy that works best for them, and allowing embeds on a list of top-level items too.

I'll think about your six follow up questions and get back to you. Been pretty busy this week but would love to chat more during the weekend if you're free. What's your timezone? I'm in Pacific time.

**Comment by ruslantalpa** [comment]
I'm gmt+2 but as a one time thing i can be online whenever, i just need a heads up a day before so that i do not make other plans

**Comment by ruslantalpa** [comment]
Based on this http://www.timeanddate.com/worldclock/meetingtime.html?iso=20150912&p1=3688&p2=224, i guess the best times are between 11am and 2pm (Pacific)

**Comment by jmealo** [comment]
I would find this useful, however, I don't have anything articulate to say about it. @ruslantalpa Do we have any alternatives we should be comparing this to? I see that this is based off of Google's work, so I'm assuming they put some though into it. Did you skip over any other ideas or inspiration before choosing to go with Google?

**Comment by ruslantalpa** [comment]
No i have not, maybe only graphql but that's a whole different ballgame. But as i said (2), the syntax of the get request is not important at all, it will be trivial to change if we use parsers so i don't have any concerns about choosing the syntax from google for now, we can switch away from that if needed literally in a few hours of work.

**Comment by ruslantalpa** [comment]
The only requirement for the "grammar" of the http request is it's ability do describe/express a tree structure, so far google's way is the most simple/short i've seen. (What we are doing now in our product is something like &select=id,name,tasks.id,tasks.name ... which is a lot more verbose)

**Comment by ruslantalpa** [comment]
But what's particularly nice about this syntax is that it does not break the old one, so everyone using postgrest can just upgrade the version

**Comment by diogob** [comment]
Regarding the point 1, I like the idea of an intermediary type but wouldn't it be reinventing things like HaskellDB or haskell-relational-record ?
Regarding the point 6, this would be a very nice patch, regardless of this feature being discussed.

@ruslantalpa are you using tables directly in the api schema? Because the foreign key trick would not work when using views.

**Comment by ruslantalpa** [comment]
1. I don't think they are one and the same thing, the libraries you are talking about (i might be wrong, i just glanced) are like a set of functions that you compose in a certain way (and it's a nice looking dsl) and when you finally call the "big function" it produces the query i guess. But this is not a data item at which you can look/inspect/transform.

2. Yes, i am using the queries from PgStructure.hs, i did not know that about the views. But i am hoping there is a way to find out if a column in a view is actually a raw column in a table that references another table. And even if that is not possible, as a user of PostgREST i would not mind providing that relational info in some form of config (config file or maybe a table in "postgrest" schema that describes the relations). But it would be much nicer if we could just find that out using a query :)

**Comment by ruslantalpa** [comment]
Regarding 6) I just looked at the info in information_schema.view_column_usage and you can find there for each column of the view, the original table/column it's based on, using that i think we can construct a "foreign keys" query for view

**Comment by begriffs** [comment]
1. My instinct as other people mentioned would be to look for existing libraries for this. However I'm not optimistic that there are any that also work with Hasql.
2. I see the flexibility here.
	* Your parsers look nice for reading the filtering operations etc 
	* If we start using DbRequests for GETs then makes sense to use the strategy for the other verbs as well. Just to keep the code uniform. (The other verbs may be simpler anyway)
3. I was unsure about how to build the relations on views, but your discovery of `information_schema.view_column_usage` seems to help.
	* One thing to consider is that doing this afresh on every request might be inefficient and we would want to cache this information on postgrest startup. Could try the naive non-cached way first to get a measurement.
	* Probably want a way to rebuild this cache periodically or on demand without needing to restart the postgrest server.
4. I'm reading the Skin code trying to understand how the types work together in Functions.hs, but the overall impression is that this is nicely structured.
5. The extra counting was there for providing pagination information but it needs to be removed. (More about this in #273 and #255)
6. The parameters to be bound often come from a url query param, which (unlike a json value) have no type other than String associated with them. When I populate hasql [statements](https://hackage.haskell.org/package/hasql-0.7.4/docs/Hasql.html#t:Stmt) with those values they are treated in the resulting postgres query as text type. This causes query execution errors when the column types are not text.
	* If we gathered a list of column types ahead of time we would have an idea how to try parsing those values in postgrest before binding them into a statement.
	* Right now the `::undefined` trick allows the database to work with strings and try to make sense of them. However it causes sloppiness like #233

Another thing that can help the conversion to better parsing and DbRequests is that the existing postgrest test suite should continue to work fine. It doesn't deal with the internal implementation, but instead tests from the outside with basic HTTP.

**Comment by ruslantalpa** [comment]
So i've made some headway in https://github.com/ruslantalpa/skin
My plan is to work there until it's fully functional (able to handle all GET requests) and then integrate it into a custom branch in PostgREST.
The current state is:
It reads the the db structure (all the schemas) at once and detects all the relations (except many to many and except views, i'll add that soon)
It understands "select" parameter with possible json paths and casting and nested items.
I added a lot of type declarations that are just naming strings to make it more clear what those strings are

I would appreciate comments on the code, if it's heading the right way, anything that does not look right ...  

Thanks

**Comment by ruslantalpa** [comment]
(foreign keys in views are also detected now)

**Comment by ruslantalpa** [comment]
So for (6) it looks like it's not possible to somehow use the "::unknown" trick (https://github.com/nikita-volkov/hasql-postgres/issues/23)
So the choices are (i think)
1) Continue generating one big sql string (works for every column type, but possible sql injection)
2) Parse each filter parameter separately and compare to it's column type then use prepared statements (safe as to sql injection, but needs a parser for every type of column + i am not sure hasql-postgres has a mapping from Haskel data types all postgresql data type)

Thought on the issue at hand are welcome.

**Comment by ruslantalpa** [comment]
**Status update**
I started integrating my experiment into PostgREST codebase here https://github.com/ruslantalpa/postgrest/tree/skin
As of this moment almost everything works (2 tests failing)
You can now do queries like
```
/clients?select=id,name,settings->>price::integer,projects(*,tasks(id,name))&id=eq.1&projects.status=eq.active
```
There was quite a bit of code added as you can see below but i think i can cut it down to about 1700-1800 lines.

Since quite a bit changed in how the request is processed, it would be very useful if users of postgrest would run this branch against their databases and see if everything is still working as expected.

![screen shot 2015-09-25 at 12 20 35](https://cloud.githubusercontent.com/assets/5537246/10099027/9c262350-638e-11e5-89a1-f6360ab7b06d.png)

**Comment by begriffs** [comment]
Wow it's almost ready! You're a champion, thanks for the amazing rewrite. :heart: Once all tests are passing I'd say open a pull request and we can discuss the changes more easily there.

On my end I'll focus on writing the [new docs](https://www.gitbook.com/book/begriffs/postgrest/details) rather than touching existing code so that I won't conflict with your work.

**Comment by ruslantalpa** [comment]
I'll probably add the pull reqest at the end of the next week, a lot more room for cleanup. Mostly i want to get the data types right (there is some duplication now) and take a closer look at the parsers to make sure they match all valid cases

**Comment by ruslantalpa** [comment]
Closing this issue, the discussion is moving to https://github.com/begriffs/postgrest/pull/295
