### ISSUE TITLE
Can't post JSON array to view

### ISSUE THREAD

**Issue by derekhawker** [begriffs/postgrest#282]
Hi,

I'm trying to create a view that returns a selection of rows as an array and take a simlar array as a POST body and updates the associated table. It's kind of a lead up to a more complicated view that returns rows with a few fields that are arrays from various tables. Anyways for now I'm just trying to get a single array from a single table working.

I have a table with two columns (id, name) called job_titles. 

``` sql
CREATE TABLE job_titles
(
  id integer NOT NULL DEFAULT nextval('job_titles_id_seq'::regclass),
  name text NOT NULL,
  CONSTRAINT job_title_id PRIMARY KEY (id),
  CONSTRAINT unique_job_title_name UNIQUE (name)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE job_titles
  OWNER TO postgres;
```

I have a view that does a select and return all name columns as a single object whose field "a" is an array of those names.

``` sql

CREATE OR REPLACE VIEW arr_test AS 
 SELECT ARRAY( SELECT job_titles.name
           FROM job_titles) AS a;

ALTER TABLE arr_test
  OWNER TO postgres;
```

I have a trigger and trigger function that handles the insert and update operations on this view. For now I've just commented out the update and delete and I'm focusing on insert

``` sql

CREATE TRIGGER person_detail_job_vw_dm_trig
  INSTEAD OF INSERT OR UPDATE OR DELETE
  ON arr_test
  FOR EACH ROW
  EXECUTE PROCEDURE person_detail_job_vw_dm();

CREATE OR REPLACE FUNCTION person_detail_job_vw_dm()
  RETURNS trigger AS
$BODY$
   BEGIN
      IF TG_OP = 'INSERT' THEN
        --INSERT INTO   VALUES(NEW.pid,NEW.pname);
        --INSERT INTO  person_job VALUES(NEW.pid,NEW.job);
        do $$
        PERFORM insert_job_titles(NEW.a);
        $$;
        RETURN NEW;
      ELSIF TG_OP = 'UPDATE' THEN
       --UPDATE person_detail SET pid=NEW.pid, pname=NEW.pname WHERE pid=OLD.pid;
       --UPDATE person_job SET pid=NEW.pid, job=NEW.job WHERE pid=OLD.pid;
       RETURN NEW;
      ELSIF TG_OP = 'DELETE' THEN
       --DELETE FROM person_job WHERE pid=OLD.pid;
       --DELETE FROM person_detail WHERE pid=OLD.pid;
       RETURN NULL;
      END IF;
      RETURN NEW;
    END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION person_detail_job_vw_dm()
  OWNER TO postgres;
```

And the referenced function

``` sql
CREATE OR REPLACE FUNCTION insert_job_titles(text[])
  RETURNS void AS
$BODY$
DECLARE
   arr ALIAS FOR $1;

BEGIN
   FOR I IN array_lower(arr, 1)..array_upper(arr, 1) LOOP
    INSERT INTO job_titles (name) VALUES(arr[I]);
   END LOOP;
END;
$BODY$
  LANGUAGE plpgsql STABLE STRICT
  COST 100;
ALTER FUNCTION insert_job_titles(text[])
  OWNER TO postgres;
```

If I do the following curl command

> curl -X GET "http://localhost:3000/arr_test" 

I get the following which is great

> [{"a":["CEO","CFO","COO","dude","Derek"]}]

But when I try and do a post 

> curl -X POST  -d '{"a":["42","n1","n2,"43"]}' "http://localhost:3000/arr_test"

I get the following error

> {"message":"Failed to parse JSON payload. Failed reading: satisfy"}

or if I supply one or two elements:

> {"hint":null,"details":null,"code":"22P02","message":"missing dimension value"}%

I'm at a loss. It seems like it should work, and I've been able to get it to work with non-array fields

**Comment by begriffs** [comment]
First thanks for the **awesome** bug report! This really helps me debug.

I'm experimenting with the post payload and watching my postgresql logs for clues. When I post

`{"a":["42"]}`

I see a problem with the sql it is generating:

```
ERROR:  malformed array literal: "["42"]" at character 41
DETAIL:  "[" must introduce explicitly-specified array dimensions.
STATEMENT:  insert into public.arr_test (a) values ('["42"]'::unknown) returning row_to_json(public.arr_test.*)
```

PostgREST is treating the value of `a` as if it was a plain string, so that looks like a legitimate bug. Looking for a workaround I try posting a string which uses postgres array literal notation

`{"a":"{'42','n1','n2','43'}"}`

Seems like we're making progress because this gives me

```
ERROR:  syntax error at or near "PERFORM" at character 10
QUERY:
	        PERFORM insert_job_titles(NEW.a);

CONTEXT:  SQL statement "do $$
	        PERFORM insert_job_titles(NEW.a);
	        $$"
	PL/pgSQL function person_detail_job_vw_dm() line 6 at SQL statement
STATEMENT:  insert into public.arr_test (a) values ('{''42'',''n1'',''n2'',''43''}'::unknown) returning row_to_json(public.arr_test.*)
```

Could this mean that postgres now understands the array but there is a problem with the trigger itself?

**Comment by derekhawker** [comment]
Hi, Thanks for responding so quick. I'd seen this array literal notation in a previous issue, but hadn't figured out how to make it work. I've only been playing with this project for a week now, but I love how easy it's been to get up and running. Starting to recommend to people.

So you'r right, it's definitely a bug on my end from array literal. I'm still a bit new to SQL and calling a function is more complicated than I expected. I stripped out the function call and pasted the code inline as follows

```sql
CREATE OR REPLACE FUNCTION person_detail_job_vw_dm()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
   BEGIN
      IF TG_OP = 'INSERT' THEN
        --INSERT INTO   VALUES(NEW.pid,NEW.pname);
        --INSERT INTO  person_job VALUES(NEW.pid,NEW.job);

	--insert_job_titles(NEW);
	
	BEGIN	
	   FOR I IN array_lower(NEW.a, 1)..array_upper(NEW.a, 1) LOOP
	    INSERT INTO job_titles (name) VALUES(NEW.a[I]);
	   END LOOP;
	END;
	
        RETURN NEW;
      ELSIF TG_OP = 'UPDATE' THEN
       --UPDATE person_detail SET pid=NEW.pid, pname=NEW.pname WHERE pid=OLD.pid;
       --UPDATE person_job SET pid=NEW.pid, job=NEW.job WHERE pid=OLD.pid;
       RETURN NEW;
      ELSIF TG_OP = 'DELETE' THEN
       --DELETE FROM person_job WHERE pid=OLD.pid;
       --DELETE FROM person_detail WHERE pid=OLD.pid;
       RETURN NULL;
      END IF;
      RETURN NEW;
    END;
$function$;

CREATE TRIGGER person_detail_job_vw_dm_trig
    INSTEAD OF INSERT OR UPDATE OR DELETE ON
      arr_test FOR EACH ROW EXECUTE PROCEDURE person_detail_job_vw_dm();
```

After this I was able to successfully POST on the view
> \# curl -X POST  -d "{\"a\":\"{'42','n1','n2','43'}\"}" "http://localhost:3000/arr_test"

and my get on the view returned the updated list:
> \# curl -X GET "http://localhost:3000/arr_test"
> [{"a":["CEO","CFO","COO","dude","Derek","'42'","'n1'","'n2'","'43'"]}]

And doing a GET on the actual job_titles, returned all the values I had just POSTed and shows that I screwed up hte starting index on my auto-incrementing id column
> [{"id":1,"name":"CEO"},{"id":2,"name":"CFO"},{"id":3,"name":"COO"},{"id":1763,"name":"dude"},{"id":1764,"name":"Derek"},{"id":1765,"name":"'42'"},{"id":1766,"name":"'n1'"},{"id":1767,"name":"'n2'"},{"id":1768,"name":"'43'"}]

Thank you once again. I can definitely work around this using array literals. So excited that I can make my single unified POST endpoint now

**Comment by diogob** [comment]
@derekhawker if you use a JSON value instead of an array when creating the view in the first example everything should work as expected. I think it is a good approach to always use json for composite types while working with PostgREST.

**Comment by ruslantalpa** [comment]
I think with the latest version this works (if i am understanding the problem correctly) by sending the header `-H "Accept: application/vnd.pgrst.object+json"`

a full request to insert one object looks like this
```
curl -s -X POST \
-H "Authorization: Bearer $JWT_TOKEN" \
-H "Content-Type: application/json" \
-H "Accept: application/vnd.pgrst.object+json" \
-H 'Prefer: return=representation' \
-d '{"name":"Google","address":"Mountain View, California, United States"}'  \
http://localhost:8080/rest/clients?select=id,created_on | \
python -mjson.tool
```
