### ISSUE TITLE
Select filtering not interpreted correctly

### ISSUE THREAD

**Issue by davejacobs** [begriffs/postgrest#283]
I'm trying to filter the fields returned via a GET endpoint and am having some trouble:

```bash
$ postgrest -h
  ...
  PostgREST 0.2.11.1 / create a REST API to an existing Postgres database
  ...
$ curl 'localhost:3001/users?select=id,name' | jq '.'
{
  "hint": null,
  "details": null,
  "code": "42703",
  "message": "column users.select does not exist"
}
```

What am I doing wrong?

**Comment by begriffs** [comment]
Oh this feature has been merged to the master branch of the project but not yet released in a downloadable binary (not in version 0.2.11.1). Right now you can use the feature only if you [build the project from source](https://github.com/begriffs/postgrest/wiki/Building-from-source).

Sorry that this wasn't better documented -- the only place that mentions it is the changelog.

**Comment by davejacobs** [comment]
Ah okay, thanks for the heads up! PS I'm loving this project so far. (I happen to be using it for rapid prototyping.)

**Comment by begriffs** [comment]
Glad you're enjoying it thus far! Let me know if you would like to build from source and if you need any help along the way. Feel free to join the support chat at https://gitter.im/begriffs/postgrest

I'll close this issue for now.
