### ISSUE TITLE
Problem posting csv

### ISSUE THREAD

**Issue by ktenney** [begriffs/postgrest#287]
curl -XPOST -H "Content-Type:text/csv" -d @hostname.csv 192.168.0.35:3000/hosts
I've tried a number of variations of the csv and the destination, consistently get
{"hint":null,"details":null,"code":"42601","message":"syntax error at or near \"returning\""}

I haven't found an example of what the csv should look like ...

PostgREST 0.2.11.1
json posts to same endpoint are working

Suggestions?

**Comment by begriffs** [comment]
Does your csv begin with the column names? Can you share details of the structure of the `hosts` table and the beginning of your csv?

**Comment by ktenney** [comment]
oops, I had spaces between the commas and the text

**Comment by ktenney** [comment]
my bad

**Comment by begriffs** [comment]
That seems like an easy mistake to make. I'll add a warning in the wiki about it.
