### ISSUE TITLE
Cap max results per response in program start

### ISSUE THREAD

**Issue by leondewey** [begriffs/postgrest#288]
Is there any way to set a max limit on the number of results returned?

**Comment by begriffs** [comment]
To limit the results you can set a `Range` request header. Here are some docs about it https://github.com/begriffs/postgrest/wiki/Routing#limiting

Let me know if that does what you want.

**Comment by leondewey** [comment]
Im talking about that being a default so I can open the API up to any one... if I had 500 000 rows when some one hit `/items` for example they would pull down them all instead of paginating.

**Comment by ruslantalpa** [comment]
put postgrest behind nginx and in nginx config check if limit parameter is present and if not, add the default value

**Comment by leondewey** [comment]
@ruslantalpa Ok cool, thought that might be the case.

**Comment by begriffs** [comment]
@leondewey alternately I could add a command line option for specifying the max allowed results for any response. So even if someone requested all rows or a huge range of rows the server would send back an amount no more than the global limit. (A missing range in the request means get all items which would then be limited by the global limit making it in essence a default value too.) Would you like this behavior better?

**Comment by jhannah** [comment]
++ Was just looking for this feature today, would love to see it implemented! <3
