### ISSUE TITLE
Getting involved in PostgREST development

### ISSUE THREAD

**Issue by calebmer** [begriffs/postgrest#289]
Hi, I'm really excited about this project, I love the vision, I love the choice of language, and I love that the user land implementation is in SQL. I've been trying to move some of my production APIs to PostgREST, and because of this I want to invest back into the project.

I have a background in PHP and NodeJS. Recently I have also taken an interest in Haskell and functional programming. That said I will likely need a mentor to help introduce me to the world of Haskell and specifically this project's code base.

If anyone is willing to help get up to speed so I can start regularly contributing that would be awesome.

PS: It seems like issue #278 *might* be a simple first contribution (I have some experience in streaming APIs in node). I would need some initial help finding and parsing documentation for Hasql and Warp.

**Comment by PierreR** [comment]
I have the feeling that #278 is actually more tricky than it looks like but if there is already some development going on, I guess it would be really educative to participate.

Note that in the list of future features, there is `watching endpoint changes with sockets and Postgres pubsub`. This is probably simpler; we need to use `postgresql-libpq` and get a good streaming interface. I was actually planning to give it a go, by-passing `hasql-postgres` (that does not implement or plan to implement `notify` (see https://github.com/nikita-volkov/hasql-postgres/issues/17).

I am more and more convinced that `list-t`is not the way to go for streaming and I would be personally interested in using the new [`streaming`package](https://hackage.haskell.org/package/streaming) for this.

**Comment by calebmer** [comment]
Being able to see the diffs between the current source and the `postgresql-libpq` source could be *super* helpful in understanding how the source works. As it touches all of the points where the database is queried.

Do you think this is a simple enough task for a Haskell newbie to tackle (no new features so I would just need to ensure tests keep passing). Or would it be better for me to observe?

Again super excited to learn more about the Haskell community and help this project grow.

**Comment by begriffs** [comment]
Love your enthusiasm @calebmer! Issue #290 would be a great place to start for learning to build the project, run the test suite and add your own test. Certainly the project [chat room](https://gitter.im/begriffs/postgrest) is a helpful spot to ask questions along with the Haskell IRC channel on freenode. Also @bitemyapp enjoys helping people get started coding Haskell and would be a good person to talk to.

If you've got some postgrest changes you'd like to share just open a pull request even if things aren't 100% finished. That will provide a nice way to chat about the code as we go. I'm on vacation for most of this week but I'll check online every so often to see if I can help.

**Comment by bitemyapp** [comment]
@calebmer @begriffs howdy. Just email me if you have questions, need pointed in the right direction, w/e.

Fair warning, I know jack and nada about postgrest other than what it does. I can mostly offer advice/help with Haskell, OSS, teaching, learning, etc.

If you want code review, just PR (if @begriffs doesn't mind) and cc me on the PR.
