### ISSUE TITLE
When "role" is not specified for authentication, an empty string is used

### ISSUE THREAD

**Issue by calebmer** [begriffs/postgrest#290]
I am using a default value for `rolname` in my table schema so I don't always expect one to be provided at the `/postgrest/users` route. When no role is specified e.g.

```json
{
  "id": "sarasmith",
  "pass": "qwerty"
}
```

The data is passed to PostgreSQL with `rolname` equal to an empty string (`""`).

**Comment by begriffs** [comment]
I created an experimental branch `tolerate-missing-role` that may fix this problem for you. Try checking out the branch and following the instructions to [build the project](https://github.com/begriffs/postgrest/wiki/Building-from-source) from source. If it works for your situation then I'll add a test and get it merged.

Or... if you're looking for a way to start contributing then you could write the test and send a pull request! It would require adding a new test to `test/Feature/AuthSpec.hs` and modifying `test/fixtures/schema.sql` to set the default value for the column in the db.

**Comment by calebmer** [comment]
The changes in `tolerate-missing-role`does not fix it, however I do believe I can build off of it and get things working.
