### ISSUE TITLE
how to get the ID after insert a new row?

### ISSUE THREAD

**Issue by john-qin** [begriffs/postgrest#297]
I am using jquery to insert a new row to the database.  you can see my codes below.

		$("#btnSubmit").click(function(){

			var title = $("#tbxTitle").val()
			var description = $("#txtDescription").val()
			var rating = $("#rating").val()
			var created_date = new Date()

			var request = {"title": title, "description": description, "category": "iPhone", "rating": rating, "created_date": created_date}

			//alert(JSON.stringify(request))

			 $.ajax({
                url: "http://localhost:3000/app",
                type: "POST",
                data: JSON.stringify(request),
                dataType: "json",
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    alert('Inserted Successfully');
                    //window.location.href = "../Index";
                    alert(JSON.stringify(data))
                },
                error: function (msg) { 
                	alert("error:")
                	alert(JSON.stringify(msg)); 
                }
            });
		})

after the new record gets inserted, I got an "error:" alert, then the error message

{"readyState":4,"responseText":"","status":201,"statusText":"Created"}

this message told me its created successfully, but why I got this message in the error callback, not in the success callback.

second, i need the api to return the ID back, how can i do that?

**Comment by ruslantalpa** [comment]
You received it in error callback because the status is (201 Created) and jquery probably interprets anything except 200 as an error (see if you can configure it to interpret 201 as ok)

To get back the created record, set this header when making the request
Prefer: return=representation

**Comment by john-qin** [comment]
thanks. it works, now i m getting the entire record back with id.  and to support status 201, i just need to change datatype from json to text.

**Comment by begriffs** [comment]
Maybe once the server responds with data (because you set `Prefer: return=representation`) then the success callback will fire as it should. In http://stackoverflow.com/a/25279053 they say

> Looking at the jquery 1.9 source, a 201 status code expects content. If there is no content (or of the wrong content type) returned with the 201, then the fail callback is invoked.

**Comment by begriffs** [comment]
@john-qin since you got it working I'm going to close this issue. Feel free to re-open it if you have more questions.
