### ISSUE TITLE
json validation issue

### ISSUE THREAD

**Issue by ktenney** [begriffs/postgrest#301]
I'm posting to a jsonb column, in the file is the following:
...
            "edd" : "Enhanced Disk Drive extensions",
            "int13floppy360" : "5.25\" 360KB floppy",
...

A couple validators are ok with that but
curl -XPOST -d @lshw.json localhost:3000/view_hardware

errors with:
{"hint":null,"details":"Token \"360KB\" is invalid.","code":"22P02","message":"invalid input syntax

If I change "5.25\" to "5.25
all is well.

I'll do that, but thought this might be of interest.

Thanks,
Kent

**Comment by joaoportela** [comment]
And if you replace `\"` with `\u0022`, does it make a difference?

**Comment by begriffs** [comment]
Please re-open if the problem persists.
