### ISSUE TITLE
Versioning should not be done in PostgREST

### ISSUE THREAD

**Issue by calebmer** [begriffs/postgrest#304]
PostgREST probably should remove the versioning feature.

Reading the discussion in #260 about SSL I thought about what other features could be done just as well with a load balancer/nginx proxy. I think versioning is one such feature.

Making versioning a responsibility of whatever proxy the developer might use makes more sense than putting it in PostgREST as a proxy can better supports legacy systems (APIs not using PostgREST). In addition versioning designation can be done wherever the developer wants, such as in the URL (some might want this despite it maybe being an anti-pattern), `X-Version` or another header, or the `Content-Type` header (as is done in PostgREST currently).

Keeping versioning in PostgREST also harms future development as we can never introduce breaking changes. We can always add features, but we can never remove code that is no longer useful because someone's old API might depend on it (we are in the versioning business after all).

I think the versioning of PostgreSQL schemas is still a very good idea, so the docs and examples should continue using the `"1"` schema; however, for developers to switch between versions they should spin up different PostgREST instances not one that is expected to handle them all. Maybe a recipe for this in the new documentation could be helpful.

I think it's a bad idea for software with such an exciting future to be mired down with perpetual legacy support by being in the business of version control.

**Comment by begriffs** [comment]
That's an interesting idea. Less internal code is better than more code, especially when more code commits us to a rigid interface we have to support.

How about if I change the `v1schema` parameter to just  `schema`? It would make postgrest read from one and only one schema. If someone wants to have two versions of the API then they run two instances of the postgrest server, each on its own port, each with a different schema parameter. Then use nginx to route traffic to the correct instance based on however the developer chooses to distinguish versions.

With the proper documentation and example nginx config files it would probably be pretty easy to set up. And people can get started with postgrest without needing to set up nginx. It's only after they need multiple versions that they need to do the extra setup.

**Comment by calebmer** [comment]
Yes please :blush: +1

I'll be getting some time back this week so I could try doing these changes if everyone agrees.
