### ISSUE TITLE
What is the plan for extending the back end logic?

### ISSUE THREAD

**Issue by danse** [begriffs/postgrest#306]
Hey, first of all congratulations for this project, it is pretty awesome. I used similar tools in the past, like [Python Eve](https://github.com/nicolaiarocci/eve) or Couch, which is in some sense comparable with a solution based on PostgREST. These solutions are incredibly effective in order to get started with a prototypical app for example, especially nowadays that thick clients and mobile apps are everywhere. 

A typical problem i met in the past was eventually extending the frame provided by these tools with some custom logic. I agree that 90% of the functionality needed by a client will be satisfied by exposing the database interface, but that remaining 10% is going to happen, developers will need to write that odd interface call that *has* to happen on the back end, and then the crystal clear design of a tool like Eve or PostgREST might suddenly turn into a cage.

So my question here is: what is the plan? Having a clear plan helps people knowing in advance how to set up their system and what to expect from the future, for the moment when they will want to extend their exposed PostgREST with some custom logic. Main alternatives i see are either to offer some hooks within the same process running PostgREST, or to assume that people will build external processes, and synchronise on the database

**Comment by ruslantalpa** [comment]
You have the stored procedures/triggers to do any logic inside the db that needs to mutate other parts of the data.
For things need to affect other parts of the system (like sending emails), my plan is to add pg_amqp to the database which provides the ability to send amqp messages to a system like rabbigmq and then custom scripts can take over and react to any event in the db that was triggered by postgrest.
The on problem i see is that pg_amqp is not provided by things like RDS so you would have to deploy your own posgresql server.

Main idea is that the db should be the extension point.

**Comment by sscarduzio** [comment]
I don't get why the db should be the only extension point. What if I want to make a synchronous call to an external billing system? Should the data store take care of that too?

And even if I don't have to integrate anything right now, should I live with the constraint that whatever bit of business logic I will be required to implement will need to be implemented in Pg/plsql?

I think this is not only an issue of separation of concerns, but also a technical limitation. PostgREST could be much more than this! 

How about an optional set of GIT-style web hooks?

**Comment by ruslantalpa** [comment]
First of all i want to make clear that these are just my opinions and not the way postgrest might choose to do things. With that out of the way, please  [give it 5 minutes] (https://signalvnoise.com/posts/3124-give-it-five-minutes) (not intended as an arrogant comment).

When it comes to implementing some logic that reacts to insert/update/delete events in the db and is dependent on some other data from the same db, i would place that in the db, the data processing should be done as close as possible to the data (as long as it does not create a bottleneck). As for the language, it's not only pgsql, you can use javascript and i guess a lot of other scripting languages through plugins.

When you need to interact with other systems (make an call to a external billing system when a upgrade is made) first you publish the events from he db to a messaging broker (rabbitmq) and on the other you have every language available to do your logic, it's not synchronous but i doubt you really need synchronous. Webhooks is a poor cousin of a message broker. Imagine if the webhooks were implemented in postgrest and one of the remote systems goes down, then none of your clients would be able to insert/update data (and of course  the response time for updates/inserts will also go up quite a lot even in normal conditions).

A message broker decouples various parts of the systems and provides great flexibility (and it's quite opposite to limited system). Postgrest will be only one part of the system with a clear responsibility of providing a rest-like interface to your system.

**Comment by sscarduzio** [comment]
Thanks Ruslan for the input.

Message brokers are ok in replacement to web hooks in general, I agree.
Unfortunately in my use case the Postgres plugins you mentioned are not a
viable option. And that's because we are already on AWS RDS and that
doesn't support any of those plugins (AMQP/Javascript ).

As a matter of fact though, I bet I'm not the only one wanting to stick to
RDS :)

As of today, apparently, the only way I have to take advantage of the
SQL->REST inference goodness of PostgREST is building a transparent HTTP
proxy that takes care of authentication/authorization and gives me an entry
point for some business logic flexibility.

Am I right?

**Comment by ruslantalpa** [comment]
For the auth/authorisation there is a discussion going on here #260 but basically it could be as you said, 
the authentication could be left for you to implement and postgrest would only respond to requests containing a valid JWT.

As for the RDS you are right, it is a limitation, but then again there might be tools that would allow you to do just that. For example, just saw this today https://github.com/JarvusInnovations/lapidus
Another way (although very hacky) is to leave your main system on RDS but have replication to your own pg instance for the soul purpose of having pg_amqp compiled into it to be able to broadcast events.

As for the transparent proxy (nginx) i would put only authentication/authorisation in it. Business logic would be done somehow after events occur in the db.

**Comment by calebmer** [comment]
I'd be curious to know what extensions require something more than a proxy layer from PostgREST. OAuth support can be done in a layer, most business logic can be done in the DB (@ruslantalpa you got me really excited for JavaScript in PostgreSQL).

Maybe a more advanced ranking algorithm would require a PostgREST extension point to emulate syntax and CSV/other content type support?

**Comment by begriffs** [comment]
Looks like there are some ideas to try in here.

We can create individual issues for specific problems, like "Sending an email from a postgrest route" or whatever as they arise. I'm closing this broader issue for now.

**Comment by danse** [comment]
[This talk from Martin Kleppmann](https://vimeo.com/145847021) sheds some light about the related architectural considerations, and [Bottledwater](https://github.com/confluentinc/bottledwater-pg) helps in actually building a similar system

**Comment by lf94** [comment]
For anyone coming here from search engines: what I'm doing is setting up a proxy within my application server. Essentially this server listens for all requests meant for PostgREST and itself. On a request the application server cares about, it does things, otherwise, it will relay it to PostgREST and relay back the response. This creates a nice separation of concerns between what PostgREST, PostgreSQL and your custom server logic do.

The next thing would be to write a very small package in your-favorite-language-X to do this glue code.

**Comment by danse** [comment]
@lf94 how does that work with authentication though?
