### ISSUE TITLE
JWT authentication fails in a load-balanced environment

### ISSUE THREAD

**Issue by fzaninotto** [begriffs/postgrest#317]
Hi, I'm posting a Postgrest issue here even though I'm not sure the problem lies in Postgrest. Please apologize if the setup I'm going to describe is already battle-tested and the problem is elsewhere.

Here is it:

```
               client
                 |
            load-balancer
           /             \
    postgrest1         postgrest2
          \               /
              PostgreSQL
```

We've installed several postgrest instances to distribute the load from clients and provide a hot failover. The load-balancer uses round robin, so a given client can make requests to either one of the postgrest instances during the same session.

Here is the problem: the JWT sent together with the client's request seems to fail randomly in this setup (we receive a 401 unauthorized response), while it works flawlessly when there is a single postgrest instance.

I'm surprised, because I thought postgrest instances were stateless, and stored everything in the underlying Postgres db - including tokens. Am I missing something?

**Comment by ruslantalpa** [comment]
@fzaninotto make absolutely sure you started both postgrest instances with the same --jwt-secret secret parameter

**Comment by fzaninotto** [comment]
That was it! Thanks a lot for your help. 

Is this already documented somewhere? I may not have seen it. If it's not, I suggest you add a simple mention of it close to the work "load-balanced" so a simple search brings to the solution.
