### ISSUE TITLE
Explicit BEGIN/END transaction control commands generating unnecessary overhead

### ISSUE THREAD

**Issue by diogob** [begriffs/postgrest#318]
Today the Hasql library seems to explicitly send a BEGIN and a COMMIT statement for every transaction, even the read-only ones (https://github.com/nikita-volkov/hasql-postgres/blob/master/library/Hasql/Postgres/Statement.hs).

I've noticed that in my production environment, having the vast majority of transactions as read only, I see only COMMIT statements being executed when monitoring the server.
This led me to believe that PostgREST was actually spending most of it's time in transaction control, so I did a small test on psql:

```bash
catarse_development=# \timing
Timing is on.
catarse_development=# begin; select version(); commit;
BEGIN
Time: 0.120 ms
                                                     version
-----------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.5beta1 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.0.72), 64-bit
(1 row)

Time: 0.293 ms
COMMIT
Time: 0.247 ms
```

And then without the explicit transaction control:
```bash
catarse_development=# select version();
                                                     version
-----------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.5beta1 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.0.72), 64-bit
(1 row)

Time: 0.286 ms
```

I understand that for slow queries the added time is neglectable. I also understand that is hard to tell if a transaction is read-only, for even a select can have functions with side-effects.

But is hard to come to terms that for some workloads this means consuming half of the DB server time with useless transaction control.

Any thoughts?

**Comment by begriffs** [comment]
Looks like the auto transaction mode is being enabled here https://github.com/begriffs/postgrest/blob/master/src/PostgREST/Main.hs#L95

We could conditionally use other values for `txSettings`, which is currently hard coded to `Just (H.ReadCommitted, Just True)`. We could check the http verb of `req` and use `Nothing` for `txSettings` on GET requests which prevents a transaction from being created.

**Comment by ruslantalpa** [comment]
Carefull not to mess the role switching mechanism, i think if you do set role in a transaction, the role would revert back to the default when the transaction is done, otherwise the role might remain set by the last command and that could be a problem

**Comment by diogob** [comment]
@ruslantalpa good catch, the transaction is needed for the role change and also local variables.
Maybe it's better to just close this issue, the transaction control is not unnecessary after all ;)
