### ISSUE TITLE
Ensure user only ever inserts for themselves

### ISSUE THREAD

**Issue by calebmer** [begriffs/postgrest#323]
I have a starring mechanism in an app I am building, the columns of which are `star_group_id` and `starrer_id`. The columns have a compound index to ensure uniqueness. How do I make sure `starrer_id` is only ever the user id identified by PostgREST authentication?

This seems to be a common scenario we should provide a recipe for (in both auth systems).

**Comment by ruslantalpa** [comment]
you create a insert/update trigger for that collumn and no matter what the value is sent, the trigger function does
NEW.starrer_id := postgres.user_vars.user_id;
RETURN NEW;

or you could check the NEW.starrer_id, and if it is different from user_id then fail in that trigger, probably this would be the better sollution

**Comment by calebmer** [comment]
Can a solution like that be put somewhere in the docs? Maybe in the [wiki](https://github.com/begriffs/postgrest/wiki/Security-and-Permissions)? It seems to be a very common scenario so there should be some documentation.

**Comment by begriffs** [comment]
Sure, I'll incorporate this into the docs on postgrest.com

**Comment by begriffs** [comment]
@calebmer actually it looks like the docs address this already with row level security:
https://github.com/begriffs/postgrest/blame/master/docs/examples/blog.md#L73-L89

What do you think about that approach?

**Comment by calebmer** [comment]
I do like the RLS approach, but the difficulty is RLS doesn't work with views so a solution (like replace triggers) still needs to be implemented for views.

**Comment by ruslantalpa** [comment]
no need for triggers, autoupdatable views work just fine
https://github.com/ruslantalpa/postgrest-rls-example/blob/master/sql/api_schema.sql#L114
when you add ```with local check option;```

**Comment by calebmer** [comment]
But can we have two different sets of rules for what a user can read and another for what users can write in auto updatable view?

**Comment by ruslantalpa** [comment]
Not sure, did not research that. I guess it depends very much on the specific example.
I don't see a real problem in using some triggers here and there in cases like this (complicated security model).
The view definition would encode the common rules then a "before insert" trigger would enforce write specific rules.
The code would still be short/clear ...
