### ISSUE TITLE
trying to make a post from jquery

### ISSUE THREAD

**Issue by ratmcarlo** [begriffs/postgrest#325]
i am trying to make a post with jquery, still getting the error:

```
{"message":"Failed to parse JSON payload. Failed reading: satisfy"}
```

Here is how I do the call:

```
$.post( "http://localhost:3000/songs", { title: "Some title" })
  .done(function( data ) {
     alert( "Data Loaded: " + data );
  });
```

I am able to do GETs with jquery on the same table.

What kind of problem is that?

Thank you in advance

**Comment by ruslantalpa** [comment]
Try
{"title":"some title"}

**Comment by calebmer** [comment]
This is not a PostgREST problem. jQuery wants to send your data with a content type of `application/x-www-form-urlencoded; charset=UTF-8` in key value pairs (`title=Some+title`). PostgREST currently does not support that content type (and I don't believe there are plans to add support it). A working example would be:

```js
$.ajax({
  method: 'POST',
  url: 'http://localhost:3000/songs',
  data: JSON.stringify({ title: 'Some title' }),
  contentType: 'application/json'
})
```

Note we are using `JSON.stringify` so jQuery does not turn our object into key/value pairs, and we are setting `contentType` to the value expected by PostgREST of `application/json`.

**Comment by begriffs** [comment]
Thanks @calebmer, I'll add this to the docs.

**Comment by ratmcarlo** [comment]
I confirm it works using ```JSON.stringify```
Thank you very much @calebmer

**Comment by begriffs** [comment]
Quick followup. As of version 0.3 we have improved the error message for this situation (thanks to your question). It now says

```json
{
  "details": "Content-type not acceptable: application/x-www-form-urlencoded",
  "message": "Cannot parse request payload"
}
```
