### ISSUE TITLE
JSONB route OK/OK does not match expectation (acquired from postgrest doc)

### ISSUE THREAD

**Issue by PierreR** [begriffs/postgrest#334]
I have this route that works as expected:
/salt_returns?return**->**user=eq.pradermecker&order=jid.desc

Here is the result: http://pastebin.com/tjWTTBHL

This is a bit at odd with the documentation that says:
> The final arrow must be the double kind, ->>, or else PostgREST will not attempt to look inside the JSON

What I find more surprising is that this route fails:
/salt_returns?return**->>**user=eq.pradermecker&order=jid.desc
with
```
{
"details": "unexpected \">\" expecting field name (* or [a..z0..9_])",
"message": "\"failed to parser tree path (return->>user)\" (line 1, column 9)"
}
```
As a further note, these routes works as expected:
* /salt_returns?full_ret**->**return**->>**user=eq.pradermecker&order=jid.desc
* /salt_returns?**select**=return->>user

I am using Postgrest version 0.2.12.0

##### Extra note
In postgresql, ` ->>` is supposed to convert the result into a text while `->` returns some json

**Comment by PierreR** [comment]
Looking at the tests suite, the above case is not included. I had been trying to add a test case for it bu unfortunately I don't know how to add to `complex_items` a simple `id` field to the `settings` attribute in order to prove the point.

Note that the following test would fail with the same error message:
```
it "can filter by properties inside json column using not" $
  get "/complex_item?id->>foo=not.eq.baz" `shouldRespondWith`
    [json| [] |]
```
But I am not sure about the expectation for this case.

**Comment by ruslantalpa** [comment]
looks like this was fixed

**Comment by begriffs** [comment]
Oops, you're right.
