### ISSUE TITLE
Add support for @> and @< operators

### ISSUE THREAD

**Issue by LeKovr** [begriffs/postgrest#338]
These operators used for [array](http://www.postgresql.org/docs/9.3/static/functions-array.html) datatype and for [text search](http://www.postgresql.org/docs/9.3/static/functions-textsearch.html), [hstore](http://www.postgresql.org/docs/9.3/static/hstore.html), [ltree](http://www.postgresql.org/docs/9.3/static/ltree.html) also.

Here is the sample for arrays.
```sql
CREATE TABLE "1".test (name TEXT, data INTEGER[]);
INSERT INTO "1".test VALUES ('row1','{2,3,4}'), ('row2','{3,4,5}');
GRANT SELECT ON "1".test to public;

SELECT * FROM "1".test;
/*
 name |  data   
------+---------
 row1 | {2,3,4}
 row2 | {3,4,5}
*/
```
http://localhost/api/test returns
```json
  [{"name":"row1","data":[2,3,4]}, {"name":"row2","data":[3,4,5]}]
```
```sql
SELECT * FROM "1".test where data = ARRAY[2,3,4];
/*
 name |  data   
------+---------
 row1 | {2,3,4}
*/
```
http://localhost/api/test?data=eq.{2,3,4} returns
```json
[{"name":"row1","data":[2,3,4]}]
```

It would be nice to get support for these queries:

```sql
SELECT * FROM "1".test where data @> ARRAY[3];
/*
 name |  data   
------+---------
 row1 | {2,3,4}
 row2 | {3,4,5}
*/

SELECT * FROM "1".test where data <@ ARRAY[1,2,3,4];
/*
 name |  data   
------+---------
 row1 | {2,3,4}
*/
```

**Comment by ruslantalpa** [comment]
Perfect, i'll look at this next week.
Could you take a look at the operator capabilities here http://postgrest.com/api/reading/#filtering and see if there are available operators in postgresql that are really useful but not available in postgrest. Also not that each pice of data that comes from outside (values for filters) is treated as a string and basically the query looks like
```
WHERE field = 'thedata'::unknown
```
So how would you write your query above knowing that the [1,2,3,4] part comes form outside and has to be treated as a string (i am asking this because i don't have much experience with PG)?

**Comment by LeKovr** [comment]
> if there are available operators in postgresql that are really useful but not available in postgrest

I guess these are POSIX regular expressions (~ ~* !~ !~*) because they ["provide a more powerful means for pattern matching than the LIKE and SIMILAR TO operators"](http://www.postgresql.org/docs/9.3/static/functions-matching.html)

> basically the query looks like ```WHERE field = 'thedata'::unknown```

I never had to use this type ("unknown") explicitly. Probably because postgresql treats any string in single quotes as unknown type variable and explicit note isn't required - ["If a type is not specified for a string literal, then the placeholder type unknown is assigned initially"](http://www.postgresql.org/docs/9.3/static/typeconv-overview.html). So why postgrest used it?

Also, there are a lot of cases when postgresql does automatic cast from string values, for example:
```sql
/*
    ----------------------------------------------------------------
    ltree
*/
select 'a.b.c'::ltree = '5';
-- f
select 'a.b.c'::ltree = 5;
/*
ERROR:  operator does not exist: ltree = integer
LINE 1: select 'a.b.c'::ltree = 5;
                              ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
*/

/*
    ----------------------------------------------------------------
    hstore
*/
select 'a=>c'::hstore = 'a=>c';
-- t
select 'a=>c'::hstore = 'd=>e';
-- f
/*
    ----------------------------------------------------------------
    bit string
*/
select '101'::bit(3) = '101';
-- t
select '101'::bit(3) = '102';
/*
ERROR:  "2" is not a valid binary digit
LINE 1: select '101'::bit(3) = '102';
                               ^
*/
```
So this is a good choice to support future datatypes in string form atfirst
> So how would you write your query above knowing that the [1,2,3,4] part comes form outside and has to be treated as a string?

As noted before, ARRAY[2,3,4]  in string form it is a '{2,3,4}'.
Btw, string array would be ... the same:
```sql
select ARRAY['a','b d','c'] @> '{a,b d}';
--  t
```

**Comment by ruslantalpa** [comment]
this can be closed, it's implemented

**Comment by LeKovr** [comment]
Yes. Thank you
