### ISSUE TITLE
Proposal for nested routes and JSON-LD

### ISSUE THREAD

**Issue by calebmer** [begriffs/postgrest#343]
Creating a nested route structure seems like the obvious next big evolution for PostgREST as we strive to become a leader in the API space.

### Outline:
1. REST adherence
2. Implementation
3. Impacts

### 1. REST adherence
REST is an excellent design, something that should be strived for. In the past few updates we have strayed in some ways, but I advocate we try to come back to REST to make our software as interoperable as possible.

Let's take a look at the REST constraints and see how we stand and what the proposed changes mean for our RESTfulness (see [Roy Fielding's Dissertation](http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm)):

1. **Client Server**: 👍
2. **Stateless**: 👍
3. **Cache**: Could definitely do better on this one
4. **Uniform Interface**: No interface at all
5. **Layered System**: 👍 (we are really good at delegating #320 😊)
6. **Code on Demand**: This one is optional, but we could still support JSONP

Nested routes can solve 3 as it allows for more cache points and allows the client to start doing very specific caching.

To adopt HATEOAS for 4 I propose we implement JSON-LD as well as nested routes so that no matter where a client is in the model, they never get lost.

### 2. Implementation
There are two parts to my suggested implementation, 1) nested routes 2) add JSON-LD support as the HATEOAS component.

As for the code changes, we would need a router, and a better way to handle mime types.

#### 2.1 Nested Routes
Every single value in the database should be accessible by a route, that is the design. So take the following data structure for instance at `/person`:

```json
[
  {
    "id": 1,
    "name": "Caleb",
    "parent": 7
  },
  {
    "id": 7,
    "name": "Shawn"
  }
]
```

`/person/1` would be:

```json
{
  "id": 1,
  "name": "Caleb",
  "parent": 7
}
```

and `/person/1/name` would be:

```
Caleb
```

In the style of the `select` parameter, `/person/1/person` or `/person/1/parent` would be:

```json
{
  "id": 7,
  "name": "Shawn"
}
```

Likewise `/person/1/parent/name` would be:

```
Shawn
```

There is a very clear impact to nesting this deeply, as I will explain in the **Impacts** section.

#### 2.2. JSON-LD
JSON-LD can be enabled/disabled completely by mime type (`application/ld+json`), however I would recommend it to be on by default as the implementation is highly unintrusive. All we would be doing with JSON-LD is as follows:

```json
[
  {
    "@id": "/person/1",
    "name": "Caleb",
    "parent": {
      "@id: "/person/7"
    }
  }
]
```

We add an `@id` property which describes the *unique* location of a resource. So an `@id` property would only ever reference a primary key, or a secondary key. With some `select` parameter magic (`?select=name,parent(name)`) the above would look like this:

```json
[
  {
    "@id": "/person/1",
    "name": "Caleb",
    "parent": {
      "@id: "/person/7",
      "name": "Shawn"
    }
  }
]
```

I've been advocating JSON-LD for a while, not because of the Web 3.0 semantic ooey-gooeys, but rather because it would be a *huge* help to clients who don't understand what a plain object or an integer `id` means. Especially with denormalized data which is a graph, but not represented as such. With JSON-LD it is now much easier to cache for clients as they know the *exact* nature of the resource.

A JSON-LD implementation is more to solve a problem using a defined and mature standard vs. a feel good implementation.

### 3. Impacts

Besides making PostgREST a more robust and API, we get a few more impacts.

1. We become more RESTful
2. Better PostgREST extension (#306). Another level could hijack a deeply nested route for custom functionality.
3. For GraphQL support (#310) if we use an outside layer, GraphQL schema can have a resolve function at every level (see [repo](https://github.com/graphql/graphql-js)). I would think this is a definite optimization as there is no over fetching.
4. Better JSONB support. That would nest too!
5. Have HATEOAS support for #234

* * *

I've been thinking of implementing these changes for a while and I wanted to get your feedback before I started, or even to answer the question is this even needed? What do you guys think, is this worth implementing?

**Comment by joaoportela** [comment]
> In the style of the select parameter, **`/person/1/person`** or `/person/1/parent` would be:
> 
>     {
>       "id": 7,
>      "name": "Shawn"
>     }

`/person/1/person` gives us the person with id 7? is this correct or a typo?

**Comment by calebmer** [comment]
@joaoportela with the current `select` parameter you would use `person` so it's not a type 😐

I do think this should be changed to the column name, that's why I had both.

**Comment by joaoportela** [comment]
Sorry. I didn't knew that, it is quite strange. What if we have multiple columns like a parent and a child reference?

Sorry for derailing the conversation, this is probably already being discussed elsewhere.

----

Back on topic:
JSON-LD seems like a good way to avoid confusion with object references.
- Do the ids need to be the database primary keys? If yes, how does it handle composed keys?
- Are there any alternatives to JSON-LD, how are they?

**Comment by calebmer** [comment]
They can be composed keys. We could represent that with the Haskell tuple syntax.

[Here](http://sookocheff.com/post/api/on-choosing-a-hypermedia-format/) is a list of more ideas for embedding hypermedia into API responses. My second choice would be HAL, but I am quite partial to JSON-LD because the rest of the standard can provide value into the future.

**Comment by ruslantalpa** [comment]
I can see a benefit for /endpoint/:id kind of nested route (limit updates/deletes to single objects) but not deeper. My feeling is that the deep nested routes evolve out of need to fetch related data which REST is not capable of (but postgrest and graphql are). 
The /endpoint/:id can be easily implemented in nginx like this (with the mentioned that it will return [{..}] and not {...} but that probably can also be implemented)
```
rewrite    /([a-z_]+)/([0-9]+) /$1?id=eq.$2 break; #support /endpoint/:id url style
```
JSON-LD can also be implemented on the db side by users of postgrest, for example for every table they create a view which contains all the columns of the table but adds an extra column "_id" which is the result of a function call "generate_path(endpoint_name,id)" or something like that. Postgresql is quite smart and maybe there is a way to have this "dynamic" column without the need of an extra view. For example we could implement a way to apply a function to a column before returning it (ignore the format of the call).
```
&select=id,name,(functionname param1 param2):as:_id:,.....
``` 
this would allow JSONLD (or any other thing which is not a specific db column) be implemented if needed by the user directly

**Comment by calebmer** [comment]
@ruslantalpa my mindset is if we can provide our users extra value without asking any more from them, we should.

REST is capable of providing related data through a nested routes method, as many have done in the past. This method is not astandard.

NGINX nested routes are difficult to keep updated and require a deeper knowledge of the technology when we could just give this away.

Remember, one of our main goals of nested routes is extensibility. The RPC format we have for calling procedures now is not intuitive and we want users to feel comfortable extending our routes. It doesn't really hurt us to add nested routes, and only helps users which only use the REST interface (those users should be our primary target too).

As for JSON-LD, that's a lot of work to implement a basic API infrastructure component. We need to implement some form of HATEOAS, I believe JSON-LD is the best option.

**Comment by ruslantalpa** [comment]
A conclusion "sort of" of the discussion in gitter.
@calebmer reason for including jsonld is something along these lines
(1) I can't embed both author and editor when they are both a person. Solution ?select=author(*),editor(*) which keeps a consistent type with JSON-LD.
(2) I can't reverse engineer ?select=a(b(c(d(e(f(g(h))))))). With JSON-LD each of these objects has a unique identifier and I can.
(3) I conditionally need the author data, but my client doesn't know what 5 means. With JSON-LD my client knows the specific url 5 lives at.
(4) In my application, I have data from request A and request B. The data conflicts. My client can't confidently update the one data store without making assumptions about my code.
(5) Component A and component B describe the same object in my data structure. It would be easier to render these objects if they used the same data source. My code currently cannot objectively find a good data source to share if their data comes from different designed requests.
(6) I would like to write a complicated popularity algorithm to display my data. Currently in PostgREST I can't crawl around the data model like a graph. With JSON-LD I can.

And my view is this:
except for (1) for which i described a solution, all the other items seem to boild down to "I can not calculate the url/unique identifier for the objects i am getting back from the api". I say this is not true, the location url is easily calculated
for a response like
```
/projects
[{
  id: 10, name: "test",
  clients: {id: 10, name:"test"}
}]
```
you use a function like
```
getResourceUrl(type,id){ return type + '/?id=eq.'+id}
clientUrl = getResourceUrl('clients', 10);
```
It's not like the client accidentally got some data from our api and now it does not know what that data means. The client "knows" it talks to a postgrest api server so it knows how the urls are constructed thus object type and id are the only things needed to calculate the location url. Even more, the client (front end dev) knows all the available object types (for a specific postgrest install) so he can even make functions like
```
getClientUrl(id){ return '/clients?id=eq.'+id }
```
The only situation where @id is useful is if somehow the objects would live on different servers/domains and the client can not guess what server/domain holds the item, but this is not the case for postgrest.

**Comment by calebmer** [comment]
Another interesting feature of JSON-LD which might be good for us to implement is the `@graph` construct. This would be specified with a `Prefer` header (`graph=true`?). Basically `@graph` returns all of the items asked for in the request in one array. So:

```json
[
  {
    "@id": "/person/1",
    "name": "Caleb",
    "parent": {
      "@id: "/person/7",
      "name": "Shawn"
    }
  }
]
```

would become:

```json
{
  "@graph": [
    {
      "@id": "/person/1",
      "name": "Caleb",
      "parent": { "@id: "/person/7" }
    },
    {
      "@id": "/person/7",
      "name": "Shawn"
    }
  ]
}
```

This could *drastically* reduce file size for requests with lots of embedded documents. Also not that the inclusion of `@graph` as a key/value pair is optional, we could always just return the array.

If this seems like an interesting proposal, maybe we should reconsider eliminating single row routes from #365. This is only an idea, it's not a high priority for me but I thought it would be a useful idea to share.

**Comment by auvipy** [comment]
following. but +1 for JSON-LD

**Comment by calebmer** [comment]
As I've experimented with Redux, I found this [normalizr](https://github.com/gaearon/normalizr) package. JSON-LD/nested routes would be really nice to work with this, entities would simply map to urls (or nested urls).

**Comment by calebmer** [comment]
I no longer think JSON-LD is the best direction for PostgREST. Benefits from a unique id can be obtained by a client who takes the primary keys and constructs it's own unique id. Ultimately for me it came down to the fact that JSON-LD is not optimal for our (close to) 1-1 translation of the database to HTTP. However, I'm still in favor of nested routes.
