### ISSUE TITLE
add mysql as a alternative db

### ISSUE THREAD

**Issue by wanghaisheng** [begriffs/postgrest#349]
is there any possible to add add mysql as a alternative db

**Comment by ruslantalpa** [comment]
No, a core feature that we use is postgresql json capabilities. Mysql does not have this.
Why not move your db to Postgresql?

**Comment by begriffs** [comment]
It is possible to make the project work with mysql but it would mean we have to implement some things inside the app that postgresql currently does for us (and does rather well). There are a lot of other issues we're dealing with now however, and mysql support would something for much later if at all.

**Comment by wanghaisheng** [comment]
@ruslantalpa right now we use a cloud service which  dose not support  postgresql though
@begriffs  thx  very much

**Comment by sscarduzio** [comment]
@begriffs what fundamental Postgres-only features is postgrest exactly relying on?

**Comment by wanghaisheng** [comment]
can we use dblink / fdw feature to hidden the underlying database such as oracle  sqlserver mysql 
@ruslantalpa @begriffs

**Comment by begriffs** [comment]
I'm not sure how well supported mysql would be through an FDW. There are some old related issues: #467 and #591. I suspect that foreign key detection will not work, which would break the resource embedding feature. I'd be curious how well it works if you try basic API table access though.

**Comment by laoshanxi** [comment]
in order to support limited features for other Databases (Oracle, MySQL, etc...) is there any other approach?
