### ISSUE TITLE
Bulk data insertion not working

### ISSUE THREAD

**Issue by waghanza** [begriffs/postgrest#351]
Hi,

I'm trying to use `postgres` for bulk insertion in my database.

I have a CSV file

```
id,name
1,2010
```

I have setup `postgres` (`0.2.12.0`) instance on my local machine (fedora 22).

Trying to insert from `CSV`

``` sh
curl -X POST -d @/tmp/toto.csv http://localhost:3000/seasons -H 'Content-Type: text/csv' 
```

I have

``` json
{"hint":null,"details":null,"code":"42601","message":"erreur de syntaxe sur ou près de « returning »"}
```

but I can insert from `JSON`

```
curl -X POST -H 'Content-type: application/json' -d '{"name":"2010","id":"1"}'  http://localhost:3000/seasons
```

Is there a mistake (in HTTP headers for example) ?

Regards,

**Comment by waghanza** [comment]
My csv is
~~~
name,id
2010,1
2011,2
2012,3
2013,4
2014,5
2015,6
2016,7
~~~
and query executed in `postgresql` was
~~~sql
insert into public.seasons (name, id2010, "12011", "22012", "32013", "42014", "52015", "62016", "7") values  returning row_to_json(public.seasons.*)
~~~

**Comment by waghanza** [comment]
with v3, the query is
~~~sql
WITH pg_source AS (INSERT INTO  public.seasons  (name, id2010, "12011", "22012", "32013", "42014", "52015", "62016", "7")  VALUES  RETURNING public.seasons.*) SELECT null, pg_catalog.count(t), null, null FROM ( SELECT  pg_source.* FROM  pg_source   LIMIT ALL OFFSET 0) t
~~~

**Comment by ruslantalpa** [comment]
The error comes form this line https://github.com/begriffs/postgrest/blob/v3/src/PostgREST/App.hs#L269
We should have the check changed to make sure we have at least the header and one line (rows > 1)

**Comment by begriffs** [comment]
@waghanza can you verify if the problem still exists in v0.3.1.1?

**Comment by begriffs** [comment]
Pretty sure this has long been fixed. Re-open the issue if you have the same trouble on v0.4.
