### ISSUE TITLE
Enable HSTS in production environments

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#37]
https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security#HSTS_mechanism_overview

We shouldn't turn this on in development because our cert is self-signed and the browser will forbid site access.

**Comment by uniphil** [comment]
This sounds like a problem to solve at the reverse-proxy layer instead.

(I'm apparently spending my sick day creeping ancient issues of OSS projects I like :) )

**Comment by begriffs** [comment]
Good idea, it's more of a docs issue so I'll close this one.
