### ISSUE TITLE
Connection to Postgres on MacOS X fails with non standard port

### ISSUE THREAD

**Issue by pbel78** [begriffs/postgrest#394]
Hi. 
thank you for the great work you are doing here!

Not sure if I identified the source of the problem but I guess with Version 3 there could be a problem with parsing the connection string: Connection to Postgres on MacOS X fails with non standard port
Tested it with users without password etc. and nothing worked until I downgraded to the latest 2 version where I can specify the db port manually.
to connect I tried the string: postgres://postgres@localhost:6001/testdb 
Error I got: can't connect to the database. In the db log file no entry was found for wrong authentification. pg_hba is probably correct as old version and pgadmin are able to connect.

**Comment by calebmer** [comment]
What is the username/password of your authenticator role? (`--db-role`/`--db-pass` in the previous format I believe)

Those values go in the connection string like so: `postgres://role:pass@localhost:6001/testdb` or they can be omit with `postgres://localhost:6001/testdb` to use the defaults.

**Comment by pbel78** [comment]
Hi. yes tried it with postgres://postgres:password@... then remove the password and tried with postgres://postgres:@... and postgres://postgres@... . Then created a login and db for default user and tried without user and password... always the same problem. Server log doesn't show any activity at all

**Comment by calebmer** [comment]
Ok cool, that wasn't entirely clear from the OP and `postgres` as a user name is generic, forgive me for checking 😊

Could you show me the exact statement you typed with all the other parameters? Both for when it works with `2.x` and what you expect to work in `3.x`. I need more information to help debug 😐

Also, what does PostgREST output? The help text?

**Comment by pbel78** [comment]
Hi
So what works is (pg_hba localhost is on "trust" level):
localhost on mac 6001 port
./postgrest:old_0.2.12 -d petr -P 6001 -U petr -a petr -p 4001 --v1schema public
or remote host on pc default port
./postgrest_old_0.2.12 -d postgres -P 6001 -U postgres -a postgres -p 3001 --v1schema public --db-host 192.168.214.50

What doesn't:
./postgrest postgresql://localhost:6001/petr -p 4001 -a petr  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgresql://localhost:6001/petr\" in connection info string\n","message":"Can't connect to the database"}

./postgrest postgresql://petr@localhost:6001/petr -p 4001 -a petr  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgresql://petr@localhost:6001/petr\" in connection info string\n","message":"Can't connect to the database"}

./postgrest postgresql://petr:@localhost:6001/petr -p 4001 -a petr  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgresql://petr:@localhost:6001/petr\" in connection info string\n","message":"Can't connect to the database"

./postgrest postgres://petr:@localhost:6001/petr -p 4001 -a petr  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgres://petr:@localhost:6001/petr\" in connection info string\n","message":"Can't connect to the database"}
/postgrest postgres://petr@localhost:6001/petr -p 4001 -a petr  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgres://petr@localhost:6001/petr\" in connection info string\n","message":"Can't connect to the database"}
Petr-Beless-MacBook-Pro-6:downloads petr$ 
./postgrest postgres://localhost:6001/petr -p 4001 -a petr  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgres://localhost:6001/petr\" in connection info string\n","message":"Can't connect to the database"}
Petr-Beless-MacBook-Pro-6:downloads petr$ 
./postgrest postgres://localhost/petr -p 4001 -a petr  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgres://localhost/petr\" in connection info 
string\n","message":"Can't connect to the database"}
./postgrest postgres://localhost:6001/ -p 4001 -a petr  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgres://localhost:6001/\" in connection info string\n","message":"Can't connect to the database"}
./postgrest postgres://localhost:6001 -p 4001 -a petr  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgres://localhost:6001\" in connection info string\n","message":"Can't connect to the database"}

PC default port:
./postgrest postgres://postgres@192.168.214.50/postgres -p 4001 -a postgres  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgres://postgres@192.168.214.50/postgres\" in connection info string\n","message":"Can't connect to the database"}
./postgrest postgres://postgres:@192.168.214.50/postgres -p 4001 -a postgres  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgres://postgres:@192.168.214.50/postgres\" in connection info string\n","message":"Can't connect to the database"}
/postgrest "postgres://postgres:@192.168.214.50/postgres" -p 4001 -a postgres  -s public
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 4001
postgrest: {"details":"missing \"=\" after \"postgres://postgres:@192.168.214.50/postgres\" in connection info string\n","message":"Can't connect to the database"}

**Comment by ruslantalpa** [comment]
what version of postgresql are you running? it should be above 9.3

**Comment by pbel78** [comment]
Hi

It is newest version (9.4)

Regards
Petr

2015-11-30 21:14 GMT+01:00 Ruslan Talpa <notifications@github.com>:

**Comment by ruslantalpa** [comment]
I still think there is something with the configuration of your db.
That error your get comes from postgresql lib.
can you try connecting to the db using psql with the same connection stirng?
http://www.postgresql.org/docs/9.4/static/app-psql.html

**Comment by calebmer** [comment]
I couldn't reproduce the error, the following string should work: `postgrest postgres://petr@localhost:6001/petr -p 4001 -a petr -s public`.

Postgres connection strings can be in two types: one the URI format we recommend and two a `key=value` format separated by spaces. Because of the `missing "="` part I can tell postgres is trying to parse the key/value format. For more info about both formats, [the Postgres docs](http://www.postgresql.org/docs/9.4/static/libpq-connect.html#LIBPQ-CONNSTRING) have a great explanation. @ruslantalpa is right, the error is coming from the Postgres library. It is a formatting issue.

Here is my best guess to what the error is, you are using a local `./postgrest` binary, so is there any possibility you are transforming the parameters in any way? I tried the following:
`postgrest " postgres://petr@localhost:6001/petr" -p 4001 -a petr -s public` (notice the space in the URI string) and sure enough I got your error.

**Comment by PierreR** [comment]
In case it helps, I am using the following (0.3.1) and it works flawlessly (using socket, no password, on linux) 
```
postgrest -- postgresql:///petr?user=petr --schema public --anonymous petr
```

**Comment by pbel78** [comment]
Thanks for all the help. Tried with psql and he doesn't like to connect without a password even pg_hba is set to trust => will sort out the connection of psql first and hopefully the other problem disappears... will check tomorrow

**Comment by begriffs** [comment]
@pbel78 any progress debugging this?

**Comment by pbel78** [comment]
Hi. I'm not 100% sure but my best guess is that on the Mac having the issue there are several version of postgres installed (9.1,9.2 and 9.4). As postgrest is working on my PC to connect to the 9.4 db on the Mac I close the issue as I believe that my mac maybe confuses some libararies he is using. Will verify that when I got more time but for now I close the issue. Thank you for everybody that helped to point me to the rigth direction.

**Comment by ferryzhou** [comment]
pbel, u can use the following command:

`postgrest  "host=localhost dbname=postgres port=6001" -p 4001 -a petr -s public`
