### ISSUE TITLE
does anyone have an Example for a rpc call

### ISSUE THREAD

**Issue by pbel78** [begriffs/postgrest#398]
Has anyone an example for a rpc call. Documentation states that it should be called with post and json in the body. I assume with a content-type : application/json header.

So I used Postman to call mydomain.com/rpc/CONVERSIONTYPES . Now funny enough a get request gives me an answer (my procedure has default values) even in the documentation it says it only works with post requuest. so far so good.

Now I change to to post request and post a raw body of type application/json:
{"V_CONVERSIONTYPES":"int"}

I would now expect that into input parameter V_CONVERSIONTYPES the value int is passed. but answer is instead: 
 404 Not Found

Header of my function is:
CREATE OR REPLACE FUNCTION DVB_GUI.CONVERSIONTYPES(
    V_CONVERSIONTYPES varchar default NULL)
  RETURNS varchar AS

call in db :+1:
select  DVB_GUI.CONVERSIONTYPES('int');

gives output:
"[{"id":"int","parameters":[{"id":"min","name":"Minimum","comment":"Minimum Value","conversiontypeid":"int","constraint":"[0-9]+","order":1},{"id":"max","name":"Maximum","comment":"Maximum Value","conversiontypeid":"int","constraint":"[0-9]+","order":2}]}]"

![image](https://cloud.githubusercontent.com/assets/4056560/11486690/f096720e-97ba-11e5-8446-018d342fc1fb.png)

**Comment by begriffs** [comment]
When you started the postgrest server what value did you use for the `--schema` argument?

Either you should set it to `DVB_GUI` or else you should change the [schema search path](http://www.postgresql.org/docs/current/static/ddl-schemas.html#DDL-SCHEMAS-PATH) to allow the function to be discovered even when operating in a difference schema.

**Comment by pbel78** [comment]
hi . just notice it could be a problem with capitalization. I test first and then post some updates

**Comment by pbel78** [comment]
Found why the get works: even I'm in the rpc path I can query tables... the get queried the tabe instead of the function which was capitalized differently. /rpc/conversionTypes => got to table with get. post didn't worked (yeah. it is a table I understand that) and /rpc/conversiontypes didn't works with get because it is a funcion => but did work with post when I changed parameter to all lower)
