### ISSUE TITLE
Multiple insert on database

### ISSUE THREAD

**Issue by zizou10** [begriffs/postgrest#405]
Hello,

I would like to insert in two tables links by one to many or many to many relations with post request.
For example:
I have two tables Subscription & Origin

Subscription is link to origin (one to many relation)
I would like to insert new entry into subscription and origin.

How can I do that ?

Regards

**Comment by ruslantalpa** [comment]
At least for now, inserts/updates work on one table at a time only, meaning you first do a POST on the child (many) table, then do a POST on the parent (one) table.

I think it might be possible to have a before insert trigger on the parent table so that when it notices a value being inserted to a "meta column" it takes that data and first inserts it in the child table then the insert continues on the main table.

**Comment by ruslantalpa** [comment]
Your situation is common (trying to insert data in multiple tables at the same time, for example add a "client" and a few "projects" in one request) so i am interested in adding such functionality in the future or at least provide an easy way/template of how to do this with db triggers

**Comment by zizou10** [comment]
Thank you for your response.

For now, I think the best way is to use sql function which takes a json in entry and insert data into multiple tables.

**Comment by begriffs** [comment]
Sure a stored proc can do it. Another option is making an [auto-updatable](http://www.postgresql.org/docs/9.4/static/sql-createview.html#SQL-CREATEVIEW-UPDATABLE-VIEWS) join view. A simple join between the parent and child tables will be updatable so you can write to it through postgrest as if it were a table.

**Comment by begriffs** [comment]
@zizou10 have you tried any of these ideas and do they work for you OK?

**Comment by zizou10** [comment]
@begriffs I try the version with Stored Procedure function but I had trouble to call the function.
I follow your tutorial but I have an error (couldn't find my function)

Can you give me an example please ?

Regards

**Comment by begriffs** [comment]
Which database schema contains your stored procedure? And what value are using for the command line option `--schema` when starting the postgrest server?

**Comment by zizou10** [comment]
I have this file postgrest to configure the postgrest service:

POSTGREST_DBPORT=5432

# database to use
POSTGREST_DBNAME=zizou

# database user
POSTGREST_DBUSER=zizou

# database password
POSTGREST_DBPASS=pass

# anonymouse user
POSTGREST_ANON=zizou

# database pool
POSTGREST_POOL=10

# jwt secret
POSTGREST_JWT_SECRET=secret

# default schema
POSTGREST_SCHEMA=public

# secure (use 1 to enable, empty string to disable)
POSTGREST_SECURE=None

/usr/local/bin/postgrest postgres://user:pass@localhost:5432/zizou --port 3000 --pool 10 --jwt-secret secret --schema public --anonymous funfid

My stored procedure is on the right schema public and I use the same one on the command line

**Comment by begriffs** [comment]
What parameters does the function take, and what value are you posting to it?

**Comment by zizou10** [comment]
I have 2 functions:
CREATE OR REPLACE FUNCTION search_client2()
RETURNS json LANGUAGE SQL AS $func$
 SELECT json_build_array(id_client) FROM clients
$func$;

Request POST:
http://myserveur:3000/rpc/search_client2
Response:
{"details":"not enough input","message":"Cannot parse request payload"}

OR
CREATE OR REPLACE FUNCTION search_client(IN in_lastname varchar, IN in_name varchar, IN in_email varchar, IN in_id_shop integer)
RETURNS json LANGUAGE SQL AS $func$
	SELECT json_build_array(funfid.client.id_client) 
	FROM clients 
    INNER JOIN shop_clients
    ON clients.id_client = shop_clients.id_client
    AND shop_clients.id_shop = in_id_shop
    AND (
    	(in_lastname IS NOT NULL OR funfid.client.lastname LIKE in_lastname)
    	OR (in_lastname IS NOT NULL OR funfid.client.name LIKE in_lastname)
    	OR (in_name IS NOT NULL OR funfid.client.name LIKE in_name)
    	OR (in_name IS NOT NULL OR funfid.client.lastname LIKE in_name)
    	OR (in_email IS NOT NULL OR funfid.client.email LIKE in_email)
    )
$func$;

Request POST:
http://myserveur:3000/rpc/search_client
{in_lastname:"and you"; in_name:"me";in_email:"toto@adnow.fr";in_id_shop=1}
Response:
{"details":"Failed reading: satisfy","message":"Cannot parse request payload"}

**Comment by begriffs** [comment]
Try modifying your request by quoting the keys and using commas rather than semicolons, like this

```json
{
	"in_lastname": "and you",
	"in_name": "me",
	"in_email": "toto@gmail.fr",
	"in_id_shop": 1
}
```

**Comment by zizou10** [comment]
it works thanks, indeed I wrote bad json object ... my fault

**Comment by begriffs** [comment]
Glad that fixed it!

Would you say this github issue is resolved, or do you have any more questions about doing multiple insert?

**Comment by zizou10** [comment]
Yes only one, on the next version of the postgrest do you think we will have multiple insert via POST request ?

**Comment by diogob** [comment]
I could add some docs to http://postgrest.com/api/writing/ with an example of solution using updatable views. For me is the cleanest solution.

**Comment by begriffs** [comment]
Yes please
