### ISSUE TITLE
Add tests for weak authenticator role

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#407]
The whole feature test suite uses an authenticator role with superuser access. In a real deployment the authenticator should not be able to access anything. It should be a `noinherit` role which can `set role` into the other users.

To keep existing tests free of JWT tokens we can ensure the anonymous role is strong, while the auth role is weak.

**Comment by ruslantalpa** [comment]
(note to myself) Another test here is to check that relations are detected by the code in #403

**Comment by ruslantalpa** [comment]
This can be closed, it's been implemented

**Comment by begriffs** [comment]
If I recall, making the auth role noinherit still causes tests to fail.

**Comment by ruslantalpa** [comment]
I'll try and see

**Comment by ruslantalpa** [comment]
Fixed in #427
