### ISSUE TITLE
Embedding Foreign Entities for N-N relationship

### ISSUE THREAD

**Issue by KoRiGaN** [begriffs/postgrest#412]
When we have a N-N relationship, for example called member between user and group, it would be great to be able to get :
- all users member of a group with GET /group?select=id.eq.group1, member{user{*}}
- all groups a user if member of GET /user?select=id.eq.user1, member{group{*}}

**Comment by ruslantalpa** [comment]
Typing on the phone so sorry for short reply :).
You are mixing &select parameter with filters like &id

What you are looking for is
/groups?select=id,users{*}&id=eq.10
And
/users?select=id,groups{*}&id=eq.22

If that works pls confirm and close the issue

**Comment by KoRiGaN** [comment]
What I mean is that if I do 
```
/user?select=id,member{*}&id=eq.22
```
I get :
```JSON
[
  {
    "id": "22",
    "member": [
      {
        "user_id": "22",
        "group_id": "181f8997-1da4-4999-8c3d-8b98e587ff76"
      },
      {
        "user_id": "22",
        "group_id": "7c3be20c-830d-4f31-a880-203c90174065"
      },
      {
        "user_id": "22",
        "group_id": "576b7428-6d06-4f23-833e-c30ae362d5aa"
      }
    ]
  }
]
```
So I have the content of the member table. It works fine, but I would like to access groups details directly for this user. In that case the member table contains only foreign key to user and group. 
Something like 
```
/user?select=id,group{*}&id=eq.22
or
/user?select=id,member{*, group{*}}&id=eq.22
```
to get something like :
```JSON
[
  {
    "id": "22",
    "member": [
      {
        "user_id": "836f7644-d35a-41ea-989a-1e9f08ad8866",
        "group_id": "181f8997-1da4-4999-8c3d-8b98e587ff76",
        "group": {
            "id": "181f8997-1da4-4999-8c3d-8b98e587ff76",
            "name": "group one"
        }
      },
      {
        "user_id": "836f7644-d35a-41ea-989a-1e9f08ad8866",
        "group_id": "7c3be20c-830d-4f31-a880-203c90174065",
        "group": {
            "id": "7c3be20c-830d-4f31-a880-203c90174065",
            "name": "group two"
        }
      },
      {
        "user_id": "836f7644-d35a-41ea-989a-1e9f08ad8866",
        "group_id": "576b7428-6d06-4f23-833e-c30ae362d5aa",
        "group": {
            "id": "576b7428-6d06-4f23-833e-c30ae362d5aa",
            "name": "group three"
        }
      }
    ]
  }
]

**Comment by ruslantalpa** [comment]
Please look at my queries carefully, there is no mention of "member" table
there is no way this
```
/users?select=id,groups{*}&id=eq.22
```
returns this
```
[
  {
    "id": "22",
    "member": [
      {
        "user_id": "836f7644-d35a-41ea-989a-1e9f08ad8866",
        "group_id": "181f8997-1da4-4999-8c3d-8b98e587ff76",
        "group": {
            "id": "181f8997-1da4-4999-8c3d-8b98e587ff76",
            "name": "group one"
        }
      }
    ]
  }
]
```

it should return this
```
[
  {
    "id": "22",
    "groups": [
       {
            "id": "181f8997-1da4-4999-8c3d-8b98e587ff76",
            "name": "group one"
        },
        {
            "id": "576b7428-6d06-4f23-833e-c30ae362d5aa",
            "name": "group three"
        }
      }
    ]
  }
]
```

(i notice your are using, user,group,member, are your tables named using singular?)
please try this
```
/users?select=id,groups{*}&id=eq.22 #if plural
/user?select=id,group{*}&id=eq.22 #if singular
```

and tell me the result

**Comment by begriffs** [comment]
@KoRiGaN so your goal is to list a given user and embed the groups he is in? It appears you also have a join table called members. The cool thing is you don't actually have to mention `members` in your URL. PostgREST detects that the join table exists. If you ask for

```
/user?select=id,group{*}&id=eq.22
```

what will happen is PostgREST tries to find a foreign key relation between `user` and `group`. It won't find one directly, but it will find one that goes through `members`, and will I think return what you want.

**Comment by begriffs** [comment]
@KoRiGaN I'm assuming this fixed your problem, so closing. Let me know if not and we can re-open this issue.
