### ISSUE TITLE
Performance regression for GET requests in 0.3+

### ISSUE THREAD

**Issue by diogob** [begriffs/postgrest#414]
In the version 0.3 some CTEs were introduced to simplify the query structure. But this generates a barrier for the PostgreSQL optimizer and prevents some nodes from collapsing in the query plan tree.
To demonstrate I'll use a query that can be generated using the postgrest_test database.

First we need some test data for the problems only manifest in large relations:
```sql
insert into test.simple_pk 
select s::text, 'testing for k = ' || s from generate_series(1, 100000) s;
```
Then we generate a query with an ORDER BY:
```sql
WITH pg_source AS ( 
	SELECT  test.simple_pk.* 
	FROM  test.simple_pk 
        ORDER BY k
) 
SELECT 
	(SELECT pg_catalog.count(1) FROM (SELECT * FROM pg_source) a ), 
	pg_catalog.count(t), 
	null, 
	array_to_json(array_agg(row_to_json(t)))::character varying 
FROM 
	(SELECT * FROM pg_source LIMIT 1 OFFSET 0) t
```
The above query is generated by a GET request using some filters and a limit 1. The generated plan (with a total cost of 7116 blks in my test env) is:
<img width="525" alt="screen shot 2015-12-08 at 5 49 33 pm" src="https://cloud.githubusercontent.com/assets/20662/11671149/2619f4ae-9dd4-11e5-8d86-5141a7d48bbd.png">

---

## Possible solution

After trying several different formats and different queries, the best compromise for all different scenarios was the query bellow:

```sql
SELECT 
	(SELECT pg_catalog.count(1) FROM ( 
	SELECT  test.simple_pk.* 
	FROM  test.simple_pk) a ), 
	pg_catalog.count(t), 
	null, 
	array_to_json(array_agg(row_to_json(t)))::character varying 
FROM 
	( 
	SELECT  test.simple_pk.* 
	FROM  test.simple_pk 
        ORDER BY k LIMIT 1 OFFSET 0) t;
```

This query does not use CTEs and also drops the **ORDER BY** clause in the subquery used for counting.

The generated plan is:

<img width="538" alt="screen shot 2015-12-08 at 5 56 34 pm" src="https://cloud.githubusercontent.com/assets/20662/11671266/0bbfabac-9dd5-11e5-9c5f-2559c73b5b99.png">

The cost is 1985 in my test env. Much cheaper than the original.

Even if alternatives with CTEs can perform quite well in this test environment, when I take the queries to my production database all hell breaks loose unless I use the non-CTE version.

I'm going to post another comment here with tests for more complex queries.

**Comment by ruslantalpa** [comment]
Any way to write a test for this?

**Comment by diogob** [comment]
@ruslantalpa I was still investigating, and I found another solution, so we can keep the CTEs!
I isolated the problem a bit further, and it's connected with the cost of counting records in the CTE.
Using the same example above I've created another query:
```sql
WITH pg_source AS ( 
    SELECT  test.simple_pk.* 
    FROM  test.simple_pk
    ORDER BY k
),
pg_source_count AS ( 
    SELECT  count(1)
    FROM  test.simple_pk
) 
SELECT 
    (SELECT count(1) FROM pg_source_count), 
    pg_catalog.count(t), 
    null, 
    array_to_json(array_agg(row_to_json(t)))::character varying 
FROM 
    (SELECT * FROM pg_source LIMIT 1 OFFSET 0) t
```

The generated plan is:

<img width="526" alt="screen shot 2015-12-08 at 9 34 40 pm" src="https://cloud.githubusercontent.com/assets/20662/11674947/8eb2eb0a-9df3-11e5-9a82-008ed15639f2.png">

The estimated cost in my test env was 6841 blks, but the speed was better than all alternatives. Besides, this query structure works vowed well for my production environment (I'm always skeptical of test data).

It seems that this solution gives us the best of both worlds keeping the CTEs and the speed for the price of having an extra CTE for counting.

Tomorrow I'll try to create a spec for this.

**Comment by ruslantalpa** [comment]
Since there is still a need for a separate "count" query, with or without cte is all the same from the code point of view (for the "GET" request). So maybe investigate it a bit more to make a decision which way to go on this. 
As for the insert/update requests, probably for now it's better to keep it as it is and in most cases the inserted records will be less then 1k so there will not be much of the impact of having it in a single cte

**Comment by diogob** [comment]
So I've made some more tests with the same query to check how the cost and execution time changes according to the number of row in the source. I have all steps documented but to spare you guys of details I'm posting just my charted results.
First the estimated cost:

<img width="587" alt="screen shot 2015-12-09 at 5 24 01 pm" src="https://cloud.githubusercontent.com/assets/20662/11700762/bafce2e6-9e99-11e5-9702-f1667c64457e.png">

And the time:

<img width="595" alt="screen shot 2015-12-09 at 5 24 07 pm" src="https://cloud.githubusercontent.com/assets/20662/11700765/c3324532-9e99-11e5-985d-b060ec0a479c.png">

The disparity between estimated cost persists even when I change server, filtering, ordering, use nested data or set a different random page cost. The difference is too big for the estimate to be accurate. My guess is that the CTEs are interfering with the estimates. I honestly believe the two queries are equivalent in terms of execution cost.

**Comment by diogob** [comment]
Oh, regarding the spec, I gave up on it. It would be too slow to create all the needed test data. But I have a script that I've used for the tests above and for the test with nested columns, so I can send you these if needed.

**Comment by ruslantalpa** [comment]
no need right now, i think i will go with inline, it has the same speed and it has also the better estimation, why risk it :)

**Comment by diogob** [comment]
:beers: 

Just an example of a nested query using the inline method:
```sql
SELECT
  (SELECT pg_catalog.count(1)
   FROM
     (SELECT test.clients.id,
        ( SELECT array_to_json(array_agg(row_to_json(p1)))
         FROM
           ( SELECT test.projects.id,
              ( SELECT array_to_json(array_agg(row_to_json(tasks)))
               FROM
                 (SELECT test.tasks.id,
                         test.tasks.name
                  FROM test.tasks
                  WHERE test.tasks.project_id = test.projects.id
                    AND test.tasks.name LIKE 'Design%'::UNKNOWN) tasks ) AS tasks
            FROM test.projects
            WHERE test.projects.client_id = test.clients.id) p1 ) AS projects
      FROM test.clients) s), 
   pg_catalog.count(t),
   NULL,
   array_to_json(array_agg(row_to_json(t)))::character varying
FROM
  ( SELECT test.clients.id,
     ( SELECT array_to_json(array_agg(row_to_json(projects)))
      FROM
        ( SELECT test.projects.id,
           ( SELECT array_to_json(array_agg(row_to_json(tasks)))
            FROM
              (SELECT test.tasks.id,
                      test.tasks.name
               FROM test.tasks
               WHERE test.tasks.project_id = test.projects.id
                 AND test.tasks.name LIKE 'Design%'::UNKNOWN) tasks ) AS tasks
         FROM test.projects
         WHERE test.projects.client_id = test.clients.id) projects ) AS projects
   FROM test.clients
   ORDER BY test.clients.id ASC LIMIT 10
   OFFSET 0) t
```

**Comment by ruslantalpa** [comment]
The count query will be much simpler since it does not need to go deep and embed related items.

**Comment by ruslantalpa** [comment]
@diogob who are you creating all those nice graphs and how are you progressively generating test data?
Can you do the same for related tables (clients>projects>tasks)
and test the performance of the query generated by ```/projects?select=id,clients{id},tasks{id}&id=in.1,100,400,22```
i am interested to see the impact of the number of rows (in all 3 tables) on the query that extracts the data and embeds related tables

PS: the #414 is ready for merging i think
