### ISSUE TITLE
Moving 1-N and N-N embeds to nested routes.

### ISSUE THREAD

**Issue by calebmer** [begriffs/postgrest#418]
Here's an idea I'd like to throw out. In some scenarios it is important to limit/offset the documents returned by 1-N and N-N relations, but we can only limit/offset with headers.

Why don't we remove these embedding capabilities and move them to a bested route. This has the advantage of all our current semantics/headers. It also doesn't need single document routes to work. For example:

`/people/posts?id=eq.5&posts.topic_id=7`

**Comment by calebmer** [comment]
I'm not too bought in on this at the moment, but I'd like to put it out there.

**Comment by begriffs** [comment]
In your example is it restricting to the person with id 5 and embedding their posts of a certain topic? Are all columns of the person returned? Could they be filtered? What if we want more than posts embedded? The nested hierarchy restricts expressing relationships I think.

But you're right that we should think of a way to limit the number of embedded results per main result.

**Comment by calebmer** [comment]
A better idea would probably be the other way around:

`/people/posts?people.id=eq.5&topic_id=7`

This would match the relationship of a hypothetical `author_id` column and filter where `author_id` is 5. All columns would be returned but could be modified with a `select`, it would operate just like a normal route.

Maybe nested hierarchy is not a good idea, but the more I think about the more sense it makes to remove array embedding in responses entirely. That should be the clients responsibility.

The best use case for nesting routes/embedding arrays is probably N-N.

**Comment by begriffs** [comment]
Aside from the challenge we're facing about limiting/offsetting embedded arrays they seem to be nothing but convenient and fast. What are the other reasons you mention for removing embedded arrays?

**Comment by calebmer** [comment]
At the moment, the only warrant is pretty much just that more control/uniform interface is nice 😊

There is no real killer issue I see at the moment, but it is a weaker part in the design of PostgREST that could use some discussion and new ideas. I know it's a big part of GraphQL to embed collections, but does that mean it should also be a big part of PostgREST?

**Comment by ruslantalpa** [comment]
So what you are saying is in order for the client to get a list of projects with their tasks, they need to make 2 consecutive trips to the server instead of one because this is more "uniform/control"?

**Comment by calebmer** [comment]
Yes. I don't think that's a problem. Especially with new technologies like HTTP2. If you want to make 1 super optimized HTTP request use a system like Falcor or GraphQL. We are designing an API which carefully follows the initial RESTful intent of HTTP not a wild new way to fetch data.

Keeping collection embeds requires new syntaxes and new designs on our part (maybe not in the near future) when we have a good system as it is.

**Comment by ruslantalpa** [comment]
I am not designing an api that "follows the initial restful intent", if that is the intent of the project please let me know (@begirffs). I will never use a system that forces me (frontend dev) to make two consecutive requests (no way to use http2 to make it parallel) instead of one because of some supposed standard, and yes, i will use another system that does that for me (or build one).

**Comment by calebmer** [comment]
REST is kinda in the name. Also, I've been playing around with Redux, two requests is better under that architecture (or at least in the way I'm using it).

**Comment by begriffs** [comment]
I'm going through issues today, tagging them and cleaning them up. I'm going to close this one for now.
