### ISSUE TITLE
GraphQL compatibility

### ISSUE THREAD

**Issue by ustun** [begriffs/postgrest#430]
I just saw this project, and looks great. 

Now that GraphQL is gaining steam, how about something for that in addition to REST? I think it would be great.

I even came up with a name: PostGraphQL :)

**Comment by ruslantalpa** [comment]
@ustun there is a discussion here https://github.com/begriffs/postgrest/issues/310 
Please post your comments there and close this thread.
Thank you

**Comment by ustun** [comment]
Sorry, should have searched.
