### ISSUE TITLE
Post row containing JSONB to REST endpoint

### ISSUE THREAD

**Issue by davidthewatson** [begriffs/postgrest#436]
I have the following schema in PostgreSQL 9.4.1:

```
sensor_data=# \d dog
                         Table "public.dog"
 Column |  Type   |                      Modifiers                      
--------+---------+-----------------------------------------------------
 id     | integer | not null default nextval('dog_id_seq'::regclass)
 uuid   | uuid    | not null
 attrs  | jsonb   | not null
Indexes:
    "dog_pkey" PRIMARY KEY, btree (id)
    "dog_attrs" gin (attrs)
```

I am using PostgREST to auth, JWT, and GET records from this table. However, I'm having trouble POSTing new records from python-requests.

This is my input:

```
>>> data
{'attrs': {'weight': 72.729988, 'signal_strength': 58, 'imei': '8432747', 'battery_voltage': 6031, 'dt': '2015-10-24T11:30:35.479000'}, 'uuid': '497ccda6-3b65-48ca-a314-24a86a829536'}
```

I generated the new UUID and deleted the id key,value pair since it's SERIAL.

I POST the data as follows:
    headers = {'Content-type': 'application/json'}
    # auth is a pre-existing JWT token which is working with GET, OPTIONS, etc.
    r = requests.post('http://localhost:3000/dog', auth=auth, data=data, headers=headers)

Which gives:
    {"hint":null,"details":null,"code":"42501","message":"permission denied for relation dog"}

It seemed strange that I'd get a 404 for a permissions denied error. The relevant log lines:

```
127.0.0.1 - - [22/Dec/2015:16:00:26 -0500] "GET /dog HTTP/1.1" 200 - "" "python-requests/2.9.1"
127.0.0.1 - - [22/Dec/2015:16:02:49 -0500] "POST /dog HTTP/1.1" 404 - "" "python-requests/2.9.1"
```

How can I debug this? Thanks!

**Comment by begriffs** [comment]
Does the db role you're using have `insert` privilege to the `dog` table and `usage, select` privileges on `dog_id_seq`?

**Comment by begriffs** [comment]
@davidthewatson have you had a chance to look into this more? Are the access privileges good?

**Comment by begriffs** [comment]
Please try with the [new release](https://github.com/begriffs/postgrest/releases/tag/v0.4.0.0) and re-open the issue if you have problems.
