### ISSUE TITLE
Can't load .so/.DLL when build on OS X 10.11.2

### ISSUE THREAD

**Issue by iporsut** [begriffs/postgrest#438]
I try to build by stack on OSX 10.11.2 but it's fail can't load .so/.DLL

    Configuring profunctors-5.1.1...
    Building profunctors-5.1.1...
    Preprocessing library profunctors-5.1.1...
    [ 1 of 14] Compiling Data.Profunctor.Trace ( src/Data/Profunctor/Trace.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/Data/Profunctor/Trace.o )
    [ 2 of 14] Compiling Data.Profunctor.Unsafe ( src/Data/Profunctor/Unsafe.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/Data/Profunctor/Unsafe.o )
    <command line>: can't load .so/.DLL for: /Users/weerasak/.stack/snapshots/x86_64-osx/lts-3.0/7.10.2/lib/x86_64-osx-ghc-7.10.2/StateVar-1.1.0.1-6K4a3UqSdqh6lGAm1wlr9s/libHSStateVar-1.1.0.1-6K4a3UqSdqh6lGAm1wlr9s-ghc7.10.2.dylib (dlopen(/Users/weerasak/.stack/snapshots/x86_64-osx/lts-3.0/7.10.2/lib/x86_64-osx-ghc-7.10.2/StateVar-1.1.0.1-6K4a3UqSdqh6lGAm1wlr9s/libHSStateVar-1.1.0.1-6K4a3UqSdqh6lGAm1wlr9s-ghc7.10.2.dylib, 5): Library not loaded: /usr/local/lib/ghc-7.10.2/trans_3eG64VdP2vzGjP6wJiCp5X/libHStransformers-0.4.2.0-3eG64VdP2vzGjP6wJiCp5X-ghc7.10.2.dylib
      Referenced from: /Users/weerasak/.stack/snapshots/x86_64-osx/lts-3.0/7.10.2/lib/x86_64-osx-ghc-7.10.2/StateVar-1.1.0.1-6K4a3UqSdqh6lGAm1wlr9s/libHSStateVar-1.1.0.1-6K4a3UqSdqh6lGAm1wlr9s-ghc7.10.2.dylib
      Reason: image not found)

**Comment by ruslantalpa** [comment]
Do you by any chan e have installed ghc/cabal before stack then tried to compile postgrest?

Try stack build and pasa the parameter ghc-local so that it ignores your haskell instalatiin

**Comment by iporsut** [comment]
I solved by
stack init --solver --force && stack build
Thanks.

**Comment by iporsut** [comment]
I solved by
stack init --solver --force && stack build
Thanks.
