### ISSUE TITLE
Centos binary does not work in Centos 6

### ISSUE THREAD

**Issue by realart** [begriffs/postgrest#440]
Fails with: "libgmp.so.10 not found". Doesn't look like there is easy fix for this.

**Comment by begriffs** [comment]
@realart sorry for the super slow response. Does the [v0.3.1.1](https://github.com/begriffs/postgrest/releases/tag/v0.3.1.1) release also have this problem?

**Comment by diogob** [comment]
I've had the same problem on ubuntu trusty (using the AWS default image).
The solution was to install the library libgmp10:
```
sudo aptitude install libgmp10
```
I believe a similar solution could be applied to Centos 6.

**Comment by begriffs** [comment]
@diogob so I should add `libgmp10` to the instructions here?

https://github.com/begriffs/postgrest/blame/master/docs/install/server.md#L49-L52

**Comment by diogob** [comment]
I'm not sure if this would be necessary to build (maybe stack installs this as a GHC dependency). But we should add to the `Installing from Pre-Built Release`, maybe before [this line](https://github.com/begriffs/postgrest/blame/master/docs/install/server.md#L13)

I can test the building instructions tomorrow as well.

**Comment by begriffs** [comment]
I tried it on CentOS 6 including the libgmp trick but there were other problems as well. Sorry I don't remember what they were because it was a few days ago that I tried it.

I'm still hoping we can find a way to run the 7 binary on 6. However you can always build from source on 6 in the meantime.

**Comment by mzsamantha** [comment]
I am running into this same issue. Building from source is problematic as stack is giant. A better solution would be appreciated.

**Comment by begriffs** [comment]
Try the CentOS 6 binary in the latest release: https://github.com/begriffs/postgrest/releases/tag/v0.3.2.0

**Comment by begriffs** [comment]
I'll soon be creating binaries for release 0.4, and want to be sure it doesn't suffer from the CentOS 6 problem. Can someone verify whether 0.3.2.0 works OK? (@realart, @mzsamantha)

**Comment by mzsamantha** [comment]
I'd love to test the new binary - I built mine current from scratch and found the CPU issue in https://github.com/begriffs/postgrest/pull/604 , so I would have needed a new build one way or another.

**Comment by allentc** [comment]
> Can someone verify whether 0.3.2.0 works OK?

I tested the postgrest-0.3.2.0-centos-6.tar.xz binary on centos 6.8 x86_64 with postgresql 9.6 using a Google cloud VM.  No problems.

**Comment by begriffs** [comment]
Thank you!
