### ISSUE TITLE
Login alias function

### ISSUE THREAD

**Issue by zizou10** [begriffs/postgrest#441]
Hello,

I follow this readme file to manage authentification:
https://github.com/begriffs/postgrest/blob/master/docs/examples/users.md

The only difference between your code and mine is I added function in the schema which manage the version of my project "21" and I created this function:
>
CREATE OR REPLACE FUNCTION "21".login(email text, pass text) 
RETURNS basic_auth.jwt_claims LANGUAGE plpgsql as $$
	SELECT public.login(email, pass);
$$;

When I do that I have this error:
>
ERROR:  syntax error at or near "SELECT"
LINE 3:  SELECT public.login(email, pass);

Any idea to fix that ?

Regards

**Comment by SebAlbert** [comment]
You need to write BEGIN and END statements in functions defined in PL/pgSQL - it's not a PostgREST error; it shouldn't be working in psql or pgAdmin or any other Client software either.

**Comment by zizou10** [comment]
Thanks Sebastian you right !
It s fixed
Le sam. 26 déc. 2015 à 10:33, Sebastian Albert <notifications@github.com> a
écrit :
