### ISSUE TITLE
OPTIONS request to non-existent table does not throw any error

### ISSUE THREAD

**Issue by timwis** [begriffs/postgrest#442]
Feel free to close this if it's intentional, but I noticed that an `OPTIONS` request to a [non-existent table](https://postgrest.herokuapp.com/foo) does not give any indication that it doesn't exist. It returns `200` with a body that looks like an empty table:
```json
{
  "pkey": [],
  "columns": []
}
```

**Comment by begriffs** [comment]
Not intentional at all. It should probably throw a 404, thanks for reporting.

**Comment by calebmer** [comment]
Could we put an easy/beginner tag on this issue so I can find next time I have a quick moment to do some bugfixes.
