### ISSUE TITLE
Security  system

### ISSUE THREAD

**Issue by zizou10** [begriffs/postgrest#444]
Hi,

How can I manage authentification & security for users ?
For example, I have two users:
- user with id = 1 
- user with id = 2 
- id = 1 can have access only on his information and the same thing with id = 2. I don't want id = 2 can update or change information for id = 1

I follow your tutorial:
http://postgrest.com/examples/users/
and
http://postgrest.com/examples/blog/

I'm on PostgreSQL 9.4, so I can't use row level security.

Any idea to manage that ?

Regards

**Comment by begriffs** [comment]
Just saw you closed this issue. Sorry I didn't respond! You can expose a view which filters the underlying table. Include a column in the underlying table to say which role created each row and give that column a default value of `current_user`. Then in your view

```sql
create view foo as
  select a,b,c from bar where owner = current_user
```

**Comment by zizou10** [comment]
Thanks for your response
