### ISSUE TITLE
Using foreign key relationships for view

### ISSUE THREAD

**Issue by matias-piin** [begriffs/postgrest#447]
Hi,

I'm trying to create a view and query it using postgREST but when I do it seems that all FK relationships are not there (fair enough). Is there a way to tell postgREST to look at the original table's FKs? Is there anyway to get around this?

The message I see is the following:
```
{
details: "no relation between <table> and <my_view>",
message: "could not find foreign keys between these entities"
}
```

Thank you!
Matias

**Comment by ruslantalpa** [comment]
@matias-piin please post the "CREATE" statements of all the tables and view related to this request and also the url you are trying to request.

**Comment by matias-piin** [comment]
Thanks for the quick reply, sorry it took so long to get back to you but im running into a problem while trying to simplify and reproduce this issue. I'm trying to create a simple case using a book and author table as this but I can't even get the basic relationships (without even a view) working now. Could you take a look and see if I'm doing something wrong? Thank you!

SQL Query:

```
CREATE TABLE book
(
book_id serial primary key,
name varchar(255)
);

CREATE TABLE author
(
author_id serial primary key,
book_id serial not null references book(book_id),
name varchar(255)
);

INSERT INTO book VALUES (1, 'My Book');
INSERT INTO author VALUES (1, 1, 'John Cook');

GRANT ALL ON TABLE book TO webapp;
GRANT ALL ON TABLE author TO webapp;
```

In this case if I use the following query: `/book?book_id=eq.1&select=book_id,name,author{*}`

I get this result:
```
{
details: "no relation between author and book",
message: "could not find foreign keys between these entities"
}
```

**Comment by begriffs** [comment]
I created your schema locally and it worked for me actually. Can you tell me the command line arguments you used when starting postgrest?

**Comment by matias-piin** [comment]
@begriffs Thanks so much for your reply. I actually had not restarted my docker service for postgREST after creating my view and that ended up being the problem. It is now working as intended :)

On a small side note, if I have a column that contains JSON (geoJSON specifically) can I have postgREST treat this as JSON and not return it as just a string?

Thanks for all the help!

**Comment by begriffs** [comment]
That's right, PostgREST loads table relationships on startup because it's kind of a slow query. Might be nice to have it listen for SIGHUP or and reload the relationships to avoid any downtime from a restart. Well that's another issue.

For your other question try casting the column type like this

```http
/foo?select=bar::json
```

Let me know if that works.

**Comment by matias-piin** [comment]
Makes sense, I guess since I could query the table without restarting I was just assuming that postgREST was picking up all my changes.

The casting worked great! 

Thanks for all the help!!! I'm really liking this tool :)

**Comment by begriffs** [comment]
Awesome!

Don't forget to join the project chat room if you haven't already. Lots of helpful people there. https://gitter.im/begriffs/postgrest
