### ISSUE TITLE
"Getting Started" examples fail with various errors

### ISSUE THREAD

**Issue by kinghajj** [begriffs/postgrest#451]
I'm following [this guide](http://postgrest.com/examples/start/) on Mac OS X 10.11, with PostgREST 0.3.0.2 installed via Homebrew against [Postgress.app](http://postgresapp.com/), using Postman to test the REST API.

The first error occurs when I attempt to run

    GET http://localhost:3000/competition?select=name,film{title}

Result:

    {
      "hint": null,
      "details": null,
      "code": "42703",
      "message": "column competition.title does not exist"
    }

The next one

    http://localhost:3000/competition?select=name,film{title,director{*}}

fails with a different error:

    {
      "hint": null,
      "details": null,
      "code": "42P01",
      "message": "missing FROM-clause entry for table \"film\""
    }

I copy-and-pasted the schema definition exactly as the guide specified. Any idea why these occur? Is the guide out-of-date, or is there a bug?

**Comment by begriffs** [comment]
Thanks for reporting the problem, I'll try to reproduce it locally.

**Comment by ruslantalpa** [comment]
The last error seems familiar, i think i fixed it in the master but it's not released
@begriffs try 3.0.2 and master separately, i think the master will work

**Comment by cpursley** [comment]
I'm experenicing the same issue with this endpoint.

Postgres mac app version 9.4.5
postgrest 0.3.0.2

I've been playing with postgres for the first time today. My mind is blown, thanks for creating it.

**Comment by kinghajj** [comment]
I tried @ruslantalpa's suggestion and compiled from master, and now those queries succeed as expected.

**Comment by begriffs** [comment]
Good to know. I'll release a new version with the newest fixes.

**Comment by begriffs** [comment]
Try with the new release please https://github.com/begriffs/postgrest/releases/tag/v0.3.0.3

**Comment by kinghajj** [comment]
Yes, that version works, too. Thanks for the help, and, like cpursley said, for making PostgREST! Seems very promising, can't wait to try it out this weekend.

**Comment by dacodekid** [comment]
@begriffs  I've installed it via ```brew``` and the error still exist on that version. Thx for this wonderful library.

**Comment by begriffs** [comment]
Try the 0.3.0.3 [release](https://github.com/begriffs/postgrest/releases/tag/v0.3.0.3), the brew package is a little behind.

**Comment by dacodekid** [comment]
Yep. Done that already after visited this thread. Just wanted bring that issue to ur attention.

**Comment by begriffs** [comment]
I see, thanks.

**Comment by begriffs** [comment]
Sent a PR to update the homebrew package https://github.com/Homebrew/homebrew/pull/48532

Also added this to my release checklist so homebrew will stay up to date with the newest version.
