### ISSUE TITLE
How to update user's password?

### ISSUE THREAD

**Issue by zizou10** [begriffs/postgrest#455]
Hi,

I would like to update password and as I understand I need to update on users view.

For that I has users view based on authentification part tutorial, I also managed versioning with schema "21".
How can I configure postgrest to update information into users view ?

Regards

**Comment by begriffs** [comment]
Are you following the [user management tutorial](http://postgrest.com/examples/users/) or building your own custom schema?

**Comment by begriffs** [comment]
@zizou10 did you figure this out?

**Comment by begriffs** [comment]
Closing the issue here as it is a matter of documentation. Feel free to open doc questions on https://github.com/begriffs/postgrest-docs
