### ISSUE TITLE
Error starting postrest with UTF8 encode db

### ISSUE THREAD

**Issue by jesusnoriega** [begriffs/postgrest#460]
Hello, my db is utf-8 encoded.  I got this error:

postgrest: {"hint":null,"details":null,"code":"22021","message":"secuencia de bytes no válida para codificación «UTF8»: 0xf1 0x6f"}

But when I try with a new db SQL ASCII encoded there is not problem and service start normally. 
Can you give some hint?

**Comment by begriffs** [comment]
Thanks for reporting the problem.

It's odd because I use a UTF-8 database myself without any problem. When do you see the error? Is it right away when PostgREST tries to start, or after a specific API action? What version of PostgreSQL are you using?

**Comment by jesusnoriega** [comment]
The error message appears just starting the postgRest init command with my production database.

I test the same start service command using the example database without any problem. Then try querying the service using Postman application on Chrome, and works great.

I guess could be a problem with spanish special characters like Ññ áéíóú. This is the difference between the test and my production database. 

The server is running on version PostgreSQL 9.4 also test with 9.3.

![error 1](https://cloud.githubusercontent.com/assets/16711931/12354712/4de8506a-bb5d-11e5-85fe-923caaa9e350.PNG)
![error 2](https://cloud.githubusercontent.com/assets/16711931/12354719/58a9c790-bb5d-11e5-833d-abd9504cf841.PNG)

**Comment by begriffs** [comment]
Can you try two more tests for me please?

1. Run this in your database:

   ```sql
   SHOW SERVER_ENCODING;
   ```
2. Try making this request to PostgREST

   ```
   http://192.168.1.78:3000/clientes_vehiculos_view?clienteid=eq.3
   ```
   I'm hoping this will select HECTOR LOPEZ (which has no special Spanish characters).

Let me know what response you get for these.

**Comment by jesusnoriega** [comment]
Of course,

Server Encode is SQL_ASCII
Query with clienteid = 3 works and throw me the correct data for the record but when I change the filter to clienteid = 1 ( record has an accent é in the text )  it throws an error:

"code": "22021",
"message": "secuencia de bytes no válida para codificación «UTF8»: 0xe9 0x22 0x2c"

Images attached for the query results.

![error with accent in the data](https://cloud.githubusercontent.com/assets/16711931/12366562/932cc9d2-bba1-11e5-9de1-11409e88a279.PNG)

![show server encoding](https://cloud.githubusercontent.com/assets/16711931/12366470/feb9523e-bba0-11e5-8ab0-aa1e65adac5b.PNG)
![select clienteid 3](https://cloud.githubusercontent.com/assets/16711931/12366469/feb89768-bba0-11e5-91fd-6f29445f356d.PNG)

**Comment by begriffs** [comment]
Interesting, it seems like your database is encoded with ASCII. For comparison, my local database says this:

```
# SHOW SERVER_ENCODING;
 server_encoding
-----------------
 UTF8
(1 row)
```

Would it be feasible to migrate your database from SQL-ASCII to UTF8? I found this [guide](http://blog.e-shell.org/134) about how to do that.

**Comment by jesusnoriega** [comment]
great hint, yes, I must to migrate my database from SQL-ASCII to UTF8 encoding, For some reason it still continues SQL-ASCII but I do need it UTF8...I will show you results after finish that job. Thanks again.

**Comment by begriffs** [comment]
I should probably make PostgREST check the encoding on startup and issue a warning if the encoding is not UTF8. That way people won't be surprised later if a special character gets included in their data.

**Comment by begriffs** [comment]
@jesusnoriega did converting your db format fix the problem?

**Comment by jesusnoriega** [comment]
Converting my db format solve the problem. Now I can work with spanish
special characters. Thanks for help.
