### ISSUE TITLE
Ability to set addresses to listen on

### ISSUE THREAD

**Issue by user318** [begriffs/postgrest#461]
Now postgrest accepts connections on all addresses. It will be good if there will be a way to supply it with specific addresses. So it can be run to listen on localhost only for example.

**Comment by begriffs** [comment]
Sure, I can add a `--host` command line parameter. How high priority is this issue for you?

**Comment by user318** [comment]
For me it is not high, because I now use it in test environment and can filter access to it using iptables. But in perspective, this option will be helpful for me and perhaps others. Thank you.

**Comment by SpiritQuaddicted** [comment]
For anyone ending up here in 2024, you can set e.g. `server-host = "127.0.0.1"` in your config.

**Comment by steve-chavez** [comment]
@SpiritQuaddicted Wonder if we should improve the docs to make that more clear.

Was https://docs.postgrest.org/en/v12/references/configuration.html#server-host not enough? Perhaps an example there?

**Comment by SpiritQuaddicted** [comment]
An example would be great, I think. If I look back, I seem to have googled for `"postgrest" listen localhost` and there Google shows only a generic result for the configuration page, which I did not end up visiting and reading. Maybe an example would make search engines show it right away? Might be stupid silly search engine optimisation of perfectly fine documentation but I'd try it.

Maybe simply another 1-2 lines in the list of examples with `127.0.0.1` and one from https://datatracker.ietf.org/doc/html/rfc5737?

**Comment by SpiritQuaddicted** [comment]
Just by looking at "In addition to the usual address options" I would not have felt comfortable to try `server-host = "127.0.0.1"` though to be honest. Explicit examples are super useful.

**Comment by steve-chavez** [comment]
Hm, I see no harm in adding an example since we have some for other configs too:

- https://docs.postgrest.org/en/v12/references/configuration.html#server-unix-socket
- https://docs.postgrest.org/en/v12/references/configuration.html#jwt-role-claim-key


Done in https://github.com/PostgREST/postgrest/commit/28ebe37e07c8c5ff2f5307be5c5b0b0608a6dfed
