### ISSUE TITLE
Add `libpq-dev` to dependencies to build from source, in the online documentation

### ISSUE THREAD

**Issue by eric-brechemier** [begriffs/postgrest#463]
The [instructions to build from source on Ubuntu](http://postgrest.com/install/server/#building-from-source) should indicate that `libpq-dev` must be installed beforehand. Otherwise, building `postgresql-libpq-0.9.1.1` fails during `stack build` or `stack install`.

I suggest to add:

* Install libpq-dev

```
sudo apt-get install -y libpq-dev
```

before:

* Build & install in one step

**Comment by begriffs** [comment]
Would you mind sending a pull request to update this page? https://github.com/begriffs/postgrest/blob/master/docs/install/server.md

**Comment by eric-brechemier** [comment]
No problem, I am on it.
