### ISSUE TITLE
Get request to Foreign tables returns errors if there is no conditions!

### ISSUE THREAD

**Issue by darsana** [begriffs/postgrest#467]
Created Foreign tables in postgreSql for the cassandra db,I am getting error like bellow if there is no conditions in the queries
Ex:
http://192.168.1.170:3005/statistics_real_time  
{
  "hint": null,
  "details": "<ErrorMessage code=2000 [Syntax error in CQL query] message=\"line 1:8 no viable alternative at input 'FROM' (SELECT  [FROM]...)\">",
  "code": "XX000",
  "message": "Error in python: SyntaxException"
} 
But for the request bellow giving proper result
http://192.168.1.170:3005/statistics_real_time?uid=eq.1

[
  {
    "uid": "c2aad687-e412-43f5-aac1-84c5aae394a3",
    "stat_type": "",
    "stat_name": ""
  }
]

**Comment by begriffs** [comment]
This is actually pretty exciting, connecting to Cassandra is half working!

Let's figure out why it breaks with no filtering. Can you provide logs of the SQL that this request is sending to the database? To obtain logs first [enable logging all statements](http://www.microhowto.info/howto/log_all_queries_to_a_postgresql_server.html), then [find your logs](http://blog.endpoint.com/2014/11/dear-postgresql-where-are-my-logs.html).

**Comment by begriffs** [comment]
@darsana any progress with this? I'd love to see some logs and learn how to make the foreign table work.

**Comment by darsana** [comment]
Hi... @begriffs  	



We successfully used the FDW tables in PostgreSQL , sample is bellow 


CREATE SERVER multi_srv FOREIGN DATA WRAPPER multicorn
options (
  wrapper 'pgCassandra.CassandraFDW',
   port '9160',
   hosts 'IP'
);


CREATE FOREIGN TABLE "1".nps_summary (
    project_party_id text,
    release_stage_name text,
    created_at text,
    score text,
    score_count text

)
SERVER watchtower_srv options (
   columnfamily 'nps_summary',
   keyspace 'multi_srv'

);



U can find the details from the bellow link. 

http://www.craigkerstiens.com/2013/08/05/a-look-at-FDWs/


 error log for the query  http://192.168.1.186:3000/release_stages is 


SyntaxException: <ErrorMessage code=2000 [Syntax error in CQL query] message="line 1:8 no viable alternative at input 'FROM' (SELECT  [FROM]...)">
	
2016-04-05 11:25:08 IST [4881-3] postgres@watchtowerpostgre STATEMENT:  select  (select pg_catalog.count(1) from "1".release_stages) , pg_catalog.count(t), array_to_json(array_agg(row_to_json(t)))::character varying from (select * from "1".release_stages LIMIT ALL OFFSET 0 ) t

**Comment by ruslantalpa** [comment]
I don't think this is a bug with PostgREST. The FDW used probably does not allow a `SELECT * FROM statistics_real_time` type of query. Nothing PostgREST can do about that.
If you can actually run that query on the foreign table, please reopen
