### ISSUE TITLE
Wrong status code returned for POST on duplicate key violating unique constraint

### ISSUE THREAD

**Issue by sscarduzio** [begriffs/postgrest#469]
I stumbled upon this response coming from the latest Postgrest.
```js
Status 400 
{"hint":null,"details":"Key (eid, uid)=(e1, 42d94270-1fe6-457c-8dd0-152eec8ac8f4) already exists.","code":"23505","message":"duplicate key value violates unique constraint \"event_feedbacks_sid_uid_key\""}
```
400 means bad request, but the request was perfectly ok (I just inserted the row one minute ago with the an identical request). 
In my opinion, the best code would be 409 Conflict: "The request could not be completed due to a conflict with the current state of the resource."

**Comment by calebmer** [comment]
This is any easy fix. The 23* error class could be mapped to 409.

Resources:

- [Postgres error codes](http://www.postgresql.org/docs/current/static/errcodes-appendix.html)
- [HTTP status codes](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)
- [PostgREST error code resolution](https://github.com/begriffs/postgrest/blob/master/src/PostgREST/Error.hs#L49)

Any other recommendations for Postgres error codes to HTTP status codes?

**Comment by sscarduzio** [comment]
Acually, 400 looks ok for many 23*, but I'd feel like using 409 at least for
23503	foreign_key_violation
23505	unique_violation
