### ISSUE TITLE
Select safer default value for jwt-secret

### ISSUE THREAD

**Issue by eric-brechemier** [begriffs/postgrest#473]
I suggest to use a secret made of random bytes, [with a length of 512 bits](http://stackoverflow.com/a/30520284), similar to the output of the command `openssl rand 512`.

This would make it suitable for development and deployment on a single server, unlike the current default of `'secret'`.

**Comment by joaoportela** [comment]
Do you mean changing the default constant that is in the source code?

What would be the benefits of doing this?

**Comment by eric-brechemier** [comment]
> Do you mean changing the default constant that is in the source code?

Yes.

> What would be the benefits of doing this?

The default secret is not suitable for production. Anyone can encode a JWT Token using 'secret' and pretend that they have a different role, e.g. 'postgres', and the `postgrest` server will accept to change to the requested role.

**Comment by joaoportela** [comment]
> The default secret is not suitable for production.

But a constant is never suitable for production. Event it is random bytes. The user needs to generate it, right?

**Comment by begriffs** [comment]
How about generating a new random value every time postgrest starts?

**Comment by joaoportela** [comment]
@begriffs That sounds reasonable. How would the "user" know generated jwt-secret?

**Comment by eric-brechemier** [comment]
> How about generating a new random value every time postgrest starts?

I now realize it was not explicit, but that's exactly what I had in mind.

> How would the "user" know generated jwt-secret?

1. noone knows the secret (that's a feature)
2. it is written into a file when postgrest starts (in which case you need to specify the path to the file, and thus you could have provided a file yourself)

**Comment by joaoportela** [comment]
@eric-brechemier I'm sorry, I'm not familiar with JWT terminology, hence the confusion.

(Hopefully) using the correct terminology:

First of, I assume we are talking about symmetric jwt-keys, is this correct?

How does the issuer access the jwt-secret to generate new tokens? <- This is what I was trying to ask before.

In this scenario postgrest is the consumer, right?

**Comment by ruslantalpa** [comment]
He probably means the case where pg is the consumer and also the producer (rpc returning a special type in which case pg encrypts it) 
The problem is that this is at most usefull in development. In production you probably want a more complicated producer, so you need to know the secret. Also, a restart of the server (schema change:) will invalidate all current tokens.
I dons see a problem with how things are currently working (and even less when there is support for config file)

**Comment by joaoportela** [comment]
@ruslantalpa I'm inclined to agree with you.

It seems that you wouldn't use this in production anyway and in development you would have a ton more work and you don't care that much about the security.

**Comment by eric-brechemier** [comment]
@joaoportela sorry for the confusion, I am expanding a bit to clarify:

> How would the "user" know generated jwt-secret?

I see two possibilities

* `postgrest` does not provide a mean for the "user" to know the generated jwt-secret. This is a possibility because `postgrest` server can be the only one to encrypt and decrypt JSON tokens using the secret. I think this would be a cool feature actually, that noone can know the secret easily, without somehow accessing the volatile memory of the `postgrest` server.

* alternatively, `postgrest` server could write the generated secret into a file. However, the path to the file must be known, i.e. hard-coded or configured through a command line parameter. In this case, why would you provide a path to write the secret rather than the path to a file to read the secret from? This is not much of an improvement.

**Comment by eric-brechemier** [comment]
@ruslantalpa 

> The problem is that this is at most usefull in development. In production you probably want a more complicated producer, so you need to know the secret. (...)
> I dons see a problem with how things are currently working (and even less when there is support for config file)

I agree with you, but I think that you are missing the point. The default value cannot be configured through a config file.

I would like to draw your attention on the risk that `postgrest` may be deployed in production with the default secret, which is very unsafe.

@joaoportela 

> It seems that you wouldn't use this in production anyway and in development you would have a ton more work and you don't care that much about the security.

I am actually afraid that most people do not care much about the security in general, and may just consider the default as a valid option, even for production.

**Comment by ruslantalpa** [comment]
we are not talking about average users here, they are devs building apps and it's their job to care about security  (changing the default password of a new install), the app user trusts them to. On startup the binary issues a warning if the secret is the default value and if they care so less about the security of their system and ignore that warning (and don't bother to read the docs) ... they deserve to be hacked :)

**Comment by ruslantalpa** [comment]
And if the dev cant be trusted to change a default value, imagine the mess he will create with db role permissions

**Comment by joaoportela** [comment]
@eric-brechemier 
Yeah. My terminology in that question was all wrong, I'm sorry about that.

> postgrest does not provide a mean for the "user" to know the generated jwt-secret. This is a possibility because postgrest server can be the only one to encrypt and decrypt JSON tokens using the secret. I think this would be a cool feature actually, that noone can know the secret easily, without somehow accessing the volatile memory of the postgrest server.

I didn't know that `postgrest` could be both the issuer and the consumer of a jwt-token, I thought that it was only the consumer (did I understand correctly what you're referring to?); this may change my view on things a bit.

> alternatively, postgrest server could write the generated secret into a file. However, the path to the file must be known, i.e. hard-coded or configured through a command line parameter. In this case, why would you provide a path to write the secret rather than the path to a file to read the secret from? This is not much of an improvement.

I agree with you on this. In production, you don't want to restart the issuer every time that you restart postgrest and in development this is just annoying.

**Comment by eric-brechemier** [comment]
> On startup the binary issues a warning if the secret is the default value and if they care so less about the security of their system and ignore that warning (and don't bother to read the docs) ... they deserve to be hacked :)

That's a bit harsh. In this case the current warning should at least be improved:

> WARNING, running in insecure mode, JWT secret is the default value

It does not give any hint on how to solve the issue (or choose a safe secret, for that matter)

**Comment by joaoportela** [comment]
> I am actually afraid that most people do not care much about the security in general, and may just consider the default as a valid option, even for production.

This is a very valid point. 

> we are not talking about average users here, they are devs building apps and it's their job to care about security (changing the default password of a new install), the app user trusts them to. On startup the binary issues a warning if the secret is the default value and if they care so less about the security of their system and ignore that warning (and don't bother to read the docs) ... they deserve to be hacked :)

Even good developers can make mistakes, people get tired and have to think about a lot stuff at the same time a minor lapse can turn into a major security issue.

The warning helps, but a something that just avoids mistakes altogether is better.

**Comment by eric-brechemier** [comment]
@joaoportela 

> I didn't know that postgrest could be both the issuer and the consumer of a jwt-token, I thought that it was only the consumer (did I understand correctly what you're referring to?); this may change my view on things a bit.

Yes, I have just deployed an API using `postgrest` alone for the authentication. It is not exactly simple, but there is not much code needed :) As noted by @ruslantalpa

> And if the dev cant be trusted to change a default value, imagine the mess he will create with db role permissions

that's where the complexity lies.

**Comment by begriffs** [comment]
A known default secret like `secret` allows attackers to set any role they like (as long as the authenticator role has permission to switch into it). It's bad when default behavior creates a security hole.

When a secret is not specified to postgrest on the command line I propose we do one of these things:

1. Disable accepting JWT auth or
2. Pick a randomized value

The first option is educational because we could show a helpful error message if someone tries to send an Authorization header. It would explain that the administrator needs to choose a JWT secret and how to do so.

The second option is handy for when postgrest produces and consumes its own tokens. However I'm starting to see problems with it. What if you have to restart postgrest and there are active API users with tokens? Their tokens will be confusingly invalidated. Also if you're load balancing then a token produced by one postgrest will not be consumable by another. Generating random secrets postpones users' understanding of how auth works. It works in only the simplest case and then causes confusion.

So my preference is using a default value of empty string for the JWT secret and failing with an error message in this case if the client tries to authenticate.

**Comment by eric-brechemier** [comment]
> So my preference is using a default value of empty string for the JWT secret and failing with an error message in this case if the client tries to authenticate.

I'm fine with that.

> What if you have to restart postgrest and there are active API users with tokens? Their tokens will be confusingly invalidated.

Agreed.

**Comment by joaoportela** [comment]
> So my preference is using a default value of empty string for the JWT secret and failing with an error message in this case if the client tries to authenticate.

And maybe link to the relevant documentation?

What was proposed by @begriffs seems to solve the most critical issue: avoiding mistakes that lead to an exposed system.

**Comment by begriffs** [comment]
The master branch no longer uses a default JWT secret. If you start postgrest without a secret and somebody tries to authenticate with JWT then they get a server error about the missing configuration.

**Comment by eric-brechemier** [comment]
Excellent.
