### ISSUE TITLE
Support for Postgres 9.5 INSERT ... ON CONFLICT DO UPDATE ... a.k.a "upsert"

### ISSUE THREAD

**Issue by sscarduzio** [begriffs/postgrest#482]
It would be nice if the upsert semantics would be implicitly present in every insert.
As pointed out by @begriffs in #256, the `Prefer` header would be spot on for this.

I imagine something along these lines would change the default behaviour:

```
Prefer: resolution=ignore-duplicates
```

**Comment by begriffs** [comment]
If that prefer header is set then we can modify the sql. My only question is how to handle postgresql <9.5.  I guess it will just create an error which will be shown to the client so maybe there is nothing special we need to do.

**Comment by sscarduzio** [comment]
How about giving a 412?

**412 Precondition Failed**
*The precondition given in one or more of the request-header fields evaluated to false when it was tested on the server. This response code allows the client to place preconditions on the current resource metainformation (header field data) and thus prevent the requested method from being applied to a resource other than the one intended.*

**Comment by begriffs** [comment]
@sscarduzio cool idea for the status code.

Let's move the discussion back to #256 to keep it in one place.
