### ISSUE TITLE
Default order direction is documented wrong & not explicitly tested for

### ISSUE THREAD

**Issue by motiz88** [begriffs/postgrest#484]
The documentation [here](https://github.com/begriffs/postgrest/wiki/Routing#ordering) and on [postgrest.com](http://postgrest.com/api/reading/#ordering) states that `?order=col` will default to sorting in descending order. In fact, there is a [tangentially related test](https://github.com/begriffs/postgrest/blob/b9fd083c772831106f82c055832cc70f15e2ffbd/test/Feature/RangeSpec.hs#L33) that depends on the _opposite_ (`ASC` default) being true.

Also, there's no test dedicated to this detail either way.

(Aside: Is there a preferred way to submit documentation issues?)

**Comment by begriffs** [comment]
Uh oh, sorry for the inaccurate docs. The pages you see on postgrest.com come from markdown in the `docs/` folder of this repo, for instance https://github.com/begriffs/postgrest/blob/master/docs/api/reading.md

Thanks for pointing out the problem. If you send a pull request to correct this file I'll run the script to deploy your change to the site.
