### ISSUE TITLE
Push element inside an array column

### ISSUE THREAD

**Issue by sscarduzio** [begriffs/postgrest#488]
Given a table with a column of type `character varying[]`, it should be possible to update this value with one more item.

```
PATCH /table/column 
{
 "push_value": "blah"
} 

```
should translate to:

`update table set column = array_append(column, 'blah')`

Similarly for jsonb[] typed columns:

```
PATCH /table/column 
{
 "push_value": {"a": "b"}
} 

```
would translate to:

`update events set speakers = speakers || '{"a":"b"}'::jsonb`

----

We could also support removing items from the arrays with something like:

```
PATCH /table/column 
{
 "pop_value": "blah"
} 

```

**Comment by begriffs** [comment]
Can you explain the use case for string concatenation in more detail?

**Comment by sscarduzio** [comment]
I fixed the character varying[] example, as it does not work with the append syntax. My bad!

**Comment by begriffs** [comment]
If we're going to extend the behavior of PATCH it probably makes sense to choose a well-known patch format, such as RFC6902. Here is how it specifies adding an array element: https://tools.ietf.org/html/rfc6902#page-12

Also how much overhead does it add for you to push an element on the array on the client side and send the whole array back to the server? I know it's not ideal, but if your array is small enough then maybe it'll be OK.

**Comment by elimisteve** [comment]
@begriffs @sscarduzio It appears that there is no way to append to an array via PostgREST, is that correct?  I see #465 and am thinking I should just create my own very simple RPC function that does the array append I desire...

**Comment by mckinlde** [comment]
@elimisteve did you create an rpc?  I am currently trying to append to a bigint[] array and surprised there isn't a function for that.

**Comment by elimisteve** [comment]
@mckinlde I don't recall but yes that's how I would solve this problem if I were you; just make a 1-line function that you call via POST request to `/rpc/your_func_name`.

**Comment by mckinlde** [comment]
@elimisteve Thanks for the reply, after more reading I discovered that passing a parameter to a sql function would open me to an injection attack (input from the client being handled as instructions, rather than my current architecture that only handles input as data), so I've opted to instead use two requests GET/POST and handle appending client side.

If someone else wants to rm my comments as off-topic feel free; I'm uneasy about derailing this thread already as a non-contributing end user of pgrest.

**Comment by elimisteve** [comment]
> after more reading I discovered that passing a parameter to a sql function would open me to an injection attack

@mckinlde Not if your function just appends to a `bigint[]` as described above.

Furthermore, part of the beauty of PostgREST -- if one handles auth correctly (using RLS etc) -- is that PostgREST becomes the database role/user of whoever is making the incoming authenticated request, and thus cannot do anything to the DB that the request-making user doesn't have permission to do. Pretty cool!

**Comment by mckinlde** [comment]
@elimisteve "Not if your function just appends to a bigint[] as described above."
I don't understand--an rpc can take a parameter int and append it without that parameter being vulnerable to a ;?

"using RLS etc"
+1, this capability is one of the main reasons I chose the tool--that said, I struggle with implementation.  Can you refer me to a workbook?  The best resource I have found so far is linked, I'll admit I haven't read it as I'm still full-time on MVP features: https://github.com/steve-chavez/socnet

**Comment by elimisteve** [comment]
@steve-chavez User input is surely escaped, yes? That's what Joe told me at Noisebridge, though he wasn't certain that every corner case was covered IIRC.

Plus user input that's supposed to be an int is parsed inside PostgREST and only used if it's actually an int, I believe; a semicolon can't simply be successfully injected by the user because PostgREST's int parsing would fail.

**Comment by mckinlde** [comment]
> User input is surely escaped

Would this hold for strings as well?  For example, an [rpc/login](https://postgrest.org/en/stable/how-tos/sql-user-management.html#logins)?

How do magnets work?(joke)

**Comment by mckinlde** [comment]
> @steve-chavez User input is surely escaped, yes? That's what Joe told me at Noisebridge, though he wasn't certain that every corner case was covered IIRC.
> 
> Plus user input that's supposed to be an int is parsed inside PostgREST and only used if it's actually an int, I believe; a semicolon can't simply be successfully injected by the user because PostgREST's int parsing would fail.

Would this hold for strings as well? For example, an [rpc/login](https://postgrest.org/en/stable/how-tos/sql-user-management.html#logins)?

How do magnets work?(joke)

**Comment by steve-chavez** [comment]
>  after more reading I discovered that passing a parameter to a sql function would open me to an injection attack

We use prepared statements for all queries, so the above won't happen.

> I don't understand--an rpc can take a parameter int and append it without that parameter being vulnerable to a ;?

That would be invalid input, for the same reason as:

```sql
postgres=> select '1;'::int;
ERROR:  invalid input syntax for type integer: "1;"
LINE 1: select '1;'::int;
```
