### ISSUE TITLE
Updating with empty JSON object generates invalid sql

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#493]
Patching with `{}` should be a 400 Bad Request not a server error.

**Comment by ehamberg** [comment]
Why not a 204? Updating zero fields was requested and zero fields were updated.

**Comment by begriffs** [comment]
Confirming that in v0.4 patching with `{}` still returns 400 with

```json
{
  "hint": null,
  "details": null,
  "code": "42601",
  "message": "syntax error at or near \"RETURNING\""
}
```

The correct response is probably 204 like @ehamberg suggests (or 200 and `[]` if `Prefer: return=representation` was requested).
