### ISSUE TITLE
bigint columns truncated to Javascript limits (52 - 53 bits)

### ISSUE THREAD

**Issue by skabbes** [begriffs/postgrest#498]
For bigint columns in postgres, postgREST returns values like this:

```javascript
[{"bigint_column":8200357849092798618}]
```

Which I suppose is valid JSON, however since Javascript can't represent that value exactly (truncates to 8200357849092798000), it isn't very useful JSON.

What do you think about _always_ returning bigint columns as strings?

**Comment by begriffs** [comment]
The JSON spec doesn't itself limit the size of numbers, and there are alternate JSON parsers for javascript such as [json-bigint](https://www.npmjs.com/package/json-bigint).

If you don't want to use an alternate parser you can change the types in postgrest's results yourself with the `select` query param:

```
GET /foo?select=*,bigint_column::text
```

Let me know if this works for you.

**Comment by skabbes** [comment]
While I agree with you, it seems that a goal of postgrest is to provide an API that is consumable by web clients (it has premissive CORS, for example).  I would argue that even though the JSON spec itself is language agnostic, Javascript is the defacto JSON standard.

I respect that postgrest focuses so much on purity, but this seems like a major usability flaw that can be easily addressed.  I am crying a little bit on the inside for all those people who are currently using bigint primary key autoincrementing who simply haven't hit this bug yet (as they remain under 52 bits), but will one day unknowingly.

Either way, your choice as maintainer, and thanks for the fix suggestion.

**Comment by begriffs** [comment]
Oh I forgot to mention, you could try using the `uuid` type as well for primary keys. These will be long strings which you can [generate](http://www.postgresql.org/docs/9.5/static/uuid-ossp.html) with postgresql functions.

**Comment by skabbes** [comment]
To close the loop here, I ended up adapting the recursive decent [json2 parser](https://github.com/douglascrockford/JSON-js) to at least prevent the information loss of bigint -> JS double.

With respect to UUID, I don't think I can afford the size hit on my indexes unfortunately.  Need to put my memory to good use.

For anyone reading in the future who is curious why I am hitting this problem:
I'm actually using a variant of [pseudo_encrypt](https://wiki.postgresql.org/wiki/Pseudo_encrypt) on 64 bit numbers so I can get all the benefits of autoincrementing sequences without the information leak that usually comes with them.  Not to mention eliminating an entire class of bugs where developers assume primary keys imply time-ordering.

Thanks again for all the help, this is an awesome project.

**Comment by emsi** [comment]
> If you don't want to use an alternate parser you can change the types in postgrest's results yourself with the `select` query param:
> 
> ```
> GET /foo?select=*,bigint_column::text
> ```

@begriffs It would be grate to have a global configuration option to turn on such conversion for all big int type fields.

**Comment by begriffs** [comment]
Mariusz Woloszyn wrote:
> > If you don't want to use an alternate parser you can change the
> > types in postgrest's results yourself with the `select` query param:
> > 
> > ```
> > GET /foo?select=*,bigint_column::text
> > ```
> 
> @begriffs It would be grate to have a global configuration option to
> turn on such conversion for all big int type fields. 

Given the JSON standard (RFC 8259) guarantees that only numbers in the
range [-(2**53)+1, (2**53)-1] will be representable on all
implementations, I think it's incorrect of PostgREST to return bigint as
a plain number in JSON.

https://datatracker.ietf.org/doc/html/rfc8259#section-6

Your suggestions of a config var sounds sensible to change the behavior.
The next major version of PostgREST could make a breaking change of
using text by default for encoding bigint in JSON output.

I'm not involved in the day-to-day coding of this project anymore, but
just weighing in because you tagged me in the message. :)

**Comment by wolfgangwalther** [comment]
> Given the JSON standard (RFC 8259) guarantees that only numbers in the range [-(2**53)+1, (2**53)-1] will be representable on all implementations, I think it's incorrect of PostgREST to return bigint as a plain number in JSON.

I don't think this should be taken as a PostgREST issue at all. PostgreSQL is doing the json conversion and we are just exposing it via REST. If this was considered wrong, it should be fixed in PostgreSQL.

**Comment by emsi** [comment]
> > Given the JSON standard (RFC 8259) guarantees that only numbers in the range [-(2**53)+1, (2**53)-1] will be representable on all implementations, I think it's incorrect of PostgREST to return bigint as a plain number in JSON.
> 
> I don't think this should be taken as a PostgREST issue at all. PostgreSQL is doing the json conversion and we are just exposing it via REST. If this was considered wrong, it should be fixed in PostgreSQL.

The conversion from bigint to json is clearly wrong as it does not conform to JSON standard.
