### ISSUE TITLE
postgREST does not return exp field in jwt token

### ISSUE THREAD

**Issue by bobcolner** [begriffs/postgrest#500]
Creating new issue for better visibility.

I have updated the login function from blog user-management example to include an `exp` token expiration field. I'm useing postgREST version 3.0.4

```
create type basic_auth.jwt_claims AS (role text, email text, exp integer);

create or replace function
login(email text, pass text) returns basic_auth.jwt_claims
  language plpgsql
  as $$
declare
  _role name;
  result basic_auth.jwt_claims;
begin
  select basic_auth.user_role(email, pass) into _role;
  if _role is null then
    raise invalid_password using message = 'invalid user or password';
  end if;
  -- TODO; check verified flag if you care whether users
  -- have validated their emails
  select _role as role, login.email as email,
         (round(extract(epoch from now()))+5*60)::int as exp
         into result;
  return result;
end;
$$;
```
I can confirm that the new psql login function returns an jwt_claims type with the exp integer field added. However, the actual jwt token returned by the postgrest login endpoint does not include the exp field, only email and role. As a result my token is effectively valid forever.

Perhaps I missing something obvious?

**Comment by begriffs** [comment]
I'm wondering if you have two functions named `login` (perhaps in different schemas) and that your web client is continuing to call the old one through postgrest. Can you share the command line arguments you used to start postgrest? Also you've verified that calling the function directly in psql returns the record you expect?

**Comment by bobcolner** [comment]
Only one login function in my DB. Also, I can confirm that the login function does return the enriched jwt_type (email, role, exp) tuple. 

When I call the /login API endpoint I get a JWT that decodes to only {email, role} ;(

Sounds like this is working for others so I may have some issue in my setup. I can try to create simple script to recreate.

**Comment by NikolayS** [comment]
+1 here. Encountered with it trying to pass `iat` ("issued at") value in JWT payload.

**Comment by NikolayS** [comment]
(and there is another, older issue: #198)

**Comment by ruslantalpa** [comment]
the encode function expects those parts like this https://bitbucket.org/ssaasen/haskell-jwt/src/307893f0c629a854fb2f969a7b55aa08a1a9189d/src/Web/JWT.hs?at=master&fileviewer=file-view-default#JWT.hs-189:214
and we send them like this https://github.com/begriffs/postgrest/blob/master/src/PostgREST/Auth.hs#L80
all in unregisteredClaims

**Comment by ruslantalpa** [comment]
the right way to do it is probably something like
```JSON.decode $ JSON.parse jsonstr``` and it should generate the correct JWTClaimsSet definition

**Comment by bobcolner** [comment]
Thanks for the feedback. A simple example related to the blog.sql example would be of great help.

**Comment by NikolayS** [comment]
There is such example yet, since the problem is inside Haskell code, and PostgREST modification is needed.

While it is not fixed yet, you can rename your `exp` param to smth that is not reserved word in JWT spec (e.g., `expires`). I had to do the same in my case: `issued_at` instead of `iat`.

**Comment by bobcolner** [comment]
Thanks Nikolay, I can confirm that the /rpc/login API works when using `expires` vs. `exp`.
```
{
  "email": "al.green@gmail.com",
  "expires": 1456101018,
  "role": "author"
}
```
My understanding is that for PostgREST to able to reject expired tokens either 1) the haskell JWT library would need to be updated to validate the `exp` field. Or 2), the PostgREST itself could be modified to check for token expiration but would need to use a non-standard key aka. `expiries`. 

Could this be as simple as changing this line?: https://github.com/begriffs/postgrest/blob/master/src/PostgREST/Auth.hs#L57

At a high level I think postgRest is a great tool that is very close to delivering on promise or replacing API server layers for small-to-medium projects. I'm no security expert but not having token expiration seems like a show-stopper -lets fix that!

**Comment by ruslantalpa** [comment]
@bobcolner 
Postgrest detects correctly the expired tokens, so if you have a token with exp field it will work.
The problem you are seeing is that postgrest is not able to "generate" those tokens.
So you can generate those tokens somewhere else, everything will work even with the current code.

**Comment by bobcolner** [comment]
Thanks @ruslantalpa, very helpful. It makes sense that Postgrest would expire the token if you have a valid `exp` field to start with.

Indeed, I see a lot of value in have the option of using Postgrest as a standalone secure API server. 

@begriffs and others, what are your thoughts about this use-case?

**Comment by bobcolner** [comment]
bump.

What is the communities thoughts about supporting JWT expiration within PostgRest itself? Perhaps using an non-standard field?

**Comment by Recmo** [comment]
I just ran into this issue using tokens from Auth0, by default the user identifier is stored in `sub`, which is *not* available as `postgrest.claims.sub`.

**Comment by begriffs** [comment]
Looking more at the [JWT library](https://hackage.haskell.org/package/jwt-0.6.0/docs/Web-JWT.html) we use I think I see the solution. Will look into it more tonight.

**Comment by NikolayS** [comment]
Thank you @begriffs
