### ISSUE TITLE
What is the current JWT secret used by a PostgREST server instance?

### ISSUE THREAD

**Issue by eric-brechemier** [begriffs/postgrest#504]
This question is related to the issue #495. Since the binary JWT secret has been corrupted, I would like a way to find what is the actual secret used by the PostgREST instance, in its corrupted form.

**Comment by begriffs** [comment]
I'll look into these jwt problems tomorrow evening or Friday.

**Comment by eric-brechemier** [comment]
Thanks!

**Comment by begriffs** [comment]
You can add a [traceShow](https://hackage.haskell.org/package/base-4.8.2.0/docs/Debug-Trace.html#v:traceShow) in these lines where the secret is read from the command line but before it is stored inside that write-only value called configJwtSecret: https://github.com/begriffs/postgrest/blob/358254639a5d6d15f51a15f59c24630eb4828028/src/PostgREST/Config.hs#L55-L56

**Comment by eric-brechemier** [comment]
OK. Can you break it down for me? I can't see where the assignment to `configJwtSecret` is done.

**Comment by begriffs** [comment]
No problem, I made a branch called [trace-secret](https://github.com/begriffs/postgrest/tree/trace-secret) that displays the secret at startup.

**Comment by eric-brechemier** [comment]
Thanks!

**Comment by eric-brechemier** [comment]
The JWT is printed using escape sequences in a string, but that should do. I assume that I will be able to convert it back to binary when I need to.
