### ISSUE TITLE
Ordering of foreign entities

### ISSUE THREAD

**Issue by ear** [begriffs/postgrest#509]
In [embedding foreign entities](/begriffs/postgrest/blob/master/docs/api/reading.md#embedding-foreign-entities) we learn that we can “ask for a client and all of their projects” with `GET /clients?id=eq.42&select=id,name,projects{*}` .

In [ordering](/begriffs/postgrest/blob/master/docs/api/reading.md#ordering) the url syntax `GET /people?order=age.desc,height.asc` is presented and references only columns from the main entity. It is then extended to `GET /people?order=age.desc.nullslast` suggesting that using the dot to drill down into foreign entities' columns is not going to work.

What is the story for ordering embedded foreign entities? I hope I am not missing something simple.

Thank you.

**Comment by ruslantalpa** [comment]
@ear there is no story, this does not exist yet.

**Comment by ear** [comment]
Not at all? Oh… that is unfortunate. What approach(es) do you take as users currently?

**Comment by ruslantalpa** [comment]
you can always sort them on the client side

**Comment by begriffs** [comment]
@ear let's think how it might work. What syntax do you suggest in the url?

**Comment by ehamberg** [comment]
I would also like to see this. How about `GET /clients?id=eq.42&select=id,name,projects{*}&order=name,projects.name` to order by client name (ascending) and then project name (ascending)?

**Comment by ruslantalpa** [comment]
@ehamberg that's not a good syntax, you need to specify different ordering for different depths.
It's going to be like this (gonna build it soon)
```/clients?id=eq.42&select=id,name,projects{*}&order=name.asc&projects.order=id.desc```

**Comment by ruslantalpa** [comment]
Let's move this to #527 and have one issue for tracking the progress on this feature
