### ISSUE TITLE
lt,gt operator not working properly with timestamp field

### ISSUE THREAD

**Issue by AnishYalmuri** [begriffs/postgrest#510]
In my data base i have a time stamps fields , when i apply lt/gt/lte/gte it will consider only date for comparison where as it should consider time also.

**Comment by begriffs** [comment]
Can you give an example of the url that you're using to make the query?

**Comment by AnishYalmuri** [comment]
http://localhost:3000/flight_reports_images?image_datetime=gte.2013-09-15T 13:00:00&image_datetime=lte.2013-09-16T12:30:00

the output contains the records with image_datetime 2013-09-16T16:00:00 which is not required

**Comment by ruslantalpa** [comment]
@AnishYalmuri 
what is the output of this query?
```
select * from flight_reports_images
where image_datetime >= '2013-09-15T13:00:00'
and image_datetime <= '2013-09-16T12:30:30'
```

This is a simplified version of what postgrest would generate, my bet is that you will see those "16:00" records here too.
Check to see if timezone does not play a role here.

**Comment by AnishYalmuri** [comment]
i couldn't use >= or <= symbol , when i used " ' " around time field its not even considering date part also i am getting all the records as output

**Comment by AnishYalmuri** [comment]
sorry i understood your reply wrongly  .. i will check and let u know.

**Comment by AnishYalmuri** [comment]
I think what you said is correct, some problem with my data.. sorry for the inconvenience .. you can close the issue .. thanks for the quick support.
