### ISSUE TITLE
Execute RPCs only once

### ISSUE THREAD

**Issue by Recmo** [begriffs/postgrest#513]
In the user management example, the request `POST /rpc/signup` with `{ "email": "foo@bar.com", "pass": "foobar" }` fails. The log shows the following:

```
ERROR:  duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (email)=(foo@bar.com) already exists.
CONTEXT:  SQL function "signup" statement 1
STATEMENT:   SELECT
                    (select pg_catalog.count(1)  from "public"."signup"("email":='foo@bar.com'::unknown,"pass":='foobar'::unknown)  c)  as countTotal,
                   pg_catalog.count(t) as countResult,
                   array_to_json(
                     coalesce(array_agg(row_to_json(t)), '{}')
                   )::character varying
                   from (select *  from "public"."signup"("email":='foo@bar.com'::unknown,"pass":='foobar'::unknown)  LIMIT 1000000 OFFSET 0) t 
```

It appears the RPC stored procedure is called twice for one request.

A workarround is to add a `Prefer: count=none` to the request headers.

This is (in a way) a special case of #273. I file it separately because the documentation explicitly mentions that RPCs do not have to be idempotent, but postgrest fails to treat them as such.

**Comment by ssoriche** [comment]
I hate to +1 but I am seeing this exact problem using my signup function as well. I do not have unique constraint on the user ID column (I have a IF EXISTS check instead that I've commented out) and see 2 identical records including the transaction_time() value.

**Comment by begriffs** [comment]
Hm, not good. I'll try to make a failing test to reproduce.

**Comment by ruslantalpa** [comment]
this probably got introduced in 3.1.0 after the range header for rpc endpoints

**Comment by begriffs** [comment]
Yep I bet you're right.

**Comment by pawelniewie** [comment]
Would be great to have this released. I was bumping my head yesterday trying to make it work only to discover that there's a bug :-(

**Comment by begriffs** [comment]
Good call, I just made a release. https://github.com/begriffs/postgrest/releases/tag/v0.3.1.1

**Comment by pawelniewie** [comment]
Thanks @begriffs !
