### ISSUE TITLE
Allow record syntax within arrays

### ISSUE THREAD

**Issue by SebAlbert** [begriffs/postgrest#517]
Hi,

I really like the possibilities given rise to by the @> and <@ operators. However, as I'm trying to test for composite elements within arrays, e.g., a view with a field mycol of type ROW(int, int)[], I get the following error from PostgREST when requesting, e.g., the parameter with query string

mycol=@>.{(16800,16801)}

{"hint":null,"details":"Unexpected end of input.","code":"22P02","message": "malformed record literal: \"(16000\""}

I would guess you are simply splitting the value of everything between @>.{ and } by ,
If I'm correct, then could we parse this a bit better to keep commas within record parentheses intact?

Sebastian

**Comment by ruslantalpa** [comment]
i think your condition translates to
```
mycol @> '{(16800,16801)}'::unknown
```
try enabling the query logging and check the generated query and post it here then we can talk options

**Comment by SebAlbert** [comment]
You are absolutely right, that's exactly the result in the query, so this is not a parsing error on the PostgREST side in the first place, because this query doesn't work in PostgreSQL directly.

I just got it working after playing around a bit with the query, so the correct form to use this would be mycol=@>.{"(16800,16801)"}

which translates to
mycol @> '{"(16800,16801)"}'

So it was merely lack of experience with text representations on my side. Thank you!
