### ISSUE TITLE
Support RETURNING functionality on DELETE queries

### ISSUE THREAD

**Issue by nathan-rice** [begriffs/postgrest#518]
I'm working on a client side cache/data store front-end to sit in front of postgrest, and this functionality would save me a lot of trouble in terms of cache invalidation logic.

The prefer: return=representation header with a select request arg (like insertion) would be fine in my opinion.

**Comment by ruslantalpa** [comment]
Could you provide more context please about how having the information you just deleted helps you in implementing cache?

**Comment by nathan-rice** [comment]
Specifically, if I want to intelligently invalidate the data cache after a delete query, without being able to see specifically what was deleted, I have to re-implement the selection logic in the client, and basically duplicate the delete query locally.  This isn't a big deal if the predicate matched was "IN" but this blows up with full text search, for instance.  In that case I would have to query the table again just for ids, but that requires special case code, and that query is more expensive on the server side than just returning matched ids from the delete query, not to mention requiring another client round trip. 

By getting a list of ids that matched a delete query in the response, I can use the same logic to flush deleted entries from the cache regardless of what predicates were used.

**Comment by ruslantalpa** [comment]
I was thinking you were deleting records one by one which is usually the case hanse my confusion related to this feature.
The good news is that DELETE (like INSERT/UPDATE) supports RETURNING (which is the base for implementing &select for mutate queries), so this is possible.

**Comment by ruslantalpa** [comment]
i think this has been implemented (&select works on delete also) and can be closed

**Comment by begriffs** [comment]
Doesn't look like there is regression test yet for this feature, we should add one before closing. https://github.com/begriffs/postgrest/blob/master/test/Feature/DeleteSpec.hs
