### ISSUE TITLE
GET with Self Joins Error

### ISSUE THREAD

**Issue by coach1001** [begriffs/postgrest#519]
http://localhost:3000/organisations?select=*,referee{*},auditor{*}

{"hint":null,"details":null,"code":"42712","message":"table name \"organisations\" specified more than once"}

Column 'referee' and 'auditor' are self joins to the organisations table

**Comment by coach1001** [comment]
I do realise having  a response organisation object of  

{
 'id': '2',
 'orgName' : 'Acme',
 'referee' : '5',
 organisations : { 'id':5, 'orgName':'Acme Referee'},
 'auditor' : '6',
 organisations : { 'id':6, 'orgName':'Acme Auditor'} 
}

is impossible because of the the repetition of organisation but is it possible to have the nested objects prefixed by the foreign key column

eg.

{
 'id': '2',
 'orgName' : 'Acme',
 'referee' : '5',
 referee_organisations : { 'id':5, 'orgName':'Acme Referee'},
 'auditor' : '6',
 auditor_organisations : { 'id':6, 'orgName':'Acme Auditor'} 
}

**Comment by ruslantalpa** [comment]
@coach1001 your bet bet is to create a view that does the joining the way you like it then use that as an endpoint
the embedding feature is not designed/intended to do all the joins you would do in sql, it's only for including entities from other tables that are referenced using foreign key constraints.

**Comment by ruslantalpa** [comment]
Since there are no table definitions here it's hard to say what exactly is going on, but if its a case of a table having two columns which are FK's to the same table, it's possible to embed both rows by specifying the fk column instead of the table name.

**Comment by steve-chavez** [comment]
This is related to #987. I added [tests](https://github.com/steve-chavez/postgrest/blob/self-reference-fks/test/Feature/QuerySpec.hs#L457-L500) in #1054 to make sure the two self reference foreign keys embed use case works.
