### ISSUE TITLE
GET Error Deep Nested Entities with only column Names

### ISSUE THREAD

**Issue by coach1001** [begriffs/postgrest#520]
I have 3 tables (programme,kras,kpis) 

Relationships are as follows
programme -> kras.programme -> kpis.kra

The following get request works (deep nest with foreign table names):
http://localhost:3000/kpis?select=*,kras{*,programmes{*}}

and this get works (single nest with column name)
http://localhost:3000/kpis?select=*,kra{*}

this however does not (deep nest with column names)
http://localhost:3000/kpis?select=*,kra{*,programme{*}}

**Comment by ruslantalpa** [comment]
Please provide the full table definitions, the requests you are making (that is already present), the generated query (turn on query logging in postgresql) and the error you get for the request that is failing then we can build on that...

**Comment by begriffs** [comment]
@coach1001 have you figured out this problem, or still having trouble?

**Comment by ruslantalpa** [comment]
No reply for a long time, since then, however, a few bugs were fixed since then.
PS: try to avoid `*` always specify the full list of columns and try to always include the `id` of rows because of #411 bug
