### ISSUE TITLE
Postgrest deployment

### ISSUE THREAD

**Issue by loama** [begriffs/postgrest#531]
I am having many issues with the deployment of postgrest. (ubuntu 14.04, amazon EC2, postgres database over ssh tunel)
Surely it is because of my inexpertise using the ubuntu console but it would be really great to make a good tutorial on how to deploy, I see that the documentation have a deployment part which is still in work.

If someone helps me understand how to deploy it I would be really grateful and also would be glad to make a pull request with a tutorial.

Thanks

**Comment by begriffs** [comment]
I agree the docs are missing for this. Thanks for offering to help!

Can you tell me more about what you've tried and the errors you encountered?

**Comment by loama** [comment]
Great! thanks for answering that fast.

Well I´ll start describing my problem.

In localhost it is already working fine.
Installed postgrest with brew.
I set up a ssh tunnel with "ssh -L 5433:DBHOST:5432 -i DBKEY.pem DBUSER@SSHHOST"
And then run "postgrest postgres://postgres:DBPASS@localhost:5433/DBNAME -a postgres"
Everything good so far when I do postman or browser requests.

Then in my server (with apache installed) I try to do the same:

- Open terminal
- Make ssh connection to my server with "ssh USER@HOSTIP -i KEY.pem"
- Go to default apache folder var/www/html
- Install postgrest getting the tar and uncompressing it.
- Run "./postgrest postgres://postgres:DBPASS@localhost:5433/DBNAME -a postgres"
- It says "WARNING, running in insecure mode, JWT secret is the default value
 Listening on port 3000"

But when I try to access http://SERVERIP:3000 it does not give me any response.

I know the ssh tunnel is working ok because I am already using it for other parts.
I know postgrest is installed ok because it runs the process and gives me the help in console.
But I am no so sure about the last command I am running because I can change the password or the host and get the same response.

Also I think that I should be changing something in order to make it possible to see from any IP.

**Comment by begriffs** [comment]
I suspect your server allows only certain ports to be accessed from the outside.

Maybe you can get Apache to forward an open port on the outside to 3000 on the inside. What does your http.conf file look like? (here's [how to find it](http://www.commanigy.com/blog/2011/6/8/finding-apache-configuration-file-httpd-conf-location))

**Comment by loama** [comment]
I have started checking the .conf file and already (think that) have opened the port 8000
But then, when I run `./postgrest ...` it gives back

`postgrest: bind: resource busy (Address already in use)`

**Comment by begriffs** [comment]
What if you run postgrest on port 3000 and then forward port 8000 to it?

```
<VirtualHost *:8000> 
  ProxyPreserveHost On
  ProxyRequests Off
  ServerName www.example.com
  ServerAlias example.com
  ProxyPass / http://localhost:3000/
  ProxyPassReverse / http://localhost:3000/
</VirtualHost> 
```

**Comment by begriffs** [comment]
@loama did this Apache configuration work for you?

**Comment by umeshduggal** [comment]
@begriffs It will be help full if you provide some tutorial or document for deploying postgrest on ubuntu 14.04, amazon EC2, postgres database, nginx webserver in production environment.

Thanks,.

**Comment by begriffs** [comment]
Moving this issue to the new postgrest-docs repo.

**Comment by begriffs** [comment]
@loama we now have a section in the docs about configuring and running the server, care to check it out and tell me what you think? http://postgrest.com/en/v0.4/admin.html
