### ISSUE TITLE
Can't get Filtering Columns working

### ISSUE THREAD

**Issue by ratmcarlo** [begriffs/postgrest#532]
I can't get the select keyword working, still getting:

```
[~] GET /items_item?select=title
{"hint":null,"details":null,"code":"42P01","message":"relation \"public.items_item?select=title\" does not exist"}
```

**Comment by motiz88** [comment]
What postgrest version are you on?

**Comment by ratmcarlo** [comment]
```
django_pgrest=# select version();
                                      version
-----------------------------------------------------------------------------------
 PostgreSQL 9.4.5 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 5.2.0, 64-bit
(1 row)
```

**Comment by motiz88** [comment]
That's okay, what about PostgREST though? What version are you trying to use? The `?select` feature was added in [0.2.12.0](https://github.com/begriffs/postgrest/blob/01355f39a1a7321059a62c0b3cc9d7b85d9b316a/CHANGELOG.md#02120---2015-10-25).

**Comment by ratmcarlo** [comment]
I am using PostgREST 0.3.0.3

What else could I try to debug this ? Thank you

**Comment by motiz88** [comment]
I managed to reproduce the error message by requesting `/items_item%3Fselect=title`, which is the wrong URL (the `?` should not be affected in this case). So my guess is that your client is applying URL-encoding at the wrong stage for some reason.

**Comment by ratmcarlo** [comment]
I confirm that this is a client problem.
Using plain curl is working.

Not a PostgREST issue at all.
Closing this. Thank you.
