### ISSUE TITLE
leaking data via error messages

### ISSUE THREAD

**Issue by daurnimator** [begriffs/postgrest#541]
I noticed this yesterday in an some work similar to the "users" example.

```
$ curl -s -H "content-type: application/json" localhost:3000/rpc/new_user -d '{"email":"foo","pass":"bar","name":"foobar"}'   | json_pp
{
   "details" : "Failing row contains (3, anon, foo, $2a$06$cLwIOknnrG7bOOX/NwUDzOXSqig5/A0XXbBOEsMYVd0GznIbAuiMS, foobar, null).",
   "message" : "new row for relation \"users\" violates check constraint \"users_email_check\"",
   "code" : "23514",
   "hint" : null
}
```

Is leaking the hash like this expected?
Additionally, that first arg (`3`) is actually something I consider private (it's generated by a DEFAULT statement by the underlying table).

It seems like we possibly shouldn't return postgresql error messages as is?

**Comment by begriffs** [comment]
That's not good, I wonder how we should selectively disable errors from being sent to the client? Usually the errors are helpful and should be allowed through.

Also in this case how serious is the leak? The user themselves just supplied the plaintext version of the password, and each row uses its own bcrypt salt so it's not revealing a table-wide salt. It *is* revealing that the server is using bcrypt with a cost factor of `06`.

What is this value `3` all about and what does it disclose? If it's an id an auto-incrementing series you could consider using uuids instead so that the number doesn't tell people anything about how many users their are total.

**Comment by daurnimator** [comment]
> That's not good, I wonder how we should selectively disable errors from being sent to the client? Usually the errors are helpful and should be allowed through.

I'm wondering if this should be a postgres issue: it means someone can get insight into a schema/table they don't normally have access to.

> What is this value 3 all about and what does it disclose? If it's an id an auto-incrementing series you could consider using uuids instead so that the number doesn't tell people anything about how many users their are total.

In this case it's it's auto-incrementing => I don't have it exposed publicly though (e.g. the public.users view doesn't have the 'id' column).
But in other cases I will have more private things (e.g. what we consider the user's reputation; or private notes)

**Comment by begriffs** [comment]
One thing you could try is have your stored proc catch postgres exceptions and throw its own sanitized error instead.

For the UUIDs, I think `gen_random_uuid()` from pgcrypto is pretty standard but I don't really know how it behaves.

**Comment by daurnimator** [comment]
> One thing you could try is have your stored proc catch postgres exceptions and throw its own sanitized error instead.

Yeah I was considering this; but then realised it'll probably pop it's head up elsewhere (and also everyone else!)

> For the UUIDs, I think gen_random_uuid() from pgcrypto is pretty standard

It is for generating uuids (and v4 uuids are best.... except when using them as a primary key, as it kills insert performance)

**Comment by ruslantalpa** [comment]
The first thing to test is if this type of error is possible in a table/view for which a user has only access to a few columns, i.e. will it leak the data in default/private columns, my guess is no.
If it is true (error on tables do not leak) then i don't see a problem here, logic being, if you gave the user access to this RPC, you gave access to anything it can potentially touch and if that data is sensitive, the RPC is responsible for handling it (sanitise errors in this case).
If the usual operations on tables can leak data like the example above then we indeed have a problem.

**Comment by ruslantalpa** [comment]
In some other unrelated discussion, it was decided to output errors from the db as is and have the proxy hide the sensitive data. Coupled with the fact that this particular example does not leak anything except the hash of the pass that the user submitted themselves i think this can be closed.

**Comment by daurnimator** [comment]
> Coupled with the fact that this particular example does not leak anything except the hash of the pass that the user submitted themselves i think this can be closed.

The leak here is the autoincremented id; not the hashed password.

**Comment by ruslantalpa** [comment]
You are right about that, but still, i would not consider this a leak since this is information to which you granted access to that particular role (by granting access to the RPC and RPC leaking that column data).
If you consider this a leak then still, the source/culprit is the PostgreSQL and not PostgREST

**Comment by ruslantalpa** [comment]
I don't see a clear way of how to fix this in PostgREST in a general way for everybody.
The best suggestion, for now, is to have a proxy in front (openresty) and to sanitize the error response.

**Comment by bombillazo** [comment]
Any way to config the errors to return an empty string for certain roles? We want to disable a role from accessing the schemas but using them via the API still leaks schema details via error and hints

**Comment by steve-chavez** [comment]
Related https://github.com/PostgREST/postgrest/issues/2706
