### ISSUE TITLE
Nested jwt_claims

### ISSUE THREAD

**Issue by NotBrianZach** [begriffs/postgrest#550]
is there a way to return extra info along with a jwt? 

For instance, in my login rpc I want to return a display name and a jwt with the email and user role encoded, given an email and password. Tried returning a table with a nested basic_auth.jwt_claims, but postgrest doesn't seem to recognize the jwt_claims and encode it as a jwt unless it's the outermost type in the plpgsql return type.

**Comment by NotBrianZach** [comment]
here's a slice of the pertinent code

create type basic_auth.jwt_claims AS (role name, selected_email text);

-- Finally add a public function people can use to sign up.
-- You can hard code a default db role in it.
-- It alters the underlying basic_auth.users so you can set whatever role you want without restriction.
create or replace function
register(display_name text, email text, pass text) returns basic_auth.jwt_claims
language plpgsql
as $$
declare
  result basic_auth.jwt_claims;
begin
  insert into basic_auth.users (display_name, email, pass, role) values
  (register.display_name::text, register.email::text, register.pass::text, 'customer')
  returning
  basic_auth.users.role,
  register.email as selected_email into result;

  return result;
end;
$$;


create or replace function
get_login_token(email text, pass text) returns basic_auth.jwt_claims
language plpgsql
as $$
declare
  _role name;
  result basic_auth.jwt_claims;
begin
  select basic_auth.user_role(email, pass) into _role;
  if _role is null then
    raise invalid_password using message = 'invalid user or password';
  end if;
  select _role as role,
  get_login_token.email as selected_email into result;
  return result;
end;
$$;

CREATE TYPE login_auth_type as (token basic_auth.jwt_claims, display_name text);

-- And now the login function:
create or replace function
login(email text, pass text) returns table (token basic_auth.jwt_claims, display_name text)
  language plpgsql
  as $$
declare
  token basic_auth.jwt_claims;
  result login_auth_type;
  _display_name text;
begin
  select display_name from basic_auth.users where basic_auth.users.email=login.email into _display_name;
  -- TODO; check verified flag if you care whether users
  -- have validated their emails
  select get_login_token(login.email, login.pass) into token;
  select token, _display_name as display_name into result;
  return result;
end;
$$;

and output:

bash-3.2$ POST /rpc/register '{  "display_name": "bobby", "email": "abc@gmail.com", "pass" : "abc123" }'
{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZWxlY3RlZF9lbWFpbCI6ImRhcmtsb3JkdmFkZXJtb3J0QGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciJ9.PCeh2zZxwx00gl6zVcn7ozfmAwN4sptPKxsyWifIByo"}
bash-3.2$ POST /rpc/login '{  "email": "abc@gmail.com", "pass" : "abc123" }'
[{"display_name":"bobby","token":{"selected_email":null,"role":"(customer,abc@gmail.com)"}}]

**Comment by ruslantalpa** [comment]
@NotBrianZach can you edit your last comment and format the code? it's very hard to read

**Comment by begriffs** [comment]
@NotBrianZach not sure if you're still interested in resolving this issue, but here's the way it works. If you make a custom type whose name ends in `jwt_claims` such as `foo_jwt_claims` then postgrest will turn the row to JSON and then sign it as JWT.
