### ISSUE TITLE
Cannot order with "nullsfirst" without explicitly specifying an ascending order

### ISSUE THREAD

**Issue by xDAGRONx** [begriffs/postgrest#552]
In the docs for reading from the API, you have the example `GET /people?order=age.nullsfirst`. When I try to do this, I still get nulls last:

    CREATE TABLE foo (num integer)
    INSERT INTO foo values (1), (5), (2), (NULL), (6)

    GET "/foo?order=num.nullsfirst"
    "[{\"num\":1},{\"num\":2},{\"num\":5},{\"num\":6},{\"num\":null}]"

However, if I change the query to explicitly order ascending, I get the correct response:

    GET "/foo?order=num.asc.nullsfirst"
    "[{\"num\":null},{\"num\":1},{\"num\":2},{\"num\":5},{\"num\":6}]"

**Comment by begriffs** [comment]
Good catch. Would you suggest just updating the docs, or allowing nullsfirst without asc or desc?

**Comment by xDAGRONx** [comment]
If it's not too much work, I would allow nullfirst without asc or desc since you don't have to specify the order to use NULLS FIRST in Postgres.
