### ISSUE TITLE
row-level security problem in the example from documentation

### ISSUE THREAD

**Issue by michalskop** [begriffs/postgrest#554]
I implemented the row-level security as described here http://postgrest.com/examples/blog/ (with some changes in my case, but I "translated" the following examples into the documentation example). It works ok for a post with id=1 and author author@example.com if sending:

```
PATCH /posts?id=eq.1
```

with data

```
{"title": "new title"}
```

(it updates)

And it also works ok for another registered author hacker@example.com:

```
PATCH /posts?id=eq.1
```

with data

```
{"title": "hacking"}
```

(it does not updates)

However, it does not work correctly if the other registered author hacker@example.com requests

```
PATCH /posts?id=eq.1
```

with data 

```
{"title": "hacking", "author": "hacker@example.com"}
```

as it updates the post and changes its author to hacker@example.com

Using postgrest/0.3.1.1

**Comment by begriffs** [comment]
😱 Crap. We need a way to tell it to check the original value of `author` against `basic_auth.current_email()` and not whatever value of `author` was just passed in. I'm new to row-level security actually so we'll have to look into it. There's a way with triggers to reject inappropriate changes, but I'd like to be able to use RLS if we can.

**Comment by begriffs** [comment]
I merged the changes by @opensrcken and deployed the docs. Can you check whether it fixes the security hole you discovered?

**Comment by spinus** [comment]
@michalskop did you check that by any chance?
@begriffs  is it still the case in 0.4.0.0?

**Comment by begriffs** [comment]
The auth docs have been stripped down in 0.4. Want to check for me whether you see the problem in https://postgrest.readthedocs.io/en/v0.4/auth.html#sql-user-management ?

**Comment by begriffs** [comment]
Closing this. If you notice that the docs for 0.4 suggest anything insecure please open an issue on the [docs repo](https://github.com/begriffs/postgrest-docs)
