### ISSUE TITLE
postgrest: c_poll: permission denied (Operation not permitted)

### ISSUE THREAD

**Issue by nerfpops** [begriffs/postgrest#557]
I'm running PostgREST in docker (jpierre03/postgrest) and after a while the daemon outputs `postgrest: c_poll: permission denied (Operation not permitted)`. Should I be worried?

**Comment by begriffs** [comment]
PostgREST itself doesn't poll that I'm aware of, but maybe there's a low-level aspect of the web server which requires polling.

How frequently does the error message happen, and does the server continue handling requests OK?

@bobcolner @Recmo what do you guys think?

**Comment by begriffs** [comment]
@nerfpops I should also mention that this repo has its own official Dockerfile, so no need to use other repos like jpierre03/postgrest.

**Comment by nerfpops** [comment]
I haven't been able to find this projects Dockerfile on hub.docker.com. Could you create an official Dockerfile? I'm completely new at Docker so maybe there's a better way. The server seems to work and the error is only shown once (haven't been running the server for long though)

**Comment by begriffs** [comment]
Added it here - https://hub.docker.com/r/begriffs/postgrest/

Could you give it a try and see if you still get the error?

**Comment by nerfpops** [comment]
That was quick. I'll leave it running overnight and return with an answer.

**Comment by nerfpops** [comment]
Alright, after two minutes it showed up again. I'll just ignore it.

**Comment by begriffs** [comment]
Can you provide a full log so I can see the error in context?

**Comment by nerfpops** [comment]
The only thing I see is
`Listening on port 3000
postgrest: c_poll: permission denied (Operation not permitted)`

**Comment by begriffs** [comment]
If you don't mind I'm going to reopen this issue as a signal that there is more to learn about it.

**Comment by begriffs** [comment]
Closing this issue because there's another with more information.
