### ISSUE TITLE
Set role and claims not in the correct order

### ISSUE THREAD

**Issue by ruslantalpa** [begriffs/postgrest#559]
When executing a request with JWT, this is what's being executed
```
BEGIN ISOLATION LEVEL READ COMMITTED READ WRITE
set local role 'anonymous';
set local "postgrest.claims.company_id" = '1';set local role 'administrator';set local "postgrest.claims.user_id" = '1';
main query goes here
commit
```

The correct order is
```
BEGIN ISOLATION LEVEL READ COMMITTED READ WRITE
set local role 'administrator';
set local "postgrest.claims.company_id" = '1';set local "postgrest.claims.user_id" = '1';
main query goes here
commit
```

**Comment by begriffs** [comment]
I'd call this an inefficiency rather than a bug since (from my tests in psql) all claims are set properly even when the role is changed in the middle. The inefficient part is setting the role twice. I'll fix this.

**Comment by ruslantalpa** [comment]
It's better to have the certainty of the statement: "the first thing we do is switch to the appropriate role"
