### ISSUE TITLE
Move table structure body out of the OPTIONS

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#56]
Use rel="describedby" link header in the regular get response

https://www.iana.org/assignments/link-relations/link-relations.xml
https://www.mnot.net/blog/2012/10/29/NO_OPTIONS

Also include rel="describes" in the description url link headers.

**Comment by begriffs** [comment]
This information has been moved out of the OPTIONS for individual endpoints and consolidated in the root API description.

**Comment by begriffs** [comment]
Reopening this issue because people have been asking how to find out the primary and foreign keys of a relation in order to do resource embedding, and the openapi description is proving insufficient.

As mentioned above, I'm considering having each endpoint include a [describedby](https://www.mnot.net/blog/2012/10/29/NO_OPTIONS#what-should-i-use-instead) http header link. It would go to another endpoint that provides metadata about the original. Kind of like our old OPTIONS way but without abusing the options verb.

**Comment by ruslantalpa** [comment]
They can create a custom view that describes their schema with all the details they need.
Here is a base query to start from
https://gist.github.com/ruslantalpa/b2f10eb1b5f6dd0fc1c154e071a1c91b

**Comment by steve-chavez** [comment]
As mentioned in https://github.com/begriffs/postgrest/issues/790#issuecomment-381645515 having the users provide their own query is redundant work, the ideas here are worth considering, let's follow this issue on #790.
