### ISSUE TITLE
examples site has 404s, and relative links are making a mess

### ISSUE THREAD

**Issue by paul-hammant** [begriffs/postgrest#563]
http://postgrest.com/examples/examples/users/examples/start/ (etc) is possible if you click around.  Site should use absolute urls in hrefs. 

Also - there's 404s all over the place, so I can't actually see any examples.

**Comment by begriffs** [comment]
I see what you mean. How did you get into that state? When I visit postgrest.com and then go to the examples it seems to work.

**Comment by begriffs** [comment]
I'm going to close this issue rather than investing time in it because I want to switch us to Read The Docs after the 0.4 release. Thank you for reporting it however!
