### ISSUE TITLE
sendWakeup: invalid argument (Bad file descriptor)

### ISSUE THREAD

**Issue by nerfpops** [begriffs/postgrest#566]
Had to restart PostgREST because of this error:

postgrest: c_poll: permission denied (Operation not permitted)
postgrest: sendWakeup: invalid argument (Bad file descriptor)
172.19.0.1 - - [18/Apr/2016:11:11:23 +0000] "GET / HTTP/1.1" 200 - "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
Control.AutoUpdate.mkAutoUpdate: worker thread exited with exception: sendWakeup: invalid argument (Bad file descriptor)
Control.AutoUpdate.mkAutoUpdate: worker thread exited with exception: sendWakeup: invalid argument (Bad file descriptor)
Control.AutoUpdate.mkAutoUpdate: worker thread exited with exception: sendWakeup: invalid argument (Bad file descriptor)

I'm using Docker (begriffs/postgrest)

**Comment by begriffs** [comment]
Looks like issue #557 turned out to be more of a problem then we thought. I'm going to close that other issue because this one has more details.

Approximately how long was postgrest running before this happened?

**Comment by nerfpops** [comment]
Hard to say. I start and stop PostgREST all the time. Less than ½ hour and more than 5 minutes I guess. Haven't experienced this issue before though, but will keep you posted if I see it again.

**Comment by nerfpops** [comment]
Perhaps timestamps in the log would make things easier?

**Comment by begriffs** [comment]
#### Possible causes

* A revival of [this ghc bug](https://ghc.haskell.org/trac/ghc/ticket/5553)
* Incompatibility of the binary I built in Ubuntu with the debian:jessie Docker image
* Docker file handling incompatible with [Control.AutoUpdate](https://hackage.haskell.org/package/auto-update-0.1.3/docs/Control-AutoUpdate.html)

#### Debugging suggestion:

Make a custom Docker image that builds off `begriffs/postgrest` and adds an `strace`:

```bash
strace -ff -e trace=file -p <postgrest-pid>
```

This will show us the files it is trying to access.

**Comment by nerfpops** [comment]
While installing strace i noticed that `ps aux` returned

    COMMAND
    postgrest postgres://......
    /bin/bash
    [sleep] <defunct>
    [sleep] <defunct>
    ps aux

When I pinged PostgREST i got a response, and this was logged:

    sendWakeup: invalid argument (Bad file descriptor)
    172.19.0.1 - - [20/Apr/2016:08:17:23 +0000] "GET / HTTP/1.1" 200 - "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) ....

The following requests got rejected with

    Control.AutoUpdate.mkAutoUpdate: worker thread exited with exception: sendWakeup: invalid argument (Bad file descriptor)

After restarting, ps aux had no [sleep] <defunct> and PostgREST worked as expected.

**Comment by nerfpops** [comment]
Since PostgREST is always given pid 1 in the docker container I assume the strace command should be

    strace -ff -e trace=file -p 1

The error I'm getting as root is: `strace: attach: ptrace(PTRACE_ATTACH, ...): Operation not permitted`

**Comment by ruslantalpa** [comment]
please try the 4.3 relaase in docker `postgrest/postgrest` and see if it works there.
