### ISSUE TITLE
~~Clarify supported algorithms for jwt~~  Adopt support for more jwt algorithms

### ISSUE THREAD

**Issue by drawks** [begriffs/postgrest#567]
I can find no reference in the docs as to what algos are implemented/supported for jwt verification. All references in docs and examples and the default value are plain ascii strings, which makes sense for symmetric schemes such as HS256, but there is no mention of support for asymmetric schemes such as RS256/512 or ES265/512.

I'm not quiet haskell literate enough to determine if these are supported and if they are what encoding should be used for the public key when used as a secret for postgrest.

**Comment by drawks** [comment]
After digging through the code I found my answer. The JWT library in use here appears to be **the only** jwt library in existence that has only implemented support for HS256.

Seems like it would be a good idea to switch to the much more well featured https://github.com/frasertweedale/hs-jose which supports the full set of algorithms as defined in the JWT spec. 

Not being able to use asymmetric key pairs really reduces any security gains you get from having process separation of authentication and authorization.

**Comment by begriffs** [comment]
This will be the next feature I tackle because I think it will also fix #495. Given how things go I'm guessing this will be complete by the middle of next week.

**Comment by begriffs** [comment]
OK, looking more at the `jose` library I see that using it will cause a big change in how the JWT "secret" (aka `KeyMaterial`) must be specified. The `--secret` flag would probably become JSON so that these various `FromJSON` [parsers](https://hackage.haskell.org/package/jose-0.4.0.0/docs/src/Crypto-JOSE-JWA-JWK.html) could work on them. Each type of key requires different parameters inside the JSON.

As a first step I'm upgrading the jwt library we use right now to fix a bug related to secrets containing gnarly binary values. When that is fixed I can investigate this issue again. Keep in mind that supporting all these types of keys looks like a backward incompatible change for the command line arguments of the program.

**Comment by drawks** [comment]
There should only be one other parameter besides "secret" that would need to be changed and that is the "algo" which is currently hard coded to "HS256" I'm a little confused what the "different parameters" are that you are talking about. The command line args shouldn't need to change in any backwards incompatible way. You simple add an optional "--algo" flag that defaults to "HS256" which is the current behavior.

**Comment by begriffs** [comment]
The elliptic curve algo requires parameters `kty` `x`, `y`, and `d`. The RSA algo requires parameters `kty`, `n`, `e` and optionally `d`. The symmetric key algo requires `kty` and `k`.

That's what it looks like based on the code of the Crypto.JOSE.JWA.JWK module at least. Maybe there are helpers I haven't noticed yet that make it easier.

**Comment by drawks** [comment]
Those parameters should be properties of the key/secret itself. I wish I knew enough haskell to help unravel this. But, the typical pattern would be load the public key (or secret in the case of symmetric) from a file and instantiate a key object. The key object then would have attributes as you've mentioned above. Although typically the entire key object would be passed as a parameter into your signature verify function.

**Comment by begriffs** [comment]
I looked at the possibilities again using the `jose` library. It does seem like their notion of jwt secrets, JWK, require varied and more sophisticated construction. Here's an [example](https://github.com/frasertweedale/hs-jose/blob/master/example/Main.hs#L64-L73).

If someone wants to figure this out I'll accept a pull request, but I'm not interested in this feature enough to implement it myself. The HMAC-SHA256 signing is good enough for my needs.

**Comment by russelldavies** [comment]
@begriffs Are you still working on switching to the jose library (in #842 you mention you are) or does this still need someone to implement?

**Comment by begriffs** [comment]
I am working on it, and I expect it to be done by next weekend.

**Comment by russelldavies** [comment]
Fantastic. If there are some tasks related to this you'd like help with I should be able to lend a hand.

**Comment by begriffs** [comment]
Got the tests passing on my local branch! I'll be making a pull request for it in the near future.

**Comment by begriffs** [comment]
@russelldavies just an update -- I have a meeting next week to demo the new feature to a company that has generously sponsored the development. If all goes well the feature will be released soon thereafter.

**Comment by russelldavies** [comment]
@begriffs Thanks for the update, looking forward to it.

**Comment by drawks** [comment]
Any updates here?
