### ISSUE TITLE
no relation between deal and customer

### ISSUE THREAD

**Issue by Sigura** [begriffs/postgrest#568]
Hello! ,)

first, thank you for your wonderful work!

I got error:

``` javascript
{
  details: 'no relation between deal and customer',
  message: 'could not find foreign keys between these entities'
}
```

`curl "http://localhost:3000/deal_certificates?certificate_id=eq.18395&select=deal_id\{id,sent,viewed,customer_id\{*\}\}"`
same result with `curl "http://localhost:3000/deal_certificates?certificate_id=eq.18395&select=deal\{id,sent,viewed,customer\{*\}\}"`

environment:
- `PostgREST 0.3.1.1`
- `postgres 9.5.2`

where

``` sql

CREATE TABLE deal_certificates
(
deal_id integer NOT NULL,
certificate_id integer NOT NULL,
CONSTRAINT deal_certificates_pkey PRIMARY KEY (deal_id, certificate_id),
CONSTRAINT deal_certificates_certificate_id_fkey FOREIGN KEY (certificate_id)
REFERENCES certificates (id) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT deal_certificates_deal_id_fkey FOREIGN KEY (deal_id)
REFERENCES deals (id) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE
)
WITH (
OIDS=FALSE
);
CREATE TABLE deals
(
id serial NOT NULL,
sent timestamp without time zone,
viewed timestamp without time zone,
customer_id integer NOT NULL,
CONSTRAINT deals_pkey PRIMARY KEY (id),
CONSTRAINT deals_customer_id_fkey FOREIGN KEY (customer_id)
REFERENCES customers (id) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
OIDS=FALSE
);
```

all works fine without nested `curl "http://localhost:3000/deal_certificates?certificate_id=eq.18395&select=deal_id\{id,sent,viewed\}"`

both tables in schema `v1`

`postgrest postgres://postgres:password@localhost:5432/taxliencloud --port 3000 --schema v1 --anonymous anon --pool 200`

found workaround:
`curl "http://localhost:3000/certificates?id=eq.18395&select=deals\{id,sent,viewed,signed,customer\{id,last_name,first_name\},creator\{id,last_name,first_name\},certificates\{id,certificate_year,face_value,attorney_fees\}\}"`

**Comment by Sigura** [comment]
same (error) results:

* `curl "http://localhost:8080/api/v1/deal_certificates?certificate_id=eq.18395&select=deal_id\{id,sent,viewed,signed,customer_id\{id\}\}"`
* `curl "http://localhost:8080/api/v1/deal_certificates?certificate_id=eq.18395&select=deal\{id,sent,viewed,signed,customer\{id\}\}"`

without nested works fine.

**Comment by ruslantalpa** [comment]
There was bug fixed when the tables were in the public schema.
Please try the latest version. If that does not fix it, please reopen.

**Comment by Sigura** [comment]
@ruslantalpa it works, good job! Thank you!
