### ISSUE TITLE
Failing to run against Postgres 9.2.15

### ISSUE THREAD

**Issue by john-owens** [begriffs/postgrest#569]
Getting the following error when trying to run against postgres version 9.2.15.

`postgrest: Cannot run in this PostgreSQL version, PostgREST needs at least 90300`

Running postgRest version v0.3.1.1

**Comment by john-owens** [comment]
Closing. Ran on same machine as postgres, didn't experience same issue. Problem with permissions from external machine.

**Comment by begriffs** [comment]
Were you connecting to the same database both times? The machine you connect from shouldn't affect the version check -- that worries me.

What was the database url you used when running postgrest?

**Comment by john-owens** [comment]
Commands were: 
Local:
 ./postgrest postgres://user:pw@localhost:5432/dbname  --port 3000 --pool 10 --schema public --anonymous blah
 
 Remote:
 ./postgrest postgres://user:pw@dbserver:5432/dbname  --port 3000 --pool 10 --schema public --anonymous blah
 
I ran the show version command on postgres. So it according to the error, it is the wrong version. But it runs without issue locally.

```
 postgres=# SHOW server_version_num;
 server_version_num
--------------------
 90215
(1 row)
```
