### ISSUE TITLE
Read after write inconsistency for RPC 

### ISSUE THREAD

**Issue by sscarduzio** [begriffs/postgrest#571]
Using postgrest 3.1.1.1 on PostgreSQL 9.5.2 (Amazon RDS)

I have an example table:

```sql
CREATE TABLE "1".example
(
  id text
);
```
I have a function that does more or less this (I simplified it, but still breaks):
```sql
CREATE OR REPLACE FUNCTION "1".test_crud(op text)
  RETURNS json AS
$BODY$
  var ret;
  switch(op) {
    case 'get':
      ret = plv8.execute('SELECT id FROM "1".example')
      break;

    case 'add':
      ret = plv8.execute('INSERT INTO "1".example(id) VALUES (\'a\')')
      break;

    case 'remove':
      ret = plv8.execute('DELETE FROM "1".example WHERE true');
      break;

    default:
      throw new Error("invalid op" + op);
 }
 return ret;

$BODY$
  LANGUAGE plv8 IMMUTABLE STRICT
  COST 100;
ALTER FUNCTION "1".user_favorites_crud(text, text, text)
  OWNER TO root;
```

Now, to prove the read-after-write consistency, I try this in SQL:
```sql
-- This in rapid sequence returns always empty:
select "1".test_crud('add');
select "1".test_crud('remove');
select "1".test_crud('get');
```

Then using postgrest in localhost, try the same via HTTP.
The following in not-so rapid sequence (2-3 seconds between the calls) still shows some content in the example table (even after I deleted it).
```
POST /rpc/test_crud {"op": "add"}
POST /rpc/test_crud {"op": "remove"}
POST /rpc/test_crud {"op": "get"}
```

After a while, I once again try to get and I finally see empty content:
```
POST /rpc/test_crud {"op": "add"}
```

**Comment by SebAlbert** [comment]
I don't know whether it solves the issue, but I think you're misusing the IMMUTABLE flag for your function. It may cause Postgres to cache the result and not run the function again if called with the same arguments. See http://www.postgresql.org/docs/9.5/static/xfunc-volatility.html for details.

**Comment by sscarduzio** [comment]
@SebAlbert this solved the issue because I cannot reproduce anymore. Kudos!
Weird how if I called the function from SQL this did not have effect though..

**Comment by begriffs** [comment]
@SebAlbert nice work noticing that.

@sscarduzio not sure why it doesn't affect SQL queries. In any case your function isn't `immutable`, in fact it's not even `stable`. It would be more informative for the db if you mark it `volatile` instead.
