### ISSUE TITLE
Wrong status code (404) when trying to patch a column with insufficient privileges

### ISSUE THREAD

**Issue by nerfpops** [begriffs/postgrest#575]
Example:

```
create table test (allowed text, not_allowed text);
create role bob;
grant select, update(allowed) on test to bob;
```

I can update `allowed` through PostgREST and I'm given an error message when trying to update `not_allowed` so it works as expected - but the status code is 404. I believe 400 is the correct status code in this case. This is a problem since I have a webserver on top of PostgREST that forwards 404 errors to another 404 handler.

**Comment by NikolayS** [comment]
The same for DELETE:
```
404 Not Found
{
  "hint": null,
  "details": null,
  "code": "42501",
  "message": "permission denied for relation table1"
}
```

I believe that 403 Forbidden is the most suitable http status code here.

I remember some discussion (in gitter?) with ideas that 404 here would help to hide details to improve security things, BUT:
 - current approach reveals a lot of details anyway (in response's body)
 - I'd leave the task of hiding smth on admin's shoulders, maybe describing best practices in PostgREST docs. I suppose nginx would do a perfect job of hiding stuff like that (using `error_page` instruction probably). On the other hand, in some cases, users might expect more details from API -- e.g. in case of some internal API hidden for the world.

**Comment by begriffs** [comment]
You're right, we originally thought 404 would help hide resources from unauthorized people probing routes to learn the schema structure. But like you pointed out the response body kind of gives it away! 😛 So using the correct HTTP code for a denied request seems like the best bet.

**Comment by begriffs** [comment]
In v0.4 it now returns 401 when no JWT credentials are supplied and 403 when credentials are supplied but the user is not authorized.
