### ISSUE TITLE
Misleading formatting of version number in error message "PostgREST needs at least 90300"

### ISSUE THREAD

**Issue by GeraldScott** [begriffs/postgrest#577]
I was getting this error message when I started up PostgREST:

`Cannot run in this PostgreSQL version, PostgREST needs at least 90300`

Thinking that it meant version 9.0.3, I disregarded it because I am running 9.2 and went off the garden path looking for some other cause of the error. 

User ruslantalpa put me right, but it may help some other poor soul if `minimumPgVersion` could be better formatted to show the major and minor versions more sensibly.

**Comment by begriffs** [comment]
I can see how this is confusing. I'll look for a way to format the version better.
