### ISSUE TITLE
Http Status 500 index out of bounds in Generics.hs

### ISSUE THREAD

**Issue by jotpe** [begriffs/postgrest#578]
An 500 Http Status occurs, when calling a function with an invalid JSON String. (Binary Ubuntu 64 bit v0.3.1.1)

```sql
create or replace function d(in int) returns integer as 
$$ select $1 * 2; $$ immutable language sql ;
```

```bash
curl 'http://localhost:3000/rpc/d' -H "Content-Type: application/json" -X POST -d '2'
```
causes an 500 status code with "Something went wrong" in the http body

postgrest output
> ./Data/Vector/Generic.hs:235 ((!)): index out of bounds (0,0)

**Comment by begriffs** [comment]
PostgREST currently requires named arguments for calling RPC functions. For instance

```sql
create or replace function d(in foo int) returns integer as 
$$ select $1 * 2; $$ immutable language sql ;
```

would be called with

```json
{ "foo": 2 }
```

I'll improve the error message in the non-JSON arg post to document this.

**Comment by begriffs** [comment]
Moving this issue to the new postgrest-docs repo.
