### ISSUE TITLE
There is no example for updating/patching in the document

### ISSUE THREAD

**Issue by geohuz** [begriffs/postgrest#585]
I'm wondering if we can find standard way in postgrest to update a record. I can only see the 'patch' with bulk insert.

**Comment by begriffs** [comment]
Hey there, let's say you've selected a record like `GET /people?id=eq.1`. To update that record change the verb to patch and include the fields in the body of your request that you'd like to change like

```
PATCH /people?id=eq.1

{ "name": "New name", "age": 102 }
```

Let me know if this answers your question and I can add it to the docs.

**Comment by rkoberg** [comment]
Yes, that answers the question :)

**Comment by begriffs** [comment]
Moving this issue to the new postgrest-docs repo.
