### ISSUE TITLE
Unable able to retrieve JSON values where key contains double colons ("::")

### ISSUE THREAD

**Issue by rtluckie** [begriffs/postgrest#587]
## Example:

**Works as expected:**
`https://service/things?select=id,value->foo->bar->>target`

**Returns an error:**
`https://service/things?select=id,value->>environment::host::name_servers`

`"type "host" does not exist"`

I have tried everything I can think of to escape the colons, but I haven't had any luck.

I know it is silly to have "::" in a json key, but I don't have control of the upstream data source.

**PostgreSQL Schema Setup**:

    CREATE TABLE things (
        id SERIAL PRIMARY KEY,
        value JSON
    );
    
    INSERT INTO things (value) VALUES (
        '{
            "foo": {
                "bar": {
                    "target": "abc"
                }
            },
            "environment::host::name_servers": "10.10.10.10"
        }' :: JSON);
    
**Query**:

    SELECT
        value -> 'foo' -> 'bar' ->> 'target' AS target,
        value ->> 'environment::host::name_servers' AS name_server
    FROM things

**Results**:

target | name_server
------------ | -------------
abc | 10.10.10.10

[SQL Fiddle][1]

  [1]: http://sqlfiddle.com/#!15/6e6a8/1

**Comment by ruslantalpa** [comment]
@rtluckie unfortunately :: has special meaning for urls with postgrest (cast). Not sure what can be done short of creating a view in the db to give access to that column using another name

**Comment by rtluckie** [comment]
@ruslantalpa thanks for the reply!  thats what I suspected -- its an extreme edge case. i went ahead and implemented a scrubbing method to replace "::" in json/jsob keys.

 Are there any other reserved strings that I should be aware of?

**Comment by ruslantalpa** [comment]
`:` `::` `->` `->>` and the column names will always be ok if you use `a-z A-z 0-9 _ -`

**Comment by rtluckie** [comment]
@ruslantalpa thx again.  closing as 'won't fix'
