### ISSUE TITLE
Non–URL-safe characters in Location header for 201 Created

### ISSUE THREAD

**Issue by league** [begriffs/postgrest#588]
I'm just toying with postgrest for now, trying the [film festival tutorial](http://postgrest.com/examples/start/). I built from source using stack on the git master (0dc33db).

I was surprised to find that the `Location` header returned in a 201 Created response for a single entity was not properly URL-encoded, and therefore could not directly be used for retrieval. Here's a transcript using `curl`.

````
% curl -v --crlf --data-binary @- -H "Content-Type: text/csv" http://localhost:3000/festival
name
New Haven Arts & Ideas
^D
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> POST /festival HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.48.0
> Accept: */*
> Content-Type: text/csv
> Content-Length: 28
> 
* upload completely sent off: 28 out of 28 bytes
< HTTP/1.1 201 Created
< Transfer-Encoding: chunked
< Date: Sat, 14 May 2016 13:18:05 GMT
< Server: postgrest/0.3.1.1
< Location: /festival?name=eq.New Haven Arts & Ideas
< 
* Connection #0 to host localhost left intact
````

When I try to `GET` using that provided `Location`, it doesn't work:

````
% curl 'http://localhost:3000/festival?name=eq.New Haven Arts & Ideas'
Bad Request
````

I need to turn the spaces into `+` and also encode the ampersand for it to work:

````
% curl 'http://localhost:3000/festival?name=eq.New+Haven+Arts+%26+Ideas'
[{"name":"New Haven Arts & Ideas"}]
````

Seems to me that the value of the `Location` header should be ready to use as it is. Of course, this doesn't occur with numeric primary keys that are used most often in practice, but since this was the example in the tutorial, I happened to notice it. Thanks!

**Comment by league** [comment]
P.S., I have Haskell-fu so if there's agreement that this is a bug, I could take a shot at a PR.

**Comment by ruslantalpa** [comment]
I think you'll need some sql foo to fix this since the location string is calculated in the db :) (if i remember correctly) but yes, it's a bug

**Comment by league** [comment]
Unfortunately, Postgres doesn't seem to have a urlencode function built in or in any standard extension. Here are two (slow) implementations using plpgsql:
  - http://stackoverflow.com/a/33616365
  - http://stackoverflow.com/a/10322075

One could do it in Haskell but it means first tearing apart the key/value format generated by SQL, then url-encoding only the values. Otherwise the equals/ampersands separating keys/values will get encoded too. Compare:

  - `/table?k1%3Deq.foo%20%26%20bar%26k2%3Deq.42`  (url-encode entire query string, BAD)
  - `/table?k1=eq.foo%20%26%20bar&k2=eq.42` (url-encode just the values, GOOD)

**Comment by ruslantalpa** [comment]
i don't think there will be a performance issue either way (haskell or sql).
Ideally this will be done in sql with standard functions, if not, then the locationF sql can be modified a bit so it's easier to break up and encode when it comes back to haskell.

**Comment by ruslantalpa** [comment]
one way to do it is to decide on the haskell side based on the column type if (int vs string) there might be encoding issues and use this
`select regexp_replace(encode('héllo there','hex'),'(..)',E'%\\1','g');` for strings

**Comment by league** [comment]
Okay — I have a solution to this that uses your SQL regexp/encode suggestion, but applies it to every 201 that produces a Location header whether it uses ints or strings. Then on the Haskell side we round-trip it through `(renderSimpleQuery . parseSimpleQuery)` to minimize & canonicalize the %-codes.

I have to rewrite the expectations on the `jsonb` tests in `InsertSpec` because they use special characters:

    Location: /json?data=eq.{"foo":"bar"}

becomes

    Location: /json?data=eq.%7B%22foo%22%3A%22bar%22%7D

That seems reasonable, but I wanted to test that it works in a GET. Either of the above location strings produces the error:

```json
{
  "hint": "No operator matches the given name and argument type(s). You might need to add explicit type casts.",
  "details": null,
  "code": "42883",
  "message": "operator does not exist: json = unknown"
}
```

which I suppose is a separate bug. At least they fail in the same way!

**Comment by ruslantalpa** [comment]
does it also fail for `/json?data=eq.[1,2,3]` ?
Can you add a failing test to your PR, ie do the insert then use the location string to check that you can get back the record then we can debug your branch

**Comment by league** [comment]
Yes, lookups with JSON keys are failing, for both lists and objects, and whether or not they are URL-encoded. There are 2 failing tests now in the PR, #595.
