### ISSUE TITLE
Support plurality=singular for functions

### ISSUE THREAD

**Issue by nerfpops** [begriffs/postgrest#599]
Either that, or just always assume singular if function doesn't return setof T.

Setting prefer: plurality=singular doesn't seem to affect functions.

**Comment by ruslantalpa** [comment]
This should be part of a bit of refactoring for RPC path, besides plurality support, &select parameter should also be supported

**Comment by nerfpops** [comment]
Oh yes, select and filtering on function return values would be a killer feature.

**Comment by begriffs** [comment]
It's all possible now.
