### ISSUE TITLE
Why is result returned as a dictionary with the function name as key?

### ISSUE THREAD

**Issue by nerfpops** [begriffs/postgrest#600]
A sample response from this function:

    CREATE OR REPLACE FUNCTION public.nearest_droppoint(
        longitude gis_longitude,
        latitude gis_latitude)
      RETURNS jsonb AS
    $BODY$
        select to_jsonb(row) from (select *, distance_from_to(droppoint_longitude, droppoint_latitude, longitude, latitude) as distance_km from droppoints order by distance_km limit 1) row
    $BODY$
      LANGUAGE sql STABLE SECURITY DEFINER;

Returns

    [
      {
        "nearest_droppoint": {
          "droppoint_latitude": 55.696037,
          "droppoint_postal_code": "2100",
          "distance_km": 0.0070047270467817,
          "droppoint_street1": "Blegdamsvej 82",
          "droppoint_city": "K\u00f8benhavn \u00d8",
          "courier": "dao",
          "id": 470,
          "droppoint_name": "F\u00e6lledparkens Kiosk",
          "droppoint_external_id": "97487",
          "droppoint_longitude": 12.571179
        }
      }
    ]

Is there any reason to wrap the result in a dictionary by the name of the function?

**Comment by begriffs** [comment]
It's a side effect of the sql output from our `callProc` function. I bet it's possible to modify to get rid of the function name in the results.

We may want to think when to make the change though as it would be backwards incompatible with existing clients. (Like save it for the release after the current one in progress)

**Comment by begriffs** [comment]
One other note, if we remove the function name from the response then in certain situations it will not be valid JSON. For instance suppose `myfunc` returns a number like 2. Then the response would be

```json
[ { "myfunc": 2 } ]
```
Removing the function name from the output would give
```json
[2]
```
and including request header `Prefer: plurality=singular` would give back
```
2
```
which, while a javascript value, is not a valid response for the mime type `application/json`. See [this](https://stackoverflow.com/questions/7487869/is-this-simple-string-considered-valid-json) discussion for more detail.

So it might be a bad idea to implement this proposal. Thoughts?

**Comment by nerfpops** [comment]
The latest JSON spec supports strings, numbers and booleans:

From http://stackoverflow.com/a/33440554/1193236
As of 2014, RFC 7159 obsoletes the older JSON RFCs, and declares that any JSON value is valid JSON text and valid application/json content - including strings. However, it also points out the incompatibility issue with older JSON implementations:

Both jsonlint.com and codebeauty.org validates 42 as a valid json value

**Comment by ruslantalpa** [comment]
This is nice, if we eliminate this we will be able to have functions return exactly their result, i.e if it's a number, result is a number, if it's a list of rows ... then it's and array with objects ... cool :)
I'll tackle this when the #608 is merged (along with some other optimisations for rpc calls)

**Comment by begriffs** [comment]
Removing the function name is now possible with the `Prefer: plurality=singular` request header thanks to Ruslan's pull request being merged.

**Comment by ruslantalpa** [comment]
@begriffs actually your statement is not true :), the header is not needed, and there is no function name anymore anywhere. the result is exaclty the json version of what the rpc returns, that is possible because for functions that return scalars, it's now valid to return `123`, `"abc"` and have it be a valid json

**Comment by nerfpops** [comment]
I just upgraded to 0.3.2.0 and the function name is still part of the result. At least for my nearest_droppoint-sql. Using prefer: plurality=singular doesn't change the result either.

**Comment by nerfpops** [comment]
But since my function returns JSON, wouldn't it be safe to assume that the function name should be removed from the response?

**Comment by nerfpops** [comment]
Would probably be a 0.4 feature as it's not backward compatible.

**Comment by ruslantalpa** [comment]
can you post the function here?

**Comment by nerfpops** [comment]
```
CREATE OR REPLACE FUNCTION public.dummy()
  RETURNS jsonb AS
$BODY$
    select jsonb_build_object('test', 123);
$BODY$
  LANGUAGE sql;
```

POSTing {} to /rpc/dummy returns `[{"dummy":{"test":123}}]`

Would be cool if it just returned {"test":123}

**Comment by ruslantalpa** [comment]
yes, we should have a special case for json. We should open a new issue mentioning functions returning json should just forward the output and not wrap it.
One thing to look into is if it makes sense to peek into the rturned json to see if it's an array or object and based on that to alter count.

**Comment by begriffs** [comment]
This may already be fixed already, see my comment in issue 716.
