### ISSUE TITLE
Better full text search capabilities

### ISSUE THREAD

**Issue by NikolayS** [begriffs/postgrest#601]
(Per discussion in gitter chat)

PostgREST supports `@@` operator for GET queries, but it 
- 1) lacks capability to point out, which full text config should be used during `text`→`tsquery` conversion (e.g.: "english" or "russian", which have different stemmers/ispell dictionaries)
- 2) leaves the task of converting user's input to `tsquery` to the client-side developer (not always a good thing, because client-side developers often don't understand how Postgres works, how to clear user input from special characters, trim it, etc – so there is a high chance to get SQL error from Postgres; at the same time, Postgres already provides `plainto_tsquery` function, which helps to solve this task w/o headache – more about it here: http://www.postgresql.org/docs/current/static/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES)

The only current solution to have both features is to use custom function (`/rpc/xxx`).

It would be great to have both capabilities available for GET queries by default – some form of API call that would be directly transformed to `plainto_tsquery(configname, userinput)`. Maybe a new operator(s), for instance, `@` (for `plainto_tsquery` with default FTS config), `configname@` (explicit choosing config for `plainto_tsquery`), and `configname@@` (for `to_tsquery(configname, query)`):  

``` http
GET /items?tsvector=@urlencoded%20query%20here
GET /items?tsvector=english@urlencoded%20query%20here 
GET /items?tsvector=russian@много%20букв
GET /items?tsvector=english@@apples%20%7C%20bananas
```

…that would be translated correspondingly to:

``` sql
items.tsvector @@ plainto_tsquery('urlencoded query here')
items.tsvector @@ plainto_tsquery('english', 'urlencoded query here')
items.tsvector @@ plainto_tsquery('russian', 'много букв')
items.tsvector @@ to_tsquery('english', 'apples | bananas')
```

@ruslantalpa's thoughts about it:

> there is no PostgREST way of doing that at the moment (except custom rpc), only if there is a way of doing that in the db somehow to turn col @@ 'string' into col @@ plainto_tsquery('russian', 'string') on the fly.
> i can think of a relatively fast way of being able to call functions in the select parameter while maintaining backword compatibility, i am not sure about fitlers
> since col=@@.plainto_tsquery('russian', 'string') can be interpreted as col @@ 'plainto_tsquery(\'russian\', \'string\')' We need a way to differentiate

**Comment by begriffs** [comment]
Could the database administrator `SET default_text_search_config = ...` to have their API default to Russian instead? Or do you need to choose English sometimes and Russian other times?

**Comment by NikolayS** [comment]
Exactly, the project is multi-lingual, more languages are to be added in
the future. So simple config change is not an option.

**Comment by bgamari** [comment]
I am also quite interested in this feature. Does the design presented above sound reasonable?

**Comment by ruslantalpa** [comment]
@bgamari @NikolayS it sounds reasonable, with a small change.
in this recent PR https://github.com/begriffs/postgrest/pull/938 we made a small change and renamed `@@` to `fts` (full text search), the old operator is still supported but deprecated.

We already have a thing like `col=eq.2` and `col=not.eq.2`
we could have the same thing with fts like `col=english.fts.apple` although it kind of makes it impossible to use `not` with `fts`

@steve-chavez @begriffs any ideas?

@bgamari what is your use-case for this? also using multiple languages?

**Comment by ruslantalpa** [comment]
there is also a related issue here https://github.com/begriffs/postgrest/issues/887

**Comment by bgamari** [comment]
> @bgamari what is your use-case for this? also using multiple languages?

An index of the Wikipedia link graph for use in information retrieval research. Indeed, we will also have multiple languages and the query language will be determined at runtime.

**Comment by NikolayS** [comment]
> it kind of makes it impossible to use not with fts

`to_tsquery` supports its own "micro language", which includes NOT "operator", see https://www.postgresql.org/docs/current/static/datatype-textsearch.html#DATATYPE-TSQUERY:

> A tsquery value stores lexemes that are to be searched for, and can combine them using the Boolean operators & (AND), | (OR), and ! (NOT), as well as the phrase search operator <-> (FOLLOWED BY). There is also a variant <N> of the FOLLOWED BY operator, where N is an integer constant that specifies the distance between the two lexemes being searched for. <-> is equivalent to <1>.

It would be awesome to support all this. I'll think how the mapping between URI and tsquery would look like.
