### ISSUE TITLE
Embedding Foreign Entities, connection refused with two foreign keys, works with one 

### ISSUE THREAD

**Issue by NotBrianZach** [begriffs/postgrest#609]
Hi,

I do this:
`curl 'localhost:3030/anon_session_and_library_story_ids' -G --data-urlencode '&select=anon_stories{*}'`

and get this error: `Something went wrong`,
 in postgrest logs: 

```
postgrest_1  | 172.17.0.1 - - [25/May/2016:17:02:15 +0000] "GET /anon_session_and_library_story_ids HTTP/1.1" 200 - "" "curl/7.47.0"
postgrest_1  | ConnectionError (Just "could not connect to server: Connection refused\n\tIs the server running on host \"db\" (172.17.0.2) and accepting\n\tTCP/IP connections on port 5432?
\n")
```
with these tables:

```
create table if not exists anon_session_and_library_story_ids (
  session_id uuid references anon_session (session_id),
  anon_story_id bigint references anon_stories (story_id),
  registered_story_id bigint references registered_stories (story_id)
);

create table anon_stories (
  session_id uuid references anon_session (session_id),
  story_id bigint primary key default nextval('story_id_seq'),
  story text
);

create table registered_stories (
  author_email text references basic_auth.users (email)
    on delete cascade on update cascade,
  story_id bigint primary key default nextval('story_id_seq'),
  story text
);
```

my immediate suspicion is that it's because the referenced keys have the same names even though they are in different tables. (edit, I tried renaming the story_id column in registered and anon_stories to anon_story_id and registered_story_id, and the curl request still failed in the same way, after rebooting docker containers as well, and a curl selecting anon_story_id worked)

if I do 
`curl 'localhost:3030/anon_session_and_library_story_ids' -G --data-urlencode '&select=story_id'`
it works fine.
I dropped the foreign key on registered_stories
` alter table anon_session_and_library_story_ids drop constraint anon_session_and_library_story_ids_registered_story_id_fkey;`
restarted docker containers and rebooted.
and the original query works.
`curl 'localhost:3030/anon_session_and_library_story_ids' -G --data-urlencode '&select=anon_stories{*}'`
 also tried vice versa, 
`curl 'localhost:3030/anon_session_and_library_story_ids' -G --data-urlencode '&select=registered_stories{*}'`
and got the same error at first and it was fixed as well after dropping the anon_stories foreign key.

`curl 'localhost:3030/anon_session_and_library_story_ids' -G --data-urlencode '&select=anon_stories{*}'
`

I compiled the postgrest binary from cloned git repo:
```
commit 4f53aef74f47586a4fa5cff0a571e60d10316ad2
Merge: c7d863c f4027cb
Author: Joe Nelson <begriffs@users.noreply.github.com>
Date:   Sun May 22 11:36:15 2016 -0700
```

    Merge pull request #606 from begriffs/newdeps

here are my dockerfiles:

```
FROM centos

RUN yum install -y tar wget postgresql-devel

ENV POSTGREST_VERSION 0.3.1.1

#	RUN wget https://github.com/begriffs/postgrest/releases/download/v${POSTGREST_VERSION}/postgrest-${POSTGREST_VERSION}-centos.tar.xz
ADD ./postgrest /usr/local/bin/postgrest
# RUN tar --xz -xvf postgrest-${POSTGREST_VERSION}-centos.tar.xz
# RUN mv postgrest /usr/local/bin/postgrest

CMD postgrest  postgres://postgres:foobar@db:5432/postgres \
               --port 3030 \
               --schema public \
               --anonymous postgres \
               --pool 200

EXPOSE 3030

FROM postgres:9.5
RUN apt-get update  --fix-missing
RUN apt-get install -y \
  make \
  gcc \
  libpq-dev \
  postgresql-server-dev-9.5 \
  python-pip \
  python-psycopg2
RUN mkdir -p /usr/src/pg_amqp
COPY ./pg_amqp/ /usr/src/pg_amqp/
WORKDIR /usr/src/pg_amqp
RUN make
RUN make install
WORKDIR /
COPY ./scripts/ /docker-entrypoint-initdb.d/
```

and base os is ubuntu 16.04.

**Comment by ruslantalpa** [comment]
i don't think it has anything to do with your tables, look at the postgrest logs you posted, it could not connect to the database, it (postgresql) probabably died after postgrest was started. 
I have not exp with docker but it's probably something wrong with your docker config, you first need to spin up the database (and make sure it's running) then have postgrest connect to it after that

**Comment by NotBrianZach** [comment]
I can curl and receive a response from postgrest immediately after and before the queries I am talking about

```
postgrest_1  | 172.17.0.1 - - [25/May/2016:17:44:49 +0000] "GET /anon_session_and_library_story_ids HTTP/1.1" 200 - "" "curl/7.47.0"
postgrest_1  | ConnectionError (Just "could not connect to server: Connection refused\n\tIs the server running on host \"db\" (172.17.0.2) and accepting\n\tTCP/IP connections on port 5432?\n")
postgrest_1  | 172.17.0.1 - - [25/May/2016:17:45:47 +0000] "GET /anon_stories HTTP/1.1" 200 - "http://localhost:3000/storyCatalogEditor" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
```

last query here works fine

**Comment by ruslantalpa** [comment]
after you do a schema change, you need to restart postgrest (or send -HUP)

**Comment by NotBrianZach** [comment]
yea, if I hadn't it wouldn't have detected the changes to the foreign keys on the anon_session_and_library_story_ids table, and the query wouldn't have worked when there was only one key

**Comment by ruslantalpa** [comment]
try for select to do this `&select=*,anon_stories{*}` (there is a difference from your request)

**Comment by NotBrianZach** [comment]
I will try it and get back to you. also there was a slightly different error message on the same query from node superagent, think it mentioned cors, I will replicate it and post.

**Comment by NotBrianZach** [comment]
I think there's a race condition between the two docker containers. The query works sometimes. If postgrest boots up before the db is done initializing (or something) it seems not to work. Since I was modifying the schema every time postgrest always booted first. This seems to hold true even when postgrest boots before the db and the db doesn't have any schema changes from the last time it booted.

will post logs showing what I'm talking about in a sec.

Thanks for your time. I do hope one day to actually contribute :P (at least got compiling this time :P)

**Comment by ruslantalpa** [comment]
cool, since you found the problem, please close the issue (you can post the logs later here if someone is interested)

**Comment by NotBrianZach** [comment]
logs from docker compose
this run works
```
db_1         | LOG:  database system was shut down at 2016-05-25 20:11:33 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  database system is ready to accept connections
db_1         | LOG:  autovacuum launcher started
postgrest_1  | WARNING, running in insecure mode, JWT secret is the default value
postgrest_1  | Listening on port 3030
postgrest_1  | 172.17.0.1 - - [25/May/2016:20:15:41 +0000] "GET /anon_stories HTTP/1.1" 200 - "http://localhost:3000/storyCatalogEditor" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
postgrest_1  | 172.17.0.1 - - [25/May/2016:20:15:41 +0000] "GET /anon_session_and_library_story_ids HTTP/1.1" 200 - "http://localhost:3000/stories" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
postgrest_1  | 172.17.0.1 - - [25/May/2016:20:15:51 +0000] "GET /anon_session_and_library_story_ids HTTP/1.1" 200 - "" "curl/7.47.0"

zachabel@zachabel-ThinkPad-P50:~/dockercollectivestorybook/postgresql/scripts$ curl 'localhost:3030/anon_session_and_library_story_ids' -G --data-urlencode '&select=registered_stories{*}'
[]
```

this run doesn't work. 
```
zachabel@zachabel-ThinkPad-P50:~/dockercollectivestorybook/postgresql/scripts$ curl 'localhost:3030/anon_session_and_library_story_ids' -G --data-urlencode '&select=registered_stories{*}'
{"details":"could not connect to server: Connection refused\n\tIs the server running on host \"db\" (172.17.0.2) and accepting\n\tTCP/IP connections on port 5432?\n","code":"","message":"Connection error"}
zachabel@zachabel-ThinkPad-P50:~/dockercollectivestorybook/postgresql/scripts$ curl 'localhost:3030/anon_session_and_library_story_ids' -G --data-urlencode '&select=registered_stories{*}'
{"details":"could not connect to server: Connection refused\n\tIs the server running on host \"db\" (172.17.0.2) and accepting\n\tTCP/IP connections on port 5432?\n","code":"","message":"Connection error"}
```

db_1         | The files belonging to this database system will be owned by user "postgres".
db_1         | This user must also own the server process.
db_1         | 
db_1         | The database cluster will be initialized with locale "en_US.utf8".
db_1         | The default database encoding has accordingly been set to "UTF8".
db_1         | The default text search configuration will be set to "english".
postgrest_1  | WARNING, running in insecure mode, JWT secret is the default value
db_1         | 
postgrest_1  | Listening on port 3030
db_1         | Data page checksums are disabled.
db_1         | 
db_1         | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1         | creating subdirectories ... ok
db_1         | selecting default max_connections ... 100
db_1         | selecting default shared_buffers ... 128MB
db_1         | selecting dynamic shared memory implementation ... posix
db_1         | creating configuration files ... ok
db_1         | creating template1 database in /var/lib/postgresql/data/base/1 ... ok
db_1         | initializing pg_authid ... ok
db_1         | initializing dependencies ... ok
db_1         | creating system views ... ok
db_1         | loading system objects' descriptions ... ok
db_1         | creating collations ... ok
db_1         | creating conversions ... ok
db_1         | creating dictionaries ... ok
db_1         | setting privileges on built-in objects ... ok
db_1         | creating information schema ... ok
db_1         | loading PL/pgSQL server-side language ... ok
db_1         | vacuuming database template1 ... ok
db_1         | copying template1 to template0 ... ok
db_1         | copying template1 to postgres ... ok
db_1         | syncing data to disk ... 
db_1         | WARNING: enabling "trust" authentication for local connections
db_1         | You can change this by editing pg_hba.conf or using the option -A, or
db_1         | --auth-local and --auth-host, the next time you run initdb.
db_1         | ok
db_1         | 
db_1         | Success. You can now start the database server using:
db_1         | 
db_1         |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1         | 
db_1         | waiting for server to start....LOG:  database system was shut down at 2016-05-25 20:11:11 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  database system is ready to accept connections
db_1         | LOG:  autovacuum launcher started
db_1         |  done
db_1         | server started
db_1         | ALTER ROLE
db_1         | 
db_1         | 
db_1         | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/0000000_user_init.sql
db_1         | CREATE EXTENSION
db_1         | CREATE EXTENSION
db_1         | CREATE SCHEMA
db_1         | CREATE ROLE
db_1         | CREATE ROLE
db_1         | CREATE ROLE
db_1         | GRANT ROLE
db_1         | GRANT ROLE
db_1         | CREATE TABLE
db_1         | CREATE TABLE
db_1         | NOTICE:  type "token_type_enum" does not exist, skipping
db_1         | DROP TYPE
db_1         | CREATE TYPE
db_1         | CREATE TABLE
db_1         | CREATE FUNCTION
db_1         | CREATE FUNCTION
db_1         | DROP TRIGGER
db_1         | NOTICE:  trigger "ensure_user_role_exists" for relation "basic_auth.users" does not exist, skipping
db_1         | CREATE TRIGGER
db_1         | CREATE FUNCTION
db_1         | NOTICE:  trigger "encrypt_pass" for relation "basic_auth.users" does not exist, skipping
db_1         | DROP TRIGGER
db_1         | CREATE TRIGGER
db_1         | CREATE FUNCTION
db_1         | CREATE FUNCTION
db_1         | NOTICE:  trigger "send_validation" for relation "basic_auth.users" does not exist, skipping
db_1         | DROP TRIGGER
db_1         | CREATE TRIGGER
db_1         | CREATE FUNCTION
db_1         | CREATE VIEW
db_1         | CREATE FUNCTION
db_1         | DROP TRIGGER
db_1         | NOTICE:  trigger "update_users" for relation "users" does not exist, skipping
db_1         | CREATE TRIGGER
db_1         | 
db_1         | 
db_1         | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/000000_logging.sh
db_1         | in logging.sh
db_1         | in logging.sh, executed perl
db_1         | 
db_1         | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/100000_stories_and_reviews_init.sql
db_1         | CREATE SEQUENCE
db_1         | CREATE SEQUENCE
db_1         | CREATE TABLE
db_1         | COMMENT
db_1         | COMMENT
db_1         | CREATE TABLE
db_1         | COMMENT
db_1         | COMMENT
db_1         | CREATE FUNCTION
db_1         | CREATE TABLE
db_1         | COMMENT
db_1         | COMMENT
db_1         | CREATE TABLE
db_1         | COMMENT
db_1         | CREATE TABLE
db_1         | COMMENT
db_1         | COMMENT
db_1         | CREATE TABLE
db_1         | COMMENT
db_1         | CREATE TABLE
db_1         | CREATE TABLE
db_1         | INSERT 0 1
db_1         | NOTICE:  type "newly_created_story" does not exist, skipping
db_1         | DROP TYPE
db_1         | CREATE TYPE
db_1         | CREATE FUNCTION
db_1         | CREATE FUNCTION
db_1         | 
db_1         | 
db_1         | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/200000_new_session_id.sql
db_1         | CREATE FUNCTION
db_1         | 
db_1         | 
db_1         | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/200000_register_and_login.sql
db_1         | DROP TYPE
db_1         | NOTICE:  type "basic_auth.jwt_claims" does not exist, skipping
db_1         | CREATE TYPE
db_1         | CREATE FUNCTION
db_1         | CREATE FUNCTION
db_1         | CREATE FUNCTION
db_1         | CREATE FUNCTION
db_1         | 
db_1         | CREATE TABLE
db_1         | CREATE TABLE
db_1         | 
db_1         | 
db_1         | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/300000_password_reset.sql
db_1         | CREATE FUNCTION
db_1         | CREATE FUNCTION
db_1         | 
db_1         | 
db_1         | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/800000_permissions.sql
db_1         | GRANT
db_1         | GRANT
db_1         | GRANT
db_1         | GRANT
db_1         | GRANT
db_1         | GRANT
db_1         | GRANT
db_1         | GRANT
db_1         | 
db_1         | 
db_1         | 
db_1         | LOG:  received fast shutdown request
db_1         | LOG:  aborting any active transactions
db_1         | waiting for server to shut down...LOG:  autovacuum launcher shutting down
db_1         | .LOG:  shutting down
db_1         | LOG:  database system is shut down
db_1         |  done
db_1         | server stopped
db_1         | 
db_1         | PostgreSQL init process complete; ready for start up.
db_1         | 
db_1         | LOG:  database system was shut down at 2016-05-25 20:11:13 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  database system is ready to accept connections
db_1         | LOG:  autovacuum launcher started
postgrest_1  | 172.17.0.1 - - [25/May/2016:20:11:17 +0000] "GET /anon_session_and_library_story_ids HTTP/1.1" 500 - "" "curl/7.47.0"
postgrest_1  | 172.17.0.1 - - [25/May/2016:20:11:19 +0000] "GET /anon_session_and_library_story_ids HTTP/1.1" 500 - "" "curl/7.47.0"

**Comment by begriffs** [comment]
Check out this guide about controlling container startup order: https://docs.docker.com/compose/startup-order/

**Comment by begriffs** [comment]
I just learned that Docker 1.12 introduces a way to add health checks that can help to prevent this situation of one container depending on another which as not yet started. https://blog.newrelic.com/2016/08/24/docker-health-check-instruction/
