### ISSUE TITLE
404 When deleting from view

### ISSUE THREAD

**Issue by jiveformation** [begriffs/postgrest#611]
I'm not sure if this is the right forum for my issue, but I thought I'd ask here anyways.

I'm brand new to Postgrest and I love what I've seen so far.  My one difficulty seems to be that while deleting from a table returns the proper return code (204), deleting from a view (via function and trigger) returns a 404 code.

Is there something I need to do differently to make Postgrest return a 204 in this instance?

Thanks so much!

`CREATE OR REPLACE FUNCTION public.item_locations_vw_fnc()
  RETURNS trigger AS
$BODY$
      DECLARE new_item_id integer;
      DECLARE new_loc_id integer;
      DECLARE old_item_id integer;
      DECLARE old_loc_id integer;
      DECLARE query text;
   BEGIN
      IF TG_OP = 'INSERT' THEN
       SELECT item_id INTO new_item_id FROM items WHERE items.item_code = NEW.item_code;
       SELECT loc_id INTO new_loc_id FROM locations WHERE locations.location_code = NEW.location_code;
       INSERT INTO  item_locations (item_id, loc_id, username, 
		qty, put_date, put_comment)
	VALUES(
		new_item_id, new_loc_id,
		coalesce(nullif(basic_auth.current_username(), ''), NEW.username), NEW.qty, current_date, NEW.put_comment);
       RETURN NEW;
      ELSIF TG_OP = 'UPDATE' THEN
       SELECT items.item_id INTO new_item_id FROM items WHERE items.item_code = NEW.item_code;
       SELECT locations.loc_id INTO new_loc_id FROM locations WHERE locations.location_code = NEW.location_code;
       SELECT items.item_id INTO old_item_id FROM items WHERE items.item_code = OLD.item_code;
       SELECT locations.loc_id INTO old_loc_id FROM locations WHERE locations.location_code = OLD.location_code;
       UPDATE item_locations SET 
	item_id=new_item_id,
	loc_id=new_loc_id, 
	username=coalesce(nullif(basic_auth.current_username(),''), NEW.username),
	qty=NEW.qty,
	put_date=current_date,
	put_comment=NEW.put_comment
       WHERE item_id=old_item_id AND loc_id=old_loc_id;
       RETURN NEW;
      ELSIF TG_OP = 'DELETE' THEN
       SELECT items.item_id INTO old_item_id FROM items WHERE items.item_code = OLD.item_code;
       SELECT locations.loc_id INTO old_loc_id FROM locations WHERE locations.location_code = OLD.location_code;
       DELETE FROM item_locations 
	WHERE item_id=old_item_id AND loc_id=old_loc_id;
       RETURN NULL;
      END IF;
      RETURN NEW;
    END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION public.item_locations_vw_fnc()
  OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.item_locations_vw_fnc() TO public, postgres, anon, staff, manager;

CREATE TRIGGER item_locations_vw_fnc_trig
    INSTEAD OF INSERT OR UPDATE OR DELETE ON
      item_locations_v FOR EACH ROW EXECUTE PROCEDURE item_locations_vw_fnc();`

**Comment by ruslantalpa** [comment]
your function needs to return the deleted rows at the end, then you'll get a 204

**Comment by ruslantalpa** [comment]
(please close the issue when you fix this :)

**Comment by jiveformation** [comment]
Awesome!  Thank you so much!

**Comment by begriffs** [comment]
I've seen this issue pop up a few times now, I wonder if it makes sense to have a DELETE default to not attempting to read the result (an implicit `Prefer: return=none`).

**Comment by jiveformation** [comment]
Now that I know what it's expecting, I think it makes more sense as it is.  I don't know Postgresql well enough to anticipate what errors could occur (or even pass back those errors correctly... must look into this), but for people who know what they're doing, I think it would be helpful for them to differentiate between "deleted successfully" (204) and "tried to delete but it wasn't there" (404).  Ideally, I suppose there could be a user-configurable setting to tell Postgrest how seriously to treat a missing record when deleting.  Frankly though, that's looking for solutions to problems that I haven't run into yet (if I ever do).  I think if it was documented a bit more clearly and if there were a forum / knowledge-base for user-configuration issues like this one, then it wouldn't be a problem leaving it the way it is.
BTW, love the project!  Thanks for all your hard work on this!
