### ISSUE TITLE
GHC 8 fixes

### ISSUE THREAD

**Issue by ilovezfs** [begriffs/postgrest#612]
To get postgrest building under GHC 8.0.1 for Homebrew (we only typically support the latest GHC), I've needed to add a "cabal.config" file at the root of the package containing "allow-newer: base,transformers" and patch the following three dependencies:
- bytestring-tree-builder 0.2.6
- postgresql-binary 0.9
- hasql-transaction 0.4.4.1

bytestring-tree-builder and postgresql-binary needed the GHC option "-XNoImpredicativeTypes" due to increased strictness under GHC 8.

hasql-transaction needed "base" added to its build-depends.

With these changes, postgrest builds as expected and passes CI tests.

The Homebrew Ruby code that accomplishes this is, as follows:
```
+    cabalcfg = "allow-newer: base,transformers"
+    cabalcfg << "\nconstraints:"
+    cabal_sandbox do
+      %w[
+        bytestring-tree-builder 0.2.6
+        postgresql-binary 0.9
+        hasql-transaction 0.4.4.1
+      ].each_slice(2) do |pkg, ver|
+        cabalcfg << "\n#{pkg} ==#{ver}"
+        system "cabal", "get", pkg
+        cabal_sandbox_add_source "#{pkg}-#{ver}"
+        inreplace "#{pkg}-#{ver}/#{pkg}.cabal" do |s|
+          if pkg == "hasql-transaction"
+            s.gsub! "build-depends:", "build-depends: base,"
+          else
+            s.gsub! "ghc-options:", "ghc-options: -XNoImpredicativeTypes"
+          end
+        end
+      end
+      (buildpath/"cabal.config").write(cabalcfg)
+      install_cabal_package :using => ["happy"]
+    end

```

**Comment by begriffs** [comment]
Thanks for the detailed report and fix!

Alternatively I wonder if we could switch the Homebrew script to use Stack for the Haskell build. This would take care of building the extra deps.

To prepare I could try bumping the Stack resolver to LTS-6.0 and fix the NoImpredicativeTypes problem.

**Comment by ilovezfs** [comment]
You're welcome!

Stack's configurations are most likely going to require GHC 7 for a while, but if there's a configuration they have available that works under GHC 8, that's certainly an option since we can install a cabal.config at the root of the sandbox to mandate a particular config. In general, we've tried to avoid resorting to fixed configurations where possible. (By the way, have you had a chance to check whether postgrest builds with the new toy? http://blog.ezyang.com/2016/05/announcing-cabal-new-build-nix-style-local-builds/)

Regarding NoImpredicativeTypes, it would definitely be best to try to make the tweaks to avoid using GHC extensions if possible. I suppose the developers of bytestring-tree-builder and postgresql-binary are on the hook for those though (unless you know what changes are needed)! I haven't had a chance to ping them yet about it.
