### ISSUE TITLE
Weird authenticator error response

### ISSUE THREAD

**Issue by jfranki** [begriffs/postgrest#613]
I came across a weird error when trying `v0.3.1.1`.
The situtation was that I forgot to give my authenticator role the rights to set a particular role (grant permissions), so I would receive this error:
```
{
  "details": "another command is already in progress\n",
  "message": "Database client error"
}
```
And upon few subsequent attempts:
```
{
  "hint": null,
  "details": null,
  "code": "25P02",
  "message": "transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción"
}
```
After this not even a token claim could be made, as I received the second error. I had to wait several seconds for the server to become operational again.

I solved the problem granting permissions, but it worries me that the server becomes irresponsive for some time. On top of that, I tested the same situation with the previous version of PostgREST (`v.0.3.1.0`) and the server would give me the proper error fine and without becoming irresponsive (this way I discovered what was causing the trouble):
```
{
  "hint": null,
  "details": null,
  "code": "42501",
  "message": "se ha denegado el permiso para definir el rol «xxxxxxxxxx»"
}
```
Some change must have messed up this in the last version.

**Comment by begriffs** [comment]
Thanks for the report, I'll try to make a failing test to reproduce.

**Comment by nerfpops** [comment]
I'm getting the same error, though the authenticator role is set up correctly:

    GRANT anon, postgres TO authenticator;
    NOTICE:  role "authenticator" is already a member of role "anon"
    NOTICE:  role "authenticator" is already a member of role "postgres"
    GRANT ROLE

**Comment by begriffs** [comment]
Could you try to reproduce the problem using the newest code on the master branch? I upgraded the `hasql-transaction` library and am wondering if that is related.

**Comment by begriffs** [comment]
@jfranki is this still causing problems for you? Should I close the issue?

**Comment by jfranki** [comment]
Sorry for the long delay! I will reproduce the issue today with the current version and I will let you know.

**Comment by jfranki** [comment]
I believe the issue is resolved, you can close the issue.

**Comment by begriffs** [comment]
👍
