### ISSUE TITLE
Doses Postgrest support listen localhost only?

### ISSUE THREAD

**Issue by cutso** [begriffs/postgrest#614]
hi there, 
thx for your great project.
as the subject, i can't find any settings about listen host when postgrest start.
in our projects, we used postgrest as the center database interface. and we tried to control access from remote server except local area network, so we have to add a rule of iptables to limit remote user.

In postgrest starting config, only listen port can be found and without listen host. So, could these in future?

thx++++++++

**Comment by begriffs** [comment]
Hey cutso, you're correct that this is a current limitation. I'm going to close this issue because it's a duplicate of #461 but your asking again adds priority to that issue.

**Comment by cutso** [comment]
Thx for your prompt reply. I will continue to focus on these.
I do not know whether it will come true or not, because the security is the most important.

One more thing, i just take a liberty of saying that the security control is DUPLICATE.

Postgrest: "REST API for any Postgres database".
I think, most of PG-DBA used postgresql ROLE/USER's privileges to control users access. And i saw Postgrest have designed a authentication via JWT(on docs site).

So, I have to grant user's privileges and build another authentication for Postgrest.
I don't know whether you know what I mean via my poor English. 
Postgrest should achieve its own goals only that restful api, security issues should be returned to the database itself and the OS.

If Postgres can be set to listen local address, users can use their own authentication what they want to, such as HTTP BasicAuth or Reverse proxy or Application and so on. Then Postgrest can be built in any projects as a service via user's customized connection and control.

Anyway, I respect and support your decision, and thank you again.

**Comment by SebAlbert** [comment]
Hi @cutso,
regarding your thoughts on user management, I'd say thinking about large-scale projects with hundreds or thousands of similar, but different users, most DBAs probably won't like to add every single user as a Postgres DB user (role). That's where PostgREST's type of authentication comes in handy.

However, I second the thought that at some point in the future it would be great if PostgREST supported other standard ways of authentication such as HTTP Basic Auth or integrate nicely with OpenID and OAuth infrastructures and the likes. Some things of this sort may even be implementable through PostgREST's JWT support by adding certain layers (such as nginx) in a clever way, but I haven't thought it through.
