### ISSUE TITLE
Posting empty object generates malformed SQL

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#616]
Posting an empty JSON object `{}` to insert a row in a table whose columns all have default values should succeed. However it results in this error:

```json
{
  "hint": null,
  "details": null,
  "code": "42601",
  "message": "syntax error at or near \")\""
}
```

@Mithrandir21 discovered this bug in postgrest 0.3.1.1

**Comment by cutso** [comment]
I think reject empty JSON object  to post and put will be better. It's confused user that unsure data to be created or updated, at least one field have value in request.

**Comment by ruslantalpa** [comment]
put is always insert, patch is always update, i see not confusion here although wired/edge case ... insert nothing ... :)

**Comment by Mithrandir21** [comment]
There are situations where nothing needs to be inserted, like in my example where I need a "Junction Table" for a Many-to-Many relationship. The table will contain a generated UUID that can be used elsewhere.
See [Junction Table](http://www.codeproject.com/Articles/674121/When-do-we-need-junction-table-for-a-one-to-many)
See [Junction Table + Normal Form](http://stackoverflow.com/questions/20734599/how-to-construct-a-junction-table-for-many-to-many-relationship-without-breaking)

**Comment by ruslantalpa** [comment]
offtopic: why do you need the uuid in the junction table, why can't it be just 2 columns (fk to both tables) and they both form a unique index?
