### ISSUE TITLE
Is filtering working as intended?

### ISSUE THREAD

**Issue by aspidites** [begriffs/postgrest#617]
Caveat: I'm really tired, so I could be missing something obvious.

I expect the following request to only show sessions who's type is equal to "talk":
```
curl https://postgrest.herokuapp.com/sessions\?session_type.eq.talk\&select\=session_type
```
As you can see, however, I'm not filtering at all:
![2016-05-29-191741_1916x791_scrot](https://cloud.githubusercontent.com/assets/93686/15636593/884cd7dc-25d2-11e6-93b4-b65be9fc5d1d.png)

I'm using PostgreSQL 9.5.2 and postgrest 0.3.1.1

**Comment by SebAlbert** [comment]
try
`session_type=eq.talk`
(maybe with the = sign escaped for command line usage)
instead of
`session_type.eq.talk`

**Comment by aspidites** [comment]
Doh! Works like a charm (of course). Note to self: Take a name when I'm confused.
