### ISSUE TITLE
Support form content-type

### ISSUE THREAD

**Issue by daurnimator** [begriffs/postgrest#622]
For performing functions directly (e.g. login) from HTML forms it would be nice to support either  `multipart/form-data` or `application/x-www-form-urlencoded` encoded POST bodies to rpc endpoints.

**Comment by ruslantalpa** [comment]
I think it's been implemented by this commit https://github.com/begriffs/postgrest/commit/a21464ddca4068c622214f6227bd7a93d79168b8
however you will still need to have js code intercepting successful form submit and taking an action based on that.

**Comment by begriffs** [comment]
Yep `application/x-www-form-urlencoded` has been implemented. Note that after submission the browser will land on an empty page because a form-initiated insert will return no body on success. One workaround as Ruslan mentioned is to use javascript to submit your form and handle success or failure.
