### ISSUE TITLE
Customize Server header

### ISSUE THREAD

**Issue by luismartingil** [begriffs/postgrest#623]
Is there a way to customize the `Server: postgrest/0.3.1.1` header in the response? It would be great to be able to pass it as a command line arg.

**Comment by begriffs** [comment]
You can put nginx in front of the server and use the [proxy_set_header](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header) command to override `Server`.

**Comment by luismartingil** [comment]
Thanks, do you always recommend the use of **nginx** in front of `postgrest`? I was thinking on having a `--server-header=my_server_header_value` passing it in the command line.

**Comment by ruslantalpa** [comment]
@luismartingil yes, always. In addition to a lot of flexibility/ssl support, it gives you protection against a lot of DDOS attacks
PS: checkout openresty (nginx+lua) - very powerfull combination

**Comment by luismartingil** [comment]
Thanks
