### ISSUE TITLE
Register and run postgrest as Windows Service

### ISSUE THREAD

**Issue by ganchsg** [begriffs/postgrest#624]
is it posible register and run postgrest as Windows Service?

**Comment by begriffs** [comment]
Looks possible. https://stackoverflow.com/questions/3582108/create-windows-service-from-executable

Apparently it will be easiest to do so if the binary itself implements a `ServiceMain` callback. [This article](https://stackoverflow.com/questions/10037654/how-can-a-windows-service-application-be-written-in-haskell) talks about doing so in Haskell. Anybody care to help out with this feature?

**Comment by ganchsg** [comment]
Use NSSM( the non-Sucking Service Manager ) to run postgrest.exe as a service.
http://nssm.cc/
It works at windows 7

**Comment by begriffs** [comment]
Is this something I have to do when preparing the .exe for release, or something other people do on their own windows systems?

**Comment by ganchsg** [comment]
other people download NSSM from http://nssm.cc and do on their own windows systems.

**Comment by begriffs** [comment]
Would you be interested in adding a short section about windows service deployment to our docs? https://github.com/begriffs/postgrest-docs/blob/master/docs/admin/deployment.md
