### ISSUE TITLE
Sending OPTIONS request results in 500 error

### ISSUE THREAD

**Issue by anschwa** [begriffs/postgrest#629]
Hello, I'm trying out postgREST for the first time, and have it running in docker similar to [this repository](https://github.com/NotBrianZach/docker-postgrest-with-postgresql) except, I've build from source.

I'm following along with [example 1](http://postgrest.com/examples/start/) making `GET` and `POST` requests work as they should, but `OPTIONS` results in:
 ```
ConnectionError (Just "could not connect to server: Connection refused
\tIs the server running on host \"db\" (172.19.0.2) and accepting
\tTCP/IP connections on port 5432?\n")
``` 

Making another `GET` request afterwards behaves normally.

**Comment by begriffs** [comment]
This doesn't happen for you when running a server outside of docker, right?

**Comment by anschwa** [comment]
I actually never tried running without docker...

**Comment by ruslantalpa** [comment]
@anschwa you have to start postgrest in the container only after the db container is ready.

**Comment by ruslantalpa** [comment]
https://docs.docker.com/compose/startup-order/

**Comment by anschwa** [comment]
Yes I believe that's the problem from what I remember.

**Comment by ruslantalpa** [comment]
(close please :)
