### ISSUE TITLE
any way to convert a request to a table to a map (feature request?)

### ISSUE THREAD

**Issue by rkoberg** [begriffs/postgrest#630]
(new to postgrest - it is amazing!) A normal GET request on a table comes back as an array. Is there some way to "map" this to a Object literal on the postgrest server using the primary key as the default and perhaps overriding by passing a key to use? I am finding I need to always convert these to maps in my client code. (I am using ImmutableJS in a React/Redux app, and this is causing unnecessary re-renders.)

**Comment by begriffs** [comment]
Try sending the request header `Prefer: plurality=singular` as described in http://postgrest.com/api/reading/#singular-vs-plural

**Comment by rkoberg** [comment]
That returns a single object:
```
$ curl -v -X GET -H "Prefer: plurality=singular" -H "Range-Unit: regions" -H "Range: 0-4" 127.0.0.1:3000/regions
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /regions HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.43.0
> Accept: */*
> Prefer: plurality=singular
> Range-Unit: regions
> Range: 0-4
> 
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Wed, 08 Jun 2016 02:12:54 GMT
< Server: postgrest/0.3.1.1
< Content-Type: application/json; charset=utf-8
< 
* Connection #0 to host 127.0.0.1 left intact
{"id":"14b2581f-bb02-4361-a5f9-533b063907c6","parent_id":null,"name":"Hungary","level":0}
```
Without the "Prefer: plurality=singular" I would get:
```
[
  {
    "id": "14b2581f-bb02-4361-a5f9-533b063907c6",
    "parent_id": null,
    "name": "Hungary",
    "level": 0
  },
  {
    "id": "184d7902-7921-4e0e-bb75-a2e4b65eb657",
    "parent_id": null,
    "name": "Germany",
    "level": 0
  },
  {
    "id": "60f036dc-a383-4c16-a4aa-d82bbdd961a6",
    "parent_id": null,
    "name": "Australia",
    "level": 0
  },
  {
    "id": "41785963-df97-4ce1-8449-80871f812e0e",
    "parent_id": null,
    "name": "Spain",
    "level": 0
  },
  {
    "id": "368dd4f0-5bd9-40ec-a3df-751e50383a2b",
    "parent_id": null,
    "name": "France",
    "level": 0
  }
]
```
I am hoping to get:
```
{
  "14b2581f-bb02-4361-a5f9-533b063907c6":{
    "id": "14b2581f-bb02-4361-a5f9-533b063907c6",
    "parent_id": null,
    "name": "Hungary",
    "level": 0
  },
  "184d7902-7921-4e0e-bb75-a2e4b65eb657": {
    "id": "184d7902-7921-4e0e-bb75-a2e4b65eb657",
    "parent_id": null,
    "name": "Germany",
    "level": 0
  },
  "60f036dc-a383-4c16-a4aa-d82bbdd961a6": {
    "id": "60f036dc-a383-4c16-a4aa-d82bbdd961a6",
    "parent_id": null,
    "name": "Australia",
    "level": 0
  },
  "41785963-df97-4ce1-8449-80871f812e0e": {
    "id": "41785963-df97-4ce1-8449-80871f812e0e",
    "parent_id": null,
    "name": "Spain",
    "level": 0
  },
  "368dd4f0-5bd9-40ec-a3df-751e50383a2b": {
    "id": "368dd4f0-5bd9-40ec-a3df-751e50383a2b",
    "parent_id": null,
    "name": "France",
    "level": 0
  }
}
```

**Comment by ludwigschubert** [comment]
_/opinion: That looks like data duplication to me and seems like it should be a client-side transformation._

That being said, I'm also interested in how one could best handle such transformations in Postgrest—or whether Postgrest should explicitly not handle such transformations as they aren't considered restful?

**Comment by ruslantalpa** [comment]
@rkoberg @ludwigschubert 
Short answer, you can't and i don't think it will ever be possible because you can request rows and not include the primary key and then you can't generate the json object. This transformation should be done by the client if needed

Long answer 
Each postgrest request returns rows, the datastructure to represent that is arrays/lists
You are probably using a map/object because somewhere in your code you want to have random access, but if you don't have something like `mapstore.getById('id here')` then you don't need the map structure, the view should just map over the list and render the output.

as for view refresh, i don't understand why you would have reloads when doing the transformation, that should be done when you get the data back from postgrest, i.e 
instead of 
```
.then(response => fromJS(response.json()))
``` 
you should have
```
.then(response => fromJS(transform(response.json())))
```

**Comment by rkoberg** [comment]
OK, thanks for the explanations. I have been using some NoSQL DBs (e.g. Firebase, RethinkDB), and the data was stored and returned that way. I guess I was looking for a convenience feature in postgREST. 
(I am using: ```Immutable.Map(myList.map(v => [v['id'], v])))```. So I do do the transform on the client. I saw this causing a ReactJS rerender when the data came in _again_, but had not changed. I probably need to use ImmutableJS in some different way so React does not see the data as changed.)

**Comment by ruslantalpa** [comment]
Even if the data would come from postgrest as you described, the refresh would still happen because
`fromJs({a:1}) !== fromJs({a:1})` the same way as `{ foo: "bar" } !== { foo: "bar" }`

**Comment by ruslantalpa** [comment]
If don't need random access, i.e. each time you just go over each item and render it then don't use the Map, use List. List is faster when each time you go over each element in sequence.

**Comment by ruslantalpa** [comment]
(if this answers your questions please close the issue)

**Comment by rkoberg** [comment]
I need random access (finding region ancestors in my example response above where there can be several thousands of regions). Immutable.is ( https://facebook.github.io/immutable-js/docs/#/is ) used in a pure render should be seeing no changes, so need to figure that out. Anyway, closing since it is all off topic.
