### ISSUE TITLE
How to build it on centos 6 with 64 bit

### ISSUE THREAD

**Issue by zyhnjust** [begriffs/postgrest#633]
I would like to get it work on centos6. It is very hard for customer to upgrade to centos7. 
But I did not find an installer. 
Could you help to provide an install or a guide how to get one on centos6? 

The home page only introduce how to do it from source in ubuntu. But it does not work on centos 6. 
I installed ghc, haskell-platform  - configure/make install. And I cloned code for postgrest. 
Then I can not use stack. Not sure whether anything I missed? 
[postgrest]# stack build --install-ghc
-bash: stack: command not found

Could someone help?

**Comment by daurnimator** [comment]
You need to install stack. http://docs.haskellstack.org/en/stable/install_and_upgrade/#centos-red-hat-amazon-linux

**Comment by ruslantalpa** [comment]
first remove everything you just installed.
then install stack like described here
http://docs.haskellstack.org/en/stable/install_and_upgrade/#centos

then do this
```
git clone https://github.com/begriffs/postgrest.git
cd postgrest
stack build --install-ghc
sudo stack install --allow-different-user --local-bin-path /usr/local/bin
```

**Comment by zyhnjust** [comment]
Verify appriciated. 
But I have an issue to download linux version. Is that possible to download it from somewhere other? 
I need to download this one 
 Linux 64-bit, libgmp4    :(

**Comment by ruslantalpa** [comment]
I don't understand what you mean by linux version. Please paste the commands you executed and the output

**Comment by begriffs** [comment]
There is a prebuilt CentOS 6 binary now available in the latest release. https://github.com/begriffs/postgrest/releases/tag/v0.3.2.0

Try it out and let me know if it works, and we can then close this issue.

**Comment by begriffs** [comment]
(Assuming the binary worked)
