### ISSUE TITLE
Wrong HTTP Status Code if role cannot write into table

### ISSUE THREAD

**Issue by d-winter** [begriffs/postgrest#635]
When I send a POST request with a user successfully authenticated via JWT without having write permissions on the current table for this role, the returned HTTP status code is 404, not 403.

Example Response:

```
{
    "hint": null,
    "details": null,
    "code": "42501",
    "message": "permission denied for relation Items"
}
```

**Comment by begriffs** [comment]
This has been fixed on master actually, see the [changelog](https://github.com/begriffs/postgrest/blob/master/CHANGELOG.md). I'll be making a new release tomorrow or over the weekend.
