### ISSUE TITLE
Reject JWT without exp field

### ISSUE THREAD

**Issue by fab1an** [begriffs/postgrest#638]
Is something like this possible for security reasons?

**Comment by ruslantalpa** [comment]
Where would those JWT's come from? Since you are the one generating them, why would you generate them without exp and them reject them in postgrest?

**Comment by fab1an** [comment]
What if you create them by accident? I'm new to JWT and when I started playing around with postgrest I created them without `exp` intiailly. That code never got to production, but i'm a little concerned about the impossibility to invalidate them (without going stateful).

**Comment by ruslantalpa** [comment]
Fixing the mistake is easy, restart postgrest with a different secret.
Stateless is the whole point to to jwt. You add the exp and when needed, you blacklist certain jwt's (before they reach postgrest).
Read a bit more about jwt and try to better understand, they are not session ids and you can't use them like that. And the data encoded in them is not a secret, everyone can see it but they can't change it.
One way would be to assign to each user a key (random long string), the jwt contains that field and user id. Your RLS rules should check that the user still has that key associated with them. When you want to deny access to an old jwt, you change that key and the rls rules will deny  access to any rows (until the jwt expires altogether)

**Comment by fab1an** [comment]
Sounds good. I've read a couple of articles (like this one: http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/)

But I don't see why I should not use them as sessions for a mobile API. I have just a role and a userId in them.

**Comment by daurnimator** [comment]
> Read a bit more about jwt and try to better understand, they are not session ids and you can't use them like that.

They *can* be stateless. They don't *have* to be.
It's perfectly valid to use JWTs as a middle ground between all session data in the database and server-stateless-ness.

**Comment by begriffs** [comment]
Since you control the JWTs generated and can include `exp` I'm closing this issue.

**Comment by shanakadu** [comment]
I have include the exp in the claims, but the payload of the token receive is empty. If i add any other field, it work, but with exp, fail. Strange behaviour...

**Comment by begriffs** [comment]
I think the exp has to be an int. Is yours a string?

**Comment by shanakadu** [comment]
Thanks, it´s true, is an int, and works now.
