### ISSUE TITLE
java.net.SocketException: Too many open files

### ISSUE THREAD

**Issue by ratheeshcitrus** [begriffs/postgrest#642]
I am Using Postgrest to communicate with the Postgres Database,My Application is a real-time monitoring system , which sends continues requests to the Postgrest , But While using this which throws the error Too many open files,
While checking in google  I got the reason something like "the socket connections are treated like files and they use file descriptor, which is a limited resource".

Is there any issues with the closing of socket connections, or can you please recommend any solution for reducing the number of connections.

**Comment by begriffs** [comment]
Hmm, that's not good. Let's figure it out.

* Which version of postgrest are you using? (Check for the contents of the `Server` response header when you send it a request)
* Which operating system?
* Which version of postgresql?
* What value do you get if you run `psql -c 'show max_connections;'`?
* What command line arguments are you passing to postgrest?

**Comment by ratheeshcitrus** [comment]
Postgrest Version : postgrest-0.2.11.1 
OS: Ubuntu 14.04.3 LTS, 1GB RAM, 1CPU
psql (PostgreSQL) version: 9.5.0
max_connections : 100
command line arguments: /opt/postgrest-0.2.11.1 --db-host <IP Addess> --db-port 5432 --db-name <DB Name> --db-user <Username> --db-pool 200 --anonymous <User Name> --port 3002

**Comment by ruslantalpa** [comment]
@ratheeshcitrus 
- how many clients are connected to postgrest at the same time? are they closing the connection after each request?
- check your file descriptor limit, maybe it's too low http://serverfault.com/questions/208916/understanding-max-file-descriptors-for-linux-and-nginx-and-best-value-for-worke
- put postgrest behind nginx (you should anyway if the service is open to the internet) and see if this fixes things for you

**Comment by begriffs** [comment]
@ratheeshcitrus did you find a solution for this problem?

**Comment by begriffs** [comment]
@ratheeshcitrus I notice you were using `db-pool 200` which exceeds the max connections of 100. Try lowering the value. Also try the new postgrest 0.4.

I'm closing this issue because it is old, but if you're still having the problem them please re-open it.
