### ISSUE TITLE
post request through php curl return errors

### ISSUE THREAD

**Issue by darsana** [begriffs/postgrest#643]
Hi..
I updated my postgrest library with the  version v0.3.2.0  ,i was using the  postgrest-0.2.11.1 -it was working fine while using post request through the php curl . in the new version  i am getting error for the post request  while using php curl for the communication .Its working fine when i tried the same request using postman.

request 
-----------
http://192.168.1.186:3000/party
{"party_name":"test","party_type_id":3,"created_at":"2016-06-16 12:36:17","created_at_tz"
:"UTC","created_at_gmt":"2016-06-1612:36:17","created_session_id":91,"lock_version":0,"record_status_id":1}

Error response 
-----------
HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Date: Thu, 16 Jun 2016 12:42:14 GMT
Server: postgrest/0.3.2.0
Content-Type: application/json

{"hint":null,"details":null,"code":"42703","message":"column \"{\"party_name\":\"test\",\"party_type_id
\":3,\"created_at\":\" of relation \"party\" does not exist"}

**Comment by ruslantalpa** [comment]
1) confirm the exact same php code works in 2.11 (run 2 instances of postgrest on 2 ports)
2) paste the php code here after you confirmed it works in 2.11 but not in 3.2

**Comment by darsana** [comment]
version--0.2.11.1

http://192.168.1.186:3000/party

{"party_name":"test-old","party_type_id":3,"created_at":"2016-06-16
 13:27:36","created_at_tz":"UTC","created_at_gmt":"2016-06-16 13:27:36","created_session_id":91,"lock_version"
:0,"record_status_id":1}

response
-----------------
HTTP/1.1 201 Created
Transfer-Encoding: chunked
Date: Thu, 16 Jun 2016 13:26:15 GMT
Server: postgrest/0.2.11.1
Content-Type: application/json
Location: /party?id=eq.1059


version v0.3.2.
---------------------
HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Date: Thu, 16 Jun 2016 13:30:49 GMT
Server: postgrest/0.3.2.0
Content-Type: application/json

{"hint":null,"details":null,"code":"42703","message":"column \"{\"party_name\":\"test-old\",\"party_type_id
\":3,\"created_at\":\"2016-0\" of relation \"party\" does not exist"}


Its is working fine in 2.11,There is no change in code

**Comment by ruslantalpa** [comment]
paste the code

**Comment by darsana** [comment]
This is the php curl function that i am using now .Inside comment tag u can see the url and the data i am using 
function curlHttpPost($url, $postData)
    {        

         /* 
         $url= "http://192.168.1.186:3000/party";
          $postData=     {"party_name":"test","party_type_id":3,"created_at":"2016-06-16 12:36:17","created_at_tz"
        :"UTC","created_at_gmt":"2016-06-16 12:36:17","created_session_id":91,"lock_version":0,"record_status_id"
        :1}
        */
        $postData = json_encode($postData);
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
        curl_setopt($ch, CURLOPT_POST, count($postData));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);
        $response  = curl_exec($ch);
        //print_r($response);die();
        $curl_info = curl_getinfo($ch);
        $headers   = substr($response, 0, $curl_info["header_size"]);   
        preg_match("!\r\n(?:Location|URI): *(.*?) *\r\n!", $headers, $matches);     
        if (count($matches) > 0) {
            if ($matches[1]) {
                preg_match("!(?:=eq)\.([^\r\n]*)?!", $matches[1], $match);
                return ($match[1]);
            }
        }
        curl_close($ch);   
        
    }

**Comment by ruslantalpa** [comment]
add `curl_setopt($ch, CURLOPT_HTTPHEADER,     array('Content-Type: application/json'));`

**Comment by darsana** [comment]
Haii....

Its working fine...Thank you.... :+1:

**Comment by ruslantalpa** [comment]
Close please :)
