### ISSUE TITLE
two DBs, one postgrest: running postgrest server with same post is *only* looking for first DB

### ISSUE THREAD

**Issue by rkoberg** [begriffs/postgrest#646]
I had a DB named 'fwi' and ran postgrest using that. [stopped postgrest] I created another DB and ran postgrest using the new DB.

Here is what happens when running postgrest with the new DB using the api http port 3000  (500 status code). No other postgrest api servers are running.
```
$ postgrest postgres://rkoberg:@127.0.0.1:5432/rihpl -a rkoberg -s public -p 3000
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 3000
127.0.0.1 - - [16/Jun/2016:16:23:15 -0700] "GET /regions HTTP/1.1" 500 - "" "Apache-HttpClient/4.4.1 (Java/1.8.0_76-release)"
````
giving the JSON response:
```
{"details":"FATAL:  database \"fwi\" does not exist\n","code":"","message":"Connection error"}
```
Is there some caching happening somewhere?

If I start postgrest with a different port (3001 -- all other properties the same) for the api server, it works (206 status code):
```
$ postgrest postgres://rkoberg:@127.0.0.1:5432/rihpl -a rkoberg -s public -p 3001
WARNING, running in insecure mode, JWT secret is the default value
Listening on port 3001
127.0.0.1 - - [16/Jun/2016:16:22:36 -0700] "GET /regions HTTP/1.1" 206 - "" "Apache-HttpClient/4.4.1 (Java/1.8.0_76-release)"
```

**Comment by rkoberg** [comment]
I should have added I am running the release 0.3.2.0 version of postgrest, postgres (PostgreSQL) 9.5.3, and postgrest was running on port 3000 when I ran it with the 'fwi' DB.

**Comment by ruslantalpa** [comment]
no caching anywhere, i'm 99.99% sure the old instance is still running somehow and you are routed to it.
do a ps/killall or try restarting your system to make sure everything is fresh

**Comment by rkoberg** [comment]
Uff... Yes, there was an instance running. Killed it and postgrest worked as expected. Not sure how the process would still have been running (I have been stopping by ```Ctrl+c```). How can a second instance bind to the port if an old instance was already running on it?

**Comment by ruslantalpa** [comment]
cant say ... please close the bug :)
