### ISSUE TITLE
Support JSON keys containing hyphens in RPCs.

### ISSUE THREAD

**Issue by Recmo** [begriffs/postgrest#659]
I am implementing [CSP reporting](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Using_CSP_violation_reports) using a RPC callback.

Such a report looks like:
```
{
  "csp-report": {
    "document-uri": "http://example.com/signup.html",
    "referrer": "",
    "blocked-uri": "http://example.com/css/style.css",
    "violated-directive": "style-src cdn.example.com",
    "original-policy": "default-src 'none'; style-src cdn.example.com; report-uri /_/csp-reports"
  }
}
```

Unfortunately, the standard requires using hyphens in the key name and PostgreSQL does not support using hyphens in named arguments. The standard only allows supplying an URI. Note that in this use case I do not control the request headers.

Possible solutions are:
* Normalize named arguments by replacing `-` with `_` (and perhaps some other chars).
* Allow RPC calls without named arguments, instead taking one verbatim JSON argument.

The later has my preference: it is intuitively simple and can handle all JSON input. It would require some means of deciding whether to map the JSON to named arguments or not. Headers are not an option in my use case. Perhaps we can special case functions that have one named argument `postgrest_raw_json json`.

**Comment by ruslantalpa** [comment]
Why not Zoidberg? :) i mean nginx/opneresty
have a speciall location /rpc/customfn and there get the body of the request, parse the json, change it however you like to fit your rpc function parameters and forward it to postgrest which generates the response

**Comment by Recmo** [comment]
@ruslantalpa Thanks for suggesting OpenResty, it looks interesting.

Adding a pre-processing layer server side would of course solve this. But I'm trying to keep the server side minimal and keep all the logic in the database (which seems to be the spirit of PostgREST).

PostgreSQL has all the tools I need to process raw JSON, if only I can get the raw JSON in there. It seems that a simple feature in PostgREST would allow this.

**Comment by Recmo** [comment]
It works if you double-quote your arguments:

```
CREATE FUNCTION csp_report("csp-report" json) RETURNS void
LANGUAGE SQL
SECURITY DEFINER
AS $$
	INSERT INTO hidden.csp_reports (report)
	VALUES ("csp-report")
$$;
```
