### ISSUE TITLE
/rpc: return 400 for raise 'exception' 

### ISSUE THREAD

**Issue by fab1an** [begriffs/postgrest#661]
I use a lot of `/rpc` functions. Inside of those, I'm raising exceptions and want to return `400` if the client sent syntactically or semantically invalid data. 

Right now `postgrest` returns `500` for most exceptions, especially for the standard `P0001` that is thrown when using `raise 'mymessage'`. 

I think `postgrest` should return `400` for `P0001`:

* instead of the verbose `raise data_exception using message = 'my message'` a simple `raise 'my message'` would work.
* Also I don't think using `data_exception` (which `postgrest` converts to `400`) is correct in my case, but I'm not sure which one to use of the ones listed in the [documentation](https://www.postgresql.org/docs/9.3/static/errcodes-appendix.html).

**Comment by ruslantalpa** [comment]
:+1 for p0001 = 400 (i already do that in mu custom build, should get merged soon)
Until then you can easely add this for yourself (1 line) and compile from source

**Comment by begriffs** [comment]
The P0 class, "PL/pgSQL Error" sounds like a general purpose internal error class to me. You think people are most likely to use `raise 'mymessage'` in response to faulty user input? `raise data_exception ...` seems more explicit.

**Comment by ruslantalpa** [comment]
You dont do that fore the whole clasa, just p00001

**Comment by fab1an** [comment]
@begriffs I think most internal errors would come from invalid casts, selects etc. which postgreSQL throws itself. I think most people would throw raise explicit exception on incorrect usage of the function.
But those error-classes were probably not designed with REST in mind so…

**Comment by begriffs** [comment]
OK, we can change the http code for this error, it's quite easy to do. In fact maybe you want to send a PR for this?

**Comment by fab1an** [comment]
@ruslantalpa do you have a PR for this?

**Comment by ruslantalpa** [comment]
@fab1an, @begriffs added the PR, exactly what i did
