### ISSUE TITLE
message:"invalid byte sequence for encoding \"UTF8\": 0x99" when PATCH with chinese charactor

### ISSUE THREAD

**Issue by ganchsg** [begriffs/postgrest#666]
I create a simple table call testtable with 2 field
    id int, 
    value varchar
I try POST  {"id" : 1, "value" : "香港"} , it result success without any error, after that I try call PATCH
   http://localhost:3000/testtable?id=eq.1   
   { "value" : "香港123"}
it return  message :"invalid byte sequence for encoding \"UTF8\": 0x99"

**Comment by begriffs** [comment]
Thanks for reporting this. I'll add it as a test case to the [UnicodeSpec](https://github.com/begriffs/postgrest/blob/master/test/Feature/UnicodeSpec.hs).

Which version of PostgREST are you using?

**Comment by ganchsg** [comment]
I user postgREST 0.3.1.0 , I just try download the lastest version PostgREST 0.3.2.0 and the bug is SOLVED!. is it any command options or setting, so we can see more detail log, like what SQL is generated or what client request is receive?

**Comment by begriffs** [comment]
Great to hear it's already fixed!

The [CONTRIBUTING.md](https://github.com/begriffs/postgrest/blob/master/CONTRIBUTING.md#issues) file has instructions to find your database logs. Check out the section about reporting issues.
