### ISSUE TITLE
multiple deletes in one request on same table?

### ISSUE THREAD

**Issue by rkoberg** [begriffs/postgrest#668]
Is it possible to make one request against a table and delete multiple records?

**Comment by begriffs** [comment]
Sure, use the `DELETE` HTTP verb instead of the `GET` verb. You can try the GET first to double check what you're about to delete, then change the verb.

**Comment by begriffs** [comment]
The same [filtering](http://postgrest.com/api/reading/#filtering) options used when reading can also be used when deleting.

**Comment by rkoberg** [comment]
Uff... don't know why I did not see that in the docs. Sorry.

**Comment by begriffs** [comment]
No problem!
