### ISSUE TITLE
recursive query possible?

### ISSUE THREAD

**Issue by rkoberg** [begriffs/postgrest#670]
I have a "regions" table like:

```
id  |  name  |  parent_id
```

parent_id references an id in the same table. These URLs seem to be equal: 

```
/regions?id=eq.7dcabff6-4a60-4ef5-b0a5-e22440c69f02&select=*,parent{*}
/regions?id=eq.7dcabff6-4a60-4ef5-b0a5-e22440c69f02&select=*,regions{*}
```

and produce:

```
[
  {
    "id": "7dcabff6-4a60-4ef5-b0a5-e22440c69f02",
    "parent_id": "5401a69a-687b-4103-9f20-efcfb7955c51",
    "name": "Mount Barker",
    "level": 2,
    "parent": {
      "id": "5401a69a-687b-4103-9f20-efcfb7955c51",
      "parent_id": "60f036dc-a383-4c16-a4aa-d82bbdd961a6",
      "name": "Western Australia",
      "level": 1
    }
  }
]
```

Is it possible to make a query select recursively until parent_id is null? (and what would that query be?) 

I don't really want what follows (don't want to manually nest), but this URL produces an error:

```
/regions?id=eq.7dcabff6-4a60-4ef5-b0a5-e22440c69f02&select=*,parent{*,parent{*}}
```

```
{"details":"no relation between parent and parent","message":"could not find foreign keys between these entities"}
```

The following URL does work, but again I don't want to manually nest these:

```
/regions?id=eq.7dcabff6-4a60-4ef5-b0a5-e22440c69f02&select=*,regions{*,regions{*}}
```

which produces:

```
[
  {
    "id": "7dcabff6-4a60-4ef5-b0a5-e22440c69f02",
    "parent_id": "5401a69a-687b-4103-9f20-efcfb7955c51",
    "name": "Mount Barker",
    "level": 2,
    "regions": {
      "id": "5401a69a-687b-4103-9f20-efcfb7955c51",
      "parent_id": "60f036dc-a383-4c16-a4aa-d82bbdd961a6",
      "name": "Western Australia",
      "level": 1,
      "regions": {
        "id": "60f036dc-a383-4c16-a4aa-d82bbdd961a6",
        "parent_id": null,
        "name": "Australia",
        "level": 0
      }
    }
  }
]
```

**Comment by ruslantalpa** [comment]
just saying "i don't want to" is not a valid reason to give against a solution, especially in a situation when it seems the depths of your tree is limited (i am surprised this even works)

**Comment by ruslantalpa** [comment]
as for the `parent` error, there is a bugfix that is not merged yet

**Comment by rkoberg** [comment]
OK, I meant to say that I won't know the depth/level of the selected region when making the request. So I won't know how many nested ```regions{*}``` to use.

**Comment by ruslantalpa** [comment]
make the maximum possible and it should work (get cut on a null value)

**Comment by rkoberg** [comment]
I'll be a monkey's uncle. That works fine :), btw this is what I used:
```
select=*,regions{*,regions{*,regions{*,regions{*,regions{*,regions{*,regions{*}}}}}}}
```

**Comment by begriffs** [comment]
As a further note, I think you could get unbounded recursion by making a view which utilizes the `WITH RECURSIVE` CTE construction, as demonstrated [here](http://www.practiceovertheory.com/blog/2013/07/12/recursive-query-is-recursive/).

**Comment by jmealo** [comment]
@rkoberg: I second @begriffs about using `WITH RECURSIVE` these blog posts could prove helpful:
- http://gbif.blogspot.com/2012/06/taxonomic-trees-in-postgresql.html
- http://schinckel.net/tags/tree/

**Comment by ruslantalpa** [comment]
I think this is answered/solved
