### ISSUE TITLE
Location Header Returning Full Object

### ISSUE THREAD

**Issue by wkrause13** [begriffs/postgrest#671]
I am using Postgrest v0.3.2.0 to insert data into a table with an admin role, no security is enabled and I am not using a view. However, for all of my tables, the location header is returning the entire object, rather than just the primary key. For some tables this results in a header that is too large for Nginx's default buffer size, but in general this is not the desired behavior for any of the tables. I believe the intended functionality is for Postrgrest to return a header with the primary key when it is available.  Per https://github.com/begriffs/postgrest/issues/217 I ran the following sql:
```PLpgSQL
select kc.column_name
      from
        information_schema.table_constraints tc,
        information_schema.key_column_usage kc
    where
      tc.constraint_type = 'PRIMARY KEY'
      and kc.table_name = tc.table_name and kc.table_schema = tc.table_schema
      and kc.constraint_name = tc.constraint_name
      and kc.table_schema = 'v0'
      and kc.table_name  = 'sources'
```

Which resulted in:
```
 column_name 
-------------
 id
```

My table was created using the following:

```SQL
CREATE TABLE v0.sources
(
    id integer NOT NULL DEFAULT nextval('v0.sources_id_seq'::regclass),
    name text,
    url text,
    language integer,
    CONSTRAINT sources_pkey PRIMARY KEY (id),
    CONSTRAINT sources_url_key UNIQUE (url)
)
```

Finally, here's an example location header that get's returned. 
```
/sources?id=eq.6&name=eq.BBC%20Mundo&url=eq.http%3A%2F%2Fwww.bbc.com%2Fmundo5&language=eq.5692
```

**Comment by begriffs** [comment]
This is definitely not the intended behavior. I'm wondering if postgrest failed to detect the primary key. Did you change the schema while the server was running? The server caches the db structure on startup so if changes happen later you have to refresh its cache by either sending `SIGHUP` to the postgrest process or restart the server entirely.

Before doing either of those things try requesting `OPTIONS /sources` so see what postgrest thinks the structure is. Then try the SIGHUP and send an options request again to see if it changed.

**Comment by wkrause13** [comment]
Ah, I did change the schema without restarting Postgrest. I bounced the process and it resolved the issue. Thanks so much, @begriffs!

**Comment by begriffs** [comment]
This restriction has bitten so many people...I wish there was a way to point it out better because it can be really confusing.

**Comment by rkoberg** [comment]
Create a file named "ISSUE_TEMPLATE" at the root of this project with:
```
<!--
Have you changed your DB schema? Did you restart postgREST? (do that first)
-->
```
:)
