### ISSUE TITLE
OPTIONS request returns 404 Not Found

### ISSUE THREAD

**Issue by wildsurfer** [begriffs/postgrest#673]
I have a working configuration with some tables that work just perfectly. But I have faced an issue that I'm not sure how to deal with. When I create new table everything works as expected except OPTIONS request that just return '404 Not Found'. Old tables are working with OPTIONS just fine.

My table:
```
CREATE TABLE public.test
(
  id bigint NOT NULL DEFAULT nextval('test_id_seq'::regclass) -- Ololo
);
ALTER TABLE public.test
  OWNER TO guest;
COMMENT ON COLUMN public.test.id IS 'Ololo';
```

Some requests:
```
$ curl -I -X GET http://amw-billing:3000/test
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Thu, 14 Jul 2016 17:01:30 GMT
Server: postgrest/0.3.2.0
Content-Type: application/json; charset=utf-8
Content-Range: 0-0/1
Content-Location: /test

$ curl -I -X OPTIONS http://amw-billing:3000/test
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Date: Thu, 14 Jul 2016 17:01:35 GMT
Server: postgrest/0.3.2.0

```

postgrest version is v0.3.2.0, postgresql is 9.5.3. I run both in docker containers.

There are no any error messages as I can see. Thoughts?

**Comment by ruslantalpa** [comment]
Restart PostgREST on every schema change (please close)

**Comment by begriffs** [comment]
Either restart or send the SIGHUP signal to the process. (That allows you to avoid any downtime)
