### ISSUE TITLE
Getting Bad Request response for the queries with the greater than operator 

### ISSUE THREAD

**Issue by darsana** [begriffs/postgrest#676]
Hi...

When i tried to run the query like below ,but getting responds like **Bad Request**

http://192.168.1.186:3000/user_details_project?RecordStatusId=eq.1&CreatedAt=gte.'2016-05-21 00:00:00'&CreatedAt=lte.'2016-07-20  23:59:59'

but the for the queries like below  getting the results 
http://192.168.1.186:3000/user_details_project?ParyRelationStatus=eq.1 

here is the cURL Requests with PHP that i am using ,What may be the issue ? 

function curlHttpGet($url, $request_headers = "")
    {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        if ($request_headers != "") {
            curl_setopt($ch, CURLOPT_HTTPHEADER, $request_headers);
        }
        $data = curl_exec($ch);
        if (!curl_errno($ch)) {
              return $data;
        } else { 
            return 'Curl error: ' . curl_error($ch);
        }
        curl_close($ch);
    }

**Comment by ruslantalpa** [comment]
do not quote the dates

**Comment by darsana** [comment]
Tried that way too..getting the same response ..

**Comment by ruslantalpa** [comment]
please try the request in the browser first (postman) 
add post here the request and the response you are getting (maybe also the definition of the table)

**Comment by darsana** [comment]
Got the result when i removed the time part of the date , query example like below.

http://192.168.1.186:3000/user_details_project?RecordStatusId=eq.1&CreatedAt=gte.'2016-05-21'&CreatedAt=lte.'2016-07-20'

[
  {
    "ProjectId": 2,
    "RelationId": 3,
    "PersonId": 4,
    "FirstName": "xxxxxx",
    "LastName": "k",
    "AlternativeEmail": null,
    "UserEmail": "xxxx@xxx.com",
    "StatusId": 1,
    "Status": "Active",
    "CreatedAt": "2016-06-06 12:02:43",
    "CreatedTimeStampUTC": "1465214563000",
    "RecordStatusId": 1,
    "OrganizationPartyId": 92,
    "ParyRelationStatus": 1
  }
]

using postman getting result for  both the cases .
