### ISSUE TITLE
lt+gt on json field: string comparison even if casted to ::int

### ISSUE THREAD

**Issue by ptica** [begriffs/postgrest#678]
Hi, awesome project!
however I could not get int comparison working on json fields, what did I do wrongly?
![screen shot 2016-07-21 at 12 57 14](https://cloud.githubusercontent.com/assets/169873/17020619/e75a8276-4f42-11e6-8397-71296b86f1c8.png)

**Comment by ruslantalpa** [comment]
while in `&select` you can do `::int`, you can not use that when filtering like you did, `attributes->>end::int`. If the `end` is an int, then just remove the casting, if it's string then there is no way to compare it as an int unless you create a view based on that table that extracts `end` as a column and casts it to int

**Comment by ptica** [comment]
I see,
thank you!

**Comment by steve-chavez** [comment]
In case someone stumbles into this, comparison with `jsonb` has been working since the addition of https://github.com/PostgREST/postgrest/pull/1128.

Example:

```sql
create table sample(data jsonb);
insert into sample values ('{"a": 3}', '{"a": 4}', '{"a": 5}');
```

```bash
curl "localhost:3000/sample?data->a=lte.4"

[{"data":{"a": 3}},
 {"data":{"a": 4}}]
```

Note the single arrow head operator `->`.
