### ISSUE TITLE
Getting error response for the post request

### ISSUE THREAD

**Issue by darsana** [begriffs/postgrest#679]
Post api  giving error response ,Tried to Post API giving error like below ,Get request giving proper response .Direct insertion to the table is also working properly 

http://192.168.1.186:3000/party 

SessionError (ResultError (ServerError "XX000" "cache lookup failed for foreign server 32434" Nothing Nothing))

**Comment by ruslantalpa** [comment]
the error comes from postgresql, not postgrest. seems to be related with FDW
