### ISSUE TITLE
possible to resolve multiple entities from same record to same table

### ISSUE THREAD

**Issue by rkoberg** [begriffs/postgrest#680]
I have a table of regions like:
```
id  |  parent_id  |  name  | level
```
I have a table that maps these regions to wines - "wine_regions", like:
```
id  |  wine_id  |  region_0_id  |  region_1_id  |  region_2_id  |  region_3_id  |  region_4_id  |  region_5_id  |  region_6_id  |
```
All of the region_n_id columns are constrained to the above table's region.id. A request like:
```
/wines?id=eq.27722&select=*,regions{value:id,label:name,level,parent_id},wine_regions{*}
```
gives all from wine_regions, but only resolves the first region (region_0_id, which is the only one that has a NOT NULL constraint) from the "regions" table. For example:
```
[
  {
    "id": 27722,
    "name": "Abreu Vineyard Cappella Proprietary Red, Napa Valley, USA",
    "pronounce_audio": null,
    "image": null,
    "producer_id": null,
    "variety_id": 3,
    "regions": [
      {
        "value": 1264,
        "label": "USA",
        "level": 0,
        "parent_id": null
      }
    ],
    "wine_regions": [
      {
        "id": 486,
        "wine_id": 27722,
        "region_0_id": 1264,
        "region_1_id": 1273,
        "region_2_id": 1333,
        "region_3_id": 1357,
        "region_4_id": 1358,
        "region_5_id": null,
        "region_6_id": null
      }
    ]
  }
]
```

Is there some way to make this work to resolve all of the regions?

**Comment by rkoberg** [comment]
Alternatively, I have a view like:
```
 SELECT wine_regions.wine_id,
    r0.name AS region_0,
    r1.name AS region_1,
    r2.name AS region_2,
    r3.name AS region_3,
    r4.name AS region_4,
    r5.name AS region_5,
    r6.name AS region_6
   FROM wine_regions
     LEFT JOIN regions r0 ON wine_regions.region_0_id = r0.id
     LEFT JOIN regions r1 ON wine_regions.region_1_id = r1.id
     LEFT JOIN regions r2 ON wine_regions.region_2_id = r2.id
     LEFT JOIN regions r3 ON wine_regions.region_3_id = r3.id
     LEFT JOIN regions r4 ON wine_regions.region_4_id = r4.id
     LEFT JOIN regions r5 ON wine_regions.region_5_id = r5.id
     LEFT JOIN regions r6 ON wine_regions.region_6_id = r6.id;
```
"wine_regions.wine_id" has a constraint using the wines table ID - "wines.id". A request like:
```
/wines?id=eq.27722&select=*,wine_regions{*},wine_region_names{*}
```
gives an error:
```
{"details":"no relation between wines and wine_region_names","message":"could not find foreign keys between these entities"}
```

**Comment by rkoberg** [comment]
Sorry, posted too soon :) got it working with:
```
/wines?id=eq.27722&select=*,wine_regions{region_0_id{*},region_1_id{*},region_2_id{*},region_3_id{*},region_4_id{*},region_5_id{*},region_6_id{*}}
```
Although, I would be happy to know if there is a better request or a better way to structure the DB.

**Comment by ruslantalpa** [comment]
i don't know the domain (like how can a wine belong to more then one region) but it those 3 tables model the problem correctly and the requests gives you back the data you need then i don't see how it can get any better :), i mean you just defined the tables with the constraints and you got back the data you needed.

**Comment by daurnimator** [comment]
> how can a wine belong to more then one region

Mix grapes grown in two different areas.

**Comment by ruslantalpa** [comment]
gitter ...

**Comment by rkoberg** [comment]
Yea... The DB guy changed things on me :) 

The regions are a hierarchy: USA > California > North Coast > Napa County > Napa Valley
