### ISSUE TITLE
Calls to the  Stored Procedure showing error in error logs ..

### ISSUE THREAD

**Issue by darsana** [begriffs/postgrest#684]
Direct call to the Stored Procedure like below returning the proper result

select \*  from "1".statistic_graph_widget('299','Development','2016-06-26','2016-07-26' );

but post call to the procedure like below showing errors ,

POST /rpc/statistic_graph_widget 
HTTP/1.1
Host: 192.168.1.186:3000
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 9567522f-1e83-c3ab-eba7-2a8870bd8741

{"tmp_project_party_id":"299","tmp_release_stage_name":"Development","tmp_start_date":"2016-06-26","tmp_end_date":"2016-07-26"}

ERROR:  function 1.statistic_graph_widget({"tmp_project_party_id":"299","tmp_release_stage_name":"Develop => unknown) does not exist at character 40
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  
                WITH t AS (select \*  from "1"."statistic_graph_widget"("{""tmp_project_party_id"":""299"",""tmp_release_stage_name"":""Development"",""tmp_start_date"":""2016-06-26"",""tmp_end_date"":""2016-07-26""}":=''::unknown) )
                SELECT
                  (select pg_catalog.count(1) from t) as countTotal,
                  pg_catalog.count(1) as countResult,
                  array_to_json(
                    coalesce(array_agg(row_to_json(r)), '{}')
                  )::character varying
                FROM (select \* from t ) r;

**Comment by ruslantalpa** [comment]
can you post the definition of the storred procedure?

**Comment by ruslantalpa** [comment]
make sure the keys like `tmp_project_party_id` match the names of the parameters for that particular function

**Comment by darsana** [comment]
CREATE OR REPLACE FUNCTION "1".statistic_graph_widget(tmp_project_party_id character varying, tmp_release_stage_name character varying, tmp_start_date character varying, tmp_end_date character varying)
 RETURNS SETOF "1".statistic_graph_widget_result_type
 LANGUAGE plpgsql
AS $function$
    DECLARE
          my_type "1".statistic_graph_widget_result_type;
          user_rec "1".statistic_graph_widget_result_type;
            sqlQuery VARCHAR;
       
        BEGIN
            
               sqlQuery = 'SELECT page_view_count, unique_page_count,created_at FROM "1".stat_visits_graph
               WHERE  project_party_id= '''||tmp_project_party_id||''' and release_stage_name = '''||tmp_release_stage_name||''' and created_at between '''||tmp_start_date||''' and  '''||tmp_end_date||''' order by created_at';
   
                    FOR user_rec IN EXECUTE sqlQuery
            
                    LOOP
                         my_type.page_view_count := user_rec.page_view_count;
                    my_type.unique_page_count := user_rec.unique_page_count;
                    my_type.created_at := user_rec.created_at;
                    RETURN NEXT user_rec;
                 
                    END LOOP;
              
              
            
        RETURN;
       
          END;
$function$

**Comment by ruslantalpa** [comment]
@darsana from the output of the error it looks like you sent the json payload as a string, and not as a json, i.e it was
`"{ .....}"` and it should have been `{...}`

**Comment by darsana** [comment]
I am sending the parameters as json encoded data ,Is there any function to display last executed  query in postgrest? below is the function used to send, there is no conversion to string .


    function curlHttpPostRPC($url, $postData)
    {
        $postData = json_encode($postData);
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
        curl_setopt(
            $ch, CURLOPT_HTTPHEADER, array(
               CURL_CONTENT_TYPE
            )
        );
        curl_setopt($ch, CURLOPT_POST, count($postData));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);
        $response = curl_exec($ch);
        $curl_info = curl_getinfo($ch);
        substr($response, 0, $curl_info["header_size"]);
        $header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
        curl_close($ch);
        return substr($response, $header_size);
    }

**Comment by begriffs** [comment]
Check the regular postgres logs to see which statements have been executed:

1. Enable logging for all queries. http://www.microhowto.info/howto/log_all_queries_to_a_postgresql_server.html
2. Find your log files http://blog.endpoint.com/2014/11/dear-postgresql-where-are-my-logs.html

**Comment by SebAlbert** [comment]
Looks like a PHP function, while the quoted request seems to have been posted through Postman. What is the $postData argument when you call the PHP function curlHttpPostRPC? The statement executed by PostgREST looks, like @ruslantalpa mentioned, as if you posted the entire JSON inside a string. This could maybe result from json_encode when $postData already was an encoded JSON string.

**Comment by begriffs** [comment]
@darsana did you figure out the problem?

**Comment by darsana** [comment]
I didn't get the solution for the problem yet..

As i mentioned above my post data  is 

{"tmp_project_party_id":"299","tmp_release_stage_name":"Development","tmp_start_date":"2016-06-26","tmp_end_date":"2016-07-26"},and its not inside a string and i am encoding the data using  json_encode before sending like below
  $postData = json_encode($postData);

**Comment by ruslantalpa** [comment]
@darsana 

change this line
```
$postData = json_encode($postData);
```
to
```
echo gettype($postData);
var_dump($postData);
$postData = json_encode($postData);
echo gettype($postData);
var_dump($postData);

```

execute your function and post back the (complete) output here

**Comment by begriffs** [comment]
@darsana any progress on this issue?

**Comment by begriffs** [comment]
(bump)

**Comment by ruslantalpa** [comment]
I've seen this error recently and it was due to the fact that the content type was not properly set, and form the PHP code above i am not sure what this part does

```
curl_setopt(
        $ch, CURLOPT_HTTPHEADER, array(
           CURL_CONTENT_TYPE
        )
    );
```

make sure you are sending this header `"Content-Type: application/json"`
