### ISSUE TITLE
PostgreSQL DB Stored Procedure argument name always lower case

### ISSUE THREAD

**Issue by Mithrandir21** [begriffs/postgrest#685]
After a lot of trial and error, it seems I have found a somewhat weird issue in the gray array between PostgreSQL and Postgrest.

I will leave up to better men to figure out how to fix/workaround the issue.

When creating a Stored Procedure (might apply in other areas as well, not sure) in PostgreSQL, **all function arguments are stored in lowercase**, regardless of the argument case in the procedure creation script.

### Example:
> CREATE FUNCTION somefunc(HappY int)

In this example, the argument will be stored in the PostgreSQL DB as "happy".

### The issue:
It seems Postgrest has too much respect and respects the case of a field in any POST.
This means that if you use the field name "HappY", which is a reasonable thing to do, your POST will fail because Postgrest will not find a function "somefunc(HappY int)".

I believe @begriffs said he could downcase all Stored Procedure argument names passed in a POST, so that even if your POST field name is "HappY", Postgrest will look for a function with the argument name "happy".

Any thoughts on this?

**Comment by SebAlbert** [comment]
The SQL specification requires field names etc. to be case-insensitive. PostgreSQL realizes that by lowercasing all identifiers. You can force PostgreSQL to use the case-combination of your choice by enclosing it in double quotes, like so:

`CREATE FUNCTION somefunc("HappY" int)`

**Comment by Mithrandir21** [comment]
Well then.
That seems to have solved that mystery.

Maybe a simple notice or explanation in the docs would be enough.
