### ISSUE TITLE
order embedding entities by embedded value

### ISSUE THREAD

**Issue by rkoberg** [begriffs/postgrest#686]
I see how you can order embedded entities inside their referencing entity, but can you order the embedding entities by embedded values? For example, in the docs there is:
```
GET /projects?select=id,name,tasks{id,name}&order=id.asc&tasks.order=name.asc
```
Is there some way to do (let's say there is only one task per project):
```
GET /projects?select=id,name,task{id,name}&order=task.name.asc
GET /projects?select=id,name,task{id,name}&task.name.order=asc
```
That is, order the projects by the task's name?

**Comment by ruslantalpa** [comment]
No there is not.
What's the usecase?

(generally i would refrain from ordering on the server unless you are doing pagination, use the CPU of the client to order the result)

**Comment by rkoberg** [comment]
Yes, this is for paging after a user requests a particular sorted order. I have several entities that have a 'has one' referencing another entity. To simplify, let's say I have a products table:
```
id   |   title   | variety_id
```
and a varieties table:
```
id  | title    
```
A request would be made to sort a result set (for paging) by variety name. Something like:
```
/products?select=*,variety_id{*}&order=variety_id.title.asc
```
I see I can reverse my thinking and do:
```
/varieties?select=*,products{*}&order=title.desc
```
which groups the products by variety, which kind of gives me what I want. But, I will get a requested range of varieties (the header "Range: `${startItem}-${endItem}`") versus a range of products and that complicates paging.

**Comment by ruslantalpa** [comment]
Postgrest to the rescue.
For this sort of things you do this
For products table, you add a `computed column` called `variety_name`, which is basically a function, you don't actually add a column (if for api you are using a view, you add it to the select section, and also remember to add an index on that column).

Then you can do a sort on that column as if it's part of the table (even though it's a value returned by a function)

This is a example for a computed column called `node_id` defined on the table `products`.
In your case the function will not be immutable but i guess stable, but you get the idea

```sql
create or replace function node_id(projects) returns text as $$
select encode(convert_to('project_' || $1.id::text, 'utf-8'), 'base64')
$$ immutable language sql;
create index on projects (node_id(projects.*));
```

when this function id defined, i can think of it as a column
```sql
select id, name, node_id from projects -- maybe you projects.node_id instead of node_id ... but it works in postgrest
```

**Comment by rkoberg** [comment]
Sweet! I know just enough to be dangerous with SQL and postgres... Wanted to try this out and my guess at a function worked! Here is what the function looks like (the "products" table I used above is actually named "wines"):
```
create or replace function variety_title(wines) returns text as $$
select v.title from varieties as v where v.id=$1.variety_id
$$ immutable language sql;
create index on wines (variety_title(wines.*));
```
(postgres error'd/complained that I needed to use immutable)
And a select looks like:
```
select *, wines.variety_title from wines order by wines.variety_title
```
And an API request looks like:
```
/wines?select=id,title,variety_id{id,title}&order=variety_title.asc
```

**Comment by rkoberg** [comment]
Perhaps off-topic, but of curiousity and in the postgREST world, would you prefer a view over using a function for this type of thing? It looks like I would want an "inline function", but because of the ORDER BY, the function can't be inlined (I am mostly guessing from what I have been reading). From what I have been reading, an EXPLAIN VERBOSE would show the function if inlined, but it shows the function call:
```
explain verbose select * from wines order by wines.variety_title limit 10
```
```
Limit  (cost=196.76..196.79 rows=10 width=2298)
  Output: id, title, pronounce_audio, image, producer_id, variety_id, region_0_id, region_1_id, region_2_id, region_3_id, region_4_id, region_5_id, region_6_id, (variety_title(wines.*))
  ->  Sort  (cost=196.76..198.39 rows=649 width=2298)
        Output: id, title, pronounce_audio, image, producer_id, variety_id, region_0_id, region_1_id, region_2_id, region_3_id, region_4_id, region_5_id, region_6_id, (variety_title(wines.*))
        Sort Key: (variety_title(wines.*))
        ->  Seq Scan on public.wines  (cost=0.00..182.74 rows=649 width=2298)
              Output: id, title, pronounce_audio, image, producer_id, variety_id, region_0_id, region_1_id, region_2_id, region_3_id, region_4_id, region_5_id, region_6_id, variety_title(wines.*)
```

**Comment by egno** [comment]
Dear @rkoberg! 
I've this problem to. And I put a little patch into my postgrest [fork](https://github.com/egno/postgrest/blob/master/CHANGELOG.md)
