### ISSUE TITLE
JWT issue with the generated token from claims.

### ISSUE THREAD

**Issue by shanakadu** [begriffs/postgrest#688]
I will try to explain as best thant i can.
 We have the type 
`CREATE TYPE basic_auth.jwt_claims AS
   (role text,
    email text,
    "time" text,
    exp text);`

But the token than we receive from the login service , it has a empty payload.

If i remove exp field.

`CREATE TYPE basic_auth.jwt_claims AS
   (role text,
    email text,
    "time" text)`

The token works,and i can say more, if we add others fields, the new fields added appears in the payload of the JWT .  We are using posgrest 0.3.2.0.

Any hint?

Thanks in advance.

**Comment by ruslantalpa** [comment]
Exp is a reserved field name in jwt, it needs to be int, not text

**Comment by shanakadu** [comment]
Thanks. It´s work.
