### ISSUE TITLE
Postgres jwt_claims function error handling

### ISSUE THREAD

**Issue by gavin-thompson** [begriffs/postgrest#692]
I use postgrest to run a postgres rpc/login function written in plpythonu, which returns a jwt_claims data type, for generating JWTs for ajax clients.

I am unsure how to handle errors in the function without sensitive information leakage. If the function raises an exception, it is logged in the Postgres log, along with CONTEXT information, which contains the SQL statement that selected the function - including the parameters, in this case the userid and password.

Turning down the logging level in Postgres stops CONTEXT from being logged, but that hides a lot of other potentially useful info.

Catching exceptions in the function and returning null stops sensitive info being logged, but Postgrest generates a JWT with a role of 'null',  and no error condition is sent to the ajax client.

It would be nice to be able to raise an exception (maybe of type warning, rather than error) in the function, have it caught by Postgrest which logs a message without sensitive info, and returns an error to the ajax client. 

Is something like that possible, or is another approach better?

**Comment by begriffs** [comment]
That's not good, I can see how you want to keep passwords etc out of the logs. Can you give me an example of how the logs look and where the sensitive information leaks out?

**Comment by gavin-thompson** [comment]
Extract from Postgres log:

```
2016-08-09 13:55:59  ERROR:  spiexceptions.InvalidPassword: 
2016-08-09 13:55:59  CONTEXT:  Traceback (most recent call last):
          PL/Python function "login", line 30, in <module>
            raise spiexceptions.InvalidPassword
        PL/Python function "login"
2016-08-09 13:55:59  STATEMENT:  
                    WITH t AS (select *  from "public"."login"("userid":='bogus'::unknown,"password":='bogus-password'::unknown) )
                    SELECT
                      (select pg_catalog.count(1) from t) as countTotal,
                      pg_catalog.count(1) as countResult,
                      array_to_json(
                        coalesce(array_agg(row_to_json(r)), '{}')
                      )::character varying
                    FROM (select * from t ) r;
```

**Comment by begriffs** [comment]
What if you did `RAISE WARNING` rather than `RAISE EXCEPTION` in your procedure, and then turned down the logging level in the database to not log warnings?

**Comment by begriffs** [comment]
Did the raising a warning idea work?

**Comment by ruslantalpa** [comment]
errors leaking info seems like the same thing described here https://github.com/begriffs/postgrest/issues/541#issuecomment-319906694

closing as duplicate but at the same time the solution for now seems to be code in the proxy level
