### ISSUE TITLE
Include RPC endpoints in self-generated API docs

### ISSUE THREAD

**Issue by rkoberg** [begriffs/postgrest#694]
I see: https://github.com/begriffs/postgrest/pull/639 - I see that is merged into master - I am running 3.2.0 - is there a release coming soon? If I did start using master (instead of what comes down from a ```brew install postgrest```), to get the endpoint data, do you just make a request with ```Accept: application/swagger+json``` or ```Accept: application/openapi+json```

I also see from the API reading doc page: "As well as issuing a GET / to obtain a list of the tables, views, and stored procedures available, you can get more information about any particular endpoint."

Should I be able to see functions like /rpc/login, /rpc/signup? (like described in the example auth - http://postgrest.com/examples/users/ ) I don't see those in a GET request to the root endpoint. For example, an "anon" user, making a GET request to the root endpoint, sees only the views they have been given permission to (anon does not have access to tables). They don't see anything related to any /rpc methods in that GET request, but can POST to those endpoints to sign up and log in. If I try to make an OPTIONS (any request other than a POST) request on /rpc/login, I get ```<Response body is empty>```. Is there something we need to do when creating the /rpc endpoints so this information get exposed?

Is there someway to get a list of all open/accessible endpoints and their available request methods? (and ideally what those endpoints expect for a successful request - body, headers, ?)

**Comment by begriffs** [comment]
The version on the master branch responds with OpenAPI for the root if you request `Accept: application/openapi+json`. Also #693 will make that the default and you won't have to send any special Accept header.

Currently function calls are not described in the self-generated docs. I'll mark this as an issue for the 0.4 milestone.

**Comment by deinspanjer** [comment]
Thank you @begriffs .  Getting the RPC endpoints into the self-generated API docs will be very useful to me as I am in the process of converting a big chunk of our current views into table returning functions instead.
