### ISSUE TITLE
OpenAPI shows incorrect info for stored proc args with weird names

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#710]
PR #706 uses simplistic parsing to handle the output from `pg_get_function_arguments`. Argument names that contain spaces or escaped characters will not show up correctly. This doesn't affect the ability to actually call the procs, just mangles how they appear in OpenAPI. I cut this corner to move on with other items in the 0.4 release. Let me know if the issue causes you problems and we can write a more robust parser.

**Comment by ruslantalpa** [comment]
This is probably fixed in #885
