### ISSUE TITLE
Special case for functions returning JSON

### ISSUE THREAD

**Issue by nerfpops** [begriffs/postgrest#716]
Currently, this function

```
CREATE OR REPLACE FUNCTION public.dummy()
  RETURNS jsonb AS
$BODY$
    select jsonb_build_object('test', 123);
$BODY$
  LANGUAGE sql;
```
returns `[{"dummy":{"test":123}}]`

I propose that functions with JSON(B) as return type returns the raw json-object, ie. `{"test":123}`

**Comment by nerfpops** [comment]
Related to #600

**Comment by begriffs** [comment]
Postgrest on the master branch returns this when I call your function:

```json
{"test":123}
```

**Comment by nerfpops** [comment]
Wow that's great! Looking forward to the release.
