### ISSUE TITLE
Document foreign key relationships in autogenerated API docs

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#717]
@adambaker requested this in order to make an admin panel for postgrest APIs.

**Comment by ruslantalpa** [comment]
what would this admin panel "administer"?

**Comment by begriffs** [comment]
It would allow the user to see the list of all tables and edit their contents. It would also want to know about fk relationships, so that if you're editing a `Store`, say, the program will know it has `Product`s and will show links to add and edit them.

**Comment by ruslantalpa** [comment]
This can be implemented outside PostgREST as explained here https://github.com/begriffs/postgrest/issues/13#issuecomment-319890673
