### ISSUE TITLE
Switch to normal query from prepared statements on GET requets

### ISSUE THREAD

**Issue by ruslantalpa** [begriffs/postgrest#718]
On this line https://github.com/begriffs/postgrest/blob/master/src/PostgREST/App.hs#L112 we run a prepared statement that has no parameters, everything is hardcoded (for now) in the actual query string.

This creates a suboptimal case for two reasons.
- hasql (probably) calculates a hash of the statement
- postgresql treats this a prepared statement and caches it

The problem with this is that when a server is "hammered" with a lot of requests that seem to be the same thing (only value for filters change) are actually considered different prepared statements and are cached separately thus consuming memory on the database server.
What's worse is that each connection maintains it's own cache thus making the problem worse (imagine 10k useless prepared statements cached per connection, it adds up quite fast).
Until the generated query will be a true prepared statement, we should change how we run queries.

**Comment by ruslantalpa** [comment]
@nikita-volkov from what i see hasql exposes 
- `query (sendParametricQuery)`
- `sql (sendNonparametricQuery)` 

so there is no high level function (in transaction/session context) to send a nonparametric query but for which i want to get a result, am i right?
Any way around this?

**Comment by nikita-volkov** [comment]
Your problem is with prepared statements. Just use the Query abstraction and tell Hasql not to prepare by setting the according flag.

**Comment by ruslantalpa** [comment]
@nikita-volkov pardon my haskell ignorance, how do i do that, how do i run a query and get the result back but have it not be a prepared statement? A link to a small example or to the function/abstraction/flag you are talking about. Thank you

**Comment by ruslantalpa** [comment]
ok, i see something here https://github.com/nikita-volkov/hasql/blob/master/library/Hasql/Private/Query.hs#L54
I'll dig, thank you for mentioning there is a `flag` :)

**Comment by nikita-volkov** [comment]
Just check out the API docs: http://hackage.haskell.org/package/hasql-0.19.15.2/docs/Hasql-Query.html#v:statement

**Comment by ruslantalpa** [comment]
Changing True to False on https://github.com/begriffs/postgrest/blob/master/src/PostgREST/QueryBuilder.hs#L97 fixes the memory consumption issue on the db side
