### ISSUE TITLE
Binaries for RHEL5 / CentOS5

### ISSUE THREAD

**Issue by alternone** [begriffs/postgrest#727]
Hi is there any way to use postgrest on RHEL5 / CentOS5? We need that really to use it on our legacy systems.

Problem: GLIBC 2.5 on RHEL5 but not GLIBC_2.12
/opt/postgrest/postgrest
/opt/postgrest/postgrest: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by /opt/postgrest/postgrest)
/opt/postgrest/postgrest: /lib64/libc.so.6: version`GLIBC_2.10' not found (required by /opt/postgrest/postgrest)
/opt/postgrest/postgrest: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by /opt/postgrest/postgrest)
/opt/postgrest/postgrest: /lib64/libc.so.6: version`GLIBC_2.7' not found (required by /opt/postgrest/postgrest)

Any ideas?

**Comment by ruslantalpa** [comment]
Not sure if that is possible.
Postgrest uses `stack` to compile the project, and stack supports only centos6
https://docs.haskellstack.org/en/stable/install_and_upgrade/#centos
If you could get stack working on centos5 then there is a chance you can get postgrest to compile, otherwise it does not look good.

Another option for you would be if you can get docker installed on centos5, if you have that, you can probably run postgrest inside a container

**Comment by alternone** [comment]
Hi thanks,
I allready looked for stack support of centos5 without success. Needs the same GLIBC dependencies. Docker is also not compatible. Current ugly workaround idea is a small virtual box instance running only postgrest.

**Comment by ruslantalpa** [comment]
Can you explain why you can not run postgrest on another os, a separate (low resource) box just for postgrest?

If you really really need this, you can also go lower then stack, straight to cabal.
stack only downloads all the dependencies and makes sure they are compatible, but in the end it uses cabal to compile. you can try and see what is the newest ghc/cabal that will compile on centos5 then download all the dependencies of postgrest manually and try to compile with cabal directly

**Comment by begriffs** [comment]
I tried compiling for Centos 5 tonight and it's not easy got a lot of things installed but having trouble with the cert CA.

```
# stack build
Downloading lts-7.4 build plan ...HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/fpco/lts-haskell/master//lts-7.4.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa))))
```

**Comment by ruslantalpa** [comment]
Closing this since it will be hard to compile for such an old system (12 April 2007) without stack supporting it
