### ISSUE TITLE
postgrest.conf

### ISSUE THREAD

**Issue by jhr007** [begriffs/postgrest#731]
1) Does the `postgrest.conf` get generated  with the defaults if it doesn't exist?

2)
[Dockerfile#L14-L15](https://github.com/begriffs/postgrest/blob/master/Dockerfile#L14-L15)
In the Dockerfile it says postgrest reads from `/etc/postgrest.conf`. 

Is it too late to change to `/etc/postgrest/postgrest.conf` for Docker users?

Docker lets you mount a directory inside the container, but not individual files. 

So to mount a volume that would have `/etc/postgrest.conf`, I would have to mount a docker volume to `/etc`.  This means I would also be storing everything else in `/etc` in the docker volume.  

I also think lines 14-15 should be removed, or at least replaced with a link to a single source of truth.

**Comment by begriffs** [comment]
The Dockerfile is out of date and the comment is a lie. Postgrest now requires a `-c` argument to specify the path to the configuration file. There is no default conf file location. Also postgrest will not create a file if none exists at a given path, although you can specify `--example-config` to get an example file printed to stdout.

**Comment by jhr007** [comment]
lol'd @ 'the comment is a lie' ... Fixed with #732 

Yea, My haskelese is pretty rudimentary. I couldn't find a magic string `/etc/postgrest.conf` in the code, and I just wanted to make sure the comment was wrong. 

Regarding the Docker builds, I still think there should be a default config location so Docker consumers can pass their config file into the container without having to be concerned about the container's internals.

My experience using other Docker images has been a matter of finding out what directories the config and data use, usually found on the Docker hub page. I then mount a volume at `/etc/postgrest/` and no longer care about how the docker container runs, but I know everytime the docker container runs it finds my config file. 

Since this is a docker image built on Ubuntu, I don't think hardcoding a location in the Dockerfile is a concern. 

Since there isn't an init script, maybe in the Dockerfile: 
`RUN exec postgrest -c ${POSTGREST_CONFIGFILE-'/etc/postgrest/postgrest.conf'}` 
which uses Bash variable expansion to use an environmnet variable or a default.

**Comment by ruslantalpa** [comment]
@jhr007 you can mount specific files, not only directories (in docker)

**Comment by jhr007** [comment]
@ruslantalpa [Ooops](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume)

Defaulting the Dockerfile to look for the config  in `/etc/postgrest/` would handle both cases.  

Closing this issue and moving it to the more appropriate issue #730.
