### ISSUE TITLE
View without JWT: unrecognized configuration parameter

### ISSUE THREAD

**Issue by fab1an** [begriffs/postgrest#734]
In my test-suite, when I hit a view without a valid JWT I get 

```
400 Bad Request:

{
  "hint": null,
  "details": null,
  "code": "42704",
  "message": "unrecognized configuration parameter \"postgrest.claims.userId\""
}
```

And when I run the test-suite a couple of times I get what I want:

```
401 Unauthorized

{
  "hint": null,
  "details": null,
  "code": "42501",
  "message": "permission denied for relation my_view"
}
```

Is this cached somehow?

The view is more or less:

```sql
create view schema.my_view as
    select * from internal_myView
    where assignedTo = current_setting('postgrest.claims.userId')::int;
```

**Comment by ruslantalpa** [comment]
run this
`alter database app set postgrest.claims.userId to '';`

**Comment by fab1an** [comment]
When?

**Comment by ruslantalpa** [comment]
now :)
every claim that you use in your jwt/views needs to have a default value for the cases when it does not come from the jwt so that the view/functions trying to access it do not throw errors

**Comment by fab1an** [comment]
That works, only now I get "invalid input syntax for integer", because I'm casting the '' to an int. Is there a way to specify a null?

**Comment by ruslantalpa** [comment]
use this type of function
https://github.com/ruslantalpa/sub0_sample_app/blob/master/sql/1_functions.sql#L11-L17

**Comment by ruslantalpa** [comment]
The name of the env vars changed a bit
Use this convenience lib to get the values
https://github.com/subzerocloud/postgrest-starter-kit/blob/master/db/src/libs/request/schema.sql
