### ISSUE TITLE
Created a Postgres to SNS service

### ISSUE THREAD

**Issue by matthewmueller** [begriffs/postgrest#743]
Inspired by the Postgres to RabbitMQ bridge described in the docs, I just created one for Amazon SNS:

https://github.com/matthewmueller/pg-sns-bridge

Just thought I'd share ✨

**Comment by begriffs** [comment]
Excellent, I'll add a note about it to the new docs!

**Comment by begriffs** [comment]
I created a section about external notifications in our new docs and included pg-sns-bridge

https://postgrest.readthedocs.io/en/v0.4/intro.html#ecosystem

**Comment by matthewmueller** [comment]
thanks! the docs are really shaping up :-)

**Comment by begriffs** [comment]
(I updated the name just now)
