### ISSUE TITLE
Example postgrest.conf

### ISSUE THREAD

**Issue by matthewmueller** [begriffs/postgrest#744]
Hey guys, 

I'm having a hard time figuring out what the format of the `postgrest.conf` file looks like. Are there any links to examples anywhere or just some information to get me started?

**Comment by ruslantalpa** [comment]
https://github.com/begriffs/postgrest/blob/master/src/PostgREST/Config.hs

**Comment by ruslantalpa** [comment]
Or just run it without params and get an example

**Comment by matthewmueller** [comment]
Ahh okay great, there it is: https://github.com/begriffs/postgrest/blob/4df853eff9bff6efa72436fb6331448c88fb2713/src/PostgREST/Config.hs#L144-L165

> Or just run it without params and get an example

Is that on 0.4.0.0? Has that been released yet? Actually just realized that there isn't support for a conf file on 0.3.2.0 i don't think.

**Comment by ruslantalpa** [comment]
since you said config file i thought you meant you have built it from source. 3.2 doe snot have a config file, only 4.0 which is not yet released

**Comment by ruslantalpa** [comment]
(please close)

**Comment by begriffs** [comment]
That's the, the config file is specific to v0.4 only, which has not been quite released yet. The 0.4 binary will output an example config as part of its command line usage message.

**Comment by matthewmueller** [comment]
ah okay, got confused by the dockerfile :-)

thanks for the clarification!
