### ISSUE TITLE
Returning a subset of the full object from an INSERT

### ISSUE THREAD

**Issue by matthewmueller** [begriffs/postgrest#746]
Is there anyway to do this kind of statement in Postgrest?

```sql
INSERT INTO "1".users (firstName,lastName,password)
VALUES ("mark", "jacob", "123")
RETURNING firstName, lastName
```

I tried the `Prefer: return=firstName,lastName` but that doesn't seem to work correctly on 0.3.2 anyway.

For context, this is useful when you want to lock down selects for an anon user but still allow them to create users (and not expose all your columns)

**Comment by begriffs** [comment]
I believe you post to `/mytable?select=firstName,lastName` and include `Prefer: return=representation`. Specifying columns in the prefer header certainly doesn't work.

**Comment by matthewmueller** [comment]
Unfortunately it doesn't seem like ?select applies to inserts:

Here's the SQL

```sql
WITH pg_source AS (INSERT INTO "1"."users" ("email", "access_token", "scope")SELECT "email", "access_token", "scope" FROM json_populate_recordset(null:: "1"."users" , $1) RETURNING "1"."users".*)
	      SELECT '' AS total_result_set, pg_catalog.count(t) AS page_total, ( WITH s AS (SELECT row_to_json(ss) as r from pg_source as ss  limit 1) SELECT array_agg(json_data.key || '=' || coalesce('eq.' || json_data.value, 'is.null')) FROM s, json_each_text(s.r) AS json_data WHERE json_data.key IN ('id')), coalesce(string_agg(row_to_json(t)::text, ','), '')::character varying  AS body
	      FROM (SELECT  "pg_source"."email" FROM  "pg_source"    ) t
```

The problem is that `RETURNING "1"."users".*`, which only changes in the case of `return=minimal`, but not `?select=email` with `return=representation`.

**Comment by ruslantalpa** [comment]
so you have a table in which anonymous users can insert data but can only view a limited number of columns from what they have just inserted?
can you paste here the table definition and the relevant `grant` statements?

**Comment by matthewmueller** [comment]
> so you have a table in which anonymous users can insert data but can only view a limited number of columns from what they have just inserted?

@ruslantalpa yep, exactly that.

---

Here's what the relevant statements:

```sql
create table if not exists "1".users (
  id serial primary key not null,
  role name not null default 'user',
  email text NOT NULL unique,
  stripe_id text
  -- ... a few others that are also private, like stripe_id
);

grant insert (email, access_token, scope) on "1".users to anon;
grant select (id, email, access_token, scope) on "1".users to anon;
grant usage on "1".users_id_seq to anon;
```

So if I change that `select grant (...)` to:

```sql
grant select on "1".users to anon;
```

That will work, but it'll expose the rest of the columns to the anon user.

**Comment by ruslantalpa** [comment]
Ok, i understand, fixable. @begriffs can you change this to "bug" and i'll see about fixing this (interesting case :) didn't think about it)

**Comment by matthewmueller** [comment]
Just got bitten by this again – what do you think about a default insert not returning anything? i.e. the default is `representation=minimal`

That would make a bit more sense to me anyway since the default `INSERT` is to return nothing, but if you add `RETURNING` you get to customize what gets returned.

**Comment by begriffs** [comment]
Even when it doesn't return a payload, PostgREST uses the information it requests to create a `Location` response header. I was guided by RFC7231:

> If one or more resources has been created on the origin server as a
   result of successfully processing a POST request, the origin server
   SHOULD send a 201 (Created) response containing a Location header

However in our insert statement we ought to do `RETURNING foo, bar, baz` rather than `RETURNING *`, selecting only the primary key column(s).

**Comment by matthewmueller** [comment]
Ah okay, I think the Location header is fine, it's just what's getting executed against Postgres. If you have some select permissions setup that don't let the role select on a particular column, you'll get permission denied for the POST request.

I think the primary keys would be a better solution, but I'm guessing that there may be a time when you don't want the role to be able to select your table's ID for example
