### ISSUE TITLE
Swagger-UI Trouble

### ISSUE THREAD

**Issue by geepie** [begriffs/postgrest#750]
I try to use my own API or the demo one (https://postgrest.herokuapp.com) with Swagger-UI (http://swagger.io/swagger-ui/).

I got always got the same message:
"fetching resource list: http://server:3000/; Please wait."

**Comment by ruslantalpa** [comment]
OpenAPI support is only present in the master branch, so unless you've compiled postgrest from source, the release version does not have that functionality yet.

**Comment by tomberek** [comment]
I've tested with compiling from source and it works well. Any chance of a version bump and new release?

**Comment by begriffs** [comment]
New release is ready! https://github.com/begriffs/postgrest/releases/tag/v0.4.0.0
