### ISSUE TITLE
Setting postgrest claims on RDS

### ISSUE THREAD

**Issue by matthewmueller** [begriffs/postgrest#755]
Has anyone been able to figure out how to set custom database parameters on Amazon RDS?

Something like this:

```sql
ALTER database "db" SET postgrest.claims.token TO -1;
```

I'm getting `permission denied to set parameter "postgrest.claims.token"` from the admin account.

Also opened an issue on the forum here: https://forums.aws.amazon.com/thread.jspa?threadID=244090

**Comment by ruslantalpa** [comment]
You dont need to, you can write a fn that will catch the error. I'll paste a bit later

**Comment by ruslantalpa** [comment]
```sql
create function util.env_var(v text) returns text as $$
  declare
    result text;
  begin
    begin
      select current_setting(v) into result;
    exception 
      when undefined_object then
        return null;
    end;

    return result;
  end;
$$ stable language plpgsql;
```

**Comment by begriffs** [comment]
Thanks for the snippet, Ruslan, I added it to the note in https://postgrest.readthedocs.io/en/v0.4/auth.html?highlight=claims#web-users-sharing-role

**Comment by ruslantalpa** [comment]
Credit goes to @deinspanjer (https://github.com/begriffs/postgrest/wiki/Example-get_jwt_claims()-function) i just made it shorter and general purpose :)

**Comment by matthewmueller** [comment]
ah that's perfect, thanks @ruslantalpa!
