### ISSUE TITLE
DELETE with Prefer: 'return=minimal' always returns 404

### ISSUE THREAD

**Issue by matthewmueller** [begriffs/postgrest#760]
Not sure if this is desired or not, but it looks like deleting items with `return=minimal`, even if it succeeds, will return a 404.

**Comment by diogob** [comment]
@matthewmueller I've coded a quick spec to test this case and it returns a 204 with an empty body. Could you post a script or an endpoint to help reproduce the 404 case?

**Comment by diogob** [comment]
@begriffs could not reproduce this in current master, maybe we should close it
