### ISSUE TITLE
Calling Stored Procedure

### ISSUE THREAD

**Issue by briviere** [begriffs/postgrest#771]
Hello

I have the following stored procedure I've created:

```
CREATE OR REPLACE FUNCTION public.json_merge(data json, merge_data json)
RETURNS json
IMMUTABLE
LANGUAGE sql
AS $$
    SELECT ('{'||string_agg(to_json(key)||':'||value, ',')||'}')::json
    FROM (
        WITH to_merge AS (
            SELECT * FROM json_each(merge_data)
        )
        SELECT *
        FROM json_each(data)
        WHERE key NOT IN (SELECT key FROM to_merge)
        UNION ALL
        SELECT * FROM to_merge
    ) t;
$$;
```

Using Postman I call it as follows:

POST /rpc/json_merge

```
{
	"data": {
		"a": 1
	},
	"merge_data": {
		"b": 2,
		"c": 3,
		"a": 4
	}
}
```

Postgrest returns the following:

```
{
    "details": "parse error (endOfInput) at \"\\\"data\\\": {\\n\\t\\t\\\"a\\\": 1\\n\\t},\\n\\t\\\"merge_data\\\": {\\n\\t\\t\\\"b\\\": 2,\\n\\t\\t\\\"c\\\": 3,\\n\\t\\t\\\"a\\\": 4\\n\\t}\\n\\n\"",
    "message": "Cannot parse request payload"
}
```

thanks

Brian

**Comment by begriffs** [comment]
I wonder whether you're posting that json object, or actually a string containing the json object. Sometimes client-side libraries enclose the payload in quotes.

Look at the end of the error message for instance: `4\\n\\t}\\n\\n\"`. It has an escaped quote. You can use `ngrep` to verify exactly what string is being sent over the network, more info about that here https://postgrest.readthedocs.io/en/v0.4/admin.html#debugging

**Comment by begriffs** [comment]
Oops, just noticed the discussion on gitter.

**Comment by briviere** [comment]
I was sending Content-Type: text/csv which was casuing the issue.  Changing Content-Type: application/json resolved the issue.
