### ISSUE TITLE
Use JWT through cookies instead of Bearer scheme in headers

### ISSUE THREAD

**Issue by tocttou** [begriffs/postgrest#773]
I could not find a way in documentation to use JWT authentication using cookies instead of the Bearer scheme in headers which requires you to store the JWT in localStorage (which can be a fatal in case of an XSS vulnerability). For reference: [Where to store JWTs]( https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage).

This would require recognising the token as: 

```
GET /login
Host: postgrest.com

Cookie: access_token=eyJhbGciOiJIUzI1NiIsI.eyJpc3MiOiJodHRwczotcGxlL.mFrs3Zo8eaSNcxiNfvRh9dqKP4F1cB;
```

**Comment by SebAlbert** [comment]
Seems like a perfect fit to rewrite this in the reverse proxy layer. nginx, apache etc. are all able to read and write HTTP headers while proxying a request.

But, how are Cookies less vulnerable to XSS than localstorage?

**Comment by tocttou** [comment]
Using a reverse proxy is a fair point, thanks. But it would be better if this could be integrated in the main project as it is a valid use case and easy to implement (probably).

**Comment by begriffs** [comment]
@tocttou have you investigated doing the proxy thing? If so I'd love an nginx snippet to include in the docs.

**Comment by tocttou** [comment]
Hello

Yes I was able to get it working using [lua-nginx-module](https://github.com/openresty/lua-nginx-module) to rewrite the request.

If your Postgrest API server is on `http://localhost:3000` and your Nginx Proxy is on `http://localhost:3001`, you can use this nginx proxy config and make request to your nginx proxy with a cookie `access_token` that contains the jwt (it rewrites the headers to include a `Authorization: Bearer <jwt>` header:

```
server {
  listen  0.0.0.0:3001;

  location / {
     rewrite_by_lua_block {
       local cookie_value = ngx.req.get_headers()["Cookie"]
       if cookie_value ~= nil then
         local jwt = cookie_value:match("access_token=([^ ]+)")
         ngx.req.set_header("Authorization", "Bearer " .. jwt)
       end
       ngx.req.clear_header("Cookie")
     }
     proxy_pass http://0.0.0.0:3000;
  }
}
```

Actual request (to nginx proxy by the client):

```
GET  HTTP/1.1
Host: localhost:3001
Cookie: access_token=mah.osum.token
```

Request relayed to Postgrest:

```
GET  HTTP/1.1
Host: localhost:3000
Authorization: Bearer mah.osum.token
```

**Comment by ruslantalpa** [comment]
Closing this since implementation in OpenResty is the preferred way. The only way to add is there is a better way to read the cookie like this
```lua
local ck = require 'resty.cookie'
local cookie = ck:new()
local token = cookie:get('COOKIE_NAME_HERE')
```

**Comment by TonnyLTP** [comment]
What I did is setting local config in login plpgsql function, and do the transfer job in nginx (without lua).

```
_cookie := format('[{"set-cookie": "access_token=%s; path=/; HttpOnly; max-age=86400"}]', _token);

PERFORM set_config('response.headers', _cookie, true);
```

expected postgrest would support to read token from cookie, but currently seems not. So I have to transfer token from cookie header to authorizaition header.

```
if ($cookie_access_token) {
  set $auth "Bearer $cookie_access_token";
}

if ($http_authorization) {
  set $auth $http_authorization;
}

proxy_set_header Authorization $auth;
```

I hope it could support to read access_token or session_token in cookie header as jwt token.

**Comment by chamini2** [comment]
I would appreciate this option too

**Comment by swuecho** [comment]
for anyone who using envoy proxy.

```
 - name: envoy.filters.http.lua
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                inline_code: |
                  -- called on request path
                  function envoy_on_request(request_handle)
                          local headers = request_handle:headers()
                          local cookieString = headers:get("cookie")
                          if cookieString ~= nil then
                              local jwt = cookieString:match("jwt=([^; ]+)")
                              headers:add("authorization", "Bearer " .. jwt)
                          end
                  end
```

**Comment by yevon** [comment]
Anybody implemented this in ingress nginx on kubernetes?

**Comment by yevon** [comment]
Solved in kubernetes nginx ingress by doing this, inspired in @TonnyLTP  solution:

This solution includes an access token and a refresh token for more secure login implementations.

```
nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($cookie_access_token) {
        set $auth "Bearer $cookie_access_token";
      }
      if ($http_authorization) {
        set $auth $http_authorization;
      }
      if ($cookie_refresh_token) {
        set $auth "Bearer $cookie_refresh_token";
      }      
      proxy_set_header Authorization "${auth}";
```

**Comment by mckinlde** [comment]
The ability to set custom headers was added in [PR 986](https://github.com/PostgREST/postgrest/pull/986), which I found in [this discussion](https://github.com/PostgREST/postgrest/issues/940).

@TonnyLTP and @yevon have the closest approach for my use case--as of now I am pretty confident I can change the /login endpoint to respond with a set-cookie header to store the JWT, but once I've done that how do I ensure the rest of the endpoints in postgrest are checking the cookie header for a JWT?

**Comment by yevon** [comment]
Postgrest always validates if there is an auth header present for all endpoints, you have to explicity specify which ones do not require any auth, like the login. Once you specify your token http only cookie is valid for your api.example.com, the web browser will always send that cookie to the server automatically for every request against api.example.com. And with the nginx / proxy approach, you transform the cookie to an auth header before passing it to the postgrest backend.

**Comment by mckinlde** [comment]
Thank you @yevon; so there isn't a way to configure pgRest to check the cookie directly instead of the Auth header?  I was hoping I could simply change a config setting instead of running a reverse proxy--if transforming is required then I'll be running another server for that purpose alone.

I'm a novice end user, and I really appreciate the help; my goal is to use the JWT auth/auth as described in [SQL User Management](https://postgrest.org/en/stable/how-tos/sql-user-management.html) and [Tutorial 1](https://postgrest.org/en/stable/tutorials/tut1.html), with the sole difference of storing the JWT as an `Http Only` `SameSite` cookie.

**Comment by yevon** [comment]
You could achieve this by implementing a pre-validation pgsql script and validate the token yourself, but this would be even more complicated than the proxy approach. I think that right now there is no way to accept tokens via cookie officially, or compatibility with a short term token with long term refresh tokens. It would be nice having this kind of support.

**Comment by mckinlde** [comment]
@yevon That is the case.  I've opened a [new issue](https://github.com/PostgREST/postgrest/issues/3050) requesting the feature, it has been previously discussed many times and I include links to those discussions as well as relevant documentation and snippets--I'm a bit wordy, I'd appreciate editorial suggestions there!

**Comment by donkey-hottie** [comment]
I'm leaving this here for posterity. I use this db-pre-request function to get JWT from cookies to avoid setting up a reverse proxy. I would prefer if using JWT directly from cookies was supported but this works fine for me.

```plpgsql
CREATE OR REPLACE FUNCTION validatejwtfromcookie()
    RETURNS void
    LANGUAGE 'plpgsql'
AS $BODY$
declare
    vi_jwt_exp integer;
    vi_jwt_session uuid;
    vi_jwt_role varchar;
    vi_cookie_token text;

    v_auth_token jsonb;
    v_token_valid boolean;
begin
    --extract and parse jwt from cookie if cookie exists and set it as the jwt claim
    vi_cookie_token:=current_setting('request.cookies', true)::json->>'token';
    if vi_cookie_token is not null
    then
        --check token claims and validity; the secret in this snippet is only valid for my local development server
        select payload,valid
        into v_auth_token,v_token_valid
        from public.verify(token := vi_cookie_token,secret:= 'AtBmiZbdbytqAG9o36EZZE8BFgqDB7bRFASDF',algorithm := 'HS256');
        --raise exception if token is not valid
        if not v_token_valid
        then
            select returnfailure('28000','validatesession','token is no longer valid');
        end if;
        --set token claims from cookie to jwt claims
        vi_jwt_exp:=v_auth_token->>'exp';
        vi_jwt_session:=v_auth_token->>'session';
        vi_jwt_role:=v_auth_token->>'role';		
        perform set_config('request.jwt.claims','{"role": "' || vi_jwt_role || '","exp": ' || vi_jwt_exp || ',"session": "' || vi_jwt_session || '"}', true);	
    end if;
end
$BODY$;
```

**Comment by mckinlde** [comment]
Sick
