### ISSUE TITLE
Patch pg array doesn't work

### ISSUE THREAD

**Issue by isairz** [begriffs/postgrest#774]
I'm tring to apply this nice project to my admin page.
My db has pg array for store tags.

The following code is minimal case and result to use pg-array (character varying[])

PATCH /posts?id=eq.1234
```json
{
  "id": 1234,
  "name": "Title",
  "tags": [ "a", "b", "c"]
}
```
Error Result
```json
{
  "hint": null,
  "details": "\"[\" must introduce explicitly-specified array dimensions.",
  "code": "22P02",
  "message": "malformed array literal: \"[\"a\",\"b\",\"c\"]\""
}
```

I found a workaround using pg array representation
PATCH /posts?id=eq.1234
```json
{
  "id": 1234,
  "name": "Title",
  "tags": "{a,b,c}"
}
```

The pg-array style is right way? Or do you have any plan to fix?
If pg-array style is right, please write this to document. :smile: 

Have a nice day.

**Comment by begriffs** [comment]
Cool workaround, good to know that works. Another workaround is to use json or jsonb in the column rather than a postgres array.

**Comment by hugomrdias** [comment]
I ran into the same issue with rpc
Using an array inside JSON for a parameter with an array type doesn't. 
The workaround above also works but it's a bit strange to use, I need to stringify an normal array to the pgsql syntax. 
@begriffs would you consider supporting arrays?

**Comment by begriffs** [comment]
I think it's ambiguous when you post

```json
{ "foo": [1,2,3] }
```

whether it is destined for a function taking a postgres array for its argument named foo, or whether the argument is of type json. If you guys can think of a way to disambiguate it then I'm happy to accept a pull request.

**Comment by hugomrdias** [comment]
if i set the param foo to JSON or JSONB and send

```
{ "foo": [1,2,3] }
```
it errors out with "there is no function( foo TEXT)

**Comment by isairz** [comment]
I want just to notice. (but i found duplicate issue #282, sorry)

I think this workaround is strange, but not very strange because PostgreSQL has same syntax to represent array. My admin page already had perprocessor that convert comma separated string to javascript array. so I just change target to pg array. I think it will be easy to use preprocessor in many cases.

What just confused me is that GET is perfectly supported, but the issue of POST and PATCH is not even documented.

I close this issue because it is duplicated. Thanks!
