### ISSUE TITLE
Empty body is enforced when calling a non-parameterized rpc?

### ISSUE THREAD

**Issue by tnhu** [begriffs/postgrest#777]
I'm not sure if this is a feature or a bug. When making an rpc call to a store procedure which does not accept parameters, I have to pass an empty body, otherwise, Postgrest returns an exception.

```sql
CREATE FUNCTION version() RETURNS text
AS $$
  select version();
$$ LANGUAGE sql;
```

This works fine (empty body passed by `-d '{}'`):

```sh
curl -X POST -H "Content-Type: application/json" -d '{}' "http://localhost:3333/rpc/version"
```

This does not:

```sh
curl -X POST -H "Content-Type: application/json" "http://localhost:3333/rpc/version"
```

```json
{"details":"Error in $: not enough input","message":"Cannot parse request payload"}
```

**Comment by begriffs** [comment]
I verified this happens on master too. Strictly speaking an empty string is not json and you claimed the content type of the post body to be json... but I verified that it happens even when the content type is not specified. Maybe we should add a special case for an empty post body.

**Comment by ruslantalpa** [comment]
I think from a convenience point of view, "" should be equal to {} in the context of RPC body, could be labeled as a bug

**Comment by begriffs** [comment]
Tentatively labeling this as a good issue for new contributors as well if it's a matter of detecting and replacing an empty post body for the RPC route.
