### ISSUE TITLE
Support optparse-applicative 0.13

### ISSUE THREAD

**Issue by felixonmars** [begriffs/postgrest#778]
Hi,

I noticed the constraint added in #752. Would it be possible to support optparse-applicative 0.13?

**Comment by begriffs** [comment]
Sure, but it'll involve a code adjustment to deal with the breaking changes of 0.13. I'll look into it after the next major postgrest release which is coming soon.

**Comment by felixonmars** [comment]
That's great to hear! We'll wait for the next major release to add into Arch Linux's official repositories then. Thanks!

**Comment by begriffs** [comment]
Much appreciated!

**Comment by begriffs** [comment]
The release is out and new binaries are available at https://github.com/begriffs/postgrest/releases/tag/v0.4.0.0

Do Arch packages require building from source, or do one of those binaries suffice?

**Comment by felixonmars** [comment]
We will be building from source, thanks for the update :)

**Comment by PierreR** [comment]
v.0.4 is still contraining `optparse-applicative` < 0.13.0.0 which mean `postgrest` won't appear in the next stack `LTS-8`  that should be released in a week or so.
Can I try and help on this issue ?

**Comment by PierreR** [comment]
I have just realized that `postgrest` is not on stackage ... so the urgency point is just moot.

**Comment by PierreR** [comment]
@begriffs let me know if you need some help regarding this issue. Maybe you maintain a branch that has already incorporated such changes. If you haven't done any work on this, I am willing to give it a shot in a couple of days).

**Comment by begriffs** [comment]
Sorry for the delayed response. I'd love some help upgrading optparse-applicative if you want to give it a shot.

**Comment by PierreR** [comment]
@begriffs Could we get this change in a 4.0.1 release or something ? That would really help to get it to stackage, which in turn helps to get it into nixpkgs, which in turn help (me) when trying building satellite project such as `postgrest-ws`.
