### ISSUE TITLE
Something went wrongHTTP/1.0 500 Internal Server Error

### ISSUE THREAD

**Issue by ranjanprj** [begriffs/postgrest#780]
First this is great work so thank you.
I'm using Postgrest on AWS and I am encoutering the following message intermittently.

> 
> Something went wrongHTTP/1.0 500 Internal Server Error
> Date: Sat, 24 Dec 2016 05:24:54 GMT
> Server: postgrest/0.3.2.0
> Content-Type: text/plain; charset=utf-8
> 
> Something went wrong

1. This happens when I put a wrong query at the end such as "count" 
api/authors?email=eq.someone@gmail.com&**count**
2. After I leave the server running overnight and try to login again, again I encounter the problem.

Current solution is to terminate the Postgrest process and start again.
What could be the issue ?

Thanks 

P.S  I'm using the latest release.

**Comment by begriffs** [comment]
Thanks for reporting, I haven't seen this bug before.

Some questions to help debug:

* How often would you say the error happens? Is it most requests or pretty rare? Are certain requests more prone to it, or does it happen about equally for any kind of request?
* Are you able to examine the CPU and memory usage on the machine?
* Anything funny in the postgresql logs at around the times of the error?
* Does it help if you send `SIGHUP` to the postgrest process? (For instance by running `killall -HUP postgrest`)

**Comment by ranjanprj** [comment]
I will work on the logs and mem.

It happens if I do not query the server for few hours, I am suspecting
session timeouts.

This happens both in my local VM 2GB ram and AWS 1 GB ram with only
Postgres running.

Plus it happened when I put "count"  in from entity in URL

Like API/employees?count

**Comment by ranjanprj** [comment]
Reproduced it again.
Left the server running for some time ( 4-6 hrs ) without making any requests, got the same error.

killall -HUP postgrest did not help.
Logs and mem/cpu on the server is fine, nothing out of ordinary.

**Comment by begriffs** [comment]
When you say you're using the latest release do you mean version 0.3.2.0 or a custom build from the master branch?

**Comment by ranjanprj** [comment]
No, it's not a custom build, it's 0.3.2.0

On 26-Dec-2016 01:27, "Joe Nelson" <notifications@github.com> wrote:

When you say you're using the latest release do you mean version 0.3.2.0 or
a custom build from the master branch?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/begriffs/postgrest/issues/780#issuecomment-269135407>,
or mute the thread

**Comment by ranjanprj** [comment]
This is recurring now consistently, is there a fix expected in coming release. Let me know

Thanks

**Comment by begriffs** [comment]
I don't know whether it has been fixed in the new version because I never noticed it in the original. We'll be releasing v0.4 pretty soon and you can try that. If you want to try it early you can build the master branch of this repo from source. Here are the new docs that describe how to do that https://postgrest.readthedocs.io/en/v0.4/install.html#build-from-source

Also is there a way to modify the client to avoid sending a malformed query param? I recognize this is a postgrest bug but fixing the client would be a workaround while we work to reproduce, test, and fix the server bug.

**Comment by ranjanprj** [comment]
Yeah, I see that no one has reported this earlier, so it's a bit perplexing,  will wait for the new release. 
Thanks again.

**Comment by ranjanprj** [comment]
Ah I figured it out , it was my ssh terminal session timeout causing the issue. Using "screen" command before postgrest did the trick. Closing this and wishing you happy new year.

**Comment by begriffs** [comment]
Happy new year!

Should we mention the issue of terminal session in the docs? I wonder if piping the output of postgrest to the syslog and backgrounding the process would accomplish the same thing.

**Comment by ranjanprj** [comment]
It would be better for the new community members as I was doing this
primarily on AWS and thought the issue was with postgrest. so yes please if
you can.
Thanks

**Comment by begriffs** [comment]
I added a note to the docs about it.
