### ISSUE TITLE
question: about login process (secret for jwt.sign)

### ISSUE THREAD

**Issue by Sigura** [begriffs/postgrest#783]
build postgrest from master because pre-request needed for security

If I'm understand correctly now login result does not decrypt to token response automatically.

and constructions like this needed:

```
    jwt.sign(
      row_to_json(t), '!!secret!!'
    ) as token
```

could you please describe way how I can avoid keeping secret in sql?

maybe secret available as `current_setting`?

ps: sorry I have no Haskell experience.

pps: and thank you for your wonderful work!

**Comment by ruslantalpa** [comment]
you can run this query manually once
```
alter database mydbname set jwt_secret to 'secretgoeshere';
```

then your function will be

```
jwt.sign(
     row_to_json(t), current_setting('jwt_secret')
) as token
```

**Comment by Sigura** [comment]
custom_variable_classes disappeared in 9.2,

https://www.postgresql.org/docs/9.3/static/release-9-2.html#AEN117369

now error: `ERROR: unrecognized configuration parameter "jwt_secret"`

works without exception: `alter database taxliencloud set app.jwt_secret to '!!secret!!';`
but empty for `select current_setting('app.jwt_secret')`

((((

**Comment by Sigura** [comment]
works well:

```
SET app.jwt_secret TO '!!!secret!!!';
```

**Comment by ruslantalpa** [comment]
(close pls)

**Comment by begriffs** [comment]
I added the "alter database" trick as a note in the docs.
