### ISSUE TITLE
OpenAPI Suggestion: do not set .host when serving over *4, !4, *6 or !6

### ISSUE THREAD

**Issue by ldesgoui** [begriffs/postgrest#784]
Hello,

It might come from my inexperience in networking, but setting the config's `server-host` value to anything other than a bindable, local address fails (as per expected, I guess), this means that the OpenAPI `.host` value returned always results in a local address, making it impossible to use with online tools.

I suggest to remove the field when the config's `server-host` value is set to the special values, this will force tools to use the host used to retrieve the documentation json (described here: http://swagger.io/specification/#schema-13).

Then again it could be a failure on my part, and please do tell me if so, I tried setting `server-host` to the IP of my server and I was met with

    Listening on port 3000
    postgrest: bind: unsupported operation (Cannot assign requested address)

when launching the app.

EDIT:
Looking at the source code, it seems a simple conditional would be required at https://github.com/begriffs/postgrest/blob/master/src/PostgREST/OpenAPI.hs#L270, it would also make `escapeHostName` a few lines higher deprecated.

Thanks!

**Comment by ruslantalpa** [comment]
that setting is meant to specify the ip address postgrest should listen not, it's not a setting for openapi.

in order of external tools to access your local running postgrest, that ip needs to be public on the internet

if you need openapi response to have something else then the ip that postgrest listens on, you can use server-proxy-uri

(if it does not work, post your complete config here)

**Comment by ldesgoui** [comment]
Oh wow, my bad, I had looked at the option but failed to understand. Thanks !

**Comment by begriffs** [comment]
In your opinion are the roles of these config parameters explained clearly enough in https://postgrest.readthedocs.io/en/v0.4/admin.html ?

(I know these docs are not yet advertised so you perhaps did not see them, but I'd like your opinion about the clarity of the docs.)

**Comment by ldesgoui** [comment]
Oh, I had no idea of these existing, I only knew from the `--help` option of the binary. I think it could be good to link the config documentation there.

The docs themselves seem to be explained clearly.
