### ISSUE TITLE
Rate limiting functionality

### ISSUE THREAD

**Issue by ranjanprj** [begriffs/postgrest#785]
Is there exists or plans of  any rate limiting functionality in postgrest. This will have good effects on security side of things as well.

P.S Keep up the awesome work.

**Comment by jackfirth** [comment]
Just guessing at what the devs would say, but that's probably something that would be better done in a proxy. [This article](https://lincolnloop.com/blog/rate-limiting-nginx/) indicates it would only take one line of nginx configuration to add some naive rate limiting.

**Comment by ruslantalpa** [comment]
@jackfirth  completely true. Out of curiosity, why is it "naive" rate limiting, is r/s + burst not enough in most of the cases?

**Comment by jackfirth** [comment]
@ruslantalpa I was being a bit fast and loose with my words, that's a perfectly acceptable rate limiting scheme for most cases. In some cases (particularly when exposing an API to multiple different third parties) it can be combined with a client quota system, such that requests are tied to specific clients through API keys and clients are given a quota of X requests per hour / day / month / etc.
