### ISSUE TITLE
documentation disappeared :(

### ISSUE THREAD

**Issue by radiospiel** [begriffs/postgrest#789]
@begriffs congratulations to your new release! Just as I wanted to start playing around with postgrest the website disappeared and postgrest.com always redirects to http://postgrest.com/en/v0.4/ now. This is unfortunate since the website had more examples to get me started than what is now visible here. I assume this is a result of the newly released version, but I hope to get back to a visible documentation soon :)

**Comment by begriffs** [comment]
Sorry for the abrupt switch, didn't realize people would still want to consult the old docs.

The docs for v0.3 are still available at https://github.com/begriffs/postgrest-docs/tree/master/docs
