### ISSUE TITLE
Column restriction privileges require an explicit select param

### ISSUE THREAD

**Issue by jwbrew** [begriffs/postgrest#792]
Firstly, hello! I've been watching & using postgrest for a few weeks now (and think it's utterly brilliant too, so thank you!) but this is my first issue. 

I've been using GRANT SELECT (a, b, c) ON x to restrict data visibility based on user roles. In order to perform a successful get on this table it requires the app consuming the resource to know which columns it has permission to access and explicitly only request them. 

This is fine for our in-house apps, but may cause issues as & when we open the api up publicly. Is there value in returning just the columns for which privileges have been granted on when making a get request by default?

**Comment by jwbrew** [comment]
Just for a little more context; we have a table containing sensitive user data that needs to be available to an appropriately authorised user, but also available to an anonymous user, with the sensitive data stripped. I've tried doing this with multiple views, but I find myself prefixing views with anon_ and user_ which seems counter intuitive.

**Comment by ruslantalpa** [comment]
@jwbrew You either document your public API and say:
make a request and specify &select param (/items?select=a,b,c)
and whoever does a (/items) will get an error

or you put a proxy in front of postgrest and whenever an unautheticated  request comes in without a select parameter, you force a default value

**Comment by jwbrew** [comment]
Makes sense, thanks @ruslantalpa :)
