### ISSUE TITLE
Postgrest not sending data 

### ISSUE THREAD

**Issue by sushant12** [begriffs/postgrest#801]
I have successfully ran postgrest as mentioned in [this](http://postgrest.com/en/v0.4/admin.html#hardening-postgrest) doc . When I hit `domain.com/api endpoint`, postgrest is logging the output and various data points are also shown. When I try to visit `domain/api/categories` I get a 404 error.

**Comment by begriffs** [comment]
What database schema does `categories` live in, and which schema are you choosing to expose in your api?

**Comment by sushant12** [comment]
@begriffs , in my prod server when I run a curl request to localhost:3004 it shows me the endpoints and when I run localhost:3004/categories it gives me the categories as well. I think that the issue is with the nginx + postgrest. domain.com/api is showing me the enpoints but domain.com/api/categories is giving me 404 err. i am using rails

**Comment by sushant12** [comment]
@begriffs  this is how my sites-available/default file looks like

```
upstream app {
  # Path to Puma SOCK file, as defined previously
  server unix:/home/deploy/jvn/shared/tmp/sockets/puma.sock fail_timeout=0;
}

upstream postgrest {
    server localhost:3004;
    keepalive 64;
  }

server {
  listen 80;
  server_name localhost;

  root /home/deploy/jvn/current/public;

  try_files $uri/index.html $uri @app;

  location / {
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Connection '';
    proxy_pass http://app;
  }

  location ~ ^/(assets|fonts|system)/|favicon.ico|robots.txt {
    gzip_static on;
    expires max;
    add_header Cache-Control public;
  }

location /api {
      default_type  application/json;
      proxy_hide_header Content-Location;
      add_header Content-Location  /api$upstream_http_content_location;
      proxy_set_header  Connection "";
      proxy_http_version 1.1;
      proxy_pass http://postgrest/;
    }

  error_page 500 502 503 504 /500.html;
  client_max_body_size 4G;
  keepalive_timeout 10;
}
```

**Comment by sushant12** [comment]
@begriffs  I checked the postgrest log and found this
`127.0.0.1 - - [11/Feb/2017:08:23:46 +0000] "GET //categories HTTP/1.1" 404 - "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"` 

it should be making request like /categories but it is requestion //categories. I get this logged when I make request to domain/api/categories
