### ISSUE TITLE
Disable OpenAPI interface

### ISSUE THREAD

**Issue by avvensis** [begriffs/postgrest#804]
Is't possible to disable OpenAPI in PostgREST configuration file?

**Comment by avvensis** [comment]
Alternatively, Nginx could do it, but i don't know how to describe Location to disable root access.

**Comment by ruslantalpa** [comment]
maybe like this (didn't try)
```
location ^~ /[a-z]+ {
  ....
}
```

**Comment by giangstrider** [comment]
Hey guys, I'm newcomer.
And this issues very urgent for our product now.
it's expose everything in root path.
So anyway to disable OpenAPI until now?
Many thanks for support!

**Comment by ruslantalpa** [comment]
@giangstrider  you control access to `/` through nginx that you put in front of postgrest

**Comment by begriffs** [comment]
@giangstrider also remember that even if openapi shows the endpoints, you can control people's access to each of them using postgresql role permissions.

**Comment by begriffs** [comment]
A slight correction to what I said. If you remove access for a given role to read a table/function/etc then that object will not appear in OpenAPI output.

**Comment by steve-chavez** [comment]
> but it's better to configure it in PostgREST.

@dwagin Yeah, now you can do `openapi-mode="disabled"`

https://postgrest.org/en/v8.0/configuration.html#openapi-mode
