### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by sushant12** [begriffs/postgrest#807]
I am using [mithrill-postgrest](https://github.com/catarse/mithril-postgrest). I have done exactly what the postgrest docs [docs](http://postgrest.com/en/v0.4/admin.html#hardening-postgrest) said.

Everthing is running fine except that the mithrill-postgrest library is adding `/` to the url.
Foreg: as per the docs the postgrest url now becomes domain/api . If i want to query data the url will become domain.com/apicategories . But the mithrill postgrest lib adds domain/api/categories. 

My app is running in the same instance where the postgrest is running. I have configured postgrest in the same nginx server which also serves my app.

Can you recommend me a solution? I have thought of configure the postgrest in different port. for eg 
my postgrest is running on 3004 port. I want to configure it in my nginx conf like domain:3004 which will show me the endpoints I can query to and domain.com:3004/categories which will give me categories.

**Comment by sushant12** [comment]
anything on this one?

**Comment by begriffs** [comment]
The route `/api/categories` looks correct and `/apicategories` incorrect. If I'm understanding you, mithril-postgrest is generating the routes correctly, but your nginx config is not right to expose `/apicategories` as a route. (Perhaps the docs have a typo that led you to configure nginx that way.)

**Comment by sushant12** [comment]
@begriffs is it possible for you to check if the doc has a typo? My nginx conf skill is noob

**Comment by sushant12** [comment]
changing  location /api to location /api/ solved the issue

**Comment by begriffs** [comment]
Cool, glad you got it working. Could you send a pull request to update the incorrect place in the docs please?

**Comment by sushant12** [comment]
sure
