### ISSUE TITLE
localhost install for dummies

### ISSUE THREAD

**Issue by ppKrauss** [begriffs/postgrest#811]
There are a UBUNTU-16LTS script for install localhost PostgREST server?

For dummies:  step-by-step, supposing zero-knowledge about Docker, Haskell, etc. having only Apache (conflict?) and PostgreSQL 9.6+ as base environment... I can help to develop and test the script, but  will also need some help from experts here to do some progress.

**Comment by ruslantalpa** [comment]
Has nothing to do with docker, haskell .... it's a binary, download it, save it, start it.

**Comment by ppKrauss** [comment]
So... It is "plug and play"?!   

Well, let's write a script from download to run, using [admin guide](http://postgrest.com/en/v0.4/admin.html) and the latest version at [postgrest/releases](https://github.com/begriffs/postgrest/releases/tag/v0.4.0.0):

```
cd ~
wget -c https://github.com/begriffs/postgrest/releases/download/v0.4.0.0/postgrest-0.4.0.0-ubuntu.tar.xz
tar xf  postgrest-0.4.0.0-ubuntu.tar.xz
ls -l postgrest
chmod 777 postgrest  # need it?
....
```
(error "no command postgrest")

do you can help for next steps in a localhost/postgres user/postgres database  basic configuration?

**Comment by ppKrauss** [comment]
ops,  correcting (to rigor the [README.md **is wrong**](https://github.com/begriffs/postgrest/blob/master/README.md)), classic UBUNTU problem, only execute as `./exe`,  so  `./postgrest --help`  is working fine!

Suggestion (see similar demand at #813), to offer simple *"one script with all you need"* and some files for options, configs and examples... A folder "/dummies_install"  or a README's link to a separeted little *git* for it... A in fact **plug and play**, two steps to  work with a table `t` as in `http://localhost:3000/t?select=note&label=eq.b`.

**Comment by begriffs** [comment]
How about a section in the docs like "Installation -> Getting Started"? It could link to the release page and include a tiny tutorial with wget, untar, configure, run like you mentioned.

If you'd like to write this section and open a pull request against https://github.com/begriffs/postgrest-docs that would be super cool.

**Comment by ppKrauss** [comment]
Hi @begriffs, thanks!  

As first draft I send my pull request at [postgrest-docs](https://github.com/begriffs/postgrest-docs/pulls)... So, we can close this issue.
