### ISSUE TITLE
Installation instructions on Windows

### ISSUE THREAD

**Issue by jackrabb1t** [begriffs/postgrest#813]
I could not find any instructions for installing on windows.

Has anyone tried this before?

**Comment by begriffs** [comment]
You can download a windows binary from https://github.com/begriffs/postgrest/releases/tag/v0.4.0.0 and just run it, or [build from source](https://postgrest.readthedocs.io/en/v0.4/install.html#build-from-source).

**Comment by jackrabb1t** [comment]
thank you begriffs and ppKrauss!

**Comment by jackrabb1t** [comment]
It asked to download libpq.dll which I did, and I now am able to run it. 
Thanks!!
