### ISSUE TITLE
Prevent connections from going idle

### ISSUE THREAD

**Issue by fab1an** [begriffs/postgrest#814]
Is there a way to keep the connection to postgres open, even when there are no requests arriving?

**Comment by ruslantalpa** [comment]
No, the amount of time before the connection is closed after being idle is defined here
https://github.com/begriffs/postgrest/blob/master/main/Main.hs#L67
and it's 10s
If you want longer intervals, you need to compile from source

**Comment by fab1an** [comment]
Ok, thanks.

**Comment by begriffs** [comment]
We could theoretically expose this is a config file parameter... What's the use case?

**Comment by fab1an** [comment]
I patched it already.

I'm running PL/Java for generating PDFs and other things. Every JDBC-Connection holds on to a JVM. The method calls are fast, I'm getting 50ms responses with hundreds of concurrent clients, but the JVM startup is very slow - sometimes a couple of seconds.

So what I would like is for postgrest to keep it's pooled connections open, so that the JVMs don't get destroyed (and also benefit from self-tuning over their runtime).
