### ISSUE TITLE
Any plans for POST full-JSON to RPC?

### ISSUE THREAD

**Issue by ppKrauss** [begriffs/postgrest#815]
PostgreSQL 9.5+ accepts JSON as parameter in user-defined functions... It will be perfect to expand universe of applications and to simplify communication. But,

> Procedures must used named arguments. To supply arguments in an API call, include a JSON object in the request payload and each key/value of the object will become an argument. [[guide](http://postgrest.com/en/v0.4/api.html#stored-procedures)]

so, it is only "at this moment" limitation, or an architecture planned to be as it, closed to JSON?

**Comment by begriffs** [comment]
You can also call a function that takes a single parameter of type json by sending the header `Prefer: params=single-object` to PostgREST with your request. That way the JSON request body will be used as the single argument. Is this the functionality you're looking for?
