### ISSUE TITLE
Any plans for GET rpc with path-parameters?

### ISSUE THREAD

**Issue by ppKrauss** [begriffs/postgrest#816]
PostgREST offers the [stored-procedure call](http://postgrest.com/en/v0.4/api.html#stored-procedures) by `POST /rpc/function_name`, but no option to use GET and/or the [usual path-parameter](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-templating)... There are some plan for it?

**Comment by begriffs** [comment]
We have been discussing it in #328. It's been a while since I've reviewed it. Check out the conversation and let me know what you think.

**Comment by ppKrauss** [comment]
I was enthusiastic with PostgREST... On the flip-side, many people would say *"don't count your chickens before they hatch"*, i.e. don't expect a lot from PostgREST while hasn't been released/delivered to solve real problems. So let's  see what I think, my dreams about real life use of PostgREST.

--------

**PostgREST is not REST without GET**: see [OpenApi specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md), that use as reference a good and mature (2012) standard, [RFC&nbsp;6570](https://tools.ietf.org/html/rfc6570) (URI templates). Today we can't work without it, it is impossible to deliver professional development without it.

## Short-term solutions to GET-URI-templating endpoints

As in a good *controller schema design*, like in [Spring-boot ](https://projects.spring.io/spring-boot/), Django, CakePHP, and other mature frameworks, we can **centralize all *endpoint* definitions**.  With PostREST-Nginx we can centralize in the `/etc/nginx/sites-available/*` scripts. So a simple and natural way to do it is parse simple directives into ugly-but-reliable Nginx scripts.  

The solution that I scratched at issue #825 ("templating and translating endpoints to Nginx")  is valid for both, the today's incomplete PostgREST schema (incomplete support for stored procedures) and a future complete one.

## Long-term motivations

Are there a pent-up demand for *PostgreSQL experts*, where we see PostgREST as a potential supplier? **YES**: 

*   In **[Agile](https://en.wikipedia.org/wiki/Agile_software_development) context**, *PostgreSQL experts* lost market share to the competition with agile-frameworks (Spring-boot, Django, CakePHP, etc.) and [NoSQL](https://en.wikipedia.org/wiki/NoSQL). Today the cost of  a system implemented in SQL-side by *PostgreSQL expert* team is 2 to 10 times more expensive than a agile-framework team. We lost the game: only few older and crazy companies use *SQL experts* in (agile) system development. <br/> If a back-end system can be developed with PostgREST in 1/2 or 1/10 of the competitor's development-time, will be rationale to contract a *PostgreSQL experts* team.

* in traditional development and maintenance of traditional systems, PostgREST also can be a good tool... for plug new web functionalities, and as developer checking-tool, or a tool for a testing team.

* in mix one:  if PostgREST offers a complete infrastruture to use and expose XML, [JSON and JSONb](https://www.postgresql.org/docs/current/static/functions-json.html) datatypes of *PostgreSQL 9.6+* at enpoints, will be fine... Not need "url-query syntax" for JSON, but need to offer good *endpoints*, as eg. MongoDB endpoints.
 
## Long-term solutions

PostgREST use [Convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration), and it is good... But need an **"general switch" configuration** to offer other options! A full-OpenAPI spec need *template URI* (*pathParam*) with POST... See #815.

**Comment by begriffs** [comment]
Thanks for taking the time to explain your expectations for api server design and suggesting how postgrest could address them.

However I think postgrest might not be what you're looking for, and may not ever be. What makes me think that is when you say
> Today the cost of a system implemented in SQL-side by PostgreSQL expert team is 2 to 10 times more expensive than a agile-framework team. We lost the game: only few older and crazy companies use SQL experts in (agile) system development.
Having SQL experts create an API is pretty much the main goal of postgrest. We are specifically not positioning ourselves as another Django or CakePHP. Many people are super productive using those technologies I'm sure, but it's just not my interest.

Happy to help you with specific questions about using postgrest for a project, and I hope you find it useful, but I'm closing this issue. It's not the direction we're going. Feel free to reply if I've misunderstood you.
