### ISSUE TITLE
Question: postgrest and PostgreSQL 9.5

### ISSUE THREAD

**Issue by mapsa** [begriffs/postgrest#820]
Hello,
I've installed postgrest 0.4 and PostgreSQL 9.5 and after follow your installation instructions I have this error:
ERROR:  schema "jwt" does not exist
LINE 4:   SELECT jwt.sign(
Do I have a problem with the installation?
Thanks,
Paola

**Comment by begriffs** [comment]
Did you install the https://github.com/michelp/pgjwt extension in your database?

**Comment by mapsa** [comment]
Yes! that was the problem. I had to change "jwt.sign" for just "sign" after. However, I couldn't make the authentification work.
Thanks for your reply.
