### ISSUE TITLE
Cannot connect when using postgrest.conf

### ISSUE THREAD

**Issue by lifepillar** [begriffs/postgrest#824]
I am using Postgrest 0.3.2.0 under macOS, installed with Homebrew. I can run the server and connect successfully if I pass the parameters on the command-line:

```
postgrest postgres://test_user:test_pwd@127.0.0.1:5432/testdb -a test_user -s raw_data
```

If I use the following `postgrest.conf` instead:

```
db-uri = "postgres://test_user:test_pwd@127.0.0.1:5432/testdb"
db-schema = "raw_data"
db-anon-role = "test_user"
```

I have two problems:

1. `postgrest postgrest.conf` results in `Missing: (-a|--anonymous ROLE)` even if `db-anon-role` is present in `postgrest.conf`;

2. I can run the server with `postgrest posgrest.conf -a test_user`, but when I visit `http://127.0.0.1:3000/testdb` I get the following message:

```
{"details":"missing \"=\" after \"postgrest.conf\" in connection info string\n","code":"","message":"Connection error"}
```

Any idea how I can fix this?

**Edit:** added missing port to web URL.

**Comment by ruslantalpa** [comment]
version 3.2 works with command line parameters only
version 4.0 works with config file only

if you want to use the config file, use the last version (4.0)

**Comment by lifepillar** [comment]
Ah ok, 4.0 works. Thanks!
