### ISSUE TITLE
Computed Column only works in public-schema

### ISSUE THREAD

**Issue by chrismayer** [begriffs/postgrest#828]
When implementing a "Computed Column" according to the documentation [here](https://postgrest.com/en/v0.4/api.html#computed-columns), it only worked when the function defining the computed column is in the ``public`` schema.

Is this a bug or is the PostgREST version used too old or is this wanted behaviour?

``Tested version is PostgREST v0.3.0 with PostgreSQL 9.4.``

**Comment by begriffs** [comment]
It's by design actually, postgrest exposes tables/views/functions in a schema that you [designate](https://postgrest.readthedocs.io/en/v0.3.2/install_server.html#running-the-server) with the `--schema` command line argument. It is intentionally hiding the other information. (One exception is that views in the public schema can internally refer to tables in another schema if desired.)

Also if you're on v0.3.0 you should really consider upgrading. Even a later 0.3.x release has many bugfixes. You can see the changes in the [releases](https://github.com/begriffs/postgrest/releases) page.

**Comment by chrismayer** [comment]
Thanks for your detailed explanation @begriffs. I am already using the ``--schema`` option (let's say schema "foo"). But putting the function for the computed column in the schema "foo" (``foo.compute_my_col(bar)``) does not have any effect. The computed column cannot be queries via HTTP. Only when I put the function into the public schema, the computed column is avaliable via HTTP. 

> Also if you're on v0.3.0 you should really consider upgrading

I know that 0.3.0 is much too old :see_no_evil: and an update to a newer PostgREST version is on top of my TODO list.

**Comment by begriffs** [comment]
> Only when I put the function into the public schema, the computed column is avaliable via HTTP.

That actually sounds like a bug. I'd expect the computed column to be available when its function is in the schema you expose. I'm curious if the same problem occurs in a newer postgrest version...

**Comment by chrismayer** [comment]
Agree that it is not a good strategy to dig deeper in the old version. I will upgrade within the next days and will report here if this still occurs.

**Comment by steve-chavez** [comment]
I can confirm this on the latest version, to reproduce on current test suite change the [computed column always_true](https://github.com/begriffs/postgrest/blob/master/test/fixtures/schema.sql#L121) ```public``` schema to ```test```. Two tests will fail with: 

```
{"hint":null,"details":null,"code":"42703","message":"column items.always_true does not exist"}
```

They will pass if this is added to ```privileges.sql```:

```
ALTER ROLE postgrest_test_authenticator SET search_path = 'public', 'test';
```

So it seems that in order to detect the computed column in the exposed schema the user needs to have the schema in his search_path.

**Comment by begriffs** [comment]
Sounds like consequence of how postgresql does computed columns, but probably deserves a note in the docs.

**Comment by steve-chavez** [comment]
I think this is more related to the currently used syntax for computed columns:

```sql
  select i.computed_column from items i;
```

Seems this is used to conveniently avoid extra code for computed columns and treat them just as another column for building the query, but the drawback is that of the search_path. I think with this other syntax for using computed columns the search_path issue can be avoided:

```sql
  select schema.computed_column(i) from items i;
```

Though it requires extra code.

**Comment by begriffs** [comment]
How would postgrest know which syntax to use? Would we need to add information about computed columns to the db structure created at startup and then check the `?select=a,b,c` variables against that list?

**Comment by begriffs** [comment]
Here's an idea, and maybe we've discussed and rejected it already but just in case... What if in addition to qualifying the schema for all names to match the `--schema` parameter we also set the search_path to that schema for the requests? The qualified names means we won't be changing the semantics of which tables/views/procs the user sees, but the extra search_path change would fix the computed columns problem.

**Comment by fab1an** [comment]
I just stumbled over the same problem with latest version. I think that the cleanest way overall would be to do `set schema '<appschema>'` (which is completely equivalent to `set search_path='<appschema>'`).

Maybe in the future, if that's feasable, postgrest should drop all custom schema referencing (which could break by weird database-configurations anyway) and just do a `set schema` do enforce consistent behaviour.
We had a discussion about that here: #761

**Comment by begriffs** [comment]
I haven't experimented with trying to change the code, but `set schema 'abc'` sounds more elegant than our prepending `abc.` to the names of tables in queries.

**Comment by fab1an** [comment]
That is what i‘m doing now in the startup-procedure. So far everything
works.
