### ISSUE TITLE
DB2 Support

### ISSUE THREAD

**Issue by chadbrewbaker** [begriffs/postgrest#838]
I'm interested in adding DB2 support (perhaps SQLite too).  Other than pulling down info from the database specific system tables what else would be involved?

As I understand it 90% of the work would be rewriting SQL queries in DbStructure.hs. 

-- Initial notes on DB2 system tables
select * from SYSIBM.SYSCOLUMNS; 
select * from SYSIBM.SYSTABLES; 
select distinct tbname, reftbname from SYSIBM.SYSRELS;
select TBNAME, COLNAME from SYSIBM.sysforeignkeys;

--Notes on SQLite
SELECT * FROM sqlite_master;

**Comment by begriffs** [comment]
We use other postgresql features too, like JSON serialization (row_to_json, etc), CTE support for table and resultset counting, GUCs for JWT claims, named arguments for stored procedures, full text search with to_tsquery, computed columns, and jsonb operators like `->>`.

**Comment by chadbrewbaker** [comment]
Ok, might have to add client side JSON serialization for databases that don't support it. Don't need support for the other stuff.  Use case is replacing some megacorp handcrafted Java Spring REST APIs that are costing $$$ to build out and maintain.

One other feature might be batch chunking for large queries.

**Comment by PierreRochard** [comment]
Why not write postgrest for DB2 in Java (Scala?) to provide a solution for that ecosystem? 

I realize that would be time consuming, but I think the universe of "programmatically reflect database schema into REST API" solutions should grow and be polyglot. It's a paradigm shift with incredible synergies! 😄

**Comment by steve-chavez** [comment]
Aside from the JSON feature, for postgREST jwt auth to work the RDBMS should also support switching roles in transaction scope, setting environment variables in transaction scope(otherwise you'll have a 1-1 correspondence between db user and app user). So I don't think you can have that feature in SQLite though maybe you can in DB2.

**Comment by chadbrewbaker** [comment]
@PierreRochard If I had to use another language it would probably be Python. The functionality to hit a database and get the schema info in a standard format is in itself a useful project.

REST/GraphQL API on top is a separate layer to me.

**Comment by ruslantalpa** [comment]
Closing this since DB2 support is not "in the stars", at least for now :)
PS: as for GraphQL, it is the thing that sparked the work on `&select` parameter, and GraphQL on top of PostgREST is here https://subzero.cloud 😛
