### ISSUE TITLE
Bad SQL coding practices in "Computed Columns" example

### ISSUE THREAD

**Issue by vog** [begriffs/postgrest#839]
The example given in the "Computed Columns" section encourages bad coding practices:

```sql
CREATE TABLE people (
  fname text,
  lname text
);

CREATE FUNCTION full_name(people) RETURNS text AS $$
  SELECT $1.fname || ' ' || $1.lname;
$$ LANGUAGE SQL;

-- (optional) add an index to speed up anticipated query
CREATE INDEX people_full_name_idx ON people
  USING GIN (to_tsvector('english', fname || ' ' || lname));
```

This contains code duplication, which may lead to unexpected performance degradation wtihout any warnings as soon as the definition of `full_name` changes. Instead, the custom function should be reused in the index definition:

```sql
CREATE INDEX people_full_name_idx ON people
  USING GIN (to_tsvector('english', full_name(people)));
```

Note that this works with all `IMMUTABLE` functions. Moreover, `full_name()` is recognized by PostgreSQL automatically to be `IMMUTABLE`, you don't even need to add the `IMMUTABLE` keyword to your function definition.

**Comment by begriffs** [comment]
Good point -- care to send a pull request to https://github.com/begriffs/postgrest-docs ?
