### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by vog** [begriffs/postgrest#840]
The documentation contains a word duplication of "respond":

> That is to say the same API endpoint can respond respond in different formats like JSON or CSV depending on the client request.

This should be corrected to:

> That is to say the same API endpoint can respond in different formats like JSON or CSV depending on the client request.

**Comment by begriffs** [comment]
Cool, care to submit a fix in https://github.com/begriffs/postgrest-docs ?

**Comment by dk1983** [comment]
@begriffs, this is my first ever commit to any open source project, please let me know if done incorrectly or if it needs work.

**Comment by begriffs** [comment]
@dk1983 thanks for jumping in to help! You did it perfectly.
