### ISSUE TITLE
Broken reference in docs

### ISSUE THREAD

**Issue by vog** [begriffs/postgrest#841]
Section "Resource Embedding" reads as follows:

```
As seen above in `vertical_filtering`_ we can request the titles of all films like this:
```

That is, the link to "vertical filtering" is broken. It should be replaced with a proper link to section "Vertical Filtering (Columns)".

**Comment by begriffs** [comment]
Thanks, will fix. When switching the docs to Sphinx a few links got messed up.

**Comment by begriffs** [comment]
OK, I had sphinx-autobuild analyze each page and I think all the links are resolved now. Let me know if you find any others, and thanks again for pointing out broken stuff.
