### ISSUE TITLE
JWT security issues

### ISSUE THREAD

**Issue by FGRibreau** [begriffs/postgrest#842]
(I could not find an issue on this here but if it exists please close this issue as a duplicate :+1:)

I see more and more articles from security people asking **not** to use JWT for anything or at least not for sessions:

- http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/
- https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid

Currently postgrest only supports jwt as a session mechanism. I wonder if support for signed cookies was ever thought about, or why we would want to stay with jwt?

**Comment by ruslantalpa** [comment]
The part that needs investigation is if the libs used are not vulnerable and that the default alg is secure (maybe even refuse to work with secrets smaller then x number of chars and alg=none), i.e. can they be forged?

The other part that is also true is that you can not invalidate a jwt (you can only add code to black list them)

Other then that (if you store them as cookies and only do not add anything besides info to identify the user) i have not seen something that says "change that now or you will get hacked" (although i only looked over the articles and have not actually carefully considered this).

**Comment by begriffs** [comment]
Should we create some concrete issues from this discussion?

**Comment by leondutoit** [comment]
Hi, the fact that postgrest only uses HS256 means that the alg=none problem is dealt with atm. 

I see there was some discussion about the JWT library that postgrest uses in #567. As a user of postgrest I think it would be great if I could point to evidence that JWT is being handled in the a rigorous way - especially when someone questions me on that. 

One possibility would be to include a section on JWT in postgrest's docs with a discussion of: 
- known vulnerabilities 
- a justification of postgrest's library choice (Web.JWT vs jose)
- what postgrest does to protect against known vulnerabilities

Having that would be a helpful reference point for all users of postgrest. I'd be happy to contribute to such documentation and investigation of libraries as far as I'm capable.

Thinking a bit more long term, if postgrest decides to stick with JWT I would vote for extending its capabilities to handle encrypted tokens (JWE) as well.

cheers

**Comment by begriffs** [comment]
@leondutoit I'm currently adding support for more algorithms with the jose library actually. Should have a PR to review pretty soon.

Would love your help with documentation!

**Comment by leondutoit** [comment]
I see there is discussion about moving the docs the main repo (https://github.com/begriffs/postgrest-docs/issues/37). Should I wait for that to happen before sending the PR?

**Comment by begriffs** [comment]
Nah, you can open the PR against the docs repo. There's plenty of other things for me to deal with before attempting to move the docs.

**Comment by begriffs** [comment]
By the way, I've finished the feature for supporting more JWT algorithms. However it's still on a local branch while I discuss the changes with a company who has commissioned the work.

**Comment by leondutoit** [comment]
Oh man, sorry it took so long but I've finally create a PR. Hope it addresses some of the main questions people might have. Feedback welcome :)
