### ISSUE TITLE
Documentation issue in auth0 howto

### ISSUE THREAD

**Issue by timbod7** [begriffs/postgrest#843]
The documentation describing how to use auth0:

https://postgrest.com/en/v0.4/auth.html#jwt-from-auth0

shows putting the role information in the auth0 `user_metadata`.  According to the auth0 UI, `user_metadata` is for:

> Data that the user has read/write access to (e.g. color_preference, blog_url, etc.)

whereas `app_metadata` is for

> Data that the user has read-only access to (e.g. roles, permissions, vip, etc)

Hence, shouldn't the howto example be written in terms of `app_metadata`?

**Comment by begriffs** [comment]
What I know about Auth0 comes from a brief night of pairing with an employee from there. I'd love your help improving the docs if you'd like to send a PR. https://github.com/begriffs/postgrest-docs

**Comment by timbod7** [comment]
See https://github.com/begriffs/postgrest-docs/pull/49

**Comment by begriffs** [comment]
Closing since this issue has been corrected in the docs.
