### ISSUE TITLE
Filter by embedded resource count

### ISSUE THREAD

**Issue by aranwe** [begriffs/postgrest#845]
Hello everyone,

In the example for Resource embedding I would like to be able to do following:
`GET /films?select=title,nominations{rank}&nominations=count.ge.2`

The main goal is that currently if you select embedded resources PostgREST always returns the parent.
I would like to be able to filter out parents that do not contain children. This gets more serious when embedding multiple levels of resources -> you have to transfer and filter lots of unnecessary data.

Possible alternative implementation(maybe better) could be:

`GET /films?select=title,count(nominations),nominations{rank}&count=ge.2`

There is currently support for computed columns but it cannot accept the embedded resources.

If there would be possibility to pass the list of embedded resources, it might be possible to create global function - though I am not sure if this is even possible in PGSQL -> this is beyond my PGSQL skill

```
CREATE FUNCTION count_resources(SETOF resources) RETURNS integer AS $$
    WITH res as resources
    SELECT COUNT(*) FROM res;
)
$$ LANGUAGE SQL;
```

The last approach is to implement for every relation function like:
```
CREATE FUNCTION film_count_nominations(film) RETURNS integer AS $$
  SELECT COUNT(*) FROM nominations WHERE film_id=$1.id;
$$ LANGUAGE SQL;
```
But this will result in lots of functions for every relation in every table.

Is there any other way how to resolve this?

Thank you very much!

**Comment by ruslantalpa** [comment]
One way to do it would be (but i am not completely sure it's optimal)
first, do not expose the schema where your tables live, expose a schema `api` where you have only view definitions

then have the last function that you defined somewhere and a view like

```
create or replace view api.films as
select id, name,  data. film_count_nominations from data.films;
```

then add a index like this
```
create index on data.films (data.film_count_nominations(data.films.*));
```

hopefully this index will prevent running that count query on each request.

If the index trick does not work then change the definition of the `api.films` view to be a join between films and nominations so that you can calculate that count column

**Comment by ruslantalpa** [comment]
this thing is off the top of my head so take it with the grain of salt, but the main idea is correct, you have to bring up the "child property" up to the level of the parent so that you can filter based on it as if it's a property of the parent

**Comment by begriffs** [comment]
@aranwe did the comments here help you with your issue? Any progress?

**Comment by aranwe** [comment]
@begriffs sorry I have not replied :)
In the end we have a bit reworked the design - but it would have had solved the problem partially:
We needed to filter the counted relations at the same time (i.e. WHERE count(nominations) > 0 AND nomination.rank = 'XY').
There is a workaround where we would query some aggregation table and from there the "films" and "nominations", but it would look rather messy.

So the count feature would have been great anyway (but I do not need it at the moment).

Anyway adding the count to the view directly for filtering is great postgrest design pattern -> we should create a Wiki with postgrest design patterns such as this as I believe lots of people could benefit from this (I know some tips&tricks are on the webpage, but there is quite a lack of PgSQL specific design patterns, let alone those that work nicely with postgrest).

I could write something up (though I will be unavailable for the next 3weeks) :).

If you find / stumble upon some interesting pattern link it here, I can go through that later and aggregate sth :).

**Comment by begriffs** [comment]
Thanks, I'd love if you wanted to contribute a new section in https://github.com/begriffs/postgrest-docs about design patterns. (That's the repo that generates https://postgrest.com)

**Comment by ruslantalpa** [comment]
The way to implement this seems to be answered here. A separate issue for documentations can be opened in the docs repo
