### ISSUE TITLE
Rasperry Pi 3 / ARM build?

### ISSUE THREAD

**Issue by bradleyf** [begriffs/postgrest#846]
I'm trying to get postgrest on Raspberry Pi 3.   I can install everything needed to build from source EXCEPT the Nix stuff.   (specifically nix-shell) Darn!

Any way to do an Arm build in some other fashion?

**Comment by ruslantalpa** [comment]
It has nothing to do with nix. it has to do with Haskell availability for ARM
to build we use https://docs.haskellstack.org/en/stable/README/

once you get that installed and working on ARM you will probably be able to build postgrest

**Comment by ruslantalpa** [comment]
There is a discussion here https://github.com/commercialhaskell/stack/issues/2103

**Comment by begriffs** [comment]
An article here as well http://allocinit.io/haskell/haskell-on-raspberry-pi-3/

**Comment by bradleyf** [comment]
I'm making some progress as a result of Robinvd's stack 1.4.0 binary.  But I'm getting stuck again, and I really don't know the toolchain for Haskell and LLVM, so maybe someone can provide hints or tips.   I do have LLVM 3.7 installed through the distrib.  Here's the last message I'm seeing:

$ sudo stack build --install-ghc --copy-bins --local-bin-path /usr/local/bin --allow-different-user
[1 of 2] Compiling Main             ( /home/riot/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /home/riot/.stack/setup-exe-src/setup-mPHDZzAJ.o )

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM 3.7
ghc: could not execute: opt
Exit code ExitFailure 1 while running ["ghc","-rtsopts","-threaded","-clear-package-db","-global-package-db","-hide-all-packages","-package","base","-main-is","StackSetupShim.mainOverride","-package","Cabal-1.24.2.0","/home/riot/.stack/setup-exe-src/setup-mPHDZzAJ.hs","/home/riot/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs","-o","/home/riot/.stack/setup-exe-cache/arm-linux/tmp-Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2"] in /tmp/stack7187/

**Comment by begriffs** [comment]
@bradleyf any luck building using techniques from the links above?

**Comment by bradleyf** [comment]
Looks like there now is an Arm build of Stack, so I might try again soon. See here (at bottom): https://github.com/commercialhaskell/stack/issues/2103

**Comment by ruslantalpa** [comment]
tell us how it went

**Comment by ruslantalpa** [comment]
@bradleyf  We now have an automated build process for release here https://github.com/begriffs/postgrest/blob/master/.circleci/config.yml

if you figure out how to build for ARM, a PR would be welcomed

**Comment by bradleyf** [comment]
I've tried several times to build it on arm using the orignial build instructions, however there is a problem with one of the haskell libraries requiring too much RAM to compile on the PI.   I believe it's the json library.   Tried several work arounds.  No luck yet.  Bummer

**Comment by ruslantalpa** [comment]
did you try `-j1` parameter when doing `stack build`? did you have swap setup?

**Comment by bradleyf** [comment]
Yes, but it still errors out with a memory error (Haskell stack trace).   Sooo close!

**Comment by ruslantalpa** [comment]
check this out
https://medium.com/@saurabhnanda/building-haskell-specifically-lens-library-in-a-low-memory-environment-5ef58ec294a2

**Comment by bradleyf** [comment]
I’ll give it a try

**Comment by albertobissacco** [comment]
News?
It will be build?
