### ISSUE TITLE
JWT secret as a database property

### ISSUE THREAD

**Issue by sernik** [begriffs/postgrest#847]
Hello,

Is there a simple way to reference a secret, set like docs suggest: `ALTER DATABASE mydb SET "app.jwt_secret" TO '!!secret!!';` in a configuration file? Or other way round: define it in a configuration file and use it in a login function?

**Comment by ruslantalpa** [comment]
That string (that is used in the login function)  can be either a GUC or it can be a row in a table, login function can pull it from anywhere, the important part it needs to be in the DB env.

If you want to have it as a config in a file, then you need to create your own custom script that is executed on system boot (maybe in postgrest startup script) that executes a sql query and transfers that value form the file to the database

**Comment by sernik** [comment]
Thank you, this is exactly what I ended up with. The startup script greps a secret from postgrest config file, sets it as a db property, then runs postgrest executable.

Perhaps this could be done by a postgrest itself… Thanks for a great software anyway.
