### ISSUE TITLE
Setting a default limit on any table

### ISSUE THREAD

**Issue by ranjanprj** [begriffs/postgrest#851]
I have been playing with a large dataset in Postgrest and this is just a suggestion.
If a table has for example Millions of records, shouldn't Postgrest redirect to or require a "limit" clause to display only limited data in the table or view and ask user explicitly to display all the data.
 
regards

**Comment by begriffs** [comment]
Have you tried the `max-rows` configuration option? https://postgrest.com/en/v0.4/admin.html#configuration

**Comment by ranjanprj** [comment]
Ah, didn't see that, this will do. Postgrest keeps amazing me.
