### ISSUE TITLE
Please tag docker image version 0.4.0.0

### ISSUE THREAD

**Issue by purpleKarrot** [begriffs/postgrest#855]
The only available versions on https://hub.docker.com/r/begriffs/postgrest/tags/ are `nightly`, `v0.3.2.0`, and `latest`.

**Comment by begriffs** [comment]
I'll make the new tag tonight.

**Comment by statik** [comment]
Thanks! I was looking for this today as well.

**Comment by begriffs** [comment]
OK I released a v0.4.0.0 tag on docker hub. Let me know if it works properly for you. Note that it does not work with environment variables. You must map a postgrest config file into the container.

Allowing docker environment variables will be enabled in the next release.

**Comment by statik** [comment]
This is working great, thank you.
