### ISSUE TITLE
Requesting OpenAPI endpoint with Accept: application/json throws 415

### ISSUE THREAD

**Issue by timwis** [begriffs/postgrest#860]
I'm using [postgrest-client](https://github.com/calebmer/postgrest-client) (wrapper around superagent) to request the OpenAPI page (`'/'`) in order to get a list of tables / field types. It's returning `415` with message `None of these Content-Types are available: application/json`. It appears to be caused by superagent adding the `Accept: application/json` header. When I try it manually with that I can reproduce it. Is this intended?

**Comment by begriffs** [comment]
It's been fixed on the master branch actually. There's a note in the changelog.
