### ISSUE TITLE
Stored procedure with JSONB argument not exposed through postgrest 

### ISSUE THREAD

**Issue by hewe** [begriffs/postgrest#862]
I have defined a function on postgres that takes JSONB argument as the only argument, however, when attempting to call the function through postgREST it fails and complains that no function defined with argument of json type. I understand the below example I could use bulk insert via POST, however, the example is much simplified here than my actual use case.  

Step to reproduce:

1. Create the stored function with JSONB argument as follows:

`CREATE OR REPLACE FUNCTION insert_from_document(jsonArrayOfPeople **JSONB**)
  RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  people JSONB;
BEGIN
  FOR people IN SELECT * FROM jsonb_array_elements(jsonArrayOfPeople)
  LOOP
    PERFORM insert_from_raw_people(people);
  END LOOP;
END;
$$;`

2. Send the post request via curl:
`curl -X POST \
  http://localhost:3000/rpc/insert_from_document \
  -H 'content-type: application/json' \
  -H 'prefer: params=single-object' \
  -d '[{"first_name": "John", "last_name": "Smith"},{"first_name": "Bob", "last_name": "Smith"}]'`

3. Observe the error response from postgREST:
`{
  "hint": "No function matches the given name and argument types. You might need to add explicit type casts.",
  "details": null,
  "code": "42883",
  "message": "function public.insert_from_document(json) does not exist"
}`

**Comment by begriffs** [comment]
Thanks for the bug report. I was about to mention `params=single-object` but you're already using it.

Looks like the problem is in https://github.com/begriffs/postgrest/blob/master/src/PostgREST/QueryBuilder.hs#L168

We could try `insertableValueWithType "unknown"` and see if postgresql can figure out when to use json/jsonb.

**Comment by hewe** [comment]
Thanks for the suggestion. Tried` insertableValueWithType "unknown"` and I would get a different error with the same post request in my initial submission: 
```
{
  "hint": null,
  "details": null,
  "code": "22023",
  "message": "cannot extract elements from an object"
}
```

I however found a work around for this for now. The work around is to wrap the json array in a json object with a document property, eg: 
curl -X POST \ http://localhost:3000/rpc/insert_from_document \ -H 'content-type: application/json' \ -H 'prefer: params=single-object' \ -d '{"document: [{"first_name": "John", "last_name": "Smith"},{"first_name": "Bob", "last_name": "Smith"}]}'

**Comment by begriffs** [comment]
Also, what if you modified the function to take a json argument rather than jsonb? That might make the initial rpc request work.

**Comment by ruslantalpa** [comment]
This is not a workaround (wrapping the body), this is the correct way of calling a function, the body of the request (calling rpc functions) needs to be a single json object with parameter names as keys for the json object, even if it's just one parameter.
