### ISSUE TITLE
How to release (expire) JWT token?

### ISSUE THREAD

**Issue by esmeetu** [begriffs/postgrest#865]
After reading the docs: [https://postgrest.com/en/v0.4/auth.html#client-auth](https://postgrest.com/en/v0.4/auth.html#client-auth),
`client auth` works fine, but now i want to make jwt token expire. 
*Like this:*
```
POST /rpc/release_token HTTP/1.1
Authorization: Bearer <jwt token>
```
To make current `<jwt token>` expire immediately, and won't auth with that later.

Is there a way?

**Comment by begriffs** [comment]
You can use the `pre-request` configuration parameter to specify a custom stored procedure to run. In this function you can do any check you want to possibly reject a user request. For an example, see https://postgrest.com/en/v0.4/auth.html#custom-validation

**Comment by esmeetu** [comment]
@begriffs Thanks for your reply.

Still confused, should i save the `exp` variable? And then write a `pre-request` function to check the diff between `will be released` exp (new POST) and the old saved exp.

P.S. this is my related `login` function:
```sql
create function cd.login(email text, pass text) returns basic_auth.jwt_token
LANGUAGE plpgsql
AS $$
declare
  _role name;
  result basic_auth.jwt_token;
begin
  -- check email and password
  select basic_auth.user_role(email, pass) into _role;
  if _role is null then
    raise invalid_password using message = 'invalid user or password';
  end if;

  select basic_auth.sign(
      row_to_json(r), 'esmeetu'
    ) as token
    from (
      select _role as role, email as email,
         extract(epoch from now())::integer + 60*60 as exp
    ) r
    into result;
  return result;
end;
$$;
```

**Comment by begriffs** [comment]
PostgREST will automatically reject expired tokens (it compares the time of the request to the timestamp in the exp claim). So your code doesn't need logic to check for normal expiration. However if there is some other reason that you want to reject tokens, you can use a pre-request function to check for those conditions and reject the user.

Can you explain your use case?

**Comment by esmeetu** [comment]
If i want to logout, i want to make my jwt token expire immediately for security. Is that necessary?

**Comment by begriffs** [comment]
To do that you'll need a table or something in your database that keeps track of whether the user has logged out. The pre-request can check that table for the given role, and if they are logged out then it will throw an exception. The next time that user logs in it should give them a new jwt and clear the logged out indication from the table.

**Comment by esmeetu** [comment]
OK, i will try your suggestion. Thanks again. :)
