### ISSUE TITLE
Starting Postgrest

### ISSUE THREAD

**Issue by ACPK** [begriffs/postgrest#871]
I tried:

    postgrest postgres://postgrest@localhost/catarse_development

But get:

    Cannot open config file:
    
    postgres://postgrest@localhost/catarse_development: openFile: does not exist (No such file or directory)

**Comment by begriffs** [comment]
The first argument should actually be the path to a config file rather than a postgres connection string. That connection string and other parameters will live inside the config file. See https://postgrest.com/en/v0.4/admin.html

**Comment by ACPK** [comment]
@begriffs - Thank you! What would the db-schema be?

I set it as "schema", but get the error below when I visit localhost:3000/users:

    {"hint":null,"details":null,"code":"42P01","message":"relation \"db-schema.users\" does not exist"}

**Comment by begriffs** [comment]
By default when you create tables etc in a postgres database they are in the "public" schema. For testing things out feel free to expose that schema directly with postgrest. (Learn more about schemas here https://www.postgresql.org/docs/9.6/static/ddl-schemas.html)

In the long run you'll want to put your core data in one schema but expose another one to the API clients. The exposed one would have views that allow you the flexibility to change the core data without breaking clients.

**Comment by ACPK** [comment]
@begriffs - Thank you very much as your help has been extremely appreciated! Your solution worked but I now see a bunch of weird code (see below) when I visit http:localhost:3000. By any chance, do you have a sample api schema that I could work off?

    |^not[.]<@[.]|^not[.]in[.]|^not[.]notin[.]|^eq[.]|^gte[.]|^gt[.]|^lte[.]|^lt[.]|^neq[.]|^like[.]|^ilike[.]|^is[.]|^isnot[.]|^@@[.]|^@>

**Comment by ACPK** [comment]
@begriffs Thank you, and I was able to create an API schema.  In regards to the JWT, how can I test this as my application is getting "Completed 401 Unauthorized" for its API request.

**Comment by begriffs** [comment]
What does the JWT look like? You'll want to create a one with a `{ "role": "postgresql_user_name" }` claim, and sign it with a secret password that you also provide to postgrest server in the config file. You can easily create a JWT by visiting jwt.io and entering in a JSON object and a secret key.

Also if you haven't read this part of the postgrest guide, you should check it out to get an idea of how the roles work. https://postgrest.com/en/v0.4/auth.html

**Comment by ACPK** [comment]
@begriffs - Thank you for your help, as it was greatly appreciated!

With locally running, I'm working on deploying it to production using: https://elements.heroku.com/buttons/begriffs/postgrest.

I apologize for asking, but what would the url be so I can add the buildpack to an existing application?

**Comment by begriffs** [comment]
No problem, I'm happy to help.

The direct buildpack url is https://github.com/begriffs/postgrest-heroku.git

**Comment by ACPK** [comment]
I apologize if I wasn't clear. What would the postgrest url (ex: localhost:3004) so I can point my main  app to it?

**Comment by begriffs** [comment]
Heroku assigns a random port number during each deployment, but I believe it is available from the $PORT environment variable. https://devcenter.heroku.com/articles/dynos#web-dynos

**Comment by ACPK** [comment]
So how do I find out what the Web url of Postgrest is. My app requires it as it needs to know where to do API requests to.

**Comment by begriffs** [comment]
Initially I thought you had modified the buildpack or something to have your app run inside the dyno with postgrest.

But you're just wondering what the url is for your newly deployed app? The Heroku web interface should show you your apps and their urls, or you can use the command line interface described here https://devcenter.heroku.com/articles/using-the-cli#app-commands

**Comment by ACPK** [comment]
@begriffs - So I have to run it as its own app? Will I be able to push my RDS SSL files to it?

**Comment by ACPK** [comment]
@begriffs  - Thanks. I created a second app but am unable to successfully connect to my database.

I get the following error as my database url ends with "?sslca=awscreds.pem&sslmode=require":

    2017-05-11T07:41:28.795698+00:00 app[web.1]: Database connection error:
    2017-05-11T07:41:28.796654+00:00 app[web.1]: invalid URI query parameter: "sslca

**Comment by ACPK** [comment]
@begriffs  - I created a separate app using the Heroku "button" and set the configuration by adding a "postgrest.conf" file to it.  

However, I get the error:

   {"hint":null,"details":null,"code":"42501","message":"permission denied to set role \"anonymous\""}
