### ISSUE TITLE
"permission denied to set role \"anonymous\"

### ISSUE THREAD

**Issue by ACPK** [begriffs/postgrest#875]
When I visit the root path, I get:   

    {"hint":null,"details":null,"code":"42501","message":"permission denied to set role \"anonymous\""}

**Comment by SebAlbert** [comment]
Have you `GRANT`ed the `anonymous` role to the role that PostgREST is connecting as (as specified in the connect string or the environment variables)?

**Comment by ACPK** [comment]
@SebAlbert -  The issue seems not to be related to Postgrest so I'm closing this issue. The issue seems to be that my migration files that were writting for PostreSQL 9.4 don't work with 9.6. The errors I get are:

   unknown OID 24: failed to recognize type of 'aggfnoid'. It will be treated as String.
   unknown OID 194: failed to recognize type of 'adbin'. It will be treated as String.
   unknown OID 1034: failed to recognize type of 'attacl'. It will be treated as String.
   unknown OID 28: failed to recognize type of 'relfrozenxid'. It will be treated as String.
   unknown OID 2277: failed to recognize type of 'stavalues1'. It will be treated as String.

**Comment by SebAlbert** [comment]
Urgs, yes, major releases (i.e., a change in the first two numbers of a version) are generally not binary compatible. Consider pg_upgrade (or getting the old data out of the old database version by pg_dumpall and piping them into the new one via psql)

**Comment by ACPK** [comment]
@SebAlbert - Actually I found the code here:

**Comment by ACPK** [comment]
@SebAlbert - I tried on 9.4 now and it also didn't work.

**Comment by SebAlbert** [comment]
I cannot read through all those migrate SQL snippets... have you checked that the role "postgrest" has the right to become user "anonymous"? Try `GRANT anonymous TO postgrest` in your database (as a superuser)

**Comment by ACPK** [comment]
Solved it!

**Comment by SebAlbert** [comment]
Looks like this also solves #871 right?
