### ISSUE TITLE
Base64 secret cannot be decoded from a file ending with a newline

### ISSUE THREAD

**Issue by eric-brechemier** [begriffs/postgrest#877]
By convention, Unix utilities write and expect a line feed (`0a`) character at the end of each line, including the last, even when the file contains a single line.

For example, the `base64` utility installed on Mac OS X (from BSD) or Ubuntu (from GNU coreutils) both append an end of line character after the base64 value:

```
$ openssl rand 8 | base64 > /tmp/secret.base64
$ xxd /tmp/secret.base64
00000000: 714b 6559 3036 4276 4630 4d3d 0a         qKeY06BvF0M=.
```

```
## choose a secret to enable JWT auth
## (use "@filename" to load from separate file)
jwt-secret = "@/tmp/secret.base64"
secret-is-base64 = true
```

PostgREST v0.4.1.0 fails to parse this kind of file, with the error:

```
postgrest: FatalError {msg = "invalid padding"}
```

When the end of line is removed however,

```
$ openssl rand 8 | base64 | tr -d '\n' > /tmp/secret.base64
$ xxd /tmp/secret.base64
00000000: 5045 7a61 6171 4378 7542 6f3d            PEzaaqCxuBo=
```

PostgREST starts without error.

**Comment by begriffs** [comment]
Good to know. Would you be interested in sending a PR to call [strip](https://hackage.haskell.org/package/text-1.2.2.2/docs/Data-Text.html#v:strip) on the loaded string to remove the start/end whitespace prior to decoding?

**Comment by eric-brechemier** [comment]
Yes, I'll work on that next week.

**Comment by begriffs** [comment]
@eric-brechemier any progress with this?

**Comment by eric-brechemier** [comment]
@begriffs Yes, I [started to add tests](https://github.com/begriffs/postgrest/compare/master...eGullGolf:issue876) but I got sidetracked when I realized that the unit tests do not run the `App` but define their own configuration harness instead, which makes it hard to test the reading of a secret from a file.

Could you give me a hint of where to start to add such a unit test? I was wondering whether it would make sense to run some unit tests by sending HTTP requests to an instance of the PostgREST server for example.

**Comment by begriffs** [comment]
This is an area where the tests are nonexistent, which is probably why we've traditionally had more problems on the config side than the HTTP side.

I'm OK if you make the fix without tests for this one.

Ideally we should get the app configuration under test as well. Anybody who wants to tackle that would be my hero, but I'm going to leave that to the community. 😄

**Comment by eric-brechemier** [comment]
@begriffs I wrote the first unit tests for PostgREST I/O in shell script:

https://github.com/eGullGolf/postgrest/blob/issue877/test/io-tests.sh#L84

These tests could benefit from being rewritten in Haskell: for integration with other unit tests and to avoid arbitrary delays (1 second `sleep` to wait for the PostgREST server to start in each test).
