### ISSUE TITLE
Get csv response from stored procedure 

### ISSUE THREAD

**Issue by bloigge** [begriffs/postgrest#878]
First of all: Great Project!

I would like to know if there is a way to get `text/csv` from a stored procedure. My procedure returns a table and everything works fine using `Accept application/json`. But when I set the header to `text/csv` I get:

```
{
  "message": "None of these Content-Types are available: text/csv"
}
```

Stored Procedure:
```
CREATE OR REPLACE FUNCTION interface.get_new_contracts(ts bigint) 
RETURNS TABLE (
	l_id character varying,
	l_status character varying,
	l_contact character varying,
	l_ext_changed bigint
)
AS $$
BEGIN
 RETURN QUERY SELECT
	 id,
	 status,
	 contact,
	 ext_changed
 FROM
	interface.contract
 WHERE
       ext_changed > ts OR status = ''; 
END; $$ 
 
LANGUAGE 'plpgsql';
```

REST Call:
```
curl -X POST http://myserver/rpc/get_new_contracts -H 'accept: text/csv' -H 'content-type: application/json' -d '{"ts":149503100}'
```

Unfortunately I have no clue using Haskell so I am a little bit stuck.

**Comment by SebAlbert** [comment]
I second this, had this requirement only a couple of days ago, too.

**Comment by bloigge** [comment]
Thanks!
