### ISSUE TITLE
Use TAP and pgtap?

### ISSUE THREAD

**Issue by ppKrauss** [begriffs/postgrest#881]
The [TAP - test anything protocol](http://testanything.org/) can be used with Haskell (see [haskell.org/tasty-tap](https://hackage.haskell.org/package/tasty-tap)) and with PostgreSQL (see [pgtap](https://pgxn.org/dist/pgtap/doc/pgtap.html)). Will be easy to migrate [DbStructureSpec.hx](https://github.com/begriffs/postgrest/blob/master/test/Unit/DbStructureSpec.hx) parts or all [PgQuerySpec.hx](https://github.com/begriffs/postgrest/blob/master/test/Unit/PgQuerySpec.hx) to *pgtap*.

It is better to SQL user/developer to see all SQL-tests in SQL code.

**Comment by begriffs** [comment]
The DbStructureSpec.hx file is actually not used anymore, it's an old unreferenced file. However we do have  complicated sql statements in parts of the psotgrest code and it would be great to unit-test them. Would it be inconvenient to create a pull request to show me what you have in mind?

**Comment by ppKrauss** [comment]
Hi   @begriffs, there are a good clue in the [pgjwt](https://github.com/michelp/pgjwt) extension, that was  cited by you at [docs/auth.html#jwt-generation](https://postgrest.com/en/v0.4/auth.html#jwt-generation) (see [test.sql](https://github.com/michelp/pgjwt/blob/master/test.sql)).

**Comment by ruslantalpa** [comment]
those queries are tested using "integration tests" and therea are only a few of them and they never change, i don't see much value in testing them separately for now
