### ISSUE TITLE
Add binary output to rpc calls

### ISSUE THREAD

**Issue by nextstopsun** [begriffs/postgrest#883]
Please permit binary output for rpc `POST` requests and an `Accept: application/octet-stream` request header to use with it.
Right now I'm getting a response from a function returning `BYTEA` data, but it doesn't seem to be in the same binary form, that it is returned from a function in postgresql. `application/octet-stream` header is not set on response and request.
 
So I have to separate API from binary rpc calls and use [this nginx module](https://github.com/konstruxi/ngx_postgres/) instead of postgrest, which adds some inconveniences. 

My use case is quite simple: I'm serving `GEOMETRY` and other binary data out of my DB and would really like to use http rpc calls from postgrest endpoint.

Possible?

**Comment by begriffs** [comment]
I think it's probably possible, since we added it for GET. I'm personally a bit busy with other things at the moment, but will be happy to review the PR if somebody wants to implement this.
