### ISSUE TITLE
How to keep the token unique for each user?

### ISSUE THREAD

**Issue by dapangmao** [begriffs/postgrest#890]
It seems that a user can issue multiple tokens as he/she wants. Is there any way to make sure that at the same time only one token is valid for this particular user?

**Comment by ruslantalpa** [comment]
unique in timeframe means you either do not issue new ones (remember you already did) or invalidate old ones when you issue new ones. since jwt can not be invalidated, the only option is to record the ones you issued then mark them as blacklisted and on each request check the current one agains that list. possible using --pre-request function but i doubt you really really need that. maybe you just need a jwts that just expire in 1h

**Comment by dapangmao** [comment]
Thanks-@ruslantalpa This is a good thought!
To implement your idea, I could add a Redis layer to store all the JWT tokens and block all the login requests once a JWT token is still on use/TTL. However, the user experience may be not that good.

- So my question should really be - `how to expire the existing JWT tokens?`
I see the similar discussion #505 and @begriffs seems to be working on it. If I could find a way to delete the existing JWT tokens, the solution to my question will certainly be more grace.

**Comment by ruslantalpa** [comment]
the whole point of JWT is that they are stateless so you can't expire them at will. You can only have an expire mechanism if you have a `exp` field inside the jwt but once the token is issued, you can't selectively invalidate them, they are valid until they expire.
you are looking for a `regular` sessions solution where they are stored in a table in the db somewhere and it's possible using --pre-request custom function.

but again, do you really need that ability invalidate all previously issued jwts that are not expired yet?
why is it not acceptable to have tokens that expire in 1 hour?

**Comment by dapangmao** [comment]
@ruslantalpa Thanks a lot for the discussion!

I have some use cases - for example, a mobile device will do long polling and keep the session with the backend app or the DB for more than 1 hour.  Therefore, I have to increase the `exp` time for the JWTs in Postgrest. 

Currently a registered user can issue unlimited JWT tokens (each token grants the access privilege) for unlimited devices by calling the `login` function, which may bring security concerns. 

My guess is that Postgrest stores all the JWTs issued during its uptime in memory instead of the DB. I am looking for a work-around.  But if there is any option to invalidate the existing tokens now or in the future, that will be sweet.

**Comment by ruslantalpa** [comment]
you dont need to have exp longer then an hour.
what you do is whenever a token is about to expire, the client requests a new token (which again, is valid for one hour) ... refreshing the token

your tokens could have in thier payload the device id or something so you could make it so that a token issued is valid only for the device from where the login was generated

**Comment by dapangmao** [comment]
@ruslantalpa Thanks - you raised a good point. The user can always refresh the JWT tokens on the device and keep her/his status, as long as she/he is willing to login again and again after the 1-hour duration.

I asked this question, since I used to deal with a business model that tries to sell subscriptions for an application. Sometimes a few subscribers tend to resell their accounts again for profits. I just want to avoid the dilemma that one copy equals unlimited copies, by invalidating the existing JWT tokens.  

It is a little concern of mine. BTW,  Postgrest is so powerful for rapid prototyping, and I really love its simple data model.

**Comment by ruslantalpa** [comment]
the user does not need to login again, from time to time, you (the code) makes an authenticated call using the old but still valid token to something like /refresh_token which returns a new token, and from that point on you use that token.
what you need to do is have inside the jwt payload an identifier like deviceid or ip address.
whenever login is called, you generate the jwt with this data inside and make a note (database) that from now on, only jwts that have this in the payload are accepted and check that with --pre-request 

if someone does the next login from another device/location, all the old jwts will be denied even though they are still valid.

your usecase is possible to implement.

**Comment by dapangmao** [comment]
@ruslantalpa Thanks! Your thoughts are really appreciated! I will try the approaches and keep updated.
