### ISSUE TITLE
How to post a binary file?

### ISSUE THREAD

**Issue by loveencounterflow** [begriffs/postgrest#894]
I have a table for binary content:

    create table files (
      id serial primary key,
      content bytea
      )
      ;

that I can, of course, query with

    GET http://127.0.0.1:3000/files?id=eq.1&select=content
    Accept: application/octet-stream

However, I have not managed to POST binary data (i.e. upload a file). It should be most natural to use 

    curl -F "content=@path/to/file" https://localhost:3000/files

but that seems to hang indefinitely(?). Any other ways?

Since I probably will have to use an nginx server as frontend anyhow, is there any quick advice how to configure https://github.com/konstruxi/ngx_postgres/ (found it mentioned on another post) for that? Just in case binary POSTs should remain unimplemented for some time, that would probably make for a good stopgap solution.

**Comment by ruslantalpa** [comment]
Your best bet probably is to have a separate `/files` location that rewrites for get and for post uses the module you mentioned. Or go for openresty and script this with lua (only a couple of lines probably)

**Comment by loveencounterflow** [comment]
OK thanks for the pointers!

**Comment by begriffs** [comment]
Yeah I'm having a hard time coming up with what the correct HTTP interface would even be for this in postgrest itself. See if the workaround works for you, and if someone has an idea for a clean way to express that kind of a post request feel free to comment here for future consideration.
