### ISSUE TITLE
Boolean environment variable interpolation in config file

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#896]
As reported by @frosenb, attempting to read a boolean value from the environment from the config file causes an error. For example,

```bash
export ISBASE64=true
```
then
```ini
secret-is-base64 = "$(ISBASE64)"
```

Postgrest issues an error and dies:

```
ConfigError {configErrorLocation = Key "" "secret-is-base64", configConversionError = Just [ConversionError {conversionErrorLoc = "boolValue", conversionErrorWhy = TypeError, conversionErrorVal = Just (String "true"), conversionErrorType = Just Bool, conversionErrorMsg = Nothing}]}
```

**Comment by devton** [comment]
having same issue when passing a number on DB_SCHEMA=1 
```
       ConfigError {configErrorLocation = Key "" "db-schema", configConversionError = Just [ConversionError {conversionErrorLoc = "textValue", conversionErrorWhy = TypeError, conversionErrorVal = Just (Number 1.0), conversionErrorType = Just Text, conversionErrorMsg = Nothing}]}
```

**Comment by begriffs** [comment]
What if you quote it like `db-schema = "1"`?

**Comment by devton** [comment]
@begriffs this errors is on deploying using the postgrest-heroku, i think that is on env-to-config.
Directly on postgrest.conf works fine.

**Comment by begriffs** [comment]
Can you check whether it works if you deploy a fresh Heroku app? I fixed a typo in the buildpack and perhaps you deployed initially pre-typo and subsequent deploys are messed up because of it.

**Comment by grudda** [comment]
The same for me when deploying on jelastic paas. I can define the env variable by a form and there are set then on startup. But I got the same error message as above.
![image](https://user-images.githubusercontent.com/18442458/29119632-37dea126-7d07-11e7-831b-1cb6291c664d.png)

**Comment by ruslantalpa** [comment]
@begriffs i think all the issues related to env vars and configs were fixed by your 2 PRs
(comment/reopen if not so)
