### ISSUE TITLE
v0.4.2.0 does not run on Windows 10

### ISSUE THREAD

**Issue by monemihir** [begriffs/postgrest#898]
I have read the notes in "**Installation instructions on Windows #813**" issue but that hasn't worked.
I have PostgreSql 9.5 installed. I am running on Windows 10 x64.

- First error: **libpq.dll** was not found which was known acc. to the issue above. 
- Second error: **libintl-8.dll** was not found which I found under the **bin** folder of PostgreSql
- Third error: See screenshot below
![postgrest-error](https://user-images.githubusercontent.com/1818313/27616534-c3c5be84-5bf3-11e7-83da-5a2605df1bc1.jpg)

I have been happily using v0.2.10 but now need to upgrade to be able to deploy to windows/centos.

**Comment by steve-chavez** [comment]
I had the same dialog with the error message on a Windows 10, I fixed it with the following: 

On a cmd check if you can run `pg_config`, if you can't you need to add `pg_config` to your path, by default this is on a `Program Files/PostgreSQL/9.6/bin` directory. After that try running the binary release or building from source.

**Comment by begriffs** [comment]
I made a note to document this. Thanks for the report, @monemihir. Let me know if Steve's suggestion doesn't fix it for you.

**Comment by begriffs** [comment]
Now documented in https://postgrest.com/en/v4.3/install.html
