### ISSUE TITLE
v0.4.2.0 does not run on CentOS 7

### ISSUE THREAD

**Issue by monemihir** [begriffs/postgrest#899]
Following error is received:
```
[mihir@vmcentos7 Downloads]$ ./postgrest test.conf 
Listening on port 30000
Attempting to connect to the database...
postgrest: getAddrInfo: does not exist (Name or service not known)
[mihir@vmcentos7 Downloads]$ 
```

This is my conf file
```
db-uri = "postgres://testuser:test123@localhost:5432/postgrest_test_db"
db-schema = "public"
db-anon-role = "postgres"
db-pool = 100

server-host = "localhost"
server-port = 30000
```
I am running on CentOS 7
```
[mihir@vmcentos7 Downloads]$ hostnamectl
   Static hostname: vmcentos7
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 27ac7b066d974238a1fffac65ae7f0c8
           Boot ID: 97f051ea7d46425ca801eff22b4379e4
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.el7.x86_64
      Architecture: x86-64
[mihir@vmcentos7 Downloads]$ 
```
PostgreSql version is 9.5. I can connect to the Postgres server using **psql** as well as **pgadmin3**.

**Comment by joehealy** [comment]
Not sure I understand the resolution completely, but we were able to make it work using "*4" rather than localhost as the server-host parameter.

I would have thought that localhost would have been treated as a hostname as I believe server-host is a HostPreference (https://www.stackage.org/haddock/lts-8.5/warp-3.2.11.1/Network-Wai-Handler-Warp.html#t:HostPreference)

**Comment by begriffs** [comment]
It appears that `localhost` is traditionally set in `/etc/hosts`, and perhaps it is missing from that file on your system.

**Comment by gitfirenz** [comment]
I'm on centos7  (digitalocean) and it works too with listen "*4"
I add issues however with postgrest using IP V6 to connect to postgresql (and so have to fix pg_hba).

**Comment by begriffs** [comment]
Can you explain what you had to do so I can document it?

**Comment by begriffs** [comment]
I'm not sure from that Haskell library doc whether `*4` will be accessible to the outside network if your firewall allows the port through. For safety's sake wondering if 127.0.0.1 works on centos. Can you check?

**Comment by monemihir** [comment]
Yes, 127.0.0.1 works.

**Comment by begriffs** [comment]
Cool. I'm closing this issue but have an issue open in docs to mention the situation you discovered.

**Comment by monemihir** [comment]
Yup, you can close the issue but there still is an issue with CentOS 6. It looks like the binaries are built on CentOS 7 which means that they don't run on CentOS 6. 

I had to build from source to make it run. Probably should be reported as a new issue?

**Comment by begriffs** [comment]
Yeah I did build the binary on CentOS 7. Didn't realize it wasn't compatible with an earlier version. Open another issue and I'll make sure I release the next version for 6 as well as 7.

**Comment by begriffs** [comment]
Note: I documented the special host binding values in https://postgrest.com/en/v4.3/install.html#configuration
