### ISSUE TITLE
version 0.4.2.0 on Windows server 2012 R2

### ISSUE THREAD

**Issue by twistedlizard** [begriffs/postgrest#900]
Application won't start on windows server 2012 R12
Does anyone else have it working on this os?
Anything I can do to get some error log or output describing the problem at the command line?

**Comment by begriffs** [comment]
I built the executable in a 64-bit virtual machine running Windows 10, not sure if there's an incompatibility in Windows versions. If you run postgrest without any command line arguments does it print out a usage message?

**Comment by twistedlizard** [comment]
>does it print out a usage message?

No, I just get a 'postgrest.exe has stopped working' window.

**Comment by begriffs** [comment]
I wonder if you could help me out and try building postgrest from source on your machine. I'm curious if there's just some difference between windows versions that makes it incompatible.

Here are instructions for building it: https://postgrest.com/en/v4.1/install.html#build-from-source

**Comment by twistedlizard** [comment]
I'll have a go, although I'm not C programmer.
Will get back here if I get stuck.

**Comment by twistedlizard** [comment]
ok, I've downloaded & installed stack
Typing stack at the command prompt gives a whole load of options, no matter what directory I'm in,
So, I change to the postgresr-0.4.2.0 directory, where the source is unzipped.
Could you advise on those command line switches?
Are they going to install stuff? If so, where?

stack build --install-ghc --copy-bins --local-bin-path /usr/local/bin

**Comment by begriffs** [comment]
Initially, in the directory where the source is unzipped, try running

```
stack build --install-ghc
```

**Comment by twistedlizard** [comment]
Eventually, after downloading masses of stuff to
C:\Users\myusername\AppData\Local\Programs\stack\x86_64-windows
and seemingly created a c:\sr directory:

CAUTION
This is your first start of MSYS2
You must restart shell to apply necessary actions.

???

**Comment by twistedlizard** [comment]
Well, it downloaded loads of stuff to 
C:\Users\myusername\AppData\Local\Programs\stack
created, I think
C:\sr
but printed error into to the command line. No exe generated as far as I can see.

**Comment by begriffs** [comment]
Yeah it had to download some Haskell build files. Can you paste the error in this issue? I'll help you get it to build.

**Comment by twistedlizard** [comment]
Yes, I can run it again, but first can you tell me where it's going to put stuff? When I asked that question before, you said:
>Initially, in the directory where the source is unzipped
but it hasn't done that.
Its put a ton of stuff in both C:\Users\myusername\AppData\Local\Programs\stack and C:\sr

Secondly, that was running 
>stack build --install-ghc
now its downloaded all those files, would it be sufficient to run
>stack build
?

**Comment by begriffs** [comment]
Stack stores global Haskell stuff for its own uses in system folders like you noticed. It also stores build files specific to the project you're building in a `.stack-work` folder in the project folder. On my system the final binary is put in `<project folder>/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/postgrest/` but your path will differ a little since you're on Windows. You can get a list of all the locations that stack uses by running `stack path`.

If `stack build --install-ghc` completed successfully you won't need to also run `stack build` because that will have also happened.

You don't actually need to know where Stack put the postgrest binary because after you've built the code you can run `stack exec -- postgrest <arguments>` and stack will run the binary wherever it put it.

**Comment by twistedlizard** [comment]
begriffs> Can you paste the error in this issue? 

There were a few places where the log contained personal identifying information that I've changed. Otherwise:

stack : postgresql-libpq-0.9.3.0: configure
At line:1 char:1
+ stack build --install-ghc > out2.txt 2>&1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (postgresql-libpq-0.9.3.0: configure:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Package postgresql-libpq uses a custom Cabal build, but does not use a custom-setup stanza

Not using the explicit setup deps approach based on configuration
Strongly recommend fixing the package's cabal file

semigroups-0.18.2: download

stringsearch-0.3.6.6: download

stm-2.4.4.1: download

semigroups-0.18.2: configure

stm-2.4.4.1: configure

semigroups-0.18.2: build

semigroups-0.18.2: copy/register

stm-2.4.4.1: build

stringsearch-0.3.6.6: configure

stringsearch-0.3.6.6: build

stm-2.4.4.1: copy/register

stringsearch-0.3.6.6: copy/register


--  While building package postgresql-libpq-0.9.3.0 using:
      
C:\Users\MYNAME\AppData\Local\Temp\stack6292\postgresql-libpq-0.9.3.0\.stack-work\dist\ca59d0ab\setup\setup 
--builddir=.stack-work\dist\ca59d0ab configure 
--with-ghc=C:\Users\myname.MYDOMAIN\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc.EXE 
--with-ghc-pkg=C:\Users\myname.MYDOMAIN\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc-pkg.EXE 
--user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\b201cfe6\pkgdb 
--libdir=C:\sr\snapshots\b201cfe6\lib --bindir=C:\sr\snapshots\b201cfe6\bin --datadir=C:\sr\snapshots\b201cfe6\share 
--libexecdir=C:\sr\snapshots\b201cfe6\libexec --sysconfdir=C:\sr\snapshots\b201cfe6\etc 
--docdir=C:\sr\snapshots\b201cfe6\doc\postgresql-libpq-0.9.3.0 
--htmldir=C:\sr\snapshots\b201cfe6\doc\postgresql-libpq-0.9.3.0 
--haddockdir=C:\sr\snapshots\b201cfe6\doc\postgresql-libpq-0.9.3.0 --dependency=base=base-4.9.1.0 
--dependency=bytestring=bytestring-0.10.8.1 --extra-include-dirs=C:\Users\myname.MYDOMAIN\AppData\Local\Programs
\stack\x86_64-windows\msys2-20150512\mingw64\include 
--extra-lib-dirs=C:\Users\myname.MYDOMAIN\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib
    Process exited with code: ExitFailure 1
    Logs have been written to: 
C:\downloads\stack\postgrest-0.4.2.0\postgrest-0.4.2.0\.stack-work\logs\postgresql-libpq-0.9.3.0.log

    [1 of 2] Compiling Main             ( 
C:\Users\MYNAME\AppData\Local\Temp\stack6292\postgresql-libpq-0.9.3.0\Setup.hs, 
C:\Users\MYNAME\AppData\Local\Temp\stack6292\postgresql-libpq-0.9.3.0\.stack-work\dist\ca59d0ab\setup\Main.o )
    [2 of 2] Compiling StackSetupShim   ( C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs, C:\Users\MYNAME\AppData\Loc
al\Temp\stack6292\postgresql-libpq-0.9.3.0\.stack-work\dist\ca59d0ab\setup\StackSetupShim.o )
    Linking 
C:\Users\MYNAME\AppData\Local\Temp\stack6292\postgresql-libpq-0.9.3.0\.stack-work\dist\ca59d0ab\setup\setup.exe 
...
    Configuring postgresql-libpq-0.9.3.0...
    setup.EXE: The program 'pg_config' is required but it could not be found.

**Comment by steve-chavez** [comment]
I think that's an underlying issue with [postgresql-libpq](https://github.com/lpsmith/postgresql-libpq), if you cannot call the command ```pg_config``` from cmd it won't build, the easiest way to work around that is to install postgresql with the graphical installer, here are some [instructions](https://github.com/lpsmith/postgresql-simple/pull/66#issue-15152384), after that retry building PostgREST.

**Comment by twistedlizard** [comment]
ok. That's the problem. The postgresql bin directory wasn't on the path.
Once I've added it, postgrest starts ok and going to
http://localhost:3000/todos
in a browser gives the expected output!

So, there's no problem with that build on windows server 2012 R12, although maybe it could give a helpful error message if it can't find the postgresql binaries, or whichever one it needs.

Thanks to all.
