### ISSUE TITLE
v0.4.2.0 does not run on CentOS 6

### ISSUE THREAD

**Issue by monemihir** [begriffs/postgrest#902]
It seems like the binaries are built on CentOS 7 and are not backward compatible.

When trying to run the pre-built ones I get the following error:
```
./postgrest-0.4.2.0: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./postgrest-0.4.2.0)
```

Building from source works though.

Read on most forums that GLIBC 2.14 can be installed side-by-side with the one that comes default on CentOS 6 but it is a very bad idea I reckon to do this since there is no way to know which other packages would break if this is done.

Best would be to either release a separate binary for CentOS 6 or make the latest ones backward compatible.

**Comment by ruslantalpa** [comment]
for 4.3 we'll switch to an autobuild script #923 which has centos6 as a target
