### ISSUE TITLE
Is it possible to filter based on a related table?

### ISSUE THREAD

**Issue by chrissound** [begriffs/postgrest#904]
https://stackoverflow.com/questions/44972593/postgrest-filter-does-not-seem-work-with-fields-from-related-table

I'm not really able to determine if this is possible or not reading the docs.

**Comment by ruslantalpa** [comment]
@chrissound you have your answer in stackoverflow, :) please close

**Comment by chrissound** [comment]
Well seems like it's not possible. :( Thanks for the response.
