### ISSUE TITLE
Resource Embedding Unexpected Behavior: table is being treated as pivot

### ISSUE THREAD

**Issue by scottgrayson** [begriffs/postgrest#907]
```sql
-- users
create table data.users ( -- df: mult=3.0
  id serial primary key,
....
-- forms
create table data.forms ( -- df: mult=10.0
  id serial primary key,
  user_id integer references data.users(id) default request.user_id(),
....
-- pitches
create table data.pitches ( -- df: mult=100.0
  id serial primary key,
  user_id integer references data.users(id) default request.user_id(),
  form_id integer references data.forms(id) not null,
....
```
http://localhost:8080/rest/users?select=name,forms(name)
creates this query
```sql
SELECT  "api"."users"."name", COALESCE ((SELECT array_to_js on(array_agg(row_to_json("forms"))) 
FROM (SELECT  "api"."forms"."name" FROM  "api"."pitches", "api"."forms"  
WHERE  "api"."forms"."id" = "api"."pitches"."form_id" 
AND  "api"."users"."id" = "api"."pitches"."user_id"  ) "forms"), '[]') 
AS "forms" FROM  "api"."users"
```

### intended behavior:
users (one to many) forms
### recieved:
users (many to many through pitches) forms

**Comment by ruslantalpa** [comment]
when embedding parents, one can force the foreign key by using
`alias:column_fk(...)` but this is not enough to fix the path to a child relation

I was first thinking of saying `alias:table.column_fk(...)` for children but when there are multiple children, this only solves the path to direct relations, not the one through an intermediate table.

Should we jus add the support for `table.column` now and think about the other cases later?

**Comment by ruslantalpa** [comment]
maybe it could work also for many to many if we make a convention that those are table names like
`alias:link_table.table( ... )` since the name of the FK columns can be determined in that case just from table names.

**Comment by scottgrayson** [comment]
Does postgrest look at the `references` on the `data.users data.forms` even though i am querying the `api.user api.forms`?

**Comment by ruslantalpa** [comment]
yes, views don't have foreign keys between them but we look at where the column comes from and check if it's  view

**Comment by ruslantalpa** [comment]
soon :) ... #918
