### ISSUE TITLE
406 status code returned when no records found requesting a singular object

### ISSUE THREAD

**Issue by bduisenov** [begriffs/postgrest#908]
According to the documentation, a status code should be 404 https://postgrest.com/en/v4.1/api.html#singular-or-plural.

@ruslantalpa tells:

> https://github.com/begriffs/postgrest/blob/master/src/PostgREST/App.hs#L133
> should probably be
> `if contentType == CTSingularJSON && queryTotal > 1`
> and then a special case for total = 0 with a 404

**Comment by ruslantalpa** [comment]
currently it's like this
```
➜  ~ http http://localhost:3000/projects\?uid\=eq.1 \
>   'Accept: application/vnd.pgrst.object+json'
HTTP/1.1 406 Not Acceptable
Content-Type: application/vnd.pgrst.object+json; charset=utf-8
Date: Fri, 14 Jul 2017 08:28:41 GMT
Server: postgrest/0.4.1.0
Transfer-Encoding: chunked

{
    "details": "Results contain 0 rows, application/vnd.pgrst.object+json requires 1 row",
    "message": "JSON object requested, multiple (or no) rows returned"
}
```

**Comment by ruslantalpa** [comment]
Closing this since 406 is the correct response as discussed in #913 (docs issue opened here https://github.com/begriffs/postgrest-docs/issues/95)
