### ISSUE TITLE
Change database on the fly

### ISSUE THREAD

**Issue by omani** [begriffs/postgrest#910]
Hi everbody,

first of all thank you for this great piece of software.

I wonder if it is possible to change the database on the fly so HTTP requests go to the appropriate db in backend.

imagine a web application which is multi tenant. I create a database for every tenant. now if somebody hits the url http://tenantsubdomain.awesome-app.com/rpc/login I want to switch to the right database named tenantsubdomain in this case.

any ideas or other recommendations?

**Comment by omani** [comment]
other options that come to my mind would be:
* create one schema per tenant rather than database
* use one schema for all tenants (with proper ACL and RLS probably easily doable)

**Comment by ruslantalpa** [comment]
you can do that like this:
each customer has a database
to each database, you connect a dedicated postgrest instance (id does not use a lot of memory),

then, in front of all of them, you have one instance of openresty. there you have a location where you define a proxy_pass to an upstream config.

now here comes the interesting part. inside the upstream definition, since it's openresty, you can have a custom lua script that decides the IP/port or the upsteam postgrest instance where to send the request.

this is how you do it.

**Comment by ruslantalpa** [comment]
here is how an upstream definition looks like
https://github.com/subzerocloud/postgrest-starter-kit/blob/master/openresty/nginx/conf/includes/http/postgrest_upstream.conf

(please close)

**Comment by omani** [comment]
@ruslantalpa,

I think I will stick to one schema per tenant since it makes it easier to create new tenants via trigger functions rather than manually have to create a database, migrate or fill it and then define an upstream in openresty. of course this only works if I really cannot get access to header.host of the HTTP within my functions (I assume I can).

so the concept would look like this:
* tenant checks for available subdomain in SaaS application (which will be my tenant name)
* if postgrest function returns true (in "available") then tenant can sign up to get his subdomain
* this request will go to a function which creates a schema, a role, and all necessary grants for that role and schema.
* finally give new role grants to authenticator

with this I end up having one schema per tenant. and web users sharing one tenant role in claim. (still able to identify single user by claim "email" for example).

does this sound sane to you guys?

**Comment by ruslantalpa** [comment]
it's sane but you are missing a crucial step. postgrest is tied to a particualr schema so usually you would have to boot up a new postgrest instance for each customer .... but ... due to a "hack" i would say ... you might be in luck

if you specify to postgrest the schema as an empty string, then whenever it will generate a quuery, it will not fully qualify it, giving you the option to use search path.

so, do all the things that you said but when you start postgrest, give the schema as an empty string, and for each customer/dbuser that you create, make sure you set for him the apropriate search path so that the queries he generates are routed to his custom schema.

i  think you rusecase is doable

**Comment by omani** [comment]
alright. thank you very much for your help. :+1:

**Comment by omani** [comment]
another example that comes to my mind is:
* start postgrest with default schema rather than empty string
* use SET search_path to "schema of tenant" to update underlying table in appropriate table of customer (schema)
* and use only the views defined in this default schema as postgrest documentation explains.

with this I don't have to SET a schema within my "PRE_REQUEST" procedure. I just SET a schema in every view of my public exposed schema.

**Comment by ruslantalpa** [comment]
This will not work, views can not dinamically change the source table.

**Comment by omani** [comment]
yes you are right. I think then it is not possible what I want to achieve.

because setting the schema beforehands (before the request comes in) with a pre_request, sets the schema to $tenantSubDomain. and now I would have to create views in every schema of a tenant. basically the same sql schemas I am using in the boilerplate postgrest starterkit, I would have to execute them after every signup for every schema.

but here is the problem: the views AND data would be in one schema. so there would be no isolation of data. right?

**Comment by omani** [comment]
>so the only option is to really start a new postgrest instance for every tenant. same database, but different schema.

which still wouldn't solve the isolation problem. I would need two schemas for each tenant. one publicly exposed schema and one for his tables (hidden tables I reach via views in the public schema of the tenant)

so the more easier way would be to start a new postgrest instance with a different database. this results in one database per tenant.

**Comment by omani** [comment]
more thoughts on this:
one database per tenant sounds like a lot of maintenance issues to me.
imagine I want to update my SaaS application with an additional view in the public schema. I would have to update every postgrest instance. (sure I could use a central repo for all my sql files, so I don't have to deal with N tenant files.)

beside that I would have to setup each subdomain in the reverse proxy by hand (or automated, but still something would have to be done on the infrastructure).

what do you guys think of all this? what would be the best practice here for me to accomplish my goal?

**Comment by ruslantalpa** [comment]
why do you need to isolate customer data, each with his own schema in the first place?

**Comment by omani** [comment]
Because I dont feel good putting all tenants into same tables. Also to be able to scale up/out in tge future.

**Comment by ruslantalpa** [comment]
- feeling good is not a technical reason
- you don't have either an app or users right now to think about scaling
- don't complicate things and use normal tables, views, rls.
- the only real reason to use schema separation is when the data model for each customer will be different (different columns/tables), almost every other reason is a mistake.

**Comment by omani** [comment]
Ok I will start with all tenants in one db. Still I will make use of the subdomain somehow by asserting the json web token claim eg "tenant" equals the X-Shbdomain header set by openresty. And several other securities. I think RLS is enough to realize tenant data isolation.

**Comment by owais** [comment]
Logical or physical data isolation for different customers is an almost always present security requirement for enterprise applications and with postgresql, using different schemas to host data for different tenants is the most common way of complying with the requirement. Supporting multiple schemas that clients can switch between per request would open this up to a whole new suite of applications.
