### ISSUE TITLE
Can we pass through HTTP headers?

### ISSUE THREAD

**Issue by omani** [begriffs/postgrest#912]
Hi all,

sometimes it is useful to be able to get the HTTP headers from a request in the database.

can we pass the whole HTTP header as a key:value map into request.headers please? I do see request.headers.host and request.headers.origin. but request.headers.host is "postgrest" here, which does not seem to be the HTTP Host header (which should be localhost:8080).

so it seems request.headers.* were set randomly to something but not the HTTP headers.
can we change this?

**Comment by ruslantalpa** [comment]
they are not random and the host header is kind of correct.
you are used to the host being a domain with a port or something but that is a notion from the webserver where it manages multiple vhosts, here it's just one webserver, and it's "postgrest".

what you want to do is have nginx in front then forward the headers that you need and not as expected like this

https://github.com/subzerocloud/postgrest-starter-kit/blob/master/openresty/nginx/conf/includes/http/server/locations/internal_rest.conf#L8

the same as you you usually see as "X-Host" or "X-Something" ...

**Comment by omani** [comment]
Yes I did it exactly like that. I used openresty to set some headers so I can grep them with request.headers.XXX
