### ISSUE TITLE
Allow full control over HTTP status code on RPC error

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest#917]
Currently raising an exception goes through our standard exception-to-status mapping logic. However not all codes are covered. Allow the user to `raise sqlstate 'PTxyz'` and then use xyz as the status code.

**Comment by deinspanjer** [comment]
So this would specifically be for any sort of function that is invoked by the /rpc endpoint?

Would we be able to specify all the things you can specify in the raise statement such as hint and detail in addition to the err code??

Right now, several of our functions being invoked through postgrest are using the plv8 engine.  In that, you return an error by using `throw new Error(message)`.  I'm still fighting with trying to make sure we don't output information that is undesired such as the source code line, and also to be able to provide hint and such.

**Comment by begriffs** [comment]
Yeah, this would be an exception type you could raise in any function (at least plpgsql functions...maybe other languages?). It allows setting message, details and hints. Check out the postgres docs about it - https://www.postgresql.org/docs/9.6/static/plpgsql-errors-and-messages.html

This would be an example:

```plpgsql
raise sqlstate 'PT400' using message 'your request is no good';
```

Would generate HTTP 400 with the "message" key set.

**Comment by W1M0R** [comment]
Is it possible to set the http status without throwing an exception? 

My login function logs successful and failed login attempts into a different table. However, throwing an exception inside the login function causes transaction rollback to happen, losing my 'commits' to the login attempts table.

The proposed solutions on stackoverflow and elsewhere are not ideal (i.e. using dblink or pg 11/12 procedures). It would be great if I could not throw an exception in my login function, but still somehow return an error status message (code 400 with error details). I could return code 200 with a field that indicates that an error has occurred, but I would prefer an error status code.

**Comment by steve-chavez** [comment]
@W1M0R Could you open another issue with the feature request? Maybe a `SET LOCAL response.status = 400` could be offered.
