### ISSUE TITLE
octet-stream for rpcs (related to #895)

### ISSUE THREAD

**Issue by omani** [begriffs/postgrest#920]
hi all,

if I add "Accept: application/octet-stream" to my rpc function call (a POST request) I get:
"none of these content-types are available: application/octet-stream".

the function returns bytea.

is it because of the type bytea I return? the reason I want it to be binary is because the default return is as string (and decoding the bytes I get results in a string representation of the hex (bytea)).

**Comment by begriffs** [comment]
Which postgrest version are you running? The binary output support for RPC is on master but not yet in a released version.

**Comment by omani** [comment]
ah then it makes sense. I am using version "0.4.2.0" in my Dockerfile.

can we expect the above merge in the next release? can I switch to master already? (still testing).
is master a dev branch or stable branch?

**Comment by begriffs** [comment]
The feature will be incorporated into the next release. Master is usually pretty stable -- all the tests pass. However to use master you'll need to [build the binary from source](https://postgrest.com/en/v4.1/install.html#build-from-source).

**Comment by omani** [comment]
Alright. Thank you for this awesome piece of software. I enjoy it very much.
