### ISSUE TITLE
Add postgrest to stackage LTS-9

### ISSUE THREAD

**Issue by PierreR** [begriffs/postgrest#944]
I say in another issue that `postgrest` was on stackage but I can't see it anymore.

Would be nice to add it.

Cheers,

**Comment by PierreR** [comment]
Well I guess it is not there because both `configurator-ng` and `critbit` are not there ...

**Comment by PierreR** [comment]
No love for this. I don't mind enough as to go and propose the deps on stackage myself.

**Comment by begriffs** [comment]
Sorry, didn't mean to ignore this issue. I was just waiting for the verdict on configurator-ng. Looks like lpsmith doesn't care to maintain that project. (I too don't care to take over maintenance for configurator-ng, I can barely maintain my existing stuff. 😉)

So I guess to get on stackage we'll need to find an alternate configuration parser. 

Out of curiosity, what benefits are there for postgrest to be on stackage? Do other programs or libraries want to include our modules in their code and hence want postgrest as a dependency?

**Comment by PierreR** [comment]
The benefit as a nix user would be to have the package build on Hydra. But at this point I don't care that much as I can easily build `postgrest` locally (and I need to repackage it to add the `postgrest-ws` middleware anyway)

That said I believe it is best to keep non-stackage deps to the bare minimum when possible (as a general rule)
 
As a nix user, to improve build comfort, there is something more important which is to keep all deps versions equal or higher to the latest LTS. That's why I PR the update to `jose` (and might propose another one for 'hjsonschema`).
