### ISSUE TITLE
Resource Embedding is not working as stated in documentation

### ISSUE THREAD

**Issue by allochi** [begriffs/postgrest#949]
Resource Embedding is not working as stated in documentation

OS: macOS 10.12.6
postgrest: 0.4.2.0

Schema
```sql
create table owners (
	id serial primary key,
	name varchar(255)
);

create table items (
	id serial primary key,
	name varchar(255),
	owners_id int references owners(id)
);
```

```bash
# Works
$ curl -X GET 'http://localhost:3000/owners?select=name,items(name)' | jq

# Doesn't work
$ curl -X GET 'http://localhost:3000/items?select=name,owners(name)' | jq
```

The second request returns the error
```json
{
  "hint": null,
  "details": null,
  "code": "42703",
  "message": "column owners_owners.id does not exist"
}
```

Based on https://postgrest.com/en/v4.1/api.html#resource-embedding it should work.

The way around this is to include `id` of `owners` in the select `owners(id,name)` instead of only `owners(name)`
```bash
# This one works
$ curl -X GET 'http://localhost:3000/items?select=name,owners(id,name)' | jq
```

This took me few needed hours to figure out, I'm not sure if this is the intended behaviour and it is not yet documented, or it's a bug, I hope this helps and get resolved.

**Comment by ruslantalpa** [comment]
it's mentioned in the docs that are not yet live
https://github.com/begriffs/postgrest-docs/blob/master/api.rst
*The primary key of the table of the resource being embedded must be specified, either explicitly, like in the example above, or implicitly through a wildcard.*

and is tracked here https://github.com/begriffs/postgrest/issues/411 although not sure when/if it will be fixed
