### ISSUE TITLE
Caching issue with `current_setting`?

### ISSUE THREAD

**Issue by witsch** [begriffs/postgrest#953]
There seems to be some weird caching issue when trying to get header values using the `current_setting(…)` function.

I've defined the following function:
```sql
CREATE FUNCTION api.foo() RETURNS integer AS $$
    DECLARE
        foo int;
    BEGIN
        foo := current_setting('request.header.x-foo', true);
        IF foo is NULL THEN
            foo := 42;   -- dummy, in my app it's: SELECT max(…) INTO STRICT md FROM …;
        END IF;
        RETURN foo;
    END;
$$ LANGUAGE plpgsql;
```

This works fine both with and without the `X-Foo` header set, except if it's called with the header first and then without it within a couple of seconds…
```
$ http POST :3000/rpc/foo x-foo:2; http POST :3000/rpc/foo; sleep 5; http POST :3000/rpc/foo
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Range: 0-0/*
Content-Type: application/json; charset=utf-8
Date: Thu, 24 Aug 2017 12:39:25 GMT
Server: postgrest/0.4.2.0
Transfer-Encoding: chunked

2

HTTP/1.1 400 Bad Request
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Thu, 24 Aug 2017 12:39:25 GMT
Server: postgrest/0.4.2.0
Transfer-Encoding: chunked

{
    "code": "22P02",
    "details": null,
    "hint": null,
    "message": "invalid input syntax for integer: \"\""
}

HTTP/1.1 400 Bad Request
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Thu, 24 Aug 2017 12:39:31 GMT
Server: postgrest/0.4.2.0
Transfer-Encoding: chunked

{
    "code": "22P02",
    "details": null,
    "hint": null,
    "message": "invalid input syntax for integer: \"\""
}
```

However, if I increase the `sleep` to 10 or more seconds, things are fine again…
```
http POST :3000/rpc/foo x-foo:2; http POST :3000/rpc/foo; sleep 11; http POST :3000/rpc/foo
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Range: 0-0/*
Content-Type: application/json; charset=utf-8
Date: Thu, 24 Aug 2017 12:40:48 GMT
Server: postgrest/0.4.2.0
Transfer-Encoding: chunked

2

HTTP/1.1 400 Bad Request
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Thu, 24 Aug 2017 12:40:48 GMT
Server: postgrest/0.4.2.0
Transfer-Encoding: chunked

{
    "code": "22P02",
    "details": null,
    "hint": null,
    "message": "invalid input syntax for integer: \"\""
}

HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Range: 0-0/*
Content-Type: application/json; charset=utf-8
Date: Thu, 24 Aug 2017 12:41:00 GMT
Server: postgrest/0.4.2.0
Transfer-Encoding: chunked

42
```

Without the wait `current_setting(…)` apparently returns an empty string even though the header was no longer set.

I also tried restarting PostgREST within those 5 seconds wait, and in that case things are fine.

**Comment by witsch** [comment]
I'm using version 0.4.2.0 on OSX 10.11.6 installed via 'homebrew' and I'm attaching the PostgreSQL error log of the "successful" last example, i.e. waiting 11 seconds: [pg-log.txt](https://github.com/begriffs/postgrest/files/1248837/pg-log.txt)

**Comment by ruslantalpa** [comment]
Please post here the script that is doing the requests, its output (with timestamps preferably) then the db log for the entire period, with success     And errors

**Comment by ruslantalpa** [comment]
reopen if you can replicate and paste the log here

**Comment by NicolasNunezSahr** [comment]
you can use `nullif(current_setting(...), '')` to return a null if current_setting return an empty string.

**Comment by steve-chavez** [comment]
Usually `current_setting` needs to be put in a wrapper function to prevent this kind of errors. Like in https://github.com/steve-chavez/socnet/blob/b986782fed651345e53eda358e4e07f197c87b25/schema/util.sql#L11-L14.

**Comment by elimisteve** [comment]
Could be related to https://github.com/PostgREST/postgrest/issues/1774

Looks like https://github.com/PostgREST/postgrest/issues/953#issuecomment-608011692 is the solution; thanks @steve-chavez and @NicolasNunezSahr !
