### ISSUE TITLE
support for debian or windows x32

### ISSUE THREAD

**Issue by nobless** [begriffs/postgrest#957]
Hello, plans for supporting debian or windows x32 ?

**Comment by ruslantalpa** [comment]
Once this PR https://github.com/begriffs/postgrest/pull/923 is merged next week, it will be relatively trivial to add other linux distros as long as there are base docker images for them and they are supported by haskell/stack.

You can check the status of the PR in a week or so, then submit a new PR with additional changes to those scripts to build the platforms you want (it's a matter of a few bash/docker files), i don't mean anyone will mind distributions for additional platforms :).

**Comment by hivemall** [comment]
Resurrect: Will there be a debian image, if not is ubuntu binary debian suitable. If not are source builds transferable from eg deb10 to deb10 ?
