### ISSUE TITLE
Confusing error when requestion `/` openapi and `api` schema missing

### ISSUE THREAD

**Issue by ruslantalpa** [begriffs/postgrest#962]
in `accessibleTables` (or somewhere in that region) because we expect at least a few tables or rpcs there, we get a strange error when it's an empty database

error is `{"details":0,"message":"Unexpected amount of rows"}`

to reproduce it, connect to an empty database (only authenticator/anonymous roles are created)

**Comment by steve-chavez** [comment]
Only a nonexistent schema setup in the config file as in `db-schema = "nonexistent"` was required to reproduce the error, disregarding the roles or if the database had other tables/schemas.
