### ISSUE TITLE
Is it possible use "Resource Embedding" to INSERT related parent and child records in a _single_ POST request?

### ISSUE THREAD

**Issue by StefanScott** [begriffs/postgrest#969]
I am very impressed with PostgREST! Currently, I am attempting to build a simple CRUD front-end (in Elm) - also using Postman (plus Postman Interceptor) to formulate and monitor API requests and responses.

I have successfully used PostgREST's "Resource Embedding" with a _GET_ request - to return _multiple_ "child" records for each "parent" record in the JSON response, using a _single_ GET request.

Now I am wondering:

**Is it possible to use "Resource Embedding" with a _POST_ request in PostgREST - to insert into two (related - parent/child) tables using a _single_ POST request?**

In other words, is it possible to:

- INSERT (POST) a new _parent_ record; and

- INSERT (POST) several new related _child_ records

...using a _single_ POST request - involving "Resource Embedding"?

---

For example, my database schema has parent table "Directors" and (1-to-N related) child table "Films" - similar to the example in the PostgREST manual:

```
CREATE TABLE "Directors" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT
);

CREATE TABLE "Films" (
  "director_id" INTEGER NOT NULL, 
  "id" SERIAL PRIMARY KEY, 
  "title" TEXT,
  "year" INTEGER
);

ALTER TABLE "Films" 
  ADD CONSTRAINT Director_has_Films 
  FOREIGN KEY ("director_id") 
  REFERENCES "Directors" ("id") 
  ON UPDATE CASCADE 
  ON DELETE CASCADE;
```

So I would like to do a _single_ POST request, which performs the following two things (in succession):

- POST (INSERT) a new "parent" record in table "Directors" (eg, "Fellini"); and

- POST (INSERT) two new "child" records in table "Films" (eg, "Satyricon" and "La Dolce Vita").

Below is my (non-working) POST request which I formulated to look roughly "similar" to the example GET request provided under "Resource Embedding" in the PostgREST manual:

https://postgrest.com/en/v4.3/api.html#resource-embedding

```
POST http://localhost:5001/Directors?select=name,Films(title,year)
```

body text (application/json):

```
[
  {
    "name": "Fellini",
    "Films": [
      {
        "title": "Satyricon",
        "year": 1969
      },
      {
        "title": "La Dolce Vita",
        "year": 1960
      }
    ]
  }
]

```

The above POST request gives an error:

```
{
    "hint": null,
    "details": null,
    "code": "42703",
    "message": "column \"Films\" of relation \"Directors\" does not exist"
}
```

Of course, this error makes sense - there really is no column named "Films" in table "Directors"!

---

**Remarks**

When doing a GET request involving "Resource Embedding", the JSON returned by PostgREST actually _"adds"_ an attribute which "does not exist" in the parent table (having the same name as the "child" table representing the "Embedded Resource").

This is why I was hopeful that there might be some way to also use PostgREST to perform a POST request also involving an "Embedded Resource" - ie, using a _single_ POST request to create both the "parent" record and multiple (related) "child" records.

Thanks for any help!

**Comment by ruslantalpa** [comment]
Not possible.

**Comment by ruslantalpa** [comment]
a bit more info here https://github.com/begriffs/postgrest/issues/667#issuecomment-231573405

**Comment by steve-chavez** [comment]
See #818.
