### ISSUE TITLE
Release 0.4.3 to dockerhub?

### ISSUE THREAD

**Issue by statik** [begriffs/postgrest#973]
Hi!

I am excited about the 0.4.3 release because #567 means that I can use postgrest with Keycloak. I have been using postgrest via the docker images published at https://hub.docker.com/r/begriffs/postgrest/tags/, but I don't see any tag for 0.4.3. Could you push the new release to dockerhub as well?

Thank you for postgrest, it's a very useful tool.

**Comment by statik** [comment]
I have now found https://hub.docker.com/r/postgrest/postgrest/tags/ which has 0.4.3. This repo doesn't show up until the 4th page of results on dockerhub when searching for postgrest, but I'm sure that will improve over time as we start using it.

I think this issue can be closed, but perhaps a sentence could be added to the top of the description for https://hub.docker.com/r/begriffs/postgrest/ pointing to the new repo at postgrest/postgrest to help people find it?

**Comment by begriffs** [comment]
Good idea, I'll make a note to add that message, and will close this issue when it's done. Even better would be if dockerhub allows me to set up a redirect from the old repo to the new one, but don't know if dockerhub can do that.

**Comment by rvernica** [comment]
*postgrest/postgrest* is indeed very hard to find on Docker Hub. Another aspect that might help with its visibility is to have the repository build automatically from source.

**Comment by begriffs** [comment]
I added a reminder for myself in another place. Closing this issue because it is complete at least as named.
