### ISSUE TITLE
rpc function(with OUT parameters) must have return named same as function name

### ISSUE THREAD

**Issue by Jacob-Kroeze** [begriffs/postgrest#974]
If I have a function
`create function my_rpc( foo int, OUT bar text)`
I get an error like this
`{
  "details": "Row number 0",
  "message": "Row error: unexpected null"
}`
The function works if the OUT parameter is named the same as the function (which is a nice practice anyway). So this works:
`create function my_rpc( foo int, OUT my_rpc text)`

**Comment by ruslantalpa** [comment]
paste a sample function (working/nonworking) and the full query that generates that error

**Comment by Jacob-Kroeze** [comment]
I see, this is hard to replicate. I'll try again tomorrow! Here is the shape of the function that led me to submit the issue.
`create or replace function v1.save_facts(tbl text, ref text, val jsonb, timeagg text DEFAULT NULL::text, ef_at timestamp with time zone DEFAULT now(), txtime timestamp with time zone DEFAULT now(), add boolean DEFAULT true, OUT result jsonb) returns jsonb
LANGUAGE SQL
AS $$
select result::jsonb from fact.save_facts(
        tbl, ref, val, timeagg, ef_at, txtime, add
        )
$$;`

**Comment by nelsonfncosta** [comment]
I updated to PostgREST `0.4.3.0` from `0.4.0.0`, and started getting the same error, changing the OUT parameter name to the function name solves the problem **but** the output format changes.
output on `0.4.0.0`
```
[
    {
        "OUT_KEY": {OUT_VALUE...}
    }
]
```
output on `0.4.3.0`
```
{OUT_VALUE...}
```
Not sure if i missed something on the release notes or the doc

**Comment by steve-chavez** [comment]
There isn't explicit support for OUT parameters in PostgREST, that's why that change wasn't documented.

Why use the `OUT` syntax instead of `RETURNS TABLE(cols..)`, they are equivalent and personally I find the `RETURNS TABLE` much more clearer since it's easier to visualize what's being returned.

**Comment by nelsonfncosta** [comment]
@steve-chavez  For my use case I cannot use `RETURNS TABLE(cols..)` because I do not know how many cols I have or the type and name of the columns.
thanks for the reply

**Comment by steve-chavez** [comment]
A simpler function for reproducing the error:
```sql
create function test.single_out_param(num int, OUT num_plus_one int) AS $$
  select num + 1;
$$ language sql;
```
When doing:
```http
GET /rpc/single_out_param?num=1
```
The following response is obtained:
```json
{ "details": "Row number 0", "message": "Row error: unexpected null" }
```
