### ISSUE TITLE
Clarify secret/token wording in Tutorial 1 

### ISSUE THREAD

**Issue by rvernica** [begriffs/postgrest#976]
The wording in *Step 2. Make a Secret* and *Step 3. Sign a Token* of [Tutorial 1](https://postgrest.com/en/v4.3/tutorials/tut1.html#step-2-make-a-secret) is a bit unclear.

1.

> Clients authenticate with the API using JSON Web Tokens. These are JSON objects which are cryptographically signed using a password known to only us and the server. Because clients do not know the password,...

It's unclear who the three parties us: *clients*, *server*, and *us*. Aren't we the *client* in this tutorial? 

In a real scenario, I would guess that the clients authenticate with an authentication service which generates the JWT. This is made clear later:

> Ordinarily your own code in the database or in another server will create and sign authentication tokens, but for this tutorial we will make one “by hand.” 

2.

> While the token may look well obscured, it’s easy to reverse engineer the payload. The token is merely signed, not encrypted, so don’t put things inside that you don’t want a determined client to see.

It might be worth adding that the password itself cannot be recovered. I guess this is obvious for people familiar with JWT.

**Comment by begriffs** [comment]
Thanks for the suggestions! I'll fix up the tutorial and clarify the sloppy writing.

**Comment by begriffs** [comment]
I copied this issue to the docs repo, so closing it here.
