### ISSUE TITLE
JWSError JWSInvalidSignature

### ISSUE THREAD

**Issue by rvernica** [begriffs/postgrest#977]
It does not seem that the JSON Web Token verification works as intended or maybe the documentation is outdated. I am getting a `401` `JWSError JWSInvalidSignature` on the `POST` requests with authorization token.

I followed [Tutorial 0](https://postgrest.com/en/v4.3/tutorials/tut0.html) and [Tutorial 1](https://postgrest.com/en/v4.3/tutorials/tut1.html) word-by-word and this is what I get:

```bash
> cat postgrest.conf
db-uri = "postgres://postgres:mysecretpassword@localhost/postgres"
db-schema = "api"
db-anon-role = "web_anon"
jwt-secret = "secret"
```

```bash
> ./postgrest postgrest.conf
Listening on port 3000
Attempting to connect to the database...
Connection successful
127.0.0.1 - - [15/Sep/2017:14:58:02 -0700] "GET /todos HTTP/1.1" 200 - "" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [15/Sep/2017:14:58:23 -0700] "POST /todos HTTP/1.1" 401 - "" "curl/7.53.1"
```

The token I use is identical with the one in the [tutorial](https://postgrest.com/en/v4.3/tutorials/tut1.html#step-3-sign-a-token).
```bash
> export TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidG9kb191c2VyIn0.IF9PKgLZ_XA70Uz5vm0OxrqYTCQdXxBA0Oz4uK8lBqM"
> curl http://localhost:3000/todos -v -X POST \
     -H "Authorization: Bearer $TOKEN"   \
     -H "Content-Type: application/json" \
     -d '{"task": "learn how to auth"}'

Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> POST /todos HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.53.1
> Accept: */*
> Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidG9kb191c2VyIn0.IF9PKgLZ_XA70Uz5vm0OxrqYTCQdXxBA0Oz4uK8lBqM
> Content-Type: application/json
> Content-Length: 29
> 
* upload completely sent off: 29 out of 29 bytes
< HTTP/1.1 401 Unauthorized
< Transfer-Encoding: chunked
< Date: Fri, 15 Sep 2017 21:58:23 GMT
< Server: postgrest/0.4.3.0
< Content-Type: application/json; charset=utf-8
< WWW-Authenticate: Bearer error="invalid_token", error_description="JWSError JWSInvalidSignature"
< 
* Connection #0 to host localhost left intact
{"message":"JWSError JWSInvalidSignature"}%     
```
---
postgrest `0.4.3.0`
PostgreSQL `9.6.5`
Fedora `26`

**Comment by begriffs** [comment]
In v4.3 we require a secret of at least 32 characters. See if that helps, and we can update the docs. Thanks for your report.

**Comment by rvernica** [comment]
I secret of 32 characters works. Thanks.

**Comment by wildsurfer** [comment]
I believe postgrest should notify user somehow that secret is less than 32 characters :)

**Comment by begriffs** [comment]
I opened a docs pull request to help clarify the 32-char minimum.

We can improve postgrest's error message later when https://github.com/frasertweedale/hs-jose/issues/46 gets closed due to https://github.com/frasertweedale/hs-jose/commit/59ca5e656370e5b7812faadf5234aa9b0724e782 in check-jwk branch of jose

**Comment by kristoffern** [comment]
> In v4.3 we require a secret of at least 32 characters. See if that helps, and we can update the docs. Thanks for your report.

@begriffs This is your local friendly tester reporting that the tutorial still don't mention anything about 32 characters.
Easily enough to find the problem with a quick google and this issue. But would avoid future problems for others if you updated the note saying it has to be 32 characters at least :-)

Source: https://postgrest.org/en/v4.1/tutorials/tut1.html#tut1

Apart from that, thanks for an awesome product :+1:

**Comment by wolfgangwalther** [comment]
@kristoffern You are reading a very much outdated version of the docs and the tutorial. The latest version has this length hint for the secret:
https://postgrest.org/en/stable/tutorials/tut1.html#step-2-make-a-secret

**Comment by kristoffern** [comment]
Doooh, thank you, and checking at the URL I see it's version 4.1 as well. Sorry for the inconvenience 😔
But, thanks for the quick response.

**Comment by hudo259** [comment]
This really needs to be more prominent in the documentation, imho. It cost me 2 days of messing around before I came across the issue here, which solved my problem.

**Comment by steve-chavez** [comment]
Tracking on https://github.com/PostgREST/postgrest/issues/1840

**Comment by laurenceisla** [comment]
> This really needs to be more prominent in the documentation, imho. It cost me 2 days of messing around before I came across the issue here, which solved my problem.

> Tracking on [#1840](https://github.com/PostgREST/postgrest/issues/1840)

If the error is about the "JWT secret must be at least 32 characters long" then it's already fixed in #3628. PostgREST won't start if the length is not at least 32 characters long (it won't reload the config either) and will return a proper message.

This will be available in the next major release.

**Comment by jcianci12** [comment]
If anyone is struggling with this I have set up a docker stack that runs postgrest with RLS and runs some simple jwt tests that might be helpfull.[jwt-postgrest-example](https://github.com/jcianci12/jwt-postgrest-example)

**Comment by hudo259** [comment]
> If anyone is struggling with this I have set up a docker stack that runs postgrest with RLS and runs some simple jwt tests that might be helpfull.[jwt-postgrest-example](https://github.com/jcianci12/jwt-postgrest-example)

Thank you!
