### ISSUE TITLE
Automated builds at Docker Hub are broken

### ISSUE THREAD

**Issue by wildsurfer** [begriffs/postgrest#982]
Automated build at Docker Hub seems to be broken. Version `v0.4.3.0` is released but still not there.

![screenshot at sep 22 18-36-47](https://user-images.githubusercontent.com/1456389/30752524-35624048-9fc5-11e7-81c6-3356ef10f64d.png)

**Comment by ruslantalpa** [comment]
It's at postgrest/postgrest

**Comment by wildsurfer** [comment]
Good to know! Thanks :)
