### ISSUE TITLE
FatalError. Malformed proxy uri

### ISSUE THREAD

**Issue by wildsurfer** [begriffs/postgrest#983]
This bug seems to be related to merge request #968. It says that issue is fixed but it isn't.

When I try to run `postgrest/postgrest:v0.4.3.0` I face with issue:

```
postgrest: FatalError {fatalErrorMessage = "Malformed proxy uri, a correct example: https://example.com:8443/basePath"}
```

Here is a quick repo that will help to reproduce the issue:

```bash
git clone https://github.com/wildsurfer-bug-reports/begriffs-postgrest-MalformedProxyUri.git
cd begriffs-postgrest-MalformedProxyUri
docker-compose up
```

**Comment by wildsurfer** [comment]
Same is happening for `postgrest/postgrest:latest`

**Comment by ruslantalpa** [comment]
https://github.com/subzerocloud/postgrest-starter-kit/blob/master/docker-compose.yml#L47

**Comment by wildsurfer** [comment]
@ruslantalpa, would you be so kind to provide some explanations? Should I add this env variable to my code? If so, what is a value for it? I'm not using any proxies.

**Comment by ruslantalpa** [comment]
yes, add it, make it the same as the url where you'll be accessing it, probably `http://localhost:3000`
(this is temporary until 4.4)

**Comment by wildsurfer** [comment]
As far as I see in docs `server-proxy-uri` is no required to be set. Is this an issue in docs?

![screenshot at sep 22 20-29-42](https://user-images.githubusercontent.com/1456389/30756875-0610f8f6-9fd5-11e7-9d6a-227269068833.png)

**Comment by wildsurfer** [comment]
Oops, I missed end of your last message `(this is temporary until 4.4)`. Thanks for explanation. Now it is clear for me

**Comment by ruslantalpa** [comment]
it is a issue with the docker image, if you do not pass the var, it sends to the exacutable an empty string, which is not the same as missing param and the 4.3 binary tries to parse an empty string as a url. in 4.4 the binary will consider an empty string as a missing param
