### ISSUE TITLE
Heroku -Postgres Roles

### ISSUE THREAD

**Issue by ACPK** [begriffs/postgrest#984]
With Heroku's Postgres roles, can we now use Heroku' Postgres private spaces rather than RDS?

https://devcenter.heroku.com/articles/heroku-postgresql-credentials

 Note: Heroku Postgres credentials are available only to production-class plans (Standard, Premium, Private, and Shield) on Postgres 9.6 and above. Hobby-tier plans include only the default credential, which cannot create other credentials or grant permissions.

**Comment by begriffs** [comment]
Ha, it was *you* who alerted me to this! Sorry I replied in another issue with this link back to you. Got confused. 😉 

Could you open this issue on https://github.com/begriffs/postgrest-docs ? I think it's more a matter for documentation than for the main project. In fact if you want to contribute a pull request there that would be great as well...

Closing this issue.
