### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by barbalex** [begriffs/postgrest#989]
I get this error when connecting like this: `./postgrest postgrest.conf`:

![error](https://user-images.githubusercontent.com/669783/30924939-819574dc-a3b0-11e7-9c30-ecd24a12a29f.png)

`postggrest.conf` is:

    db-uri = "postgres://authenticator:authenticator_secret@localhost:5432/apflora"
    db-schema = "apflora"
    db-anon-role = "anon"
    server-port = 4001
    jwt-secret = "jwt_secret"

db-roles are (ignore the ones prefixed with org_ - they stem from a different database):

![roles](https://user-images.githubusercontent.com/669783/30924991-ad7dbbea-a3b0-11e7-8e43-f15e33e0d9bb.png)

This error seems to depend on the `db-uri` defined in `postgrest.conf`:

Happens with:

- postgres://authenticator:authenticator_secret@localhost:5432/apflora
- postgres://authenticator:authenticator_secret@localhost/apflora
- postgres://postgres:postgres_secret@localhost:5432/apflora

but not with:

- postgres://postgres:postgres_secret@localhost/apflora

The secrets do not contain any unusual characters.

**Comment by ruslantalpa** [comment]
what is the version of postgrest, postgresql, can you connect using psql using those connection strings?

**Comment by barbalex** [comment]
PostgreSQL is v9.6
postgrest is v0.4.3.0

**Comment by barbalex** [comment]
I got it now: user `authenticator` needed to be granted connection an db apflora. That is what psql told me when I tried to connect as authenticator. So thanks a lot for helping!

The nature of the error that occurs when this permission does not exist is a bit misleading.

This step is missing from https://postgrest.com/en/v4.1/auth.html#permissions.

I am of course a complete and total roles-noob. Maybe it is not `connection` but rather `usage` that should be granted?

Any way, it would help bad noobs like me if that were added to the auth example.

**Comment by barbalex** [comment]
The same error occurs if authenticator's password is wrong. It would be a lot of help if these errors were more precise.

**Comment by begriffs** [comment]
@barbalex so that weird error about "invalid UTF-8 stream" is actually caused by attempting to use an authenticator role that doesn't have access to the database? Can you give me the minimal test case to reproduce?

I tried to reproduce this error by altering `pg_hba.conf` to reject all connections. However the error message I get is clearer. I'm on PostgREST v4.4

```
$ ./postgrest foo.conf
Listening on port 3000
Attempting to connect to the database...
FATAL:  pg_hba.conf rejects connection for host "::1", user "failman", database "mydb", SSL off
{
  "details":"FATAL:  pg_hba.conf rejects connection for host \"::1\", user \"failman\", database \"mydb\", SSL off\n",
  "code":"",
  "message":"Database connection error"
}
```

**Comment by lcp580** [comment]
postgrest psql: FATAL:  Ident authentication failed for user "authenticator"
db-uri = "postgres://authenticator:mysecretpassword@localhost:5433/articledb"
db-schema = "api"
db-anon-role = "web_anon"

----
postgresql v9.6
centos 7
postgrest v7.0

**Comment by elimisteve** [comment]
Wrong way I was doing:

> CREATE ROLE authenticator NOINHERIT;

Right way, apparently:

> CREATE ROLE authenticator NOINHERIT LOGIN;
> ALTER ROLE authenticator WITH PASSWORD 'somecrazyrandomsecurepasswordhere';

Then in `postgrest.conf`, do

> db-uri = "postgres://authenticator:somecrazyrandomsecurepasswordhere@localhost:5432/my_app_name"

Then PostgREST will be able to connect to Postgres!

**Comment by elimisteve** [comment]
[In the docs](https://postgrest.org/en/latest/auth.html?highlight=authenticator#permissions) it says to do `CREATE ROLE authenticator NOINHERIT`, but then you can't log in as that user.

**Comment by soufianerafik** [comment]
> Wrong way I was doing:
> 
> > CREATE ROLE authenticator NOINHERIT;
> 
> Right way, apparently:
> 
> > CREATE ROLE authenticator NOINHERIT LOGIN;
> > ALTER ROLE authenticator WITH PASSWORD 'somecrazyrandomsecurepasswordhere';
> 
> Then in `postgrest.conf`, do
> 
> > db-uri = "postgres://authenticator:somecrazyrandomsecurepasswordhere@localhost:5432/my_app_name"
> 
> Then PostgREST will be able to connect to Postgres!

Thank you, your solution worked for me.
