### ISSUE TITLE
current_setting('request.jwt.claim.username', true) returns nothing

### ISSUE THREAD

**Issue by barbalex** [begriffs/postgrest#990]
This function sets the claims:

    create or replace function
    apflora.login(username text, pass text)
    returns basic_auth.jwt_token
      as $$
    declare
      _role name;
      result basic_auth.jwt_token;
    begin
      -- check username and password
      select basic_auth.user_role($1, $2) into _role;
      if _role is null then
        raise invalid_password using message = 'invalid user or password';
      end if;

      select basic_auth.sign(
          row_to_json(r), current_setting('app.jwt_secret')
        ) as token
        from (
          select _role as role,
          $1 as username,
          extract(epoch from now())::integer + 60*60*24*30 as exp
        ) r
        into result;
      return result;
    end;

Login from the webapp works. Checking the token on https://jwt.io reveals that `username`, `role` and `exp` are set correctly.

I then want to set users in sql using the username contained in the jwt claim like this:

    ALTER TABLE apflora.popber ALTER COLUMN "MutWer" SET DEFAULT current_setting('request.jwt.claim.username', true);

Unfortunately the value set is always null.

If I use instead:

    ALTER TABLE apflora.popber ALTER COLUMN "MutWer" SET DEFAULT current_setting('request.jwt.claim.role', true);

Then `postgres` is set. Although the actual user's role was `z`.

`postggrest.conf` is:

    db-uri = "postgres://postgres:postgres_secret@localhost/apflora"
    db-schema = "apflora"
    db-anon-role = "postgres"
    server-port = 4001
    jwt-secret = "jwt_secret"

This is of course using way to powerful roles for authenticator and anonymous users. The reason is that the connection errors out when I use the correct ones (https://github.com/begriffs/postgrest/issues/989).

How could I get `current_setting('request.jwt.claim.username', true)` to return the correct value?

**Comment by ruslantalpa** [comment]
wrap it in a function
https://github.com/subzerocloud/postgrest-starter-kit/blob/master/db/src/data/todo.sql#L5
PS: these however are not postgrest questions 😛

**Comment by barbalex** [comment]
Thanks a lot!

The wording in the docs (https://postgrest.com/en/v4.1/auth.html#web-users-sharing-role) does not lead a noob like me to notice that this needs to be packed into a function though. It sounded to me as if this were a function that postgrest provided. Which is why I also thought it was a postgrest issue.

**Comment by robertjpayne** [comment]
@ruslantalpa is this still the case? I'm having this same issue, I've tried wrapping it into a function but it never comes through. According to jwt.io my token is fine?

```
create or replace function jwt_env_var(v text) returns text as $$
    select current_setting(v, true);
$$ stable language sql;

create or replace function jwt_claim(c text) returns text as $$
    select public.jwt_env_var('request.jwt.claim.' || c);
$$ stable language sql;

drop view if exists api.users;
create view api.users as
  select * from public.jwt_env_var('user_id');
```

Just returns null even though the token has a `user_id` in the payload…

**Comment by steve-chavez** [comment]
@robertjpayne It works for me without wrapping, check the [database logs](http://postgrest.org/en/v5.0/admin.html#database-logs) and see if statements like `set local "request.jwt.claim.username" = 'John Doe'` appear.

**Comment by robertjpayne** [comment]
@steve-chavez I'll have a look, what's odd is I can get the `request.jwt.claim.role` but I can't get anything else at all.

It's a bit frustrating and doesn't make much sense -- I'll keep an eye on the db logs and see if there is any commands getting executed to set others.

**Comment by steve-chavez** [comment]
@robertjpayne `request.jwt.claim.role` always get set to the `db-anon-role`, even if no `Authorization` header is sent.

**Comment by robertjpayne** [comment]
@steve-chavez there is a authorisation header set though in my case and it's valid according to jwt.io and my sign methods.

And it will let me get a custom role out of the auth header not just the default one but if I try to get any other claim in the jwt payload it just always is null.

**Comment by robertjpayne** [comment]
@steve-chavez yea so something is fishy, here's the log file:

```
LOG:  duration: 1.686 ms  statement: SELECT datname FROM pg_database WHERE datallowconn ORDER BY LOWER(datname)
LOG:  duration: 1.698 ms  statement: SELECT datname FROM pg_database WHERE datallowconn ORDER BY LOWER(datname)
LOG:  duration: 0.156 ms  statement: SET client_encoding = 'UTF8';SET client_min_messages TO WARNING;
LOG:  duration: 0.078 ms  parse 0: BEGIN ISOLATION LEVEL READ COMMITTED READ ONLY
LOG:  duration: 0.040 ms  bind 0: BEGIN ISOLATION LEVEL READ COMMITTED READ ONLY
LOG:  duration: 0.033 ms  execute 0: BEGIN ISOLATION LEVEL READ COMMITTED READ ONLY
LOG:  duration: 0.584 ms  statement: set schema 'api';set local role 'postgres';set local "request.jwt.claim.role" = 'postgres';set local "request.header.host" = '127.0.0.1:3000';set local "request.header.connection" = 'keep-alive';set local "request.header.accept" = '*/*';set local "request.header.user-agent" = 'Rested/2009 CFNetwork/902.1 Darwin/17.7.0 (x86_64)';set local "request.header.accept-language" = 'en-us';set local "request.header.accept-encoding" = 'gzip, deflate';
LOG:  duration: 1.039 ms  parse 1: 
	       WITH ignored_body AS (SELECT $1::text) ,
	       pg_source AS (
	         SELECT "api"."test"()
	       )
	       SELECT
	         null::bigint AS total_result_set,
	         1 AS page_total,
	         (row_to_json(_postgrest_t)->'test')::character varying AS body,
	         coalesce(nullif(current_setting('response.headers', true), ''), '[]') AS response_headers
	       FROM (SELECT "pg_source".* FROM "pg_source"    ) _postgrest_t;
LOG:  duration: 0.381 ms  bind 1: 
	       WITH ignored_body AS (SELECT $1::text) ,
	       pg_source AS (
	         SELECT "api"."test"()
	       )
	       SELECT
	         null::bigint AS total_result_set,
	         1 AS page_total,
	         (row_to_json(_postgrest_t)->'test')::character varying AS body,
	         coalesce(nullif(current_setting('response.headers', true), ''), '[]') AS response_headers
	       FROM (SELECT "pg_source".* FROM "pg_source"    ) _postgrest_t;
DETAIL:  parameters: $1 = '{}'
LOG:  duration: 0.087 ms  execute 1: 
	       WITH ignored_body AS (SELECT $1::text) ,
	       pg_source AS (
	         SELECT "api"."test"()
	       )
	       SELECT
	         null::bigint AS total_result_set,
	         1 AS page_total,
	         (row_to_json(_postgrest_t)->'test')::character varying AS body,
	         coalesce(nullif(current_setting('response.headers', true), ''), '[]') AS response_headers
	       FROM (SELECT "pg_source".* FROM "pg_source"    ) _postgrest_t;
DETAIL:  parameters: $1 = '{}'
LOG:  duration: 0.024 ms  parse 2: COMMIT
LOG:  duration: 0.012 ms  bind 2: COMMIT
LOG:  duration: 0.034 ms  execute 2: COMMIT
```

The JWT I'm using is:

```
eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjogImNvcnRleCIsICJlbWFpbCI6ICJ5b2xvIiwgInVzZXJfaWQiOiAiODA0OTdiMzBhZDg1NGVhNmFkMjhhYmVjNDgzOWMwMTAiLCAib3JnYW5pemF0aW9uX2lkIjogImI2Nzg1YzZjMzY4MDQwNGE4OGRiM2ViMWY5NmViMThjIn0.N7n1A5DLJiN9DbpbgDZ7MdmwtI8-7NvFWF_TQfatvmMb6E38mvwrk-YmV7yYuPzqVRYFPmMSpT1lToNSqD42tA
```

As you can see in the JWT is `email` `user_id` `organization_id` but according to the DDL they are never set into the settings.

Maybe I'm encoding the claims wrong or do I need to set something special up so it extracts them from the JWT payload? The documentation isn't super clear if anything additional has to be done.

**Comment by steve-chavez** [comment]
@robertjpayne I see you deleted your comment(though I got it on email), did you manage to clear the issue? Probably the auth header was not being sent correctly, it needs to be like `Authorization: Bearer <token>`.

**Comment by robertjpayne** [comment]
@steve-chavez it was a few things, but the primary culprit was the JWT's were not signed properly. The secret key I was using was exactly 32 textual characters long (no base-64) but I had to lengthen it to work with Postgrest.

It's all resolved now though :)

**Comment by RyanRutkin** [comment]
@robertjpayne Could you elaborate on this? I am having the same issue.
